SootopolisCity_House5_MapScripts::
	.byte 0

SootopolisCity_House5_EventScript_Maniac::
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end

SootopolisCity_House5_EventScript_Girl::
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end

SootopolisCity_House5_Text_SootopolisMtPyreConnection:
	.string "Zwischen Xeneroville und\n"
	.string "dem Pyroberg gibt's 'ne\l"
	.string "komplett krasse Connection.\p"
	.string "Meine Bros und ich haben das\n"
	.string "im alten Labor gegoogelt,\l"
	.string "wo ich mal gejobbt hab.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea:
	.string "Mein großer Bro war früher\n"
	.string "immer am Meer am grinden\l"
	.string "und hat den Scheiß studiert.$"

