MysteryhoeleL_MapScripts::
	.byte 0



MysteryhoeleL_EventScript_Krokel::
	msgbox MysteryhoeleL_Text_Krokel, MSGBOX_NPC
	end

MysteryhoeleL_Text_Krokel:
	.string "Hey {PLAYER}, ich bin ein\n"
	.string "Bote von diesem Rom Entwickler.\l"
	.string "Sein Name ist Zauke07!\p"
	.string "Immer wenn du mich am Ende einer\n"
	.string "Route siehst, sprich mich an, denn\l"
	.string "ich habe einen heißen Tipp für dich!\p"
	.string "Tipp:\p"
	.string "In dieser Höhle versteckt sich ein\n"
	.string "Starter aus der 9 Generation mit\l"
	.string "einer Spawnrate von 1%!\p"
	.string "Welches es ist, musst du selbst\n"
	.string "herausfinden :D !$"
