RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "Die TRAINERSCHULE in METAROST ist\n"
	.string "wirklich top organisiert.\p"
	.string "Man sagt, wenn du dort lernst, kannst\n"
	.string "du es bis zur ARENALEITUNG schaffen!$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "FELIZIA ist nicht nur stark, sie kennt\n"
	.string "sich auch richtig gut mit POKéMON aus.\p"
	.string "Man merkt, dass sie alles ernst nimmt.$"
