#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#include "constants/global.h"
#include "constants/map_event_ids.h"

#define PLAYER_AVATAR_GFX_MALE_NORMAL     (IS_FRLG ? OBJ_EVENT_GFX_RED_NORMAL     : OBJ_EVENT_GFX_BRENDAN_NORMAL)
#define PLAYER_AVATAR_GFX_MALE_MACH_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_RED_BIKE       : OBJ_EVENT_GFX_BRENDAN_MACH_BIKE)
#define PLAYER_AVATAR_GFX_MALE_ACRO_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_RED_BIKE       : OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE)
#define PLAYER_AVATAR_GFX_MALE_SURFING    (IS_FRLG ? OBJ_EVENT_GFX_RED_SURF       : OBJ_EVENT_GFX_BRENDAN_SURFING)
#define PLAYER_AVATAR_GFX_MALE_UNDERWATER (IS_FRLG ? OBJ_EVENT_GFX_RED_SURF       : OBJ_EVENT_GFX_BRENDAN_UNDERWATER)
#define PLAYER_AVATAR_GFX_MALE_FIELD_MOVE (IS_FRLG ? OBJ_EVENT_GFX_RED_FIELD_MOVE : OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE)
#define PLAYER_AVATAR_GFX_MALE_FISHING    (IS_FRLG ? OBJ_EVENT_GFX_RED_FISH       : OBJ_EVENT_GFX_BRENDAN_FISHING)
#define PLAYER_AVATAR_GFX_MALE_WATERING   (IS_FRLG ? OBJ_EVENT_GFX_RED_FIELD_MOVE : OBJ_EVENT_GFX_BRENDAN_WATERING)
#define PLAYER_AVATAR_GFX_MALE_VSSEEKER   (IS_FRLG ? OBJ_EVENT_GFX_RED_VS_SEEKER  : OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE)
#define PLAYER_AVATAR_GFX_FEMALE_NORMAL     (IS_FRLG ? OBJ_EVENT_GFX_GREEN_NORMAL     : OBJ_EVENT_GFX_MAY_NORMAL)
#define PLAYER_AVATAR_GFX_FEMALE_MACH_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_GREEN_BIKE       : OBJ_EVENT_GFX_MAY_MACH_BIKE)
#define PLAYER_AVATAR_GFX_FEMALE_ACRO_BIKE  (IS_FRLG ? OBJ_EVENT_GFX_GREEN_BIKE       : OBJ_EVENT_GFX_MAY_ACRO_BIKE)
#define PLAYER_AVATAR_GFX_FEMALE_SURFING    (IS_FRLG ? OBJ_EVENT_GFX_GREEN_SURF       : OBJ_EVENT_GFX_MAY_SURFING)
#define PLAYER_AVATAR_GFX_FEMALE_UNDERWATER (IS_FRLG ? OBJ_EVENT_GFX_GREEN_SURF       : OBJ_EVENT_GFX_MAY_UNDERWATER)
#define PLAYER_AVATAR_GFX_FEMALE_FIELD_MOVE (IS_FRLG ? OBJ_EVENT_GFX_GREEN_FIELD_MOVE : OBJ_EVENT_GFX_MAY_FIELD_MOVE)
#define PLAYER_AVATAR_GFX_FEMALE_FISHING    (IS_FRLG ? OBJ_EVENT_GFX_GREEN_FISH       : OBJ_EVENT_GFX_MAY_FISHING)
#define PLAYER_AVATAR_GFX_FEMALE_WATERING   (IS_FRLG ? OBJ_EVENT_GFX_GREEN_FIELD_MOVE : OBJ_EVENT_GFX_MAY_WATERING)
#define PLAYER_AVATAR_GFX_FEMALE_VSSEEKER   (IS_FRLG ? OBJ_EVENT_GFX_GREEN_VS_SEEKER  : OBJ_EVENT_GFX_MAY_FIELD_MOVE)

#define OBJ_EVENT_GFX_BRENDAN_NORMAL                       0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE                    1
#define OBJ_EVENT_GFX_BRENDAN_SURFING                      2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE                   3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                         4
#define OBJ_EVENT_GFX_NINJA_BOY                            5
#define OBJ_EVENT_GFX_TWIN                                 6
#define OBJ_EVENT_GFX_BOY_1                                7
#define OBJ_EVENT_GFX_GIRL_1                               8
#define OBJ_EVENT_GFX_BOY_2                                9
#define OBJ_EVENT_GFX_GIRL_2                               10
#define OBJ_EVENT_GFX_LITTLE_BOY                           11
#define OBJ_EVENT_GFX_LITTLE_GIRL                          12
#define OBJ_EVENT_GFX_BOY_3                                13
#define OBJ_EVENT_GFX_GIRL_3                               14
#define OBJ_EVENT_GFX_RICH_BOY                             15
#define OBJ_EVENT_GFX_WOMAN_1                              16
#define OBJ_EVENT_GFX_FAT_MAN                              17
#define OBJ_EVENT_GFX_POKEFAN_F                            18
#define OBJ_EVENT_GFX_MAN_1                                19
#define OBJ_EVENT_GFX_WOMAN_2                              20
#define OBJ_EVENT_GFX_EXPERT_M                             21
#define OBJ_EVENT_GFX_EXPERT_F                             22
#define OBJ_EVENT_GFX_MAN_2                                23
#define OBJ_EVENT_GFX_WOMAN_3                              24
#define OBJ_EVENT_GFX_POKEFAN_M                            25
#define OBJ_EVENT_GFX_WOMAN_4                              26
#define OBJ_EVENT_GFX_COOK                                 27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST                    28
#define OBJ_EVENT_GFX_OLD_MAN                              29
#define OBJ_EVENT_GFX_OLD_WOMAN                            30
#define OBJ_EVENT_GFX_CAMPER                               31
#define OBJ_EVENT_GFX_PICNICKER                            32
#define OBJ_EVENT_GFX_MAN_3                                33
#define OBJ_EVENT_GFX_WOMAN_5                              34
#define OBJ_EVENT_GFX_YOUNGSTER                            35
#define OBJ_EVENT_GFX_BUG_CATCHER                          36
#define OBJ_EVENT_GFX_PSYCHIC_M                            37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                         38
#define OBJ_EVENT_GFX_MANIAC                               39
#define OBJ_EVENT_GFX_HEX_MANIAC                           40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL                       41
#define OBJ_EVENT_GFX_SWIMMER_M                            42
#define OBJ_EVENT_GFX_SWIMMER_F                            43
#define OBJ_EVENT_GFX_BLACK_BELT                           44
#define OBJ_EVENT_GFX_BEAUTY                               45
#define OBJ_EVENT_GFX_SCIENTIST_1                          46
#define OBJ_EVENT_GFX_LASS                                 47
#define OBJ_EVENT_GFX_GENTLEMAN                            48
#define OBJ_EVENT_GFX_SAILOR                               49
#define OBJ_EVENT_GFX_FISHERMAN                            50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M                 51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F                 52
#define OBJ_EVENT_GFX_TUBER_F                              53
#define OBJ_EVENT_GFX_TUBER_M                              54
#define OBJ_EVENT_GFX_HIKER                                55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M                 56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F                 57
#define OBJ_EVENT_GFX_NURSE                                58
#define OBJ_EVENT_GFX_ITEM_BALL                            59
#define OBJ_EVENT_GFX_BERRY_TREE                           60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES              61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES               62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE                    63
#define OBJ_EVENT_GFX_PROF_BIRCH                           64
#define OBJ_EVENT_GFX_MAN_4                                65
#define OBJ_EVENT_GFX_MAN_5                                66
#define OBJ_EVENT_GFX_REPORTER_M                           67
#define OBJ_EVENT_GFX_REPORTER_F                           68
#define OBJ_EVENT_GFX_BARD                                 69
#define OBJ_EVENT_GFX_ANABEL                               70
#define OBJ_EVENT_GFX_TUCKER                               71
#define OBJ_EVENT_GFX_GRETA                                72
#define OBJ_EVENT_GFX_SPENSER                              73
#define OBJ_EVENT_GFX_NOLAND                               74
#define OBJ_EVENT_GFX_LUCY                                 75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL                     76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL                77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL                 78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL                   79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL                  80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL                 81
#define OBJ_EVENT_GFX_CUTTABLE_TREE                        82
#define OBJ_EVENT_GFX_MART_EMPLOYEE                        83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN                   84
#define OBJ_EVENT_GFX_TEALA                                85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK                       86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER                     87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT                      88
#define OBJ_EVENT_GFX_MAY_NORMAL                           89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE                        90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE                        91
#define OBJ_EVENT_GFX_MAY_SURFING                          92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE                       93
#define OBJ_EVENT_GFX_TRUCK                                94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX                95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY                 96
#define OBJ_EVENT_GFX_BIRCHS_BAG                           97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                          98
#define OBJ_EVENT_GFX_ARTIST                               99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL                 100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE              101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE              102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING                103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE             104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL                     105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE                  106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE                  107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING                    108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE                 109
#define OBJ_EVENT_GFX_CAMERAMAN                            110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER                   111
#define OBJ_EVENT_GFX_MAY_UNDERWATER                       112
#define OBJ_EVENT_GFX_MOVING_BOX                           113
#define OBJ_EVENT_GFX_CABLE_CAR                            114
#define OBJ_EVENT_GFX_SCIENTIST_2                          115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE                       116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M                        117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F                        118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M                       119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F                       120
#define OBJ_EVENT_GFX_SIDNEY                               121
#define OBJ_EVENT_GFX_PHOEBE                               122
#define OBJ_EVENT_GFX_GLACIA                               123
#define OBJ_EVENT_GFX_DRAKE                                124
#define OBJ_EVENT_GFX_ROXANNE                              125
#define OBJ_EVENT_GFX_BRAWLY                               126
#define OBJ_EVENT_GFX_WATTSON                              127
#define OBJ_EVENT_GFX_FLANNERY                             128
#define OBJ_EVENT_GFX_NORMAN                               129
#define OBJ_EVENT_GFX_WINONA                               130
#define OBJ_EVENT_GFX_LIZA                                 131
#define OBJ_EVENT_GFX_TATE                                 132
#define OBJ_EVENT_GFX_WALLACE                              133
#define OBJ_EVENT_GFX_STEVEN                               134
#define OBJ_EVENT_GFX_WALLY                                135
#define OBJ_EVENT_GFX_LITTLE_BOY_3                         136
#define OBJ_EVENT_GFX_BRENDAN_FISHING                      137
#define OBJ_EVENT_GFX_MAY_FISHING                          138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN                139
#define OBJ_EVENT_GFX_SS_TIDAL                             140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW                     141
#define OBJ_EVENT_GFX_PICHU_DOLL                           142
#define OBJ_EVENT_GFX_PIKACHU_DOLL                         143
#define OBJ_EVENT_GFX_MARILL_DOLL                          144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                          145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL                       146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL                       147
#define OBJ_EVENT_GFX_TOTODILE_DOLL                        148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL                      149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                          150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL                        151
#define OBJ_EVENT_GFX_DITTO_DOLL                           152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL                        153
#define OBJ_EVENT_GFX_TREECKO_DOLL                         154
#define OBJ_EVENT_GFX_TORCHIC_DOLL                         155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                          156
#define OBJ_EVENT_GFX_DUSKULL_DOLL                         157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                          158
#define OBJ_EVENT_GFX_BALTOY_DOLL                          159
#define OBJ_EVENT_GFX_KECLEON_DOLL                         160
#define OBJ_EVENT_GFX_AZURILL_DOLL                         161
#define OBJ_EVENT_GFX_SKITTY_DOLL                          162
#define OBJ_EVENT_GFX_SWABLU_DOLL                          163
#define OBJ_EVENT_GFX_GULPIN_DOLL                          164
#define OBJ_EVENT_GFX_LOTAD_DOLL                           165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                          166
#define OBJ_EVENT_GFX_PIKA_CUSHION                         167
#define OBJ_EVENT_GFX_ROUND_CUSHION                        168
#define OBJ_EVENT_GFX_KISS_CUSHION                         169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION                       170
#define OBJ_EVENT_GFX_SPIN_CUSHION                         171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION                      172
#define OBJ_EVENT_GFX_BALL_CUSHION                         173
#define OBJ_EVENT_GFX_GRASS_CUSHION                        174
#define OBJ_EVENT_GFX_FIRE_CUSHION                         175
#define OBJ_EVENT_GFX_WATER_CUSHION                        176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL                     177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL                      178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL                      179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL                    180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL                   181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL                   182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL                     183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL                    184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL                      185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL                   186
#define OBJ_EVENT_GFX_LATIAS                               187
#define OBJ_EVENT_GFX_LATIOS                               188
#define OBJ_EVENT_GFX_GAMEBOY_KID                          189
#define OBJ_EVENT_GFX_CONTEST_JUDGE                        190
#define OBJ_EVENT_GFX_BRENDAN_WATERING                     191
#define OBJ_EVENT_GFX_MAY_WATERING                         192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING                   193
#define OBJ_EVENT_GFX_MAY_DECORATING                       194
#define OBJ_EVENT_GFX_ARCHIE                               195
#define OBJ_EVENT_GFX_MAXIE                                196
#define OBJ_EVENT_GFX_KYOGRE_FRONT                         197
#define OBJ_EVENT_GFX_GROUDON_FRONT                        198
#define OBJ_EVENT_GFX_FOSSIL                               199
#define OBJ_EVENT_GFX_REGIROCK                             200
#define OBJ_EVENT_GFX_REGICE                               201
#define OBJ_EVENT_GFX_REGISTEEL                            202
#define OBJ_EVENT_GFX_SKITTY                               203
#define OBJ_EVENT_GFX_KECLEON                              204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP                        205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP                       206
#define OBJ_EVENT_GFX_RAYQUAZA                             207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                          208
#define OBJ_EVENT_GFX_PIKACHU                              209
#define OBJ_EVENT_GFX_AZUMARILL                            210
#define OBJ_EVENT_GFX_WINGULL                              211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW                212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING                     213
#define OBJ_EVENT_GFX_AZURILL                              214
#define OBJ_EVENT_GFX_MOM                                  215
#define OBJ_EVENT_GFX_LINK_BRENDAN                         216
#define OBJ_EVENT_GFX_LINK_MAY                             217
#define OBJ_EVENT_GFX_JUAN                                 218
#define OBJ_EVENT_GFX_SCOTT                                219
#define OBJ_EVENT_GFX_POOCHYENA                            220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                          221
#define OBJ_EVENT_GFX_GROUDON_SIDE                         222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN                     223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE                   224
#define OBJ_EVENT_GFX_KIRLIA                               225
#define OBJ_EVENT_GFX_DUSCLOPS                             226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE                     227
#define OBJ_EVENT_GFX_SUDOWOODO                            228
#define OBJ_EVENT_GFX_MEW                                  229
#define OBJ_EVENT_GFX_RED                                  230
#define OBJ_EVENT_GFX_LEAF                                 231
#define OBJ_EVENT_GFX_DEOXYS                               232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE                      233
#define OBJ_EVENT_GFX_BRANDON                              234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN                      235
#define OBJ_EVENT_GFX_LINK_RS_MAY                          236
#define OBJ_EVENT_GFX_LUGIA                                237
#define OBJ_EVENT_GFX_HOOH                                 238
#define OBJ_EVENT_GFX_POKE_BALL                            239
#define OBJ_EVENT_GFX_OW_MON                               240

#define OBJ_EVENT_GFX_RED_MACH_BIKE                        241
#define OBJ_EVENT_GFX_RED_ACRO_BIKE                        242
#define OBJ_EVENT_GFX_RED_SURFING                          243
#define OBJ_EVENT_GFX_RED_FISHING                          244
#define OBJ_EVENT_GFX_RED_RIDING                           245

#define OBJ_EVENT_GFX_LEAF_MACH_BIKE                       246
#define OBJ_EVENT_GFX_LEAF_ACRO_BIKE                       247
#define OBJ_EVENT_GFX_LEAF_SURFING                         248
#define OBJ_EVENT_GFX_LEAF_FIELD_MOVE                      249
#define OBJ_EVENT_GFX_LEAF_FISHING                         250
#define OBJ_EVENT_GFX_LEAF_RIDING                          251

#define OBJ_EVENT_GFX_BRENDAN_RIDING                       252
#define OBJ_EVENT_GFX_MAY_RIDING                           253
#define OBJ_EVENT_GFX_ETHAN                                254
#define OBJ_EVENT_GFX_ETHAN_MACH_BIKE                      255
#define OBJ_EVENT_GFX_ETHAN_ACRO_BIKE                      256
#define OBJ_EVENT_GFX_ETHAN_SURFING                        257
#define OBJ_EVENT_GFX_ETHAN_FIELD_MOVE                     258
#define OBJ_EVENT_GFX_ETHAN_FISHING                        259
#define OBJ_EVENT_GFX_ETHAN_RIDING                         260
#define OBJ_EVENT_GFX_LYRA                                 261
#define OBJ_EVENT_GFX_LYRA_MACH_BIKE                       262
#define OBJ_EVENT_GFX_LYRA_ACRO_BIKE                       263
#define OBJ_EVENT_GFX_LYRA_SURFING                         264
#define OBJ_EVENT_GFX_LYRA_FIELD_MOVE                      265
#define OBJ_EVENT_GFX_LYRA_FISHING                         266
#define OBJ_EVENT_GFX_LYRA_RIDING                          267
#define OBJ_EVENT_GFX_LUCAS                                268
#define OBJ_EVENT_GFX_DAWN                                 269
#define OBJ_EVENT_GFX_HILBERT                              270
#define OBJ_EVENT_GFX_HILDA                                271
#define OBJ_EVENT_GFX_CALEM                                272
#define OBJ_EVENT_GFX_SERENA                               273
#define OBJ_EVENT_GFX_ELIO                                 274
#define OBJ_EVENT_GFX_SELENE                               275
#define OBJ_EVENT_GFX_VICTOR                               276
#define OBJ_EVENT_GFX_VICTOR_RIDING                        277
#define OBJ_EVENT_GFX_GLORIA                               278
#define OBJ_EVENT_GFX_GLORIA_RIDING                        279
#define OBJ_EVENT_GFX_FLORIAN                              280
#define OBJ_EVENT_GFX_FLORIAN_RIDING                       281
#define OBJ_EVENT_GFX_JULIANA                              282
#define OBJ_EVENT_GFX_JULIANA_RIDING                       283
#define OBJ_EVENT_GFX_BUG_CATCHER_RIDING                   284
#define OBJ_EVENT_GFX_KANTO_AGATHA                         285
#define OBJ_EVENT_GFX_KANTO_BLAINE                         286
#define OBJ_EVENT_GFX_KANTO_BLUE                           287
#define OBJ_EVENT_GFX_KANTO_BROCK                          288
#define OBJ_EVENT_GFX_KANTO_BRUNO                          289
#define OBJ_EVENT_GFX_KANTO_ERIKA                          290
#define OBJ_EVENT_GFX_KANTO_GIOVANNI                       291
#define OBJ_EVENT_GFX_KANTO_KOGA                           292
#define OBJ_EVENT_GFX_KANTO_LANCE                          293
#define OBJ_EVENT_GFX_KANTO_LORELEI                        294
#define OBJ_EVENT_GFX_KANTO_LTSURGE                        295
#define OBJ_EVENT_GFX_KANTO_MISTY                          296
#define OBJ_EVENT_GFX_KANTO_PROFOAK                        297
#define OBJ_EVENT_GFX_KANTO_SABRINA                        298
#define OBJ_EVENT_GFX_KANTO_ROCKET_GIOVANNI                299
#define OBJ_EVENT_GFX_JOHTO_BUGSY                          300
#define OBJ_EVENT_GFX_JOHTO_CLAIR                          301
#define OBJ_EVENT_GFX_JOHTO_CHUCK                          302
#define OBJ_EVENT_GFX_JOHTO_FALKNER                        303
#define OBJ_EVENT_GFX_JOHTO_JASMINE                        304
#define OBJ_EVENT_GFX_JOHTO_KAREN                          305
#define OBJ_EVENT_GFX_JOHTO_MORTY                          306
#define OBJ_EVENT_GFX_JOHTO_PRYCE                          307
#define OBJ_EVENT_GFX_JOHTO_WHITNEY                        308
#define OBJ_EVENT_GFX_JOHTO_WILL                           309
#define OBJ_EVENT_GFX_JOHTO_RED                            310
#define OBJ_EVENT_GFX_SINNOH_AARON                         311
#define OBJ_EVENT_GFX_SINNOH_BERTHA                        312
#define OBJ_EVENT_GFX_SINNOH_BYRON                         313
#define OBJ_EVENT_GFX_SINNOH_CRASHER_WAKE                  314
#define OBJ_EVENT_GFX_SINNOH_CYNTHIA                       315
#define OBJ_EVENT_GFX_SINNOH_FANTINA                       316
#define OBJ_EVENT_GFX_SINNOH_FLINT                         317
#define OBJ_EVENT_GFX_SINNOH_GARDENIA                      318
#define OBJ_EVENT_GFX_SINNOH_LUCIAN                        319
#define OBJ_EVENT_GFX_SINNOH_ROARK                         320
#define OBJ_EVENT_GFX_SINNOH_VOLKNER                       321
#define OBJ_EVENT_GFX_SINNOH_CANDICE                       322
#define OBJ_EVENT_GFX_SINNOH_MAYLENE                       323
#define OBJ_EVENT_GFX_UNOVA_ALDER                          324
#define OBJ_EVENT_GFX_UNOVA_BRYCEN                         325
#define OBJ_EVENT_GFX_UNOVA_CAITLIN                        326
#define OBJ_EVENT_GFX_UNOVA_CLAY                           327
#define OBJ_EVENT_GFX_UNOVA_DRAYDEN                        328
#define OBJ_EVENT_GFX_UNOVA_ELESA                          329
#define OBJ_EVENT_GFX_UNOVA_GRIMSLEY                       330
#define OBJ_EVENT_GFX_UNOVA_IRIS                           331
#define OBJ_EVENT_GFX_UNOVA_LENORA                         332
#define OBJ_EVENT_GFX_UNOVA_MARLON                         333
#define OBJ_EVENT_GFX_UNOVA_MARSHAL                        334
#define OBJ_EVENT_GFX_UNOVA_CHILI                          335
#define OBJ_EVENT_GFX_UNOVA_CILAN                          336
#define OBJ_EVENT_GFX_UNOVA_CRESS                          337
#define OBJ_EVENT_GFX_UNOVA_SHAUNTAL                       338
#define OBJ_EVENT_GFX_UNOVA_SKYLA                          339
#define OBJ_EVENT_GFX_UNOVA_BURGH                          340
#define OBJ_EVENT_GFX_UNOVA_ROXIE                          341
#define OBJ_EVENT_GFX_KALOS_CLEMONT                        342
#define OBJ_EVENT_GFX_KALOS_DIANTHA                        343
#define OBJ_EVENT_GFX_KALOS_DRASNA                         344
#define OBJ_EVENT_GFX_KALOS_GRANT                          345
#define OBJ_EVENT_GFX_KALOS_KORRINA                        346
#define OBJ_EVENT_GFX_KALOS_MALVA                          347
#define OBJ_EVENT_GFX_KALOS_OLYMPIA                        348
#define OBJ_EVENT_GFX_KALOS_RAMOS                          349
#define OBJ_EVENT_GFX_KALOS_SIEBOLD                        350
#define OBJ_EVENT_GFX_KALOS_VALERIE                        351
#define OBJ_EVENT_GFX_KALOS_VIOLA                          352
#define OBJ_EVENT_GFX_KALOS_WIKSTROM                       353
#define OBJ_EVENT_GFX_KALOS_WULFRIC                        354
#define OBJ_EVENT_GFX_ALOLA_ACEROLA                        355
#define OBJ_EVENT_GFX_ALOLA_HALA                           356
#define OBJ_EVENT_GFX_ALOLA_HAPU                           357
#define OBJ_EVENT_GFX_ALOLA_ILIMA                          358
#define OBJ_EVENT_GFX_ALOLA_KAHILI                         359
#define OBJ_EVENT_GFX_ALOLA_KIAWE                          360
#define OBJ_EVENT_GFX_ALOLA_KUKUI                          361
#define OBJ_EVENT_GFX_ALOLA_LANA                           362
#define OBJ_EVENT_GFX_ALOLA_MALLOW                         363
#define OBJ_EVENT_GFX_ALOLA_MINA                           364
#define OBJ_EVENT_GFX_ALOLA_MOLAYNE                        365
#define OBJ_EVENT_GFX_ALOLA_NANU                           366
#define OBJ_EVENT_GFX_ALOLA_OLIVIA                         367
#define OBJ_EVENT_GFX_ALOLA_SOPHOCLES                      368
#define OBJ_EVENT_GFX_GALAR_ALLISTER                       369
#define OBJ_EVENT_GFX_GALAR_BEA                            370
#define OBJ_EVENT_GFX_GALAR_GORDIE                         371
#define OBJ_EVENT_GFX_GALAR_KABU                           372
#define OBJ_EVENT_GFX_GALAR_LEON                           373
#define OBJ_EVENT_GFX_GALAR_MELONY                         374
#define OBJ_EVENT_GFX_GALAR_MILO                           375
#define OBJ_EVENT_GFX_GALAR_NESSA                          376
#define OBJ_EVENT_GFX_GALAR_OPAL                           377
#define OBJ_EVENT_GFX_GALAR_PIERS                          378
#define OBJ_EVENT_GFX_GALAR_RAIHAN                         379
#define OBJ_EVENT_GFX_PALDEA_BRASSIUS                      380
#define OBJ_EVENT_GFX_PALDEA_GRUSHA                        381
#define OBJ_EVENT_GFX_PALDEA_IONO                          382
#define OBJ_EVENT_GFX_PALDEA_KATY                          383
#define OBJ_EVENT_GFX_PALDEA_KOFU                          384
#define OBJ_EVENT_GFX_PALDEA_LARRY                         385
#define OBJ_EVENT_GFX_PALDEA_RYME                          386
#define OBJ_EVENT_GFX_PALDEA_GEETA                         387
#define OBJ_EVENT_GFX_PALDEA_HASSEL                        388
#define OBJ_EVENT_GFX_PALDEA_POPPY                         389
#define OBJ_EVENT_GFX_PALDEA_RIKA                          390
#define OBJ_EVENT_GFX_PALDEA_TULIP                         391
#define OBJ_EVENT_GFX_MISC_AROMA_GIRL                      392
#define OBJ_EVENT_GFX_MISC_BACKPACKER_F                    393
#define OBJ_EVENT_GFX_MISC_BACKPACKER_M                    394
#define OBJ_EVENT_GFX_MISC_BUG_CATCHER                     395
#define OBJ_EVENT_GFX_MISC_BURGLAR                         396
#define OBJ_EVENT_GFX_MISC_CHANNELER                       397
#define OBJ_EVENT_GFX_MISC_CLOWN                           398
#define OBJ_EVENT_GFX_MISC_HEX_MANIAC                      399
#define OBJ_EVENT_GFX_MISC_HEX_MANIAC_SECRET               400
#define OBJ_EVENT_GFX_MISC_KALOS_ENGINEER                  401
#define OBJ_EVENT_GFX_MISC_KALOS_WORKER                    402
#define OBJ_EVENT_GFX_MISC_LOOKER                          403
#define OBJ_EVENT_GFX_MISC_NPC_LADY                        404
#define OBJ_EVENT_GFX_MISC_NPC_MYSTERY_GIFT                405
#define OBJ_EVENT_GFX_MISC_NPC_TUTOR                       406
#define OBJ_EVENT_GFX_MISC_NURSE                           407
#define OBJ_EVENT_GFX_MISC_PEONIA                          408
#define OBJ_EVENT_GFX_MISC_POKE_FAN_F                      409
#define OBJ_EVENT_GFX_MISC_PROFESSOR_ELM                   410
#define OBJ_EVENT_GFX_MISC_RUIN_MANIAC                     411
#define OBJ_EVENT_GFX_MISC_SCIENTIST                       412
#define OBJ_EVENT_GFX_MISC_SUPER_NERD                      413
#define OBJ_EVENT_GFX_MISC_UNOVA_SCIENTIST_F               414
#define OBJ_EVENT_GFX_MISC_VETERAN                         415
#define OBJ_EVENT_GFX_MISC_YOUNG_COUPLE_F                  416
#define OBJ_EVENT_GFX_MISC_YOUNG_COUPLE_M                  417
#define OBJ_EVENT_GFX_MISC_BALL_GUY                        418
#define OBJ_EVENT_GFX_RIVAL_AVERY                          419
#define OBJ_EVENT_GFX_RIVAL_BARRY                          420
#define OBJ_EVENT_GFX_RIVAL_BEDE                           421
#define OBJ_EVENT_GFX_RIVAL_BIANCA                         422
#define OBJ_EVENT_GFX_RIVAL_CHEREN                         423
#define OBJ_EVENT_GFX_RIVAL_GLADION                        424
#define OBJ_EVENT_GFX_RIVAL_HAU                            425
#define OBJ_EVENT_GFX_RIVAL_HOP                            426
#define OBJ_EVENT_GFX_RIVAL_HUGH                           427
#define OBJ_EVENT_GFX_RIVAL_KLARA                          428
#define OBJ_EVENT_GFX_RIVAL_MARNIE                         429
#define OBJ_EVENT_GFX_RIVAL_N                              430
#define OBJ_EVENT_GFX_RIVAL_SHAUNA                         431
#define OBJ_EVENT_GFX_RIVAL_SILVER                         432
#define OBJ_EVENT_GFX_RIVAL_TIERNO                         433
#define OBJ_EVENT_GFX_RIVAL_TREVOR                         434
#define OBJ_EVENT_GFX_RIVAL_NEMONA                         435
#define OBJ_EVENT_GFX_RIVAL_PENNY                          436
#define OBJ_EVENT_GFX_RIVAL_ARVEN                          437
#define OBJ_EVENT_GFX_TEAM_FLARE_GRUNT_F                   438
#define OBJ_EVENT_GFX_TEAM_FLARE_GRUNT_M                   439
#define OBJ_EVENT_GFX_TEAM_FLARE_LYSANDER                  440
#define OBJ_EVENT_GFX_TEAM_GALACTIC_CYRUS                  441
#define OBJ_EVENT_GFX_TEAM_GALACTIC_GRUNT_F                442
#define OBJ_EVENT_GFX_TEAM_GALACTIC_GRUNT_M                443
#define OBJ_EVENT_GFX_TEAM_NEO_PLASMA_COLRESS              444
#define OBJ_EVENT_GFX_TEAM_NEO_PLASMA_GRUNT_F              445
#define OBJ_EVENT_GFX_TEAM_NEO_PLASMA_GRUNT_M              446
#define OBJ_EVENT_GFX_TEAM_PLASMA_GHETSIS                  447
#define OBJ_EVENT_GFX_TEAM_PLASMA_GRUNT_F                  448
#define OBJ_EVENT_GFX_TEAM_PLASMA_GRUNT_M                  449
#define OBJ_EVENT_GFX_TEAM_ROCKET_ARCHER                   450
#define OBJ_EVENT_GFX_TEAM_ROCKET_ARIANA                   451
#define OBJ_EVENT_GFX_TEAM_ROCKET_PETREL                   452
#define OBJ_EVENT_GFX_TEAM_ROCKET_PROTON                   453
#define OBJ_EVENT_GFX_PC                                   454
#define OBJ_EVENT_GFX_PC_STAND                             455
#define OBJ_EVENT_GFX_BATTLE_STATUE                        456
#define OBJ_EVENT_GFX_PHONE_BOOTH                          457
#define OBJ_EVENT_GFX_POKEBLOCK_MIXER                      458
#define OBJ_EVENT_GFX_POKEBLOCK_MIXER_GOLD                 459
#define OBJ_EVENT_GFX_FOOD_PIE                             460
#define OBJ_EVENT_GFX_SMALL_SIGN                           461
#define OBJ_EVENT_GFX_DEVIL_MAN                            462
#define OBJ_EVENT_GFX_WORK_TABLE                           463
#define OBJ_EVENT_GFX_QUEST_BOARD                          464
#define OBJ_EVENT_GFX_STATUE_LEVEL_0                       465
#define OBJ_EVENT_GFX_STATUE_LEVEL_1                       466
#define OBJ_EVENT_GFX_STATUE_LEVEL_2                       467
#define OBJ_EVENT_GFX_STATUE_LEVEL_3                       468
#define OBJ_EVENT_GFX_ITEM_SILVER_TM                       469
#define OBJ_EVENT_GFX_ITEM_GOLD_TM                         470
#define OBJ_EVENT_GFX_ITEM_POKE_BALL                       471
#define OBJ_EVENT_GFX_ITEM_MEDICINE                        472
#define OBJ_EVENT_GFX_ITEM_HOLD_ITEM                       473
#define OBJ_EVENT_GFX_ITEM_MASTER_BALL                     474
#define OBJ_EVENT_GFX_ITEM_EVO_STONE                       475
#define OBJ_EVENT_GFX_ITEM_RARE_CANDY                      476
#define OBJ_EVENT_GFX_ITEM_MINT                            477
#define OBJ_EVENT_GFX_ITEM_MEGA_STONE                      478
#define OBJ_EVENT_GFX_ITEM_Z_CRYSTAL                       479
#define OBJ_EVENT_GFX_ITEM_DYNAMAX_BALL                    480
#define OBJ_EVENT_GFX_ITEM_HEALING                         481
#define OBJ_EVENT_GFX_ITEM_TERA_ORB                        482
#define OBJ_EVENT_GFX_ITEM_TERA_SHARD                      483
#define OBJ_EVENT_GFX_GRASS_DEFAULT                        484
#define OBJ_EVENT_GFX_GOLD_GRASS                           485
#define OBJ_EVENT_GFX_FLAG_ADVENTURE                       486
#define OBJ_EVENT_GFX_DECOR_BED                            487
#define OBJ_EVENT_GFX_DECOR_DRAWERS                        488
#define OBJ_EVENT_GFX_DECOR_ROTOM_FAN                      489
#define OBJ_EVENT_GFX_DECOR_ROTOM_FROST                    490
#define OBJ_EVENT_GFX_DECOR_ROTOM_HEAT                     491
#define OBJ_EVENT_GFX_DECOR_ROTOM_MOW                      492
#define OBJ_EVENT_GFX_DECOR_ROTOM_WASH                     493
#define OBJ_EVENT_GFX_DECOR_WARDROBE                       494
#define OBJ_EVENT_GFX_DECOR_CAULDREN                       495
#define OBJ_EVENT_GFX_GLITCH_KATE                          496
#define OBJ_EVENT_GFX_GLITCH_ERMA                          497
#define OBJ_EVENT_GFX_GLITCH_RAVEN                         498
#define OBJ_EVENT_GFX_GLITCH_TAILS                         499
#define OBJ_EVENT_GFX_GLITCH_LS7                           500
#define OBJ_EVENT_GFX_GLITCH_NACHO                         501
#define OBJ_EVENT_GFX_RIVAL_RED                            502
#define OBJ_EVENT_GFX_RIVAL_LEAF                           503
#define OBJ_EVENT_GFX_RIVAL_ETHAN                          504
#define OBJ_EVENT_GFX_RIVAL_LYRA                           505
#define OBJ_EVENT_GFX_RIVAL_LUCAS                          506
#define OBJ_EVENT_GFX_RIVAL_DAWN                           507
#define OBJ_EVENT_GFX_RIVAL_HILBERT                        508
#define OBJ_EVENT_GFX_RIVAL_HILDA                          509
#define OBJ_EVENT_GFX_RIVAL_NATE                           510
#define OBJ_EVENT_GFX_RIVAL_ROSA                           511
#define OBJ_EVENT_GFX_RIVAL_CALEM                          512
#define OBJ_EVENT_GFX_RIVAL_SERENA                         513
#define OBJ_EVENT_GFX_RIVAL_ELIO                           514
#define OBJ_EVENT_GFX_RIVAL_SELENE                         515
#define OBJ_EVENT_GFX_RIVAL_VICTOR                         516
#define OBJ_EVENT_GFX_RIVAL_GLORIA                         517
#define OBJ_EVENT_GFX_RIVAL_FLORIAN                        518
#define OBJ_EVENT_GFX_RIVAL_JULIANA                        519
#define OBJ_EVENT_GFX_AQUA_MALE                            520
#define OBJ_EVENT_GFX_AQUA_MALE_RIDING                     521
#define OBJ_EVENT_GFX_MAGMA_FEMALE                         522
#define OBJ_EVENT_GFX_MAGMA_FEMALE_RIDING                  523
#define OBJ_EVENT_GFX_GALACTIC_FEMALE                      524
#define OBJ_EVENT_GFX_GALACTIC_FEMALE_RIDING               525
#define OBJ_EVENT_GFX_DOLPHIN                              526
#define OBJ_EVENT_GFX_PLAYER_NORMAL                        527
#define OBJ_EVENT_GFX_PLAYER_RIDING                        528
#define OBJ_EVENT_GFX_PLAYER_FIELD_MOVE                    529

#define OBJ_EVENT_GFX_DAWN_MACH_BIKE                       530
#define OBJ_EVENT_GFX_DAWN_ACRO_BIKE                       531
#define OBJ_EVENT_GFX_DAWN_SURFING                         532
#define OBJ_EVENT_GFX_DAWN_FIELD_MOVE                      533
#define OBJ_EVENT_GFX_DAWN_FISHING                         534
#define OBJ_EVENT_GFX_DAWN_RIDING                          535

#define OBJ_EVENT_GFX_HILDA_MACH_BIKE                      536
#define OBJ_EVENT_GFX_HILDA_ACRO_BIKE                      537
#define OBJ_EVENT_GFX_HILDA_SURFING                        538
#define OBJ_EVENT_GFX_HILDA_FIELD_MOVE                     539
#define OBJ_EVENT_GFX_HILDA_FISHING                        540
#define OBJ_EVENT_GFX_HILDA_RIDING                         541

#define OBJ_EVENT_GFX_SERENA_MACH_BIKE                     542
#define OBJ_EVENT_GFX_SERENA_ACRO_BIKE                     543
#define OBJ_EVENT_GFX_SERENA_SURFING                       544
#define OBJ_EVENT_GFX_SERENA_FIELD_MOVE                    545
#define OBJ_EVENT_GFX_SERENA_FISHING                       546
#define OBJ_EVENT_GFX_SERENA_RIDING                        547

#define OBJ_EVENT_GFX_SELENE_MACH_BIKE                     548
#define OBJ_EVENT_GFX_SELENE_ACRO_BIKE                     549
#define OBJ_EVENT_GFX_SELENE_SURFING                       550
#define OBJ_EVENT_GFX_SELENE_FIELD_MOVE                    551
#define OBJ_EVENT_GFX_SELENE_FISHING                       552
#define OBJ_EVENT_GFX_SELENE_RIDING                        553

#define OBJ_EVENT_GFX_GLORIA_MACH_BIKE                     554
#define OBJ_EVENT_GFX_GLORIA_ACRO_BIKE                     555
#define OBJ_EVENT_GFX_GLORIA_SURFING                       556
#define OBJ_EVENT_GFX_GLORIA_FIELD_MOVE                    557
#define OBJ_EVENT_GFX_GLORIA_FISHING                       558

#define OBJ_EVENT_GFX_JULIANA_MACH_BIKE                    559
#define OBJ_EVENT_GFX_JULIANA_ACRO_BIKE                    560
#define OBJ_EVENT_GFX_JULIANA_SURFING                      561
#define OBJ_EVENT_GFX_JULIANA_FIELD_MOVE                   562
#define OBJ_EVENT_GFX_JULIANA_FISHING                      563

#define OBJ_EVENT_GFX_LUCAS_MACH_BIKE                      564
#define OBJ_EVENT_GFX_LUCAS_ACRO_BIKE                      565
#define OBJ_EVENT_GFX_LUCAS_SURFING                        566
#define OBJ_EVENT_GFX_LUCAS_FIELD_MOVE                     567
#define OBJ_EVENT_GFX_LUCAS_FISHING                        568
#define OBJ_EVENT_GFX_LUCAS_RIDING                         569

#define OBJ_EVENT_GFX_HILBERT_MACH_BIKE                    570
#define OBJ_EVENT_GFX_HILBERT_ACRO_BIKE                    571
#define OBJ_EVENT_GFX_HILBERT_SURFING                      572
#define OBJ_EVENT_GFX_HILBERT_FIELD_MOVE                   573
#define OBJ_EVENT_GFX_HILBERT_FISHING                      574
#define OBJ_EVENT_GFX_HILBERT_RIDING                       575

#define OBJ_EVENT_GFX_CALEM_MACH_BIKE                      576
#define OBJ_EVENT_GFX_CALEM_ACRO_BIKE                      577
#define OBJ_EVENT_GFX_CALEM_SURFING                        578
#define OBJ_EVENT_GFX_CALEM_FIELD_MOVE                     579
#define OBJ_EVENT_GFX_CALEM_FISHING                        580
#define OBJ_EVENT_GFX_CALEM_RIDING                         581

#define OBJ_EVENT_GFX_ELIO_MACH_BIKE                       582
#define OBJ_EVENT_GFX_ELIO_ACRO_BIKE                       583
#define OBJ_EVENT_GFX_ELIO_SURFING                         584
#define OBJ_EVENT_GFX_ELIO_FIELD_MOVE                      585
#define OBJ_EVENT_GFX_ELIO_FISHING                         586
#define OBJ_EVENT_GFX_ELIO_RIDING                          587

#define OBJ_EVENT_GFX_VICTOR_MACH_BIKE                     588
#define OBJ_EVENT_GFX_VICTOR_ACRO_BIKE                     589
#define OBJ_EVENT_GFX_VICTOR_SURFING                       590
#define OBJ_EVENT_GFX_VICTOR_FIELD_MOVE                    591
#define OBJ_EVENT_GFX_VICTOR_FISHING                       592

#define OBJ_EVENT_GFX_FLORIAN_MACH_BIKE                    593
#define OBJ_EVENT_GFX_FLORIAN_ACRO_BIKE                    594
#define OBJ_EVENT_GFX_FLORIAN_SURFING                      595
#define OBJ_EVENT_GFX_FLORIAN_FIELD_MOVE                   596
#define OBJ_EVENT_GFX_FLORIAN_FISHING                      597
#define OBJ_EVENT_GFX_RIVAL_MAY_BIKE                       598
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_BIKE                   599
#define OBJ_EVENT_GFX_RIVAL_RED_MACH_BIKE                  600
#define OBJ_EVENT_GFX_RIVAL_LEAF_MACH_BIKE                 601
#define OBJ_EVENT_GFX_RIVAL_ETHAN_MACH_BIKE                602
#define OBJ_EVENT_GFX_RIVAL_LYRA_MACH_BIKE                 603
#define OBJ_EVENT_GFX_RIVAL_LUCAS_MACH_BIKE                604
#define OBJ_EVENT_GFX_RIVAL_DAWN_MACH_BIKE                 605
#define OBJ_EVENT_GFX_RIVAL_HILBERT_MACH_BIKE              606
#define OBJ_EVENT_GFX_RIVAL_HILDA_MACH_BIKE                607
#define OBJ_EVENT_GFX_RIVAL_NATE_MACH_BIKE                 608
#define OBJ_EVENT_GFX_RIVAL_ROSA_MACH_BIKE                 609
#define OBJ_EVENT_GFX_RIVAL_CALEM_MACH_BIKE                610
#define OBJ_EVENT_GFX_RIVAL_SERENA_MACH_BIKE               611
#define OBJ_EVENT_GFX_RIVAL_ELIO_MACH_BIKE                 612
#define OBJ_EVENT_GFX_RIVAL_SELENE_MACH_BIKE               613
#define OBJ_EVENT_GFX_RIVAL_VICTOR_MACH_BIKE               614
#define OBJ_EVENT_GFX_RIVAL_GLORIA_MACH_BIKE               615
#define OBJ_EVENT_GFX_RIVAL_FLORIAN_MACH_BIKE              616
#define OBJ_EVENT_GFX_RIVAL_JULIANA_MACH_BIKE              617
#define OBJ_EVENT_GFX_NATE                                 618
#define OBJ_EVENT_GFX_ROSA                                 619
#define OBJ_EVENT_GFX_RED_NPC                              620
#define OBJ_EVENT_GFX_LEAF_NPC                             621
#define OBJ_EVENT_GFX_TRUCK_F                              622
#define OBJ_EVENT_GFX_RED_UNDERWATER                       623
#define OBJ_EVENT_GFX_LEAF_UNDERWATER                      624
#define OBJ_EVENT_GFX_RIVAL_RED_ACRO_BIKE                  625
#define OBJ_EVENT_GFX_RIVAL_LEAF_ACRO_BIKE                 626
#define OBJ_EVENT_GFX_LIGHT_SPRITE                         627
#define OBJ_EVENT_GFX_ROSA_RIDING                          628
#define OBJ_EVENT_GFX_ROSA_SURFING                         629
#define OBJ_EVENT_GFX_ROSA_FIELD_MOVE                      630
#define OBJ_EVENT_GFX_ROSA_FISHING                         631
#define OBJ_EVENT_GFX_ROSA_MACH_BIKE                       632
#define OBJ_EVENT_GFX_ROSA_ACRO_BIKE                       633
#define OBJ_EVENT_GFX_NATE_RIDING                          634
#define OBJ_EVENT_GFX_NATE_SURFING                         635
#define OBJ_EVENT_GFX_NATE_FIELD_MOVE                      636
#define OBJ_EVENT_GFX_NATE_FISHING                         637
#define OBJ_EVENT_GFX_NATE_MACH_BIKE                       638
#define OBJ_EVENT_GFX_NATE_ACRO_BIKE                       639
#define OBJ_EVENT_GFX_RIVAL_ETHAN_ACRO_BIKE                640
#define OBJ_EVENT_GFX_RIVAL_LYRA_ACRO_BIKE                 641
#define OBJ_EVENT_GFX_RIVAL_LUCAS_ACRO_BIKE                642
#define OBJ_EVENT_GFX_RIVAL_DAWN_ACRO_BIKE                 643
#define OBJ_EVENT_GFX_RIVAL_HILBERT_ACRO_BIKE              644
#define OBJ_EVENT_GFX_RIVAL_HILDA_ACRO_BIKE                645
#define OBJ_EVENT_GFX_RIVAL_NATE_ACRO_BIKE                 646
#define OBJ_EVENT_GFX_RIVAL_ROSA_ACRO_BIKE                 647
#define OBJ_EVENT_GFX_RIVAL_CALEM_ACRO_BIKE                648
#define OBJ_EVENT_GFX_RIVAL_SERENA_ACRO_BIKE               649
#define OBJ_EVENT_GFX_RIVAL_ELIO_ACRO_BIKE                 650
#define OBJ_EVENT_GFX_RIVAL_SELENE_ACRO_BIKE               651
#define OBJ_EVENT_GFX_RIVAL_VICTOR_ACRO_BIKE               652
#define OBJ_EVENT_GFX_RIVAL_GLORIA_ACRO_BIKE               653
#define OBJ_EVENT_GFX_RIVAL_FLORIAN_ACRO_BIKE              654
#define OBJ_EVENT_GFX_RIVAL_JULIANA_ACRO_BIKE              655
#define OBJ_EVENT_GFX_RIVAL_ASH                            656
#define OBJ_EVENT_GFX_ASH                                  657
#define OBJ_EVENT_GFX_UXIE                                 658
#define OBJ_EVENT_GFX_WES                                  659
#define OBJ_EVENT_GFX_RIVAL_WES                            660
#define OBJ_EVENT_GFX_HILBERT_WATERING                     661
#define OBJ_EVENT_GFX_HILDA_WATERING                       662
#define OBJ_EVENT_GFX_DAWN_WATERING                        663
#define OBJ_EVENT_GFX_LUCAS_WATERING                       664
#define OBJ_EVENT_GFX_ZAPDOS_OLD                           665
#define OBJ_EVENT_GFX_MOLTRES_OLD                          666
#define OBJ_EVENT_GFX_ARTICUNO_OLD                         667
#define OBJ_EVENT_GFX_NURSE_JOY                            668
#define OBJ_EVENT_GFX_ROCKY                                669
#define OBJ_EVENT_GFX_LANDORUS                             670
#define OBJ_EVENT_GFX_JAMES_ROCKET                         671
#define OBJ_EVENT_GFX_ROGUE_EGG                            672
#define OBJ_EVENT_GFX_APRICORN_TREE                        673
#define OBJ_EVENT_GFX_LYRA_WATERING                        674
#define OBJ_EVENT_GFX_RIVAL_ETHAN_FIELD_MOVE               675
#define OBJ_EVENT_GFX_RIVAL_LYRA_FIELD_MOVE                676
#define OBJ_EVENT_GFX_RIVAL_LUCAS_FIELD_MOVE               677
#define OBJ_EVENT_GFX_RIVAL_DAWN_FIELD_MOVE                678
#define OBJ_EVENT_GFX_RIVAL_HILBERT_FIELD_MOVE             679
#define OBJ_EVENT_GFX_RIVAL_HILDA_FIELD_MOVE               680
#define OBJ_EVENT_GFX_ETHAN_UNDERWATER                     681
#define OBJ_EVENT_GFX_LYRA_UNDERWATER                      682
#define OBJ_EVENT_GFX_LUCAS_UNDERWATER                     683
#define OBJ_EVENT_GFX_DAWN_UNDERWATER                      684
#define OBJ_EVENT_GFX_HILBERT_UNDERWATER                   685
#define OBJ_EVENT_GFX_HILDA_UNDERWATER                     686
#define OBJ_EVENT_GFX_RIVAL_RED_FIELD_MOVE                 687
#define OBJ_EVENT_GFX_RIVAL_LEAF_FIELD_MOVE                688
//Platinum
#define OBJ_EVENT_GFX_DP_CYNTHIA                           689
#define OBJ_EVENT_GFX_DP_AARON                             690
#define OBJ_EVENT_GFX_DP_ACE_TRAINERF                      691
#define OBJ_EVENT_GFX_DP_ACE_TRAINERM                      692
#define OBJ_EVENT_GFX_DP_ACE_TRAINER_SNOWM                 693
#define OBJ_EVENT_GFX_DP_BARRY                             694
#define OBJ_EVENT_GFX_DP_BATTLE_GIRL                       695
#define OBJ_EVENT_GFX_DP_BEAUTY                            696
#define OBJ_EVENT_GFX_DP_BERTHA                            697
#define OBJ_EVENT_GFX_DP_BLACK_BELT                        698
#define OBJ_EVENT_GFX_DP_BREEDERF                          699
#define OBJ_EVENT_GFX_DP_BUG_CATCHER                       700
#define OBJ_EVENT_GFX_DP_BYRON                             701
#define OBJ_EVENT_GFX_DP_CAMPER                            702
#define OBJ_EVENT_GFX_DP_CHARON                            703
#define OBJ_EVENT_GFX_DP_CHERYL                            704
#define OBJ_EVENT_GFX_DP_COWGIRL                           705
#define OBJ_EVENT_GFX_DP_CRASHER_WAKE                      706
#define OBJ_EVENT_GFX_DP_CYRUS                             707
#define OBJ_EVENT_GFX_DP_DRAGON_TAMER                      708
#define OBJ_EVENT_GFX_DP_FANTINA                           709
#define OBJ_EVENT_GFX_DP_FISHERMAN                         710
#define OBJ_EVENT_GFX_DP_GALACTIC_GRUNTF                   711
#define OBJ_EVENT_GFX_DP_GALACTIC_GRUNTM                   712
#define OBJ_EVENT_GFX_DP_GENTLEMAN                         713
#define OBJ_EVENT_GFX_DP_HIKER                             714
#define OBJ_EVENT_GFX_DP_JUPITER                           715
#define OBJ_EVENT_GFX_DP_LADY                              716
#define OBJ_EVENT_GFX_DP_LOOKER                            717
#define OBJ_EVENT_GFX_DP_LUCIAN                            718
#define OBJ_EVENT_GFX_DP_MARLEY                            719
#define OBJ_EVENT_GFX_DP_MARS                              720
#define OBJ_EVENT_GFX_DP_MAYLENE                           721
#define OBJ_EVENT_GFX_DP_MIRA                              722
#define OBJ_EVENT_GFX_DP_OFFICER                           723
#define OBJ_EVENT_GFX_DP_PAINTER                           724
#define OBJ_EVENT_GFX_DP_PALMER                            725
#define OBJ_EVENT_GFX_DP_PARASOL_LADY                      726
#define OBJ_EVENT_GFX_DP_PICNICKER                         727
#define OBJ_EVENT_GFX_DP_POKE_KID                          728
#define OBJ_EVENT_GFX_DP_POKE_RANGERF                      729
#define OBJ_EVENT_GFX_DP_POKE_RANGERM                      730
#define OBJ_EVENT_GFX_DP_POKEFAN_F                         731
#define OBJ_EVENT_GFX_DP_POKEFAN_M                         732
#define OBJ_EVENT_GFX_DP_ROWAN                             733
#define OBJ_EVENT_GFX_DP_PSYCHIC                           734
#define OBJ_EVENT_GFX_DP_RANCHER                           735
#define OBJ_EVENT_GFX_DP_RICH_BOY                          736
#define OBJ_EVENT_GFX_DP_RICH_LADY                         737
#define OBJ_EVENT_GFX_DP_ROCKER                            738
#define OBJ_EVENT_GFX_DP_ROUGHNECK                         739
#define OBJ_EVENT_GFX_DP_RUIN_MANIAC                       740
#define OBJ_EVENT_GFX_DP_SAILOR                            741
#define OBJ_EVENT_GFX_DP_SATURN                            742
#define OBJ_EVENT_GFX_DP_SCIENTIST                         743
#define OBJ_EVENT_GFX_DP_SKIERF                            744
#define OBJ_EVENT_GFX_DP_SKIERM                            745
#define OBJ_EVENT_GFX_DP_SOCIALITE                         746
#define OBJ_EVENT_GFX_DP_SUPERNERD                         747
#define OBJ_EVENT_GFX_DP_SWIMMERF                          748
#define OBJ_EVENT_GFX_DP_SWIMMERF2                         749
#define OBJ_EVENT_GFX_DP_SWIMMERM                          750
#define OBJ_EVENT_GFX_DP_SWIMMERM2                         751
#define OBJ_EVENT_GFX_DP_VOLKNER                           752
#define OBJ_EVENT_GFX_DP_WAITER                            753
#define OBJ_EVENT_GFX_DP_WAITRESS                          754
#define OBJ_EVENT_GFX_DP_WORKER                            755
#define OBJ_EVENT_GFX_DP_YOUNG_COUPLEF                     756
#define OBJ_EVENT_GFX_DP_YOUNG_COUPLEM                     757
#define OBJ_EVENT_GFX_DP_YOUNGSTER                         758
#define OBJ_EVENT_GFX_RIVAL_CALEM_SURFING                  759
#define OBJ_EVENT_GFX_CALEM_UNDERWATER                     760
#define OBJ_EVENT_GFX_RIVAL_ELIO_SURFING                   761
#define OBJ_EVENT_GFX_ELIO_UNDERWATER                      762
#define OBJ_EVENT_GFX_RIVAL_FLORIAN_SURFING                763
#define OBJ_EVENT_GFX_FLORIAN_UNDERWATER                   764
#define OBJ_EVENT_GFX_RIVAL_GLORIA_SURFING                 765
#define OBJ_EVENT_GFX_GLORIA_UNDERWATER                    766
#define OBJ_EVENT_GFX_RIVAL_JULIANA_SURFING                767
#define OBJ_EVENT_GFX_JULIANA_UNDERWATER                   768
#define OBJ_EVENT_GFX_RIVAL_NATE_SURFING                   769
#define OBJ_EVENT_GFX_NATE_UNDERWATER                      770
#define OBJ_EVENT_GFX_RIVAL_ROSA_SURFING                   771
#define OBJ_EVENT_GFX_ROSA_UNDERWATER                      772
#define OBJ_EVENT_GFX_RIVAL_SELENE_SURFING                 773
#define OBJ_EVENT_GFX_SELENE_UNDERWATER                    774
#define OBJ_EVENT_GFX_RIVAL_SERENA_SURFING                 775
#define OBJ_EVENT_GFX_SERENA_UNDERWATER                    776
#define OBJ_EVENT_GFX_RIVAL_VICTOR_SURFING                 777
#define OBJ_EVENT_GFX_VICTOR_UNDERWATER                    778

// FRLG objects (shifted to start after custom sprites)
#define OBJ_EVENT_GFX_RED_NORMAL                           779
#define OBJ_EVENT_GFX_RED_BIKE                             780
#define OBJ_EVENT_GFX_RED_SURF                             781
#define OBJ_EVENT_GFX_RED_FISH                             782
#define OBJ_EVENT_GFX_RED_VS_SEEKER                        783
#define OBJ_EVENT_GFX_RED_VS_SEEKER_BIKE                   784
#define OBJ_EVENT_GFX_GREEN_NORMAL                         785
#define OBJ_EVENT_GFX_GREEN_BIKE                           786
#define OBJ_EVENT_GFX_GREEN_SURF                           787
#define OBJ_EVENT_GFX_GREEN_FIELD_MOVE                     788
#define OBJ_EVENT_GFX_GREEN_FISH                           789
#define OBJ_EVENT_GFX_GREEN_VS_SEEKER                      790
#define OBJ_EVENT_GFX_GREEN_VS_SEEKER_BIKE                 791
#define OBJ_EVENT_GFX_BOY                                  792
#define OBJ_EVENT_GFX_BATTLE_GIRL                          793
#define OBJ_EVENT_GFX_MAN                                  794
#define OBJ_EVENT_GFX_ROCKER                               795
#define OBJ_EVENT_GFX_BALDING_MAN                          796
#define OBJ_EVENT_GFX_OLD_MAN_1                            797
#define OBJ_EVENT_GFX_OLD_MAN_2                            798
#define OBJ_EVENT_GFX_OLD_MAN_LYING_DOWN                   799
#define OBJ_EVENT_GFX_TUBER_M_WATER                        800
#define OBJ_EVENT_GFX_TUBER_M_LAND                         801
#define OBJ_EVENT_GFX_COOLTRAINER_M                        802
#define OBJ_EVENT_GFX_COOLTRAINER_F                        803
#define OBJ_EVENT_GFX_SWIMMER_M_WATER                      804
#define OBJ_EVENT_GFX_SWIMMER_F_WATER                      805
#define OBJ_EVENT_GFX_SWIMMER_M_LAND                       806
#define OBJ_EVENT_GFX_SWIMMER_F_LAND                       807
#define OBJ_EVENT_GFX_WORKER_M                             808
#define OBJ_EVENT_GFX_WORKER_F                             809
#define OBJ_EVENT_GFX_GBA_KID                              810
#define OBJ_EVENT_GFX_SUPER_NERD                           811
#define OBJ_EVENT_GFX_BLACKBELT                            812
#define OBJ_EVENT_GFX_SCIENTIST                            813
#define OBJ_EVENT_GFX_FISHER                               814
#define OBJ_EVENT_GFX_CHANNELER                            815
#define OBJ_EVENT_GFX_CHEF                                 816
#define OBJ_EVENT_GFX_POLICEMAN                            817
#define OBJ_EVENT_GFX_CAPTAIN                              818
#define OBJ_EVENT_GFX_CABLE_CLUB_RECEPTIONIST              819
#define OBJ_EVENT_GFX_UNION_ROOM_RECEPTIONIST              820
#define OBJ_EVENT_GFX_CLERK                                821
#define OBJ_EVENT_GFX_MG_DELIVERYMAN                       822
#define OBJ_EVENT_GFX_TRAINER_TOWER_DUDE                   823
#define OBJ_EVENT_GFX_PROF_OAK                             824
#define OBJ_EVENT_GFX_BLUE                                 825
#define OBJ_EVENT_GFX_LANCE                                826
#define OBJ_EVENT_GFX_AGATHA                               827
#define OBJ_EVENT_GFX_DAISY                                828
#define OBJ_EVENT_GFX_LORELEI                              829
#define OBJ_EVENT_GFX_MR_FUJI                              830
#define OBJ_EVENT_GFX_BRUNO                                831
#define OBJ_EVENT_GFX_BROCK                                832
#define OBJ_EVENT_GFX_MISTY                                833
#define OBJ_EVENT_GFX_LT_SURGE                             834
#define OBJ_EVENT_GFX_ERIKA                                835
#define OBJ_EVENT_GFX_KOGA                                 836
#define OBJ_EVENT_GFX_SABRINA                              837
#define OBJ_EVENT_GFX_BLAINE                               838
#define OBJ_EVENT_GFX_GIOVANNI                             839
#define OBJ_EVENT_GFX_CELIO                                840
#define OBJ_EVENT_GFX_TEACHY_TV_HOST                       841
#define OBJ_EVENT_GFX_GYM_GUY                              842
#define OBJ_EVENT_GFX_TOWN_MAP                             843
#define OBJ_EVENT_GFX_POKEDEX                              844
#define OBJ_EVENT_GFX_LITTLE_BOY_FRLG                      845
#define OBJ_EVENT_GFX_LITTLE_GIRL_FRLG                     846
#define OBJ_EVENT_GFX_YOUNGSTER_FRLG                       847
#define OBJ_EVENT_GFX_BUG_CATCHER_FRLG                     848
#define OBJ_EVENT_GFX_LASS_FRLG                            849
#define OBJ_EVENT_GFX_WOMAN_1_FRLG                         850
#define OBJ_EVENT_GFX_FAT_MAN_FRLG                         851
#define OBJ_EVENT_GFX_WOMAN_2_FRLG                         852
#define OBJ_EVENT_GFX_BEAUTY_FRLG                          853
#define OBJ_EVENT_GFX_WOMAN_3_FRLG                         854
#define OBJ_EVENT_GFX_OLD_WOMAN_FRLG                       855
#define OBJ_EVENT_GFX_CAMPER_FRLG                          856
#define OBJ_EVENT_GFX_PICNICKER_FRLG                       857
#define OBJ_EVENT_GFX_MOM_FRLG                             858
#define OBJ_EVENT_GFX_TUBER_F_FRLG                         859
#define OBJ_EVENT_GFX_HIKER_FRLG                           860
#define OBJ_EVENT_GFX_GENTLEMAN_FRLG                       861
#define OBJ_EVENT_GFX_SAILOR_FRLG                          862
#define OBJ_EVENT_GFX_NURSE_FRLG                           863
#define OBJ_EVENT_GFX_FOSSIL_FRLG                          864
#define OBJ_EVENT_GFX_RUBY                                 865
#define OBJ_EVENT_GFX_SAPPHIRE                             866
#define OBJ_EVENT_GFX_OLD_AMBER                            867
#define OBJ_EVENT_GFX_GYM_SIGN                             868
#define OBJ_EVENT_GFX_SIGN                                 869
#define OBJ_EVENT_GFX_TRAINER_TIPS                         870
#define OBJ_EVENT_GFX_CLIPBOARD                            871
#define OBJ_EVENT_GFX_METEORITE                            872
#define OBJ_EVENT_GFX_LAPRAS_DOLL                          873
#define OBJ_EVENT_GFX_SEAGALLOP                            874
#define OBJ_EVENT_GFX_SPEAROW                              875
#define OBJ_EVENT_GFX_CUBONE                               876
#define OBJ_EVENT_GFX_POLIWRATH                            877
#define OBJ_EVENT_GFX_CLEFAIRY                             878
#define OBJ_EVENT_GFX_PIDGEOT                              879
#define OBJ_EVENT_GFX_JIGGLYPUFF                           880
#define OBJ_EVENT_GFX_PIDGEY                               881
#define OBJ_EVENT_GFX_CHANSEY                              882
#define OBJ_EVENT_GFX_OMANYTE                              883
#define OBJ_EVENT_GFX_KANGASKHAN                           884
#define OBJ_EVENT_GFX_PIKACHU_FRLG                         885
#define OBJ_EVENT_GFX_PSYDUCK                              886
#define OBJ_EVENT_GFX_NIDORAN_F                            887
#define OBJ_EVENT_GFX_NIDORAN_M                            888
#define OBJ_EVENT_GFX_NIDORINO                             889
#define OBJ_EVENT_GFX_MEOWTH                               890
#define OBJ_EVENT_GFX_SEEL                                 891
#define OBJ_EVENT_GFX_VOLTORB                              892
#define OBJ_EVENT_GFX_SLOWPOKE                             893
#define OBJ_EVENT_GFX_SLOWBRO                              894
#define OBJ_EVENT_GFX_MACHOP                               895
#define OBJ_EVENT_GFX_WIGGLYTUFF                           896
#define OBJ_EVENT_GFX_DODUO                                897
#define OBJ_EVENT_GFX_FEAROW                               898
#define OBJ_EVENT_GFX_MACHOKE                              899
#define OBJ_EVENT_GFX_LAPRAS                               900
#define OBJ_EVENT_GFX_ZAPDOS                               901
#define OBJ_EVENT_GFX_MOLTRES                              902
#define OBJ_EVENT_GFX_ARTICUNO                             903
#define OBJ_EVENT_GFX_MEWTWO                               904
#define OBJ_EVENT_GFX_KABUTO                               905
#define OBJ_EVENT_GFX_DEOXYS_D                             906
#define OBJ_EVENT_GFX_DEOXYS_A                             907
#define OBJ_EVENT_GFX_DEOXYS_N                             908
#define OBJ_EVENT_GFX_SS_ANNE                              909
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER_FRLG                910
#define OBJ_EVENT_GFX_CUTTABLE_TREE_FRLG                   911
#define OBJ_EVENT_GFX_BREAKABLE_ROCK_FRLG                  912
#define OBJ_EVENT_GFX_LUGIA_SHADOW                         913
#define OBJ_EVENT_GFX_CALEM_WATERING                       914
#define OBJ_EVENT_GFX_RED_FIELD_MOVE                       915
#define OBJ_EVENT_GFX_ROCKET_M                             916
#define OBJ_EVENT_GFX_ROCKET_F                             917
#define OBJ_EVENT_GFX_BIKER                                918
#define OBJ_EVENT_GFX_BILL                                 919
#define OBJ_EVENT_GFX_SNORLAX                              920
#define OBJ_EVENT_GFX_ENTEI                                921
#define OBJ_EVENT_GFX_SUICUNE                              922
#define OBJ_EVENT_GFX_RAIKOU                               923
#define OBJ_EVENT_GFX_CELEBI                               924
#define OBJ_EVENT_GFX_JESSIE_ROCKET                        925
#define OBJ_EVENT_GFX_DARKRAI                              926

// FRLG equivalents
// #define OBJ_EVENT_GFX_MEW OBJ_EVENT_GFX_NINJA_BOY
// #define OBJ_EVENT_GFX_LUGIA OBJ_EVENT_GFX_NINJA_BOY

// NOTE: The maximum amount of object events has been expanded from 255 to 65535.
// Since dynamic graphics ids still require at least 16 free values, the actual limit
// is 65519, but even considering follower Pokémon, this should be more than enough :)
#define NUM_OBJ_EVENT_GFX                        927


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0)
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF)

// Don't use (1u << 15) to avoid conflict with BLEND_IMMUNE_FLAG.
#define OBJ_EVENT_MON               (1u << 14)
#define OBJ_EVENT_MON_SHINY         (1u << 13)
#define OBJ_EVENT_MON_FEMALE        (1u << 12)
#define OBJ_EVENT_MON_SPECIES_MASK  (~(7u << 12))

// Used to call a specific species' follower graphics. Useful for static encounters.
#define OBJ_EVENT_GFX_SPECIES(name)                 (SPECIES_##name + OBJ_EVENT_MON)
#define OBJ_EVENT_GFX_SPECIES_SHINY(name)           (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_SHINY)
#define OBJ_EVENT_GFX_SPECIES_FEMALE(name)          (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_FEMALE)
#define OBJ_EVENT_GFX_SPECIES_SHINY_FEMALE(name)    (SPECIES_##name + OBJ_EVENT_MON + OBJ_EVENT_MON_SHINY + OBJ_EVENT_MON_FEMALE)

#define OW_SPECIES(x) ((x)->graphicsId & OBJ_EVENT_MON_SPECIES_MASK)
#define OW_SHINY(x) ((x)->graphicsId & OBJ_EVENT_MON_SHINY)
#define OW_FEMALE(x) ((x)->graphicsId & OBJ_EVENT_MON_FEMALE)

// Whether Object Event is an OW pokemon
#define IS_OW_MON_OBJ(obj) ((obj)->graphicsId & OBJ_EVENT_MON)

#define SHADOW_SIZE_S       0
#define SHADOW_SIZE_M       1
#define SHADOW_SIZE_L       2
#define SHADOW_SIZE_NONE    3   // Originally SHADOW_SIZE_XL, which went unused due to shadowSize in ObjectEventGraphicsInfo being only 2 bits.

#define SHADOW_SIZE_XL_BATTLE_ONLY  SHADOW_SIZE_NONE    // Battle-only definition for XL shadow size.

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2
#define TRACKS_SLITHER    3
#define TRACKS_SPOT       4
#define TRACKS_BUG        5

#define LIGHT_TYPE_BALL             0
#define LIGHT_TYPE_PKMN_CENTER_SIGN 1
#define LIGHT_TYPE_POKE_MART_SIGN   2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
// Used for link player OWs in CreateLinkPlayerSprite
#define OBJ_EVENT_ID_DYNAMIC_BASE 0xF0

// Each object event template gets an ID that can be used to refer to it in scripts and elsewhere.
// This is referred to as the "local id" (and it's really just 1 + its index in the templates array).
// There are a few special IDs reserved for objects that don't have templates in the map data -- one for the player
// in regular offline play, five for linked players while playing Berry Blender, and one for an invisible object that
// can be spawned for the camera to track instead of the player. Additionally, the value 0 is reserved as an "empty" indicator.
#define LOCALID_NONE                         0
#define LOCALID_CAMERA                     127
#define LOCALID_BERRY_BLENDER_PLAYER_END   240 // This will use 5 (MAX_RFU_PLAYERS) IDs ending at 240, i.e. 236-240
#define LOCALID_FOLLOWING_POKEMON          254
#define LOCALID_PLAYER                     255
#define OBJ_EVENT_ID_FOLLOWER              0xFE
#define OBJ_EVENT_ID_NPC_FOLLOWER          0xFD

// Aliases for old names. "object event id" normally refers to an index into gObjectEvents, which these are not.
// Used for link player OWs in CreateLinkPlayerSprite
#define OBJ_EVENT_ID_CAMERA LOCALID_CAMERA
#define OBJ_EVENT_ID_PLAYER LOCALID_PLAYER

// Moved from src/event_object_movement.c so that they're accesible from other files.
#define OBJ_EVENT_PAL_TAG_BRENDAN                 0x1100
#define OBJ_EVENT_PAL_TAG_BRENDAN_REFLECTION      0x1101
#define OBJ_EVENT_PAL_TAG_BRIDGE_REFLECTION       0x1102
#define OBJ_EVENT_PAL_TAG_NPC_1                   0x1103
#define OBJ_EVENT_PAL_TAG_NPC_2                   0x1104
#define OBJ_EVENT_PAL_TAG_NPC_3                   0x1105
#define OBJ_EVENT_PAL_TAG_NPC_4                   0x1106
#define OBJ_EVENT_PAL_TAG_NPC_1_REFLECTION        0x1107
#define OBJ_EVENT_PAL_TAG_NPC_2_REFLECTION        0x1108
#define OBJ_EVENT_PAL_TAG_NPC_3_REFLECTION        0x1109
#define OBJ_EVENT_PAL_TAG_NPC_4_REFLECTION        0x110A
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP            0x110B
#define OBJ_EVENT_PAL_TAG_QUINTY_PLUMP_REFLECTION 0x110C
#define OBJ_EVENT_PAL_TAG_TRUCK                   0x110D
#define OBJ_EVENT_PAL_TAG_VIGOROTH                0x110E
#define OBJ_EVENT_PAL_TAG_ZIGZAGOON               0x110F
#define OBJ_EVENT_PAL_TAG_MAY                     0x1110
#define OBJ_EVENT_PAL_TAG_MAY_REFLECTION          0x1111
#define OBJ_EVENT_PAL_TAG_MOVING_BOX              0x1112
#define OBJ_EVENT_PAL_TAG_CABLE_CAR               0x1113
#define OBJ_EVENT_PAL_TAG_SSTIDAL                 0x1114
#define OBJ_EVENT_PAL_TAG_PLAYER_UNDERWATER       0x1115
#define OBJ_EVENT_PAL_TAG_KYOGRE                  0x1116
#define OBJ_EVENT_PAL_TAG_KYOGRE_REFLECTION       0x1117
#define OBJ_EVENT_PAL_TAG_GROUDON                 0x1118
#define OBJ_EVENT_PAL_TAG_GROUDON_REFLECTION      0x1119
#define OBJ_EVENT_PAL_TAG_UNUSED                  0x111A
#define OBJ_EVENT_PAL_TAG_SUBMARINE_SHADOW        0x111B
#define OBJ_EVENT_PAL_TAG_POOCHYENA               0x111C
#define OBJ_EVENT_PAL_TAG_RED_LEAF                0x111D
#define OBJ_EVENT_PAL_TAG_DEOXYS                  0x111E
#define OBJ_EVENT_PAL_TAG_BIRTH_ISLAND_STONE      0x111F
#define OBJ_EVENT_PAL_TAG_HO_OH                   0x1120
#define OBJ_EVENT_PAL_TAG_LUGIA                   0x1121
#define OBJ_EVENT_PAL_TAG_RS_BRENDAN              0x1122
#define OBJ_EVENT_PAL_TAG_RS_MAY                  0x1123
#define OBJ_EVENT_PAL_TAG_DYNAMIC                 0x1124
#define OBJ_EVENT_PAL_TAG_NPC_BLUE                0x1129
#define OBJ_EVENT_PAL_TAG_NPC_PINK                0x1130
#define OBJ_EVENT_PAL_TAG_NPC_GREEN               0x1131
#define OBJ_EVENT_PAL_TAG_NPC_WHITE               0x1132
#define OBJ_EVENT_PAL_TAG_NPC_BLUE_REFLECTION     0x1133
#define OBJ_EVENT_PAL_TAG_NPC_PINK_REFLECTION     0x1134
#define OBJ_EVENT_PAL_TAG_NPC_GREEN_REFLECTION    0x1135
#define OBJ_EVENT_PAL_TAG_NPC_WHITE_REFLECTION    0x1136
#define OBJ_EVENT_PAL_TAG_METEORITE               0x1137
#define OBJ_EVENT_PAL_TAG_SEAGALLOP               0x1138
#define OBJ_EVENT_PAL_TAG_SS_ANNE                 0x1139

#define OBJ_EVENT_PAL_TAG_CELEBI                  0x1125
#define OBJ_EVENT_PAL_TAG_RIVAL_HOP               0x1126
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_BUGSY         0x1127
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_CHUCK         0x1128
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_CLAIR         0x1129
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_FALKNER       0x112A
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_JASMINE       0x112B
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_KAREN         0x112C
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_MORTY         0x112D
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_PRYCE         0x112E
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_WHITNEY       0x112F
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_WILL          0x1130
#define OBJ_EVENT_PAL_TAG_JOHTO_NPC_RED           0x1131
#define OBJ_EVENT_PAL_TAG_KANTO_NPC_PINK          0x1132
#define OBJ_EVENT_PAL_TAG_KANTO_NPC_GREEN         0x1133
#define OBJ_EVENT_PAL_TAG_KANTO_NPC_WHITE         0x1134
#define OBJ_EVENT_PAL_TAG_KANTO_NPC_BLUE          0x1135
#define OBJ_EVENT_PAL_TAG_PLAYER                  0x1136
#define OBJ_EVENT_PAL_TAG_RIVAL_RED               0x119F
#define OBJ_EVENT_PAL_TAG_RIVAL_LEAF             OBJ_EVENT_PAL_TAG_RIVAL_RED
#define OBJ_EVENT_PAL_TAG_RIVAL_ETHAN            0x11A0
#define OBJ_EVENT_PAL_TAG_RIVAL_LYRA             0x11A1
#define OBJ_EVENT_PAL_TAG_RIVAL_BRENDAN          0x11A2
#define OBJ_EVENT_PAL_TAG_RIVAL_MAY              0x11A3
#define OBJ_EVENT_PAL_TAG_RIVAL_LUCAS            0x11A4
#define OBJ_EVENT_PAL_TAG_RIVAL_DAWN             0x11A5
#define OBJ_EVENT_PAL_TAG_RIVAL_HILBERT          0x11A6
#define OBJ_EVENT_PAL_TAG_RIVAL_HILDA            0x11A7
#define OBJ_EVENT_PAL_TAG_RIVAL_NATE             0x11A8
#define OBJ_EVENT_PAL_TAG_RIVAL_ROSA             0x11A9
#define OBJ_EVENT_PAL_TAG_RIVAL_CALEM            0x11AA
#define OBJ_EVENT_PAL_TAG_RIVAL_SERENA           0x11AB
#define OBJ_EVENT_PAL_TAG_RIVAL_ELIO             0x11AC
#define OBJ_EVENT_PAL_TAG_RIVAL_SELENE           0x11AD
#define OBJ_EVENT_PAL_TAG_RIVAL_VICTOR           0x11AE
#define OBJ_EVENT_PAL_TAG_RIVAL_GLORIA           0x11AF
#define OBJ_EVENT_PAL_TAG_RIVAL_FLORIAN          0x11B0
#define OBJ_EVENT_PAL_TAG_RIVAL_JULIANA          0x11B1

#define OBJ_EVENT_PAL_TAG_TEAM_FLARE_LYSANDER     0x11B2
#define OBJ_EVENT_PAL_TAG_TEAM_GALACTIC_CYRUS     0x11B3
#define OBJ_EVENT_PAL_TAG_TEAM_NEO_PLASMA_COLRESS 0x11B4
#define OBJ_EVENT_PAL_TAG_TEAM_PLASMA_GHETSIS     0x11B5
#define OBJ_EVENT_PAL_TAG_TEAM_ROCKET_ARCHER      0x11B6
#define OBJ_EVENT_PAL_TAG_TEAM_ROCKET_ARIANA      0x11B7
#define OBJ_EVENT_PAL_TAG_TEAM_ROCKET_PETREL      0x11B8
#define OBJ_EVENT_PAL_TAG_TEAM_ROCKET_PROTON      0x11B9
#define OBJ_EVENT_PAL_TAG_TRUCK_F                 0x11C0
#define OBJ_EVENT_PAL_TAG_PLAYER_RED              0x11C1
#define OBJ_EVENT_PAL_TAG_PLAYER_LEAF             0x11C2
#define OBJ_EVENT_PAL_TAG_PLAYER_RED_REFLECTION   0x11C3
#define OBJ_EVENT_PAL_TAG_PLAYER_LEAF_REFLECTION  0x11C4


#define OBJ_EVENT_PAL_TAG_SINNOH_AARON           0x11C5
#define OBJ_EVENT_PAL_TAG_SINNOH_BERTHA          0x11C6
#define OBJ_EVENT_PAL_TAG_SINNOH_BYRON           0x11C7
#define OBJ_EVENT_PAL_TAG_SINNOH_CRASHER_WAKE    0x11C8
#define OBJ_EVENT_PAL_TAG_SINNOH_CYNTHIA         0x11C9
#define OBJ_EVENT_PAL_TAG_SINNOH_FANTINA         0x11CA
#define OBJ_EVENT_PAL_TAG_SINNOH_FLINT           0x11CB
#define OBJ_EVENT_PAL_TAG_SINNOH_GARDENIA        0x11CC
#define OBJ_EVENT_PAL_TAG_SINNOH_LUCIAN          0x11CD
#define OBJ_EVENT_PAL_TAG_SINNOH_ROARK           0x11CE
#define OBJ_EVENT_PAL_TAG_SINNOH_VOLKNER         0x11CF
#define OBJ_EVENT_PAL_TAG_SINNOH_CANDICE         0x11D0
#define OBJ_EVENT_PAL_TAG_SINNOH_MAYLENE         0x11D1

#define OBJ_EVENT_PAL_TAG_UNOVA_ALDER            0x11D2
#define OBJ_EVENT_PAL_TAG_UNOVA_BRYCEN           0x11D3
#define OBJ_EVENT_PAL_TAG_UNOVA_CAITLIN          0x11D4
#define OBJ_EVENT_PAL_TAG_UNOVA_CLAY             0x11D5
#define OBJ_EVENT_PAL_TAG_UNOVA_DRAYDEN          0x11D6
#define OBJ_EVENT_PAL_TAG_UNOVA_ELESA            0x11D7
#define OBJ_EVENT_PAL_TAG_UNOVA_GRIMSLY          0x11D8
#define OBJ_EVENT_PAL_TAG_UNOVA_IRIS             0x11D9
#define OBJ_EVENT_PAL_TAG_UNOVA_LENORA           0x11DA
#define OBJ_EVENT_PAL_TAG_UNOVA_MARLON           0x11DB
#define OBJ_EVENT_PAL_TAG_UNOVA_MARSHAL          0x11DC
#define OBJ_EVENT_PAL_TAG_UNOVA_CHILI            0x11DD
#define OBJ_EVENT_PAL_TAG_UNOVA_CILAN            0x11DE
#define OBJ_EVENT_PAL_TAG_UNOVA_CRESS            0x11DF
#define OBJ_EVENT_PAL_TAG_UNOVA_SHAUNTAL         0x11E0
#define OBJ_EVENT_PAL_TAG_UNOVA_SKYLA            0x11E1
#define OBJ_EVENT_PAL_TAG_UNOVA_BURGH            0x11E2
#define OBJ_EVENT_PAL_TAG_UNOVA_ROXIE            0x11E3

#define OBJ_EVENT_PAL_TAG_KALOS_CLEMENT          0x11E4
#define OBJ_EVENT_PAL_TAG_KALOS_DIANTHA          0x11E5
#define OBJ_EVENT_PAL_TAG_KALOS_DRASNA           0x11E6
#define OBJ_EVENT_PAL_TAG_KALOS_GRANT            0x11E7
#define OBJ_EVENT_PAL_TAG_KALOS_KORRINA          0x11E8
#define OBJ_EVENT_PAL_TAG_KALOS_MALVA            0x11E9
#define OBJ_EVENT_PAL_TAG_KALOS_OLYMPIA          0x11EA
#define OBJ_EVENT_PAL_TAG_KALOS_RAMOS            0x11EB
#define OBJ_EVENT_PAL_TAG_KALOS_SIEBOLD          0x11EC
#define OBJ_EVENT_PAL_TAG_KALOS_VALERIE          0x11ED
#define OBJ_EVENT_PAL_TAG_KALOS_VIOLA            0x11EE
#define OBJ_EVENT_PAL_TAG_KALOS_WIKSTROM         0x11EF
#define OBJ_EVENT_PAL_TAG_KALOS_WULFRIC          0x11F0

#define OBJ_EVENT_PAL_TAG_ALOLA_ACEROLA          0x11F1
#define OBJ_EVENT_PAL_TAG_ALOLA_HALA             0x11F2
#define OBJ_EVENT_PAL_TAG_ALOLA_HAPU             0x11F3
#define OBJ_EVENT_PAL_TAG_ALOLA_ILIMA            0x11F4
#define OBJ_EVENT_PAL_TAG_ALOLA_KAHILI           0x11F5
#define OBJ_EVENT_PAL_TAG_ALOLA_KIAWE            0x11F6
#define OBJ_EVENT_PAL_TAG_ALOLA_KUKUI            0x11F7
#define OBJ_EVENT_PAL_TAG_ALOLA_LANA             0x11F8
#define OBJ_EVENT_PAL_TAG_ALOLA_MALLOW           0x11F9
#define OBJ_EVENT_PAL_TAG_ALOLA_MINA             0x11FA
#define OBJ_EVENT_PAL_TAG_ALOLA_MOLAYNE          0x11FB
#define OBJ_EVENT_PAL_TAG_ALOLA_NANU             0x11FC
#define OBJ_EVENT_PAL_TAG_ALOLA_OLIVIA           0x11FD
#define OBJ_EVENT_PAL_TAG_ALOLA_SOPHOCLES        0x11FE

#define OBJ_EVENT_PAL_TAG_GALAR_ALLISTER         0x1200
#define OBJ_EVENT_PAL_TAG_GALAR_BEA              0x1201
#define OBJ_EVENT_PAL_TAG_GALAR_GORDIE           0x1202
#define OBJ_EVENT_PAL_TAG_GALAR_KABU             0x1203
#define OBJ_EVENT_PAL_TAG_GALAR_LEON             0x1204
#define OBJ_EVENT_PAL_TAG_GALAR_MELONY           0x1205
#define OBJ_EVENT_PAL_TAG_GALAR_MILO             0x1206
#define OBJ_EVENT_PAL_TAG_GALAR_NESSA            0x1207
#define OBJ_EVENT_PAL_TAG_GALAR_OPAL             0x1208
#define OBJ_EVENT_PAL_TAG_GALAR_PIERS            0x1209
#define OBJ_EVENT_PAL_TAG_GALAR_RAIHAN           0x120A

#define OBJ_EVENT_PAL_TAG_PALDEA_BRASSIUS        0x120B
#define OBJ_EVENT_PAL_TAG_PALDEA_GRUSHA          0x120C
#define OBJ_EVENT_PAL_TAG_PALDEA_IONO            0x120D
#define OBJ_EVENT_PAL_TAG_PALDEA_KATY            0x120E
#define OBJ_EVENT_PAL_TAG_PALDEA_KOFU            0x120F
#define OBJ_EVENT_PAL_TAG_PALDEA_LARRY           0x1210
#define OBJ_EVENT_PAL_TAG_PALDEA_RYME            0x1211
#define OBJ_EVENT_PAL_TAG_PALDEA_GEETA           0x1212
#define OBJ_EVENT_PAL_TAG_PALDEA_HASSEL          0x1213
#define OBJ_EVENT_PAL_TAG_PALDEA_POPPY           0x1214
#define OBJ_EVENT_PAL_TAG_PALDEA_RIKA            0x1215
#define OBJ_EVENT_PAL_TAG_PALDEA_TULIP           0x1216

#define OBJ_EVENT_PAL_TAG_RIVAL_AVERY            0x1217
#define OBJ_EVENT_PAL_TAG_RIVAL_BARRY            0x1218
#define OBJ_EVENT_PAL_TAG_RIVAL_BEDE             0x1219
#define OBJ_EVENT_PAL_TAG_RIVAL_BIANCA           0x121A
#define OBJ_EVENT_PAL_TAG_RIVAL_CHEREN           0x121B
#define OBJ_EVENT_PAL_TAG_RIVAL_GLADION          0x121C
#define OBJ_EVENT_PAL_TAG_RIVAL_HAU              0x121D
#define OBJ_EVENT_PAL_TAG_RIVAL_HUGH             0x121E
#define OBJ_EVENT_PAL_TAG_RIVAL_KLARA            0x121F
#define OBJ_EVENT_PAL_TAG_RIVAL_MARNIE           0x1220
#define OBJ_EVENT_PAL_TAG_RIVAL_N                0x1221
#define OBJ_EVENT_PAL_TAG_RIVAL_SHAUNA           0x1222
#define OBJ_EVENT_PAL_TAG_RIVAL_SILVER           0x1223
#define OBJ_EVENT_PAL_TAG_RIVAL_TIERNO           0x1224
#define OBJ_EVENT_PAL_TAG_RIVAL_TREVOR           0x1225
#define OBJ_EVENT_PAL_TAG_RIVAL_NEMONA           0x1226
#define OBJ_EVENT_PAL_TAG_RIVAL_PENNY            0x1227
#define OBJ_EVENT_PAL_TAG_RIVAL_ARVEN            0x1228

#define OBJ_EVENT_PAL_TAG_GLITCH_NPC_KATE        0x1229
#define OBJ_EVENT_PAL_TAG_GLITCH_NPC_ERMA        0x122A
//#define OBJ_EVENT_PAL_TAG_GLITCH_NPC_RAVEN     0x122B
#define OBJ_EVENT_PAL_TAG_GLITCH_NPC_LS7         0x122B
#define OBJ_EVENT_PAL_TAG_GLITCH_NPC_NACHO       0x122C

#define OBJ_EVENT_PAL_TAG_MISC_PEONIA            0x122D
#define OBJ_EVENT_PAL_TAG_ROUTE_EXT              0x122E
#define OBJ_EVENT_PAL_TAG_PLAYER_ASH             0x122F
#define OBJ_EVENT_PAL_TAG_PLAYER_ASH_REFLECTION  0x1230
#define OBJ_EVENT_PAL_TAG_PLAYER_WES             0x1231
#define OBJ_EVENT_PAL_TAG_PLAYER_WES_REFLECTION  0x1232

#define OBJ_EVENT_PAL_TAG_PLAYER_ETHAN           0x1233
#define OBJ_EVENT_PAL_TAG_PLAYER_ETHAN_REFLECTION 0x1234
#define OBJ_EVENT_PAL_TAG_PLAYER_LYRA            0x1235
#define OBJ_EVENT_PAL_TAG_PLAYER_LYRA_REFLECTION 0x1236
#define OBJ_EVENT_PAL_TAG_PLAYER_LUCAS           0x1237
#define OBJ_EVENT_PAL_TAG_PLAYER_LUCAS_REFLECTION 0x1238
#define OBJ_EVENT_PAL_TAG_PLAYER_DAWN            0x1239
#define OBJ_EVENT_PAL_TAG_PLAYER_DAWN_REFLECTION 0x123A
#define OBJ_EVENT_PAL_TAG_PLAYER_HILBERT         0x123B
#define OBJ_EVENT_PAL_TAG_PLAYER_HILBERT_REFLECTION 0x123C
#define OBJ_EVENT_PAL_TAG_PLAYER_HILDA           0x123D
#define OBJ_EVENT_PAL_TAG_PLAYER_HILDA_REFLECTION 0x123E
#define OBJ_EVENT_PAL_TAG_PLAYER_NATE            0x123F
#define OBJ_EVENT_PAL_TAG_PLAYER_NATE_REFLECTION 0x1240
#define OBJ_EVENT_PAL_TAG_PLAYER_ROSA            0x1241
#define OBJ_EVENT_PAL_TAG_PLAYER_ROSA_REFLECTION 0x1242
#define OBJ_EVENT_PAL_TAG_PLAYER_CALEM           0x1243
#define OBJ_EVENT_PAL_TAG_PLAYER_CALEM_REFLECTION 0x1244
#define OBJ_EVENT_PAL_TAG_PLAYER_SERENA          0x1245
#define OBJ_EVENT_PAL_TAG_PLAYER_SERENA_REFLECTION 0x1246
#define OBJ_EVENT_PAL_TAG_PLAYER_ELIO            0x1247
#define OBJ_EVENT_PAL_TAG_PLAYER_ELIO_REFLECTION 0x1248
#define OBJ_EVENT_PAL_TAG_PLAYER_SELENE          0x1249
#define OBJ_EVENT_PAL_TAG_PLAYER_SELENE_REFLECTION 0x124A
#define OBJ_EVENT_PAL_TAG_PLAYER_VICTOR          0x124B
#define OBJ_EVENT_PAL_TAG_PLAYER_VICTOR_REFLECTION 0x124C
#define OBJ_EVENT_PAL_TAG_PLAYER_GLORIA          0x124D
#define OBJ_EVENT_PAL_TAG_PLAYER_GLORIA_REFLECTION 0x124E
#define OBJ_EVENT_PAL_TAG_PLAYER_FLORIAN         0x124F
#define OBJ_EVENT_PAL_TAG_PLAYER_FLORIAN_REFLECTION 0x1250
#define OBJ_EVENT_PAL_TAG_PLAYER_JULIANA         0x1251
#define OBJ_EVENT_PAL_TAG_PLAYER_JULIANA_REFLECTION 0x1252
#define OBJ_EVENT_PAL_TAG_RIVAL_ASH              0x1253
#define OBJ_EVENT_PAL_TAG_RIVAL_WES              0x1254
#define OBJ_EVENT_PAL_TAG_TEAM_ROCKET_M_F        0x1255
#define OBJ_EVENT_PAL_TAG_FOLLOW_MON_0            0x1256
#define OBJ_EVENT_PAL_TAG_TEAM_FLARE_GUNT       0x1257
#define OBJ_EVENT_PAL_TAG_ENTEI                   0x1258
#define OBJ_EVENT_PAL_TAG_RAIKOU                  0x1259
#define OBJ_EVENT_PAL_TAG_SUICUNE                 0x125A
#define OBJ_EVENT_PAL_TAG_ARTICUNO                0x125B
#define OBJ_EVENT_PAL_TAG_MOLTRES                 0x125C
#define OBJ_EVENT_PAL_TAG_ZAPDOS                  0x125D
#define OBJ_EVENT_PAL_TAG_Nurse_OW                0x125E
#define OBJ_EVENT_PAL_TAG_Rocky                   0x125F
#define OBJ_EVENT_PAL_TAG_LANDORUS                0x1260
#define OBJ_EVENT_PAL_TAG_JAMES_ROCKET            0x1261
#define OBJ_EVENT_PAL_TAG_ROGUE_EGG               0x1262
#define OBJ_EVENT_PAL_TAG_ETHAN_FIELD_MOVE        0x1263
#define OBJ_EVENT_PAL_TAG_AZURILL_OW              0x1264
#define OBJ_EVENT_PAL_TAG_UXIE                    0x1266
#define OBJ_EVENT_PAL_TAG_LYRA_FIELD_MOVE         0x1267
#define OBJ_EVENT_PAL_TAG_HILBERT_FIELD_MOVE      0x1268
#define OBJ_EVENT_PAL_TAG_HILDA_FIELD_MOVE        0x1269
#define OBJ_EVENT_PAL_TAG_LUCAS_MACH_BIKE         0x126A
#define OBJ_EVENT_PAL_TAG_LUCAS_FIELD_MOVE        0x126B
//Platinum
#define OBJ_EVENT_PAL_TAG_DP_CYNTHIA              0x126C
#define OBJ_EVENT_PAL_TAG_DP_AARON                0x126D
#define OBJ_EVENT_PAL_TAG_DP_ACE_TRAINERF         0x126E
#define OBJ_EVENT_PAL_TAG_DP_ACE_TRAINERM         0x126F
#define OBJ_EVENT_PAL_TAG_DP_ACE_TRAINER_SNOWM    0x1270
#define OBJ_EVENT_PAL_TAG_DP_BARRY                0x1271
#define OBJ_EVENT_PAL_TAG_DP_BATTLE_GIRL          0x1272
#define OBJ_EVENT_PAL_TAG_DP_BEAUTY               0x1273
#define OBJ_EVENT_PAL_TAG_DP_BERTHA               0x1274
#define OBJ_EVENT_PAL_TAG_DP_BLACK_BELT           0x1275
#define OBJ_EVENT_PAL_TAG_DP_BREEDERF             0x1276
#define OBJ_EVENT_PAL_TAG_DP_BUG_CATCHER          0x1277
#define OBJ_EVENT_PAL_TAG_DP_BYRON                0x1278
#define OBJ_EVENT_PAL_TAG_DP_CAMPER               0x1279
#define OBJ_EVENT_PAL_TAG_DP_CHARON               0x127A
#define OBJ_EVENT_PAL_TAG_DP_CHERYL               0x127B
#define OBJ_EVENT_PAL_TAG_DP_COWGIRL              0x127C
#define OBJ_EVENT_PAL_TAG_DP_CRASHER_WAKE         0x127D
#define OBJ_EVENT_PAL_TAG_DP_CYRUS                0x127E
#define OBJ_EVENT_PAL_TAG_DP_DRAGON_TAMER         0x127F
#define OBJ_EVENT_PAL_TAG_DP_FANTINA              0x1280
#define OBJ_EVENT_PAL_TAG_DP_FISHERMAN            0x1281
#define OBJ_EVENT_PAL_TAG_DP_GALACTIC_GRUNTF      0x1282
#define OBJ_EVENT_PAL_TAG_DP_GALACTIC_GRUNTM      0x1283
#define OBJ_EVENT_PAL_TAG_DP_GENTLEMAN            0x1284
#define OBJ_EVENT_PAL_TAG_DP_HIKER                0x1285
#define OBJ_EVENT_PAL_TAG_DP_JUPITER              0x1286
#define OBJ_EVENT_PAL_TAG_DP_LADY                 0x1287
#define OBJ_EVENT_PAL_TAG_DP_LOOKER               0x1288
#define OBJ_EVENT_PAL_TAG_DP_LUCIAN               0x1289
#define OBJ_EVENT_PAL_TAG_DP_MARLEY               0x128A
#define OBJ_EVENT_PAL_TAG_DP_MARS                 0x128B
#define OBJ_EVENT_PAL_TAG_DP_MAYLENE              0x128C
#define OBJ_EVENT_PAL_TAG_DP_MIRA                 0x128D
#define OBJ_EVENT_PAL_TAG_DP_OFFICER              0x128E
#define OBJ_EVENT_PAL_TAG_DP_PAINTER              0x128F
#define OBJ_EVENT_PAL_TAG_DP_PALMER               0x1290
#define OBJ_EVENT_PAL_TAG_DP_PARASOL_LADY         0x1291
#define OBJ_EVENT_PAL_TAG_DP_PICNICKER            0x1292
#define OBJ_EVENT_PAL_TAG_DP_POKE_KID             0x1293
#define OBJ_EVENT_PAL_TAG_DP_POKE_RANGERF         0x1294
#define OBJ_EVENT_PAL_TAG_DP_POKE_RANGERM         0x1295
#define OBJ_EVENT_PAL_TAG_DP_POKE_FAN_F            0x1296
#define OBJ_EVENT_PAL_TAG_DP_POKE_FAN_M            0x1297
#define OBJ_EVENT_PAL_TAG_DP_ROWAN                0x1298
#define OBJ_EVENT_PAL_TAG_DP_PSYCHIC              0x1299
#define OBJ_EVENT_PAL_TAG_DP_RANCHER              0x129A
#define OBJ_EVENT_PAL_TAG_DP_RICH_BOY             0x129B
#define OBJ_EVENT_PAL_TAG_DP_RICH_LADY            0x129C
#define OBJ_EVENT_PAL_TAG_DP_ROCKER               0x129D
#define OBJ_EVENT_PAL_TAG_DP_ROUGHNECK            0x129E
#define OBJ_EVENT_PAL_TAG_DP_RUIN_MANIAC          0x129F
#define OBJ_EVENT_PAL_TAG_DP_SAILOR               0x12A0
#define OBJ_EVENT_PAL_TAG_DP_SATURN               0x12A1
#define OBJ_EVENT_PAL_TAG_DP_SCIENTIST            0x12A2
#define OBJ_EVENT_PAL_TAG_DP_SKIERF               0x12A3
#define OBJ_EVENT_PAL_TAG_DP_SKIERM               0x12A4
#define OBJ_EVENT_PAL_TAG_DP_SOCIALITE            0x12A5
#define OBJ_EVENT_PAL_TAG_DP_SUPERNERD            0x12A6
#define OBJ_EVENT_PAL_TAG_DP_SWIMMERF             0x12A7
#define OBJ_EVENT_PAL_TAG_DP_SWIMMERF2            0x12A8
#define OBJ_EVENT_PAL_TAG_DP_SWIMMERM             0x12A9
#define OBJ_EVENT_PAL_TAG_DP_SWIMMERM2            0x12AA
#define OBJ_EVENT_PAL_TAG_DP_VOLKNER              0x12AB
#define OBJ_EVENT_PAL_TAG_DP_WAITER               0x12AC
#define OBJ_EVENT_PAL_TAG_DP_WAITRESS             0x12AD
#define OBJ_EVENT_PAL_TAG_DP_WORKER               0x12AE
#define OBJ_EVENT_PAL_TAG_DP_YOUNG_COUPLEF        0x12AF
#define OBJ_EVENT_PAL_TAG_DP_YOUNG_COUPLEM        0x12B0
#define OBJ_EVENT_PAL_TAG_DP_YOUNGSTER            0x12B1
#define OBJ_EVENT_PAL_TAG_LUGIA_SHADOW            0x12B2
#define OBJ_EVENT_PAL_TAG_NPC_OLD_MAN_1           0x12B3
#define OBJ_EVENT_PAL_TAG_NPC_OLD_MAN_2           0x12B4
#define OBJ_EVENT_PAL_TAG_BIG_SNORLAX             0x12B5
#define OBJ_EVENT_PAL_TAG_JESSIE_ROCKET           0x12B6
#define OBJ_EVENT_PAL_TAG_DARKRAI                 0x12B7

#if OW_FOLLOWERS_POKEBALLS
// Vanilla
#define OBJ_EVENT_PAL_TAG_BALL_MASTER             0x1150
#define OBJ_EVENT_PAL_TAG_BALL_ULTRA              0x1151
#define OBJ_EVENT_PAL_TAG_BALL_GREAT              0x1152
#define OBJ_EVENT_PAL_TAG_BALL_SAFARI             0x1153
#define OBJ_EVENT_PAL_TAG_BALL_NET                0x1154
#define OBJ_EVENT_PAL_TAG_BALL_DIVE               0x1155
#define OBJ_EVENT_PAL_TAG_BALL_NEST               0x1156
#define OBJ_EVENT_PAL_TAG_BALL_REPEAT             0x1157
#define OBJ_EVENT_PAL_TAG_BALL_TIMER              0x1158
#define OBJ_EVENT_PAL_TAG_BALL_LUXURY             0x1159
#define OBJ_EVENT_PAL_TAG_BALL_PREMIER            0x115A
// Gen IV/Sinnoh
#define OBJ_EVENT_PAL_TAG_BALL_DUSK               0x115B
#define OBJ_EVENT_PAL_TAG_BALL_HEAL               0x115C
#define OBJ_EVENT_PAL_TAG_BALL_QUICK              0x115D
#define OBJ_EVENT_PAL_TAG_BALL_CHERISH            0x115E
#define OBJ_EVENT_PAL_TAG_BALL_PARK               0x115F
// Gen II/Johto Apricorns
#define OBJ_EVENT_PAL_TAG_BALL_FAST               0x1160
#define OBJ_EVENT_PAL_TAG_BALL_LEVEL              0x1161
#define OBJ_EVENT_PAL_TAG_BALL_LURE               0x1162
#define OBJ_EVENT_PAL_TAG_BALL_HEAVY              0x1163
#define OBJ_EVENT_PAL_TAG_BALL_LOVE               0x1164
#define OBJ_EVENT_PAL_TAG_BALL_FRIEND             0x1165
#define OBJ_EVENT_PAL_TAG_BALL_MOON               0x1166
#define OBJ_EVENT_PAL_TAG_BALL_SPORT              0x1167
// Gen V
#define OBJ_EVENT_PAL_TAG_BALL_DREAM              0x1168
// Gen VII
#define OBJ_EVENT_PAL_TAG_BALL_BEAST              0x1169
// Gen VIII
#define OBJ_EVENT_PAL_TAG_BALL_STRANGE            0x116A
#endif //OW_FOLLOWERS_POKEBALLS
// Used as a placeholder follower graphic
#define OBJ_EVENT_PAL_TAG_SUBSTITUTE              0x7611
#define OBJ_EVENT_PAL_TAG_LIGHT                   0x8001
#define OBJ_EVENT_PAL_TAG_LIGHT_2                 0x8002
#define OBJ_EVENT_PAL_TAG_EMOTES                  0x8003
#define OBJ_EVENT_PAL_TAG_NEON_LIGHT              0x8004
// Not a real OW palette tag; used for the white flash applied to followers
#define OBJ_EVENT_PAL_TAG_WHITE                   (OBJ_EVENT_PAL_TAG_NONE - 1)
#define OBJ_EVENT_PAL_TAG_NONE                    0x11FF

// This + localId is used as the tileTag
// for compressed graphicsInfos
// '(C)ompressed (E)vent'
#define COMP_OW_TILE_TAG_BASE 0xCE00

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
