#ifndef GUARD_CONSTANTS_REGIONS_H
#define GUARD_CONSTANTS_REGIONS_H

// Core-series regions
enum Region
{
    REGION_NONE,
    REGION_KANTO,
    REGION_JOHTO,
    REGION_HOENN,
    REGION_SINNOH,
    REGION_UNOVA,
    REGION_KALOS,
    REGION_ALOLA,
    REGION_GALAR,
    REGION_HISUI,
    REGION_PALDEA,
    REGIONS_COUNT,
};

// Starter region IDs (used for starter selection)
#define STARTER_REGION_KANTO   REGION_KANTO
#define STARTER_REGION_JOHTO   REGION_JOHTO
#define STARTER_REGION_HOENN   REGION_HOENN
#define STARTER_REGION_SINNOH  REGION_SINNOH
#define STARTER_REGION_UNOVA   REGION_UNOVA
#define STARTER_REGION_KALOS   REGION_KALOS
#define STARTER_REGION_ALOLA   REGION_ALOLA
#define STARTER_REGION_GALAR   REGION_GALAR
#define STARTER_REGION_PALDEA  REGION_PALDEA
#define STARTER_REGIONS_COUNT  9

#endif  // GUARD_CONSTANTS_REGIONS_H
