#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(FOCUS_PUNCH) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(SAFEGUARD) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(DOUBLE_TEAM) \
    F(REFLECT) \
    F(SHOCK_WAVE) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(TORMENT) \
    F(FACADE) \
    F(SECRET_POWER) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(STEEL_WING) \
    F(SKILL_SWAP) \
    F(SNATCH) \
    F(OVERHEAT) \
    F(MEGA_PUNCH) \
    F(ICICLE_SPEAR) \
    F(BOUNCE) \
    F(MUD_SHOT) \
    F(ROCK_BLAST) \
    F(BRINE) \
    F(U_TURN) \
    F(PAYBACK) \
    F(ASSURANCE) \
    F(FLING) \
    F(POWER_SWAP) \
    F(GUARD_SWAP) \
    F(SPEED_SWAP) \
    F(DRAIN_PUNCH) \
    F(AVALANCHE) \
    F(SHADOW_CLAW) \
    F(THUNDER_FANG) \
    F(ICE_FANG) \
    F(FIRE_FANG) \
    F(PSYCHO_CUT) \
    F(TRICK_ROOM) \
    F(WONDER_ROOM) \
    F(MAGIC_ROOM) \
    F(POISON_JAB) \
    F(VENOSHOCK) \
    F(LOW_SWEEP) \
    F(ROUND) \
    F(HEX) \
    F(ACROBATICS) \
    F(RETALIATE) \
    F(VOLT_SWITCH) \
    F(BULLDOZE) \
    F(ELECTROWEB) \
    F(RAZOR_SHELL) \
    F(TAIL_SLAP) \
    F(SNARL) \
    F(PHANTOM_FORCE) \
    F(DRAINING_KISS) \
    F(GRASSY_TERRAIN) \
    F(MISTY_TERRAIN) \
    F(ELECTRIC_TERRAIN) \
    F(PSYCHIC_TERRAIN) \
    F(MYSTICAL_FIRE) \
    F(EERIE_IMPULSE) \
    F(FALSE_SWIPE) \
    F(AIR_SLASH) \
    F(SMART_STRIKE) \
    F(BRUTAL_SWING) \
    F(STOMPING_TANTRUM) \
    F(BREAKING_SWIPE)

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
