PacifidlogTown_House1_MapScripts::
	.byte 0

PacifidlogTown_House1_EventScript_Man::
	msgbox PacifidlogTown_House1_Text_RegiStory, MSGBOX_NPC
	end

PacifidlogTown_House1_EventScript_Woman::
	msgbox PacifidlogTown_House1_Text_SixDotsOpenThreeDoors, MSGBOX_NPC
	end

PacifidlogTown_House1_Text_RegiStory:
	.string "Hier in HOENN soll's drei absolute\n"
	.string "Monster-POKéMON geben. Pures Gestein,\l"
	.string "Eis und Stahl.\p"
	.string "Angeblich verkriechen die sich tief in\n"
	.string "irgendwelchen dunklen Höhlen.\p"
	.string "Die Story hat man mir schon reingedrückt,\n"
	.string "als ich noch'n kleiner Hosenscheißer war.$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors:
	.string "“Sechs Punkte öffnen drei Türen.”\p"
	.string "Mein Opa hat den Spruch immer gelabert,\n"
	.string "aber absolut kein Plan, was der alte\l"
	.string "Sack damit meinte.$"

