Aide_Text_HaventCaughtEnoughMons::
	.string "Mal sehen…\n"
	.string "Uff! Du hast erst\n"
	.string "{STR_VAR_3} verschiedene Pokémon!\p"
	.string "Du brauchst mindestens {STR_VAR_1},\n"
	.string "wenn du das {STR_VAR_2} haben willst.$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "Aha, verstehe.\p"
	.string "Sobald du {STR_VAR_1} Pokémon hast,\n"
	.string "kannst du dir das {STR_VAR_2} abholen.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Oh oh!\n"
	.string "Du hast gar keinen Platz mehr\n"
	.string "für das {STR_VAR_2}!$"
