gText_ApprenticeChallenge0::
	.string "Ähm, ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}.\n"
	.string "Schnief… Ich mach mir in die Hose…$"

gText_ApprenticeChallenge1::
	.string "Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}!\n"
	.string "Mach dich bereit zu sterben!$"

gText_ApprenticeChallenge2::
	.string "Ich bin Lehrling Nr. {STR_VAR_2} von {STR_VAR_1}!\n"
	.string "Nimm meine Herausforderung an!$"

gText_ApprenticeChallenge3::
	.string "Ähm… Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}…\n"
	.string "Ich verliere eh, oder?$"

gText_ApprenticeChallenge4::
	.string "Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}!\n"
	.string "Darf ich dich verhauen?$"

gText_ApprenticeChallenge5::
	.string "Ich bin beschäftigt, aber auch\n"
	.string "{STR_VAR_1}s Lehrling Nr. {STR_VAR_2}.$"

gText_ApprenticeChallenge6::
	.string "Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}.\n"
	.string "Freut mich, dich zu zerstören!$"

gText_ApprenticeChallenge7::
	.string "Ich diene {STR_VAR_1} als Lehrling Nr. {STR_VAR_2}.\n"
	.string "Darf ich anfangen?$"

gText_ApprenticeChallenge8::
	.string "Ieek! Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}!\n"
	.string "Bitte tu mir nicht weh!$"

gText_ApprenticeChallenge9::
	.string "Yeehaw! Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}!\n"
	.string "Komm her, Cowboy!$"

gText_ApprenticeChallenge10::
	.string "Ich bin {STR_VAR_1}s 1000. Lehrling!\n"
	.string "Eigentlich Nr. {STR_VAR_2}! Egal!$"

gText_ApprenticeChallenge11::
	.string "Yeah, ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}!\n"
	.string "Lass uns rocken!$"

gText_ApprenticeChallenge12::
	.string "Yippie! Ich bin sozusagen\n"
	.string "{STR_VAR_1}s Lehrling Nr. {STR_VAR_2}!$"

gText_ApprenticeChallenge13::
	.string "Hust! Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2}.\n"
	.string "Steck dich nicht an! Hust!$"

gText_ApprenticeChallenge14::
	.string "Ich hab Angst…\n"
	.string "Ich bin Lehrling Nr. {STR_VAR_2} von {STR_VAR_1}.$"

gText_ApprenticeChallenge15::
	.string "Ich bin {STR_VAR_1}s Lehrling Nr. {STR_VAR_2},\n"
	.string "und das ist kein Witz.$"

gText_ApprenticePleaseTeach0::
	.string "Bist du… {PLAYER}?\n"
	.string "Oh! Schnief… heul…\p"
	.string "Oh! E-Entschuldigung…\n"
	.string "Ich bin so nervös, ich muss heulen…\p"
	.string "Ich bin {STR_VAR_1}, und ich bete dich\n"
	.string "an, {PLAYER}.\p"
	.string "Ich… Ich habe davon geträumt, dich\n"
	.string "zu treffen und dich auszufragen.\p"
	.string "Bitte, bitte, {PLAYER}!\n"
	.string "Bring mir alles über POKéMON bei!$"

gText_ApprenticeRejectTeaching0::
	.string "Oh… A-aber…\n"
	.string "Schnief… Waaaaaaah!\p"
	.string "Bitte!\n"
	.string "Ich flehe dich an!$"

gText_ApprenticeWhichLevelMode0::
	.string "Echt? Du machst es?\n"
	.string "Geil! Krass! Awoooh!\p"
	.string "Oh… Sorry…\n"
	.string "Ich bin so glücklich, ich heule…\p"
	.string "Ähm… Sag mir was!\n"
	.string "Es geht um den DUELLTURM.\p"
	.string "Was ist besser für mich: Level 50\n"
	.string "oder Offen?$"

gText_ApprenticeLevelModeThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! Tut mir leid!\n"
	.string "Du hast entschieden, und das macht\l"
	.string "mich so glücklich…\p"
	.string "Schnief…\n"
	.string "Danke vielmals!\l"
	.string "Rede bitte wieder mit mir!$"

gText_ApprenticePleaseTeach1::
	.string "Wowee! Du bist {PLAYER}, oder?\n"
	.string "Du bist mega stark, oder?\p"
	.string "Ich bin {STR_VAR_1}!\n"
	.string "Ich bin frischgebackener TRAINER!\p"
	.string "Bitte, {PLAYER}!\n"
	.string "Sei mein Lehrer und erzähl mir,\l"
	.string "wie man Leute verprügelt!$"

gText_ApprenticeRejectTeaching1::
	.string "Och, wieso?\n"
	.string "Bütte? Bütte bütte?\l"
	.string "Sei mein Lehrer, bitte!$"

gText_ApprenticeWhichLevelMode1::
	.string "Yay! Super!\p"
	.string "Erste Frage zum DUELLTURM!\n"
	.string "Level 50 oder Offen…\n"
	.string "Was ist perfekt für mich?$"

gText_ApprenticeLevelModeThanks1::
	.string "{STR_VAR_1}, hä? Stimmt!\n"
	.string "Ich geb mein Bestes!\p"
	.string "Wenn wir uns wiedersehen, bring mir\n"
	.string "mehr bei, Meister!$"

gText_ApprenticePleaseTeach2::
	.string "Ähm… Bist du {PLAYER}?\n"
	.string "Ich heiße {STR_VAR_1}.\p"
	.string "Ich will POKéMON TRAINER werden,\n"
	.string "aber ich bin dumm…\p"
	.string "Also dachte ich, ich frage dich,\n"
	.string "weil du berühmt bist.\p"
	.string "{PLAYER}, gibst du mir Rat?$"

gText_ApprenticeRejectTeaching2::
	.string "Oh, aber…\p"
	.string "Ich will wirklich POKéMON TRAINER\n"
	.string "werden!\p"
	.string "Bitte, antworte mir!$"

gText_ApprenticeWhichLevelMode2::
	.string "Danke!\n"
	.string "Erste Frage sofort!\p"
	.string "Der DUELLTURM hat zwei Level,\n"
	.string "Level 50 und Offen, richtig?\p"
	.string "Was passt besser zu mir?$"

gText_ApprenticeLevelModeThanks2::
	.string "Oh, die {STR_VAR_1}-Herausforderung?\n"
	.string "Verstanden!\p"
	.string "Wenn ich noch was wissen will, komm\n"
	.string "ich wieder und nerve dich!$"

gText_ApprenticePleaseTeach3::
	.string "Oh? Hä? Du bist…\n"
	.string "Nein, das kann nicht sein.\p"
	.string "Jemand wie ich trifft niemals\n"
	.string "{PLAYER}.\p"
	.string "…Du bist wirklich {PLAYER}?\n"
	.string "Ich glaub’s nicht!\p"
	.string "Wenn sowas Gutes passiert,\n"
	.string "passiert gleich was Schreckliches…\p"
	.string "…Sorry…\n"
	.string "Ich bin… {STR_VAR_1}…\p"
	.string "Ich bin ein Niemand…\n"
	.string "Ich sollte nichts sagen, du\n"
	.string "vergisst es eh…\p"
	.string "Ich träumte davon, dich zu treffen,\n"
	.string "{PLAYER}, und dich um Rat zu fragen.\p"
	.string "Aber du willst sicher nicht.\n"
	.string "…Oder bist du so nett?$"

gText_ApprenticeRejectTeaching3::
	.string "Wusste ich’s doch…\p"
	.string "War klar, weil ich langweilig bin…\p"
	.string "Aber ich dachte vielleicht…\n"
	.string "Du überlegst es dir nicht anders?\p"
	.string "Ich kann nicht aufgeben.\n"
	.string "Ich frage nochmal!\p"
	.string "Bitte, gib mir Rat!$"

gText_ApprenticeWhichLevelMode3::
	.string "Echt? Ich glaub’s nicht!\n"
	.string "Du hilfst mir!\l"
	.string "Ich… bin so glücklich…\p"
	.string "Ich will was Dummes fragen,\n"
	.string "aber ich kann mich nicht entscheiden…\p"
	.string "Im DUELLTURM gibt es Level 50\n"
	.string "oder Offen.\p"
	.string "Wo habe ich eine Chance?$"

gText_ApprenticeLevelModeThanks3::
	.string "{STR_VAR_1}? Okay!\n"
	.string "Meinst du echt, ich schaff das?\p"
	.string "Ich versuche es, auch wenn es\n"
	.string "sicher schiefgeht.\p"
	.string "Danke, dass du Zeit mit einem\n"
	.string "Versager verbringst.$"

gText_ApprenticePleaseTeach4::
	.string "Oh! Du bist {PLAYER}{KUN}, oder?\p"
	.string "Man sagt, du bist hart drauf!\p"
	.string "Ich bin {STR_VAR_1}!\n"
	.string "Ich will dein Freund sein!\p"
	.string "Wusstest du?\p"
	.string "Man gewinnt nicht in der KAMPFZONE,\n"
	.string "wenn man nur Schulkram weiß.\p"
	.string "Ich höre auf deinen Rat.\n"
	.string "Du sagst ja, oder?$"

gText_ApprenticeRejectTeaching4::
	.string "Hä? Warum lehnst du ab?\n"
	.string "Ich bin es, der fragt!\l"
	.string "Überleg es dir!$"

gText_ApprenticeWhichLevelMode4::
	.string "Okay, da ist was.\n"
	.string "Entscheide für mich.\p"
	.string "DUELLTURM, Level 50 und Offen.\n"
	.string "Was ist gut für mich, {PLAYER}{KUN}?$"

gText_ApprenticeLevelModeThanks4::
	.string "Okay, {STR_VAR_1} passt?\n"
	.string "Danke!\p"
	.string "Da du entschieden hast,\n"
	.string "{PLAYER}{KUN}, bin ich nicht sauer,\l"
	.string "wenn ich verliere.\p"
	.string "Okay, ich frag dich wieder.\n"
	.string "Bye!$"

gText_ApprenticePleaseTeach5::
	.string "Oh, hi! {PLAYER}{KUN}!\n"
	.string "Ich kenn dich, du bist berühmt!\l"
	.string "Nenn mich {STR_VAR_1}! Freut mich!\p"
	.string "Ich bin TRIATHLET, also fit.\n"
	.string "Ich mache auch andere Sachen,\n"
	.string "Arbeit, Schlafen, Tanzen…\p"
	.string "Viel zu tun, schwer ein guter\n"
	.string "TRAINER zu sein.\p"
	.string "Vorschlag!\p"
	.string "Teil deine Weisheit mit mir,\n"
	.string "{PLAYER}{KUN}!$"

gText_ApprenticeRejectTeaching5::
	.string "Och, bitte?\n"
	.string "Ein Typ wie ich braucht dich,\l"
	.string "{PLAYER}{KUN}!\p"
	.string "Ehrlich, ich brauch Hilfe!$"

gText_ApprenticeWhichLevelMode5::
	.string "Danke! So gefällt mir das!\n"
	.string "Fangen wir leicht an!\p"
	.string "DUELLTURM Kurse, weißt du?\l"
	.string "Level 50 und Offen.\p"
	.string "Ich bin beschäftigt, was soll ich\n"
	.string "nehmen?$"

gText_ApprenticeLevelModeThanks5::
	.string "{STR_VAR_1}, hä? Okay, kapiert.\n"
	.string "Ich finde Zeit und probier es!\p"
	.string "…Hoppla, Arbeit ruft!\n"
	.string "Danke! Man sieht sich!$"

gText_ApprenticePleaseTeach6::
	.string "Nein! Uh-uh!\n"
	.string "Bist du der echte {PLAYER}?\p"
	.string "A-hah! Geil! Ich bin {STR_VAR_1},\n"
	.string "freut mich voll!\p"
	.string "{PLAYER}, du bist stark, oder?\p"
	.string "Alle reden über dich!\p"
	.string "Oh! Idee!\n"
	.string "Gib mir Tipps, {PLAYER}!\l"
	.string "Das macht mich härter!\p"
	.string "Gute Idee, oder?\n"
	.string "Bitte, gib mir Tipps!$"

gText_ApprenticeRejectTeaching6::
	.string "Ahahaha, tu nicht so gemein,\n"
	.string "du kannst mich nicht täuschen!\l"
	.string "Du meinst ja, oder?$"

gText_ApprenticeWhichLevelMode6::
	.string "Yay! Ich wusste, du hast ein Herz,\n"
	.string "{PLAYER}!\p"
	.string "Was frag ich zuerst?\n"
	.string "…Oh, ich hab was!\p"
	.string "Trommelwirbel!\n"
	.string "Die Frage ist…\p"
	.string "DUELLTURM Herausforderung,\n"
	.string "welcher Weg?\p"
	.string "Level 50 oder Offen?\n"
	.string "Was passt?$"

gText_ApprenticeLevelModeThanks6::
	.string "Oh-oh-oh!\n"
	.string "{STR_VAR_1}, sagst du!\l"
	.string "Danke für die coole Antwort!\p"
	.string "Das war’s für heute.\p"
	.string "Treffen wir uns wieder hier?\n"
	.string "Danke!$"

gText_ApprenticePleaseTeach7::
	.string "Entschuldigung, aber…\n"
	.string "Bist du {PLAYER}?\p"
	.string "Ich bin {STR_VAR_1}, freut mich sehr.\p"
	.string "Ich bewundere dich schon lange…\p"
	.string "… … … … … …\p"
	.string "Ähm… Ist das zu viel verlangt?\n"
	.string "Darf ich dein Lehrling werden,\n"
	.string "{PLAYER}?$"

gText_ApprenticeRejectTeaching7::
	.string "Oh…!\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "…Ich bin fast ohnmächtig geworden.\n"
	.string "Ich hab mich verhört, oder?\p"
	.string "Bitte! Bitte sag ja!$"

gText_ApprenticeWhichLevelMode7::
	.string "Oh… Ich bin entzückt!\p"
	.string "Ich will deine Zeit nicht stehlen,\n"
	.string "also rate mir dies.\p"
	.string "Ich will zum DUELLTURM.\p"
	.string "Es gibt zwei Level…\p"
	.string "Was passt zu mir?\n"
	.string "Level 50 oder Offen?$"

gText_ApprenticeLevelModeThanks7::
	.string "{STR_VAR_1} ist deine Wahl!\n"
	.string "Verstehe. Ich gebe alles!\p"
	.string "Danke, {PLAYER}.\n"
	.string "Hoffentlich hilfst du mir wieder.\l"
	.string "Pass auf dich auf!$"

gText_ApprenticePleaseTeach8::
	.string "Ieek! Ieek! {PLAYER}!\n"
	.string "Du hast mit mir geredet!\l"
	.string "Ich… Ich flipp aus!\p"
	.string "Ich! Ich heiße {STR_VAR_1}!\n"
	.string "Bin grad TRAINER geworden!\p"
	.string "Freut mich so, {PLAYER},\n"
	.string "der POKéMON-Star!\p"
	.string "Oh-oh-oh, ich weiß!\n"
	.string "Darf ich was fragen, {PLAYER}?\p"
	.string "Nimm mich als Lehrling!\n"
	.string "Ich will lernen!$"

gText_ApprenticeRejectTeaching8::
	.string "Waaaah!\n"
	.string "{PLAYER} hat mich abgelehnt…\l"
	.string "Das… Das ist eine Erfahrung!\p"
	.string "{PLAYER}, bitte! Sag ja!\p"
	.string "Ich flehe dich an!$"

gText_ApprenticeWhichLevelMode8::
	.string "Hieeeeh! {PLAYER} hat ja gesagt!\n"
	.string "{PLAYER} hat ja gesagt!\p"
	.string "Ich kann nicht schlafen…\n"
	.string "Danke tausendmal!\p"
	.string "Hier ist meine Frage!\p"
	.string "DUELLTURM, was ist richtig für mich,\n"
	.string "Level 50 oder Offen?$"

gText_ApprenticeLevelModeThanks8::
	.string "{STR_VAR_1}! Verstanden!\n"
	.string "Ich hab’s kapiert!\l"
	.string "Ich bin im Delirium vor Freude!\p"
	.string "Hoffentlich bringst du mir mehr bei.$"

gText_ApprenticePleaseTeach9::
	.string "Whoa! Bist du…\n"
	.string "Bist du vielleicht {PLAYER}{KUN}?!\l"
	.string "Der starke, berühmte TRAINER?\l"
	.string "Hallo, hab ich ein Glück!\p"
	.string "Hallo, ich bin {STR_VAR_1}!\p"
	.string "Ich suchte einen POKéMON-Lehrer.\p"
	.string "Und zack, da bist du, {PLAYER}{KUN}!\p"
	.string "Also, {PLAYER}{KUN}!\n"
	.string "Lass mich dein Lehrling sein!$"

gText_ApprenticeRejectTeaching9::
	.string "Gwaaaah!\n"
	.string "Du bist ziemlich kühl…\p"
	.string "Sei nicht so.\n"
	.string "Ich frag dich!$"

gText_ApprenticeWhichLevelMode9::
	.string "Oh, ja! Solide Antwort!\n"
	.string "Exzellent!\p"
	.string "Erster Rat zum DUELLTURM?\p"
	.string "Wenn ich gehe, was ist besser?\n"
	.string "Level 50 oder Offen?$"

gText_ApprenticeLevelModeThanks9::
	.string "Uh-huh, {STR_VAR_1} also!\n"
	.string "OK, alles klar!\l"
	.string "Ich zeig’s denen!\p"
	.string "Alles klar, mein Mentor!\n"
	.string "Adios!$"

gText_ApprenticePleaseTeach10::
	.string "Oh, hey, {PLAYER}{KUN}, oder?\n"
	.string "Die Polizei sucht dich!\p"
	.string "… … …\n"
	.string "War gelogen!\p"
	.string "Ich bin {STR_VAR_1}. Trotz Aussehen\n"
	.string "bin ich POKéMON CHAMP!\l"
	.string "…Auch gelogen!\p"
	.string "Aber das nicht.\n"
	.string "Ich kann nicht kämpfen.\p"
	.string "Wirst du mein Meister?$"

gText_ApprenticeRejectTeaching10::
	.string "Wenn du so kalt bist,\n"
	.string "zeig ich dir was!\p"
	.string "Waaah! Waaah! Waaah!\n"
	.string "Hicks!\p"
	.string "Hahaha, das waren TRUGTRÄNEN!\p"
	.string "Komm schon, sei mein Meister!$"

gText_ApprenticeWhichLevelMode10::
	.string "Yippie!\n"
	.string "Ich kauf dir ein Boot!\p"
	.string "Wieder gelogen!\n"
	.string "Aber… Danke, Meister!\p"
	.string "DUELLTURM hat Level 50 und Offen.\p"
	.string "Ich kann mich nicht entscheiden…\p"
	.string "Entscheide du, Meister!$"

gText_ApprenticeLevelModeThanks10::
	.string "Okay, {STR_VAR_1} ist besser!\n"
	.string "Ich nehme das andere!\p"
	.string "War ein Scherz!\n"
	.string "Ich gehorche, Meister!\p"
	.string "Danke, Meister!\n"
	.string "Lehre mich weiter!$"

gText_ApprenticePleaseTeach11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi, und hallo!\p"
	.string "Ich bin {STR_VAR_1}, der Rapper-MATROSE!\p"
	.string "Du bist dran, erzähl was!\p"
	.string "Uh-huh, uh-huh!\n"
	.string "{PLAYER}{KUN} ist dein Name,\l"
	.string "POKéMON dein Spiel!\p"
	.string "Jedenfalls will ich sagen,\n"
	.string "du bist der zehnte TRAINER heute.\p"
	.string "Lass uns feiern!\n"
	.string "Werde mein Mentor!$"

gText_ApprenticeRejectTeaching11::
	.string "Aber!\n"
	.string "Du musst mit mir arbeiten!\p"
	.string "Sei nicht so fies!\n"
	.string "Werde mein Mentor, please!$"

gText_ApprenticeWhichLevelMode11::
	.string "Das ist es!\n"
	.string "{PLAYER}, du hast den Geist!\p"
	.string "Hier die erste Frage!\p"
	.string "Es geht um den DUELLTURM,\n"
	.string "und meine Power!\p"
	.string "Level 50 oder Offen,\n"
	.string "was ist gut für mich?$"

gText_ApprenticeLevelModeThanks11::
	.string "Okay, {STR_VAR_1} sagst du!\n"
	.string "Ich mach das so!\p"
	.string "Wenn ich Rat brauche,\n"
	.string "{PLAYER}, hör ich auf dich!$"

gText_ApprenticePleaseTeach12::
	.string "Sag mal, bist du {PLAYER}?\n"
	.string "Soll ich reden?\l"
	.string "Warum nicht! Ich rede ja schon!\p"
	.string "{PLAYER}, überrascht?\n"
	.string "Ich sag dir wer ich bin!\p"
	.string "{STR_VAR_1} nenn mich so.\n"
	.string "Gitarren-Star, das bin ich!\p"
	.string "Hörst du mich?\n"
	.string "Du hörst mich!\p"
	.string "Mein Glück ist top,\n"
	.string "ich frag dich was!\p"
	.string "{PLAYER}, lass mich Lehrling sein!\n"
	.string "Bring mir alles bei!$"

gText_ApprenticeRejectTeaching12::
	.string "Du lehnst ab?\n"
	.string "Ich frag nochmal!\p"
	.string "{PLAYER}, ich flehe dich an!\n"
	.string "Ich muss alles lernen!$"

gText_ApprenticeWhichLevelMode12::
	.string "Lucky, yeah, woohoo!\n"
	.string "Soll ich fragen?\p"
	.string "DUELLTURM ist nah,\n"
	.string "Frage dazu?\p"
	.string "Von den Optionen,\n"
	.string "welche passt zu mir?$"

gText_ApprenticeLevelModeThanks12::
	.string "Wenn {STR_VAR_1} dein Vorschlag ist,\n"
	.string "ist es das Beste!\p"
	.string "Nun, {PLAYER}, ich muss los,\n"
	.string "vergiss mich nicht.\p"
	.string "Bis dann, mein Freund!$"

gText_ApprenticePleaseTeach13::
	.string "Oh, hi! Du da!\n"
	.string "Massier meine Schulter!\p"
	.string "…Ja, da! Genau!\n"
	.string "Aua, aua! Oooh, das tut gut!\p"
	.string "Ich heiße {STR_VAR_1}.\n"
	.string "Ich mache Karate, aber mein Körper\l"
	.string "hält das nicht aus…\p"
	.string "Ich kämpfe mit POKéMON und härte\n"
	.string "mich ab.\p"
	.string "Du bist {PLAYER}{KUN}, oder?\n"
	.string "Der CHAMP?\p"
	.string "Hör zu, gibst du mir Rat?$"

gText_ApprenticeRejectTeaching13::
	.string "Oh, warum?\p"
	.string "Ich nerve nicht, versprochen!\n"
	.string "Bitte?$"

gText_ApprenticeWhichLevelMode13::
	.string "Danke. Sehr nett!\n"
	.string "…Hust! Hust!\p"
	.string "Oogh, ich muss hart werden…\p"
	.string "Ich gehe zum DUELLTURM,\n"
	.string "aber was ist besser?\l"
	.string "Level 50 oder Offen?$"

gText_ApprenticeLevelModeThanks13::
	.string "Hm, okay. {STR_VAR_1}.\n"
	.string "Ich geh sofort hin.\p"
	.string "Hoffentlich kann ich dich weiter\n"
	.string "fragen, Mentor!$"

gText_ApprenticePleaseTeach14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Bitte, guck nicht so.\n"
	.string "Ich werde ganz rot.\p"
	.string "Ich… Ich bin {STR_VAR_1}.\p"
	.string "Es ist mir peinlich,\n"
	.string "aber ich mag Ruinen.\p"
	.string "Noch peinlicher: Ich mag die\n"
	.string "KAMPFZONE.\p"
	.string "{PLAYER}{KUN}, du bist hart…\p"
	.string "Es fällt mir schwer,\n"
	.string "aber ich will was fragen.\p"
	.string "Wirst du mein Lehrer?$"

gText_ApprenticeRejectTeaching14::
	.string "Bitte wimmel mich nicht ab!\n"
	.string "Ich sterbe vor Scham.\p"
	.string "Bitte sei mein Lehrer!\n"
	.string "Ich brauche Rat!$"

gText_ApprenticeWhichLevelMode14::
	.string "D-danke…\p"
	.string "Aber guck mich nicht so an.\n"
	.string "Ich werde nervös.\p"
	.string "Bitte, antworte ohne Blickkontakt.\p"
	.string "Im DUELLTURM…\n"
	.string "Welches Level soll ich versuchen?$"

gText_ApprenticeLevelModeThanks14::
	.string "Oh… Okay!\n"
	.string "Ich versuche das.\p"
	.string "Hoffentlich schaffe ich es,\n"
	.string "ohne rot zu werden…\p"
	.string "Danke, {PLAYER}{KUN}.\n"
	.string "Hoffentlich hilfst du mir wieder.$"

gText_ApprenticePleaseTeach15::
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein…\n"
	.string "Aber bist du echt?\p"
	.string "Nenn mich {STR_VAR_1}.\p"
	.string "Ich wollte Lehrling eines starken\n"
	.string "TRAINERS werden.\p"
	.string "Glück gehabt!\n"
	.string "…Du bist echt {PLAYER}{KUN}, ja?\p"
	.string "Nein, nein, wenn du echt bist, gut.\n"
	.string "Erkenne mich als Lehrling an.$"

gText_ApprenticeRejectTeaching15::
	.string "Oh?\n"
	.string "Warum lehnst du ab?\p"
	.string "Ich entschuldige mich für meine\n"
	.string "Skepsis.\p"
	.string "Bitte nimm mich an!$"

gText_ApprenticeWhichLevelMode15::
	.string "Du nimmst mich an?\n"
	.string "Ich will nicht zu früh feiern.\p"
	.string "Wenn es wahr ist, sorry.\n"
	.string "Aber jetzt brauch ich Rat.\p"
	.string "Wenn ich in den DUELLTURM gehe,\n"
	.string "was ist meiner würdig?\l"
	.string "Level 50 oder Offen?$"

gText_ApprenticeLevelModeThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Sicher?\p"
	.string "Verstehe. Wenn das so ist, gut.\n"
	.string "Danke für deine Zeit.\p"
	.string "Ich weiß, ich nerve, aber es freut\n"
	.string "mich, dass du mich angenommen hast.\p"
	.string "Auf Wiedersehen!$"

gText_ApprenticeWhatHeldItem0::
	.string "Seufz… Heul…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Ich habe ein Problem.\n"
	.string "Ich kann mich nicht entscheiden.\p"
	.string "Was soll mein {STR_VAR_1} halten?\p"
	.string "Bitte sag es mir, {PLAYER}.\n"
	.string "Welches Item?$"

gText_ApprenticeHoldNothing0::
	.string "Oh, echt? Mein {STR_VAR_1} soll nichts\n"
	.string "halten?$"

gText_ApprenticeThanksNoHeldItem0::
	.string "Oh, okay! Ich bin froh!\n"
	.string "Geil! Krass! Awoooh!\p"
	.string "Danke vielmals!$"

gText_ApprenticeThanksHeldItem0::
	.string "Oh, ich bin froh…\n"
	.string "Ich glaub ich hab {STR_VAR_1}.\p"
	.string "Ich bin froh!\n"
	.string "Geil! Krass! Awoooh!\p"
	.string "Danke vielmals!$"

gText_ApprenticeItemAlreadyRecommended0::
	.string "Waaaaah! Sei nicht gemein!\p"
	.string "Das Item {STR_VAR_1} wurde mir schon\n"
	.string "empfohlen, heul…\p"
	.string "Oder soll mein {STR_VAR_2} nichts halten?$"

gText_ApprenticeWhatHeldItem1::
	.string "Yay! Es ist {PLAYER}!\n"
	.string "Toll! Ich wollte was fragen!\p"
	.string "Tragen deine POKéMON Items?\n"
	.string "Ich will das auch, aber…\p"
	.string "Was ist gut für {STR_VAR_1}?\p"
	.string "Was meinst du?$"

gText_ApprenticeHoldNothing1::
	.string "Hä? Mein {STR_VAR_1} braucht nichts?$"

gText_ApprenticeThanksNoHeldItem1::
	.string "Oh, kapiert! Mach ich!\n"
	.string "Danke!$"

gText_ApprenticeThanksHeldItem1::
	.string "Oh, wow! Ein {STR_VAR_1}, hä?\n"
	.string "Okay, mach ich!\p"
	.string "Danke!$"

gText_ApprenticeItemAlreadyRecommended1::
	.string "Oh, äh, nein, das meinte ich nicht.\n"
	.string "Ich will ein anderes Item wissen.\p"
	.string "Oder soll es diesmal nichts halten?$"

gText_ApprenticeWhatHeldItem2::
	.string "{PLAYER}, hallo!\n"
	.string "Es geht um mein {STR_VAR_1}…\p"
	.string "Ich will ihm ein gutes Item geben.\n"
	.string "Was ist gut?$"

gText_ApprenticeHoldNothing2::
	.string "Oh, dann braucht mein {STR_VAR_1}\n"
	.string "nichts?$"

gText_ApprenticeThanksNoHeldItem2::
	.string "Okay, kapiert!\n"
	.string "Bis dann!$"

gText_ApprenticeThanksHeldItem2::
	.string "Oh, das Item {STR_VAR_1}?\n"
	.string "Verstanden!\p"
	.string "Ich such eins!\n"
	.string "Bis dann!$"

gText_ApprenticeItemAlreadyRecommended2::
	.string "Jemand hat mir schon von\n"
	.string "{STR_VAR_1} erzählt.\p"
	.string "Ich will ein anderes Item.\p"
	.string "Oder denkst du, {STR_VAR_2}\n"
	.string "braucht nichts?$"

gText_ApprenticeWhatHeldItem3::
	.string "Hallo, {PLAYER}…\n"
	.string "Sorry für die Störung, aber ich\l"
	.string "muss was fragen.\p"
	.string "Ich gewinne alleine nicht,\n"
	.string "also will ich meinem {STR_VAR_1}\l"
	.string "ein Item geben.\p"
	.string "Aber ich weiß nicht was.\p"
	.string "{PLAYER}, bitte, entscheide du.$"

gText_ApprenticeHoldNothing3::
	.string "Ein POKéMON von mir braucht kein\n"
	.string "Item?$"

gText_ApprenticeThanksNoHeldItem3::
	.string "Ich verstehe…\n"
	.string "Ich soll mich nicht auf Items\l"
	.string "verlassen. Ich versuch’s!\p"
	.string "Danke vielmals!$"

gText_ApprenticeThanksHeldItem3::
	.string "Das Item {STR_VAR_1}, okay.\n"
	.string "Ich weiß nicht, ob ich das kriege…\l"
	.string "Nein! Ich schaff das!\p"
	.string "Danke vielmals!$"

gText_ApprenticeItemAlreadyRecommended3::
	.string "Oh, aber…\n"
	.string "Das hab ich schon gehört…\p"
	.string "Weil ich mit {STR_VAR_1} schlecht war?\p"
	.string "Oder soll mein {STR_VAR_2} nichts halten?$"

gText_ApprenticeWhatHeldItem4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Ich wollte was fragen.\p"
	.string "Du hast mein POKéMON ausgesucht,\n"
	.string "aber welches Item soll es halten?\p"
	.string "Beende es!\p"
	.string "Was ist gut? Ich will meinem\n"
	.string "{STR_VAR_1} was geben.$"

gText_ApprenticeHoldNothing4::
	.string "Oh! Mein {STR_VAR_1} soll mit leeren\n"
	.string "Händen kämpfen?$"

gText_ApprenticeThanksNoHeldItem4::
	.string "Wenn du meinst, okay.\p"
	.string "Da du entschieden hast,\n"
	.string "{PLAYER}{KUN}, bin ich nicht sauer,\l"
	.string "wenn ich verliere.\p"
	.string "Bis zum nächsten Rat.\n"
	.string "Bye!$"

gText_ApprenticeThanksHeldItem4::
	.string "Das Item {STR_VAR_1}, hä?\n"
	.string "Nicht schlecht. Mach ich!\p"
	.string "Da du entschieden hast,\n"
	.string "{PLAYER}{KUN}, bin ich nicht sauer,\l"
	.string "wenn ich verliere.\p"
	.string "Bis zum nächsten Rat.\n"
	.string "Bye!$"

gText_ApprenticeItemAlreadyRecommended4::
	.string "Hä? Was sagst du?\n"
	.string "Du hast mir schon von {STR_VAR_1}\l"
	.string "erzählt.\p"
	.string "Oder soll mein {STR_VAR_2}\n"
	.string "nichts halten?$"

gText_ApprenticeWhatHeldItem5::
	.string "Yo, {PLAYER}{KUN}!\p"
	.string "Wir sind beide beschäftigt, treffen\n"
	.string "uns aber oft!\p"
	.string "Heute muss ich laufen, putzen,\n"
	.string "bürsten.\p"
	.string "Keine Zeit, meinem {STR_VAR_1} was zu\n"
	.string "kaufen.\p"
	.string "Keine Zeit, also sag mir, was mein\n"
	.string "{STR_VAR_1} halten soll?$"

gText_ApprenticeHoldNothing5::
	.string "Oh, weil ich beschäftigt bin,\n"
	.string "braucht mein {STR_VAR_1} nichts?$"

gText_ApprenticeThanksNoHeldItem5::
	.string "Okay, kapiert.\n"
	.string "Spart Zeit.\p"
	.string "Danke!\n"
	.string "Bis dann!$"

gText_ApprenticeThanksHeldItem5::
	.string "Okay, kapiert.\n"
	.string "Ich finde Zeit für das {STR_VAR_1}.\p"
	.string "Gut, dich als Mentor zu haben.\n"
	.string "Danke! Bis dann!$"

gText_ApprenticeItemAlreadyRecommended5::
	.string "Hä? Ich kenne {STR_VAR_1} schon.\p"
	.string "Oh, ich verstehe.\n"
	.string "Weil ich beschäftigt bin, braucht\l"
	.string "mein {STR_VAR_2} nichts?$"

gText_ApprenticeWhatHeldItem6::
	.string "Hiya, {PLAYER}! Ich bin’s!\n"
	.string "Ich brauch deinen Kopf.\l"
	.string "Bitte, Rat!\p"
	.string "Trommelwirbel!\n"
	.string "Die Frage ist…\p"
	.string "Welches Item für mein {STR_VAR_1}?$"

gText_ApprenticeHoldNothing6::
	.string "Echt? Mein {STR_VAR_1} braucht kein Item,\n"
	.string "sagst du.$"

gText_ApprenticeThanksNoHeldItem6::
	.string "Okay, mach ich!\p"
	.string "Das war’s für heute.\p"
	.string "Treffen wir uns wieder hier?\n"
	.string "Danke!$"

gText_ApprenticeThanksHeldItem6::
	.string "Uh-huh! Ein {STR_VAR_1}.\n"
	.string "Coole Wahl!\l"
	.string "Probier ich!\p"
	.string "Das war’s für heute.\p"
	.string "Treffen wir uns wieder hier?\n"
	.string "Danke!$"

gText_ApprenticeItemAlreadyRecommended6::
	.string "Ahahah! Albern!\n"
	.string "Das hast du mir schon gesagt!\p"
	.string "Alles okay, {PLAYER}?\p"
	.string "Oh, warte! Mein {STR_VAR_2} braucht\n"
	.string "kein Item, sagst du.$"

gText_ApprenticeWhatHeldItem7::
	.string "Hallo, {PLAYER}. Ich hoffe, es\n"
	.string "geht gut.\p"
	.string "Darf ich fragen?\p"
	.string "Mein Gegner hatte ein Item.\p"
	.string "Ich habe verloren…\p"
	.string "Ich will nicht zurückbleiben.\n"
	.string "Ich will meinem {STR_VAR_1} ein Item\l"
	.string "geben.\p"
	.string "Bitte entscheide, was richtig ist…$"

gText_ApprenticeHoldNothing7::
	.string "Also… Mein POKéMON braucht kein\n"
	.string "Item?$"

gText_ApprenticeThanksNoHeldItem7::
	.string "Ich verstehe!\n"
	.string "Ich mach weiter so.\p"
	.string "Danke, {PLAYER}.\n"
	.string "Hoffentlich hilfst du mir wieder.\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeThanksHeldItem7::
	.string "Ein {STR_VAR_1} also!\n"
	.string "Ich bestelle es.\p"
	.string "Danke, {PLAYER}.\n"
	.string "Hoffentlich hilfst du mir wieder.\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeItemAlreadyRecommended7::
	.string "Das hast du schon gesagt,\n"
	.string "das hab ich schon.\p"
	.string "Oder sagst du… Mein POKéMON\n"
	.string "braucht kein Item?$"

gText_ApprenticeWhatHeldItem8::
	.string "Ieek! {PLAYER}!\n"
	.string "Ich… freu mich so!\p"
	.string "Oh-oh-oh! Ich muss dich was fragen,\n"
	.string "{PLAYER}!\p"
	.string "Entscheide, was mein {STR_VAR_1}\n"
	.string "halten soll!$"

gText_ApprenticeHoldNothing8::
	.string "Oh, wow! Unerwartet!\n"
	.string "Kein Item nötig?$"

gText_ApprenticeThanksNoHeldItem8::
	.string "Verstanden!\n"
	.string "Ich mach’s ohne!\p"
	.string "Hoffentlich bringst du mir mehr bei.$"

gText_ApprenticeThanksHeldItem8::
	.string "{STR_VAR_1}! Mach ich!\p"
	.string "Ähm… {PLAYER}, nutzt du das auch?\p"
	.string "Ich hol mir das!\n"
	.string "Hoffentlich bringst du mir mehr bei.$"

gText_ApprenticeItemAlreadyRecommended8::
	.string "Oh? Das hast du schon empfohlen.\p"
	.string "Ist es das Beste?\n"
	.string "Oder soll mein {STR_VAR_2}\l"
	.string "nichts halten?$"

gText_ApprenticeWhatHeldItem9::
	.string "Hola!\n"
	.string "Maestro, {PLAYER}{KUN}!\p"
	.string "Ich brauch Rat zu POKéMON-Tools.\p"
	.string "Was ist gut für mein {STR_VAR_1}?\p"
	.string "Nicht schüchtern.\n"
	.string "Raus damit!$"

gText_ApprenticeHoldNothing9::
	.string "Oh? Mein {STR_VAR_1} gewinnt ohne\n"
	.string "Item?$"

gText_ApprenticeThanksNoHeldItem9::
	.string "Si, bueno!\n"
	.string "Ich geb alles!\p"
	.string "Danke, wie immer!\n"
	.string "Adios!$"

gText_ApprenticeThanksHeldItem9::
	.string "Uh-huh, ein {STR_VAR_1}?\n"
	.string "Si, bueno!\l"
	.string "Ich find eins!\p"
	.string "Danke, wie immer!\n"
	.string "Adios!$"

gText_ApprenticeItemAlreadyRecommended9::
	.string "Nein, nein! Das hast du schon\n"
	.string "gesagt.\p"
	.string "Oh, warte…\n"
	.string "Du sagst, mein {STR_VAR_2}\l"
	.string "gewinnt ohne Item?$"

gText_ApprenticeWhatHeldItem10::
	.string "{PLAYER}{KUN}, unglaublich!\p"
	.string "Heute morgen hatte mein POKéMON\n"
	.string "10 NUGGETS!\p"
	.string "Gelogen!\n"
	.string "Wahahaha!\p"
	.string "Aber das nicht.\n"
	.string "Ich bin schlecht in Items.\p"
	.string "Entscheide, was mein {STR_VAR_1}\n"
	.string "halten soll, Meister!$"

gText_ApprenticeHoldNothing10::
	.string "Was heißt das?\n"
	.string "Nichts halten?$"

gText_ApprenticeThanksNoHeldItem10::
	.string "Okay, nichts halten.\n"
	.string "Dann hol ich was!\p"
	.string "Scherz!\n"
	.string "Ich gehorche, Meister!\p"
	.string "Danke, Meister!\n"
	.string "Lehre mich weiter!$"

gText_ApprenticeThanksHeldItem10::
	.string "Okay, {STR_VAR_1}!\n"
	.string "Ich nehme alles außer dem!\p"
	.string "Scherz!\n"
	.string "Ich gehorche, Meister!\p"
	.string "Danke, Meister!\n"
	.string "Lehre mich weiter!$"

gText_ApprenticeItemAlreadyRecommended10::
	.string "Ähm, das hast du schon gesagt.\p"
	.string "Gibt’s was anderes?\p"
	.string "Oder soll mein {STR_VAR_2}\n"
	.string "nichts halten?$"

gText_ApprenticeWhatHeldItem11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Der Rapper-MATROSE!\n"
	.string "Ich habe eine Frage,\l"
	.string "die ist krass!\p"
	.string "Eine Item-Frage,\n"
	.string "ich brauch deinen Rat!\p"
	.string "Mein {STR_VAR_1} braucht ein Item,\n"
	.string "Was soll es sein?$"

gText_ApprenticeHoldNothing11::
	.string "Echt jetzt?\n"
	.string "Mein {STR_VAR_1} braucht nichts?$"

gText_ApprenticeThanksNoHeldItem11::
	.string "Okay, ich hör dich!\n"
	.string "Mein POKéMON geht leer aus!\p"
	.string "Wenn ich Rat brauche,\n"
	.string "{PLAYER}, hör ich auf dich!$"

gText_ApprenticeThanksHeldItem11::
	.string "Okay, ein {STR_VAR_1},\n"
	.string "das nehm ich.\l"
	.string "Gut, dich zu fragen!\p"
	.string "Wenn ich Rat brauche,\n"
	.string "{PLAYER}, hör ich auf dich!$"

gText_ApprenticeItemAlreadyRecommended11::
	.string "Okay, {STR_VAR_1}, sagst du?\n"
	.string "Das hast du schon gesagt.\l"
	.string "Ich brauch was Neues.\p"
	.string "Oder, echt?\n"
	.string "Mein POKéMON braucht nichts?$"

gText_ApprenticeWhatHeldItem12::
	.string "Hey, {PLAYER}!\n"
	.string "Wieder da!\p"
	.string "Soll ich Rat holen?\n"
	.string "Warum nicht!\p"
	.string "{PLAYER}, nerv ich?\n"
	.string "Nee, oder?\p"
	.string "Hörst du mir zu?\n"
	.string "Ich brauch Rat.\p"
	.string "Ein Item für mein {STR_VAR_1}.\n"
	.string "Ich kann mich nicht entscheiden.$"

gText_ApprenticeHoldNothing12::
	.string "Mein {STR_VAR_1} braucht nichts?\n"
	.string "Nichts halten?$"

gText_ApprenticeThanksNoHeldItem12::
	.string "Wenn nichts das Beste ist,\n"
	.string "mach ich das!\p"
	.string "Nun, {PLAYER}, ich muss los,\n"
	.string "vergiss mich nicht.\p"
	.string "Bis dann, mein Freund!$"

gText_ApprenticeThanksHeldItem12::
	.string "Wenn {STR_VAR_1} das Beste ist,\n"
	.string "mach ich das!\p"
	.string "Nun, {PLAYER}, ich muss los,\n"
	.string "vergiss mich nicht.\p"
	.string "Bis dann, mein Freund!$"

gText_ApprenticeItemAlreadyRecommended12::
	.string "Hab ich von {STR_VAR_1}\n"
	.string "nicht schon gehört?\l"
	.string "Sicher!\p"
	.string "Ich brauch was Neues!\n"
	.string "Oder braucht mein {STR_VAR_2} nichts?$"

gText_ApprenticeWhatHeldItem13::
	.string "Gwah! Aua! {PLAYER}{KUN}, Arm gebrochen!\n"
	.string "Nicht anfassen!\p"
	.string "Gebrochen beim Item-Testen.\p"
	.string "Also, entscheide du.\p"
	.string "{PLAYER}{KUN}, was ist gut für mein\n"
	.string "{STR_VAR_1}?$"

gText_ApprenticeHoldNothing13::
	.string "Aua…\p"
	.string "Also mein {STR_VAR_1} braucht nichts?$"

gText_ApprenticeThanksNoHeldItem13::
	.string "Hm, okay. Einfacher so.\p"
	.string "Hoffentlich kann ich dich weiter\n"
	.string "fragen.$"

gText_ApprenticeThanksHeldItem13::
	.string "Hm, okay. {STR_VAR_1}.\n"
	.string "Arm ist okay, ich geb es ihm.\p"
	.string "Hoffentlich kann ich dich weiter\n"
	.string "fragen.$"

gText_ApprenticeItemAlreadyRecommended13::
	.string "Nein, nein, das hast du schon\n"
	.string "gesagt.\p"
	.string "Was Besseres?\p"
	.string "Oh, warte.\n"
	.string "Mein {STR_VAR_2} braucht nichts?$"

gText_ApprenticeWhatHeldItem14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Bitte, guck nicht so.\n"
	.string "Meine POKéMON haben nichts.\p"
	.string "Ich… Es ist mir peinlich,\n"
	.string "aber ich brauch Rat.\p"
	.string "Welches Item macht mein {STR_VAR_1}\n"
	.string "stark?\p"
	.string "{PLAYER}{KUN}, was denkst du?$"

gText_ApprenticeHoldNothing14::
	.string "Oh… Besser ohne Item?$"

gText_ApprenticeThanksNoHeldItem14::
	.string "Oh… Okay!\n"
	.string "Ohne Item.\p"
	.string "Nervig.\n"
	.string "Wäre das nicht zu cool?\p"
	.string "Danke, {PLAYER}{KUN}.\n"
	.string "Hoffentlich hilfst du mir wieder.$"

gText_ApprenticeThanksHeldItem14::
	.string "Oh… Okay!\n"
	.string "Ich nehme {STR_VAR_1}.\p"
	.string "Nervig.\n"
	.string "Wäre das nicht zu cool?\p"
	.string "Danke, {PLAYER}{KUN}.\n"
	.string "Hoffentlich hilfst du mir wieder.$"

gText_ApprenticeItemAlreadyRecommended14::
	.string "A-aber das hab ich schon gehört.\p"
	.string "Bitte wimmel mich nicht ab!\n"
	.string "Ich sterbe vor Scham.\p"
	.string "Oh… Meinst du, mein {STR_VAR_2}\n"
	.string "sollte kein Item haben?$"

gText_ApprenticeWhatHeldItem15::
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein…\n"
	.string "Aber bist du es echt?\l"
	.string "Ein Zwilling?\p"
	.string "Oh, nein, nein!\n"
	.string "Wenn du echt bist, vergiss meine\l"
	.string "Unhöflichkeit.\p"
	.string "Ich brauche Rat.\p"
	.string "Mein {STR_VAR_1} braucht ein Item.\p"
	.string "Was ist würdig?$"

gText_ApprenticeHoldNothing15::
	.string "Besser nichts?\n"
	.string "Sicher?$"

gText_ApprenticeThanksNoHeldItem15::
	.string "Verstehe. Gut.\n"
	.string "Danke für die Zeit.\p"
	.string "Auf Wiedersehen!$"

gText_ApprenticeThanksHeldItem15::
	.string "Ein {STR_VAR_1}?\n"
	.string "Sicher?\p"
	.string "Verstehe. Gut.\n"
	.string "Danke für die Zeit.\p"
	.string "Hoffentlich nutzt es was.\p"
	.string "Auf Wiedersehen!$"

gText_ApprenticeItemAlreadyRecommended15::
	.string "Nein, warte.\n"
	.string "Das hast du schon gesagt.\p"
	.string "Ich will was anderes.\p"
	.string "Vielleicht soll mein {STR_VAR_2}\n"
	.string "nichts halten?\l"
	.string "Sicher?$"

gText_ApprenticeWhichMonFirst0::
	.string "Waah, {PLAYER}!\n"
	.string "Dilemma, heul…\p"
	.string "Ich will kämpfen,\n"
	.string "aber ich weiß nicht wie.\p"
	.string "Wie stelle ich meine POKéMON auf?\p"
	.string "Bitte, {PLAYER}.\n"
	.string "Wen würdest du zuerst schicken?$"

gText_ApprenticeMonFirstThanks0::
	.string "Mein {STR_VAR_1} zuerst?\n"
	.string "Waaaaah!\p"
	.string "Oh! Sorry!\n"
	.string "Du hast mich glücklich gemacht,\n"
	.string "ich heule…\p"
	.string "Danke vielmals!$"

gText_ApprenticeWhichMonFirst1::
	.string "Yay! Es ist {PLAYER}!\n"
	.string "Toll! Ich wollte was fragen!\p"
	.string "Ähm, welches POKéMON zuerst?$"

gText_ApprenticeMonFirstThanks1::
	.string "Mein {STR_VAR_1}? Stimmt.\n"
	.string "Okay, mach ich!\p"
	.string "Danke!$"

gText_ApprenticeWhichMonFirst2::
	.string "{PLAYER}, hallo!\p"
	.string "Reihenfolge ist wichtig.\p"
	.string "Welches POKéMON zuerst?$"

gText_ApprenticeMonFirstThanks2::
	.string "Mein {STR_VAR_1} zuerst?\n"
	.string "Okay, kapiert!\p"
	.string "Bis dann!$"

gText_ApprenticeWhichMonFirst3::
	.string "Hallo, {PLAYER}…\n"
	.string "Sorry für die Störung.\p"
	.string "Ich habe kein Selbstvertrauen,\n"
	.string "{PLAYER}.\p"
	.string "Vielleicht Zeitverschwendung,\n"
	.string "aber ich kann mich nicht entscheiden…\p"
	.string "Welches POKéMON zuerst?$"

gText_ApprenticeMonFirstThanks3::
	.string "Mein {STR_VAR_1}?\n"
	.string "Verstanden!\p"
	.string "Ich glaub’s nicht, dass du antwortest!\p"
	.string "Ich bin so dankbar… Danke!$"

gText_ApprenticeWhichMonFirst4::
	.string "Oh, {PLAYER}{KUN}! Ich bin’s!\n"
	.string "Ich hab ein Problem.\p"
	.string "Wie stelle ich auf? Entscheidest du?\p"
	.string "Nicht alles.\p"
	.string "Nur das erste POKéMON?$"

gText_ApprenticeMonFirstThanks4::
	.string "Mein {STR_VAR_1}? Toll!\p"
	.string "Da du entschieden hast,\n"
	.string "{PLAYER}{KUN}, bin ich nicht sauer,\l"
	.string "wenn ich verliere.\p"
	.string "Bis zum nächsten Rat.\n"
	.string "Bye!$"

gText_ApprenticeWhichMonFirst5::
	.string "Hi, Lehrer {PLAYER}{KUN}!\n"
	.string "Bin beschäftigt!\p"
	.string "Radfahren, shoppen, summen.\p"
	.string "Keine Zeit für Aufstellung.\p"
	.string "Guck mal mein Team an.\n"
	.string "Wer zuerst?$"

gText_ApprenticeMonFirstThanks5::
	.string "Okay, kapiert.\n"
	.string "Ich stelle {STR_VAR_1} nach vorne!\p"
	.string "Hoppla, Freundin wartet!\n"
	.string "Danke! Bis dann!$"

gText_ApprenticeWhichMonFirst6::
	.string "Yoohoo! Hiya, {PLAYER}!\n"
	.string "Du siehst taff aus!\p"
	.string "Hör zu, ich brauch was!\p"
	.string "Trommelwirbel!\n"
	.string "Die Frage ist…\p"
	.string "Welches POKéMON zuerst?$"

gText_ApprenticeMonFirstThanks6::
	.string "Hmhm!\n"
	.string "Mein {STR_VAR_1}, sagst du!\l"
	.string "Danke für die coole Antwort!\p"
	.string "Das war’s.\p"
	.string "Treffen wir uns wieder hier?\n"
	.string "Danke!$"

gText_ApprenticeWhichMonFirst7::
	.string "Danke fürs Reden, {PLAYER}.\p"
	.string "Ich nutze dich aus, aber darf ich\n"
	.string "fragen?\p"
	.string "Entscheide die Reihenfolge.\p"
	.string "Welches POKéMON zuerst?$"

gText_ApprenticeMonFirstThanks7::
	.string "Mein {STR_VAR_1}!\n"
	.string "Ich mach das sofort!\p"
	.string "Danke, {PLAYER}.\n"
	.string "Hoffentlich hilfst du mir wieder.\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeWhichMonFirst8::
	.string "Ieek! {PLAYER}!\n"
	.string "Ich… freu mich so!\p"
	.string "Meine POKéMON sind stärker!\p"
	.string "Aber ich verliere. Es liegt an der\n"
	.string "Reihenfolge.\p"
	.string "{PLAYER}, bitte, hilf!\p"
	.string "Welches POKéMON zuerst?$"

gText_ApprenticeMonFirstThanks8::
	.string "Seufz… Ich bin überwältigt…\p"
	.string "Ein Traum, dass du entscheidest,\n"
	.string "{PLAYER}.\p"
	.string "Verstanden!\n"
	.string "{STR_VAR_1} zuerst!\p"
	.string "Hoffentlich bringst du mir mehr bei.$"

gText_ApprenticeWhichMonFirst9::
	.string "Hallo, hallo!\n"
	.string "Mein Mentor, {PLAYER}{KUN}!\l"
	.string "Gib mir Rat!\p"
	.string "Ich hab ein Team.\n"
	.string "Aber keine Reihenfolge.\p"
	.string "Hier kommst du ins Spiel, {PLAYER}{KUN}!\n"
	.string "Du entscheidest!\p"
	.string "Nicht schüchtern.\n"
	.string "Raus damit!$"

gText_ApprenticeMonFirstThanks9::
	.string "Uh-huh, {STR_VAR_1} zuerst!\n"
	.string "OK, alles klar!\l"
	.string "Ich ordne um, zack!\p"
	.string "Danke, wie immer!\n"
	.string "Adios!$"

gText_ApprenticeWhichMonFirst10::
	.string "{PLAYER}{KUN}, hör zu!\n"
	.string "Krise!\p"
	.string "Alle drei POKéMON gleichzeitig!\p"
	.string "Unmöglich!\n"
	.string "Wahahaha!\p"
	.string "Aber das nicht.\n"
	.string "Ich bin schlecht in Aufstellung.\p"
	.string "Entscheide du, Meister!$"

gText_ApprenticeMonFirstThanks10::
	.string "Okay, {STR_VAR_1}?\n"
	.string "Ich nehme ein anderes!\p"
	.string "Scherz!\n"
	.string "Ich gehorche, Meister!\p"
	.string "Danke, Meister!\n"
	.string "Lehre mich weiter!$"

gText_ApprenticeWhichMonFirst11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Der Rapper-MATROSE!\n"
	.string "Ich habe eine Aufstellungs-Frage,\l"
	.string "ich brauch deinen Rat!\p"
	.string "Welches soll zuerst raus?$"

gText_ApprenticeMonFirstThanks11::
	.string "Okay, ich hör dich!\n"
	.string "Ich tausch sie aus!\p"
	.string "Wenn ich Rat brauche,\n"
	.string "{PLAYER}, hör ich auf dich!$"

gText_ApprenticeWhichMonFirst12::
	.string "Yahoo, {PLAYER}!\n"
	.string "Wie geht’s?\p"
	.string "Soll ich fragen?\n"
	.string "Uh-huh, ich frag!\l"
	.string "Hörst du mich?\l"
	.string "Du hörst mich!\p"
	.string "Du musst entscheiden, welches\n"
	.string "POKéMON reitet!\l"
	.string "In den Kampf meine ich.$"

gText_ApprenticeMonFirstThanks12::
	.string "Mein {STR_VAR_1}? Ja!\n"
	.string "Das mach ich!\p"
	.string "Nun, {PLAYER}, ich muss los,\n"
	.string "vergiss mich nicht.\p"
	.string "Bis dann, mein Freund!$"

gText_ApprenticeWhichMonFirst13::
	.string "…Oof… ooch… {PLAYER}{KUN}…\n"
	.string "Bauchschmerzen…\p"
	.string "…Geht wieder…\p"
	.string "Hab mir Sorgen gemacht wegen\n"
	.string "Aufstellung.\p"
	.string "Also, entscheide du.\p"
	.string "{PLAYER}{KUN}, welches zuerst?$"

gText_ApprenticeMonFirstThanks13::
	.string "Hm, okay.\n"
	.string "Mein {STR_VAR_1} zuerst.\p"
	.string "Ich mach das nach dem Abendessen.\p"
	.string "Hoffentlich kann ich dich weiter\n"
	.string "fragen.$"

gText_ApprenticeWhichMonFirst14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Guck nicht so.\n"
	.string "Ich werde rot.\p"
	.string "Ähm…\n"
	.string "Ich brauch Rat.\p"
	.string "Peinlich, aber ich hab ein Team.\l"
	.string "Kann mich nicht entscheiden.\p"
	.string "Welches zuerst, damit ich fähig\n"
	.string "aussehe?$"

gText_ApprenticeMonFirstThanks14::
	.string "Oh… Okay!\n"
	.string "Ich starte mit {STR_VAR_1}.\p"
	.string "Hoffentlich werde ich nicht rot.\p"
	.string "Danke, {PLAYER}{KUN}.\n"
	.string "Hoffentlich hilfst du mir wieder.$"

gText_ApprenticeWhichMonFirst15::
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein…\n"
	.string "Aber bist du echt?\l"
	.string "Ein Doppelgänger?\p"
	.string "Nein, nein!\n"
	.string "Wenn du echt bist, sorry.\p"
	.string "Ich brauche Rat.\p"
	.string "Mein POKéMON-Team.\n"
	.string "Welches zuerst?$"

gText_ApprenticeMonFirstThanks15::
	.string "Mein {STR_VAR_1}…\n"
	.string "Du veräppelst mich nicht?\p"
	.string "Verstehe. Gut.\n"
	.string "Danke für die Zeit.\p"
	.string "Ich gebe mein Bestes.\p"
	.string "Auf Wiedersehen!$"

gText_ApprenticeWhichMon0::
	.string "Schnief…\n"
	.string "Oh, {PLAYER}!\p"
	.string "Perfektes Timing!\n"
	.string "Ich kann mich nicht entscheiden…\p"
	.string "Welches POKéMON?\p"
	.string "{STR_VAR_1} und {STR_VAR_2}…\p"
	.string "{PLAYER}, was gibt mir eine Chance?$"

gText_ApprenticeMonThanks0::
	.string "Schnief… Ich… Verstehe!\n"
	.string "Oh! Sorry!\l"
	.string "Ich heule vor Freude…\p"
	.string "Ich fange ein {STR_VAR_1}!\p"
	.string "Danke vielmals!$"

gText_ApprenticeWhichMon1::
	.string "Yay! Es ist {PLAYER}!\n"
	.string "Yay, richtiges Timing!\l"
	.string "Ich brauch Rat!\p"
	.string "Ähm, {STR_VAR_1} oder\n"
	.string "{STR_VAR_2}…\p"
	.string "Was meinst du, {PLAYER}?$"

gText_ApprenticeMonThanks1::
	.string "Oh, {STR_VAR_1} ist besser!\n"
	.string "Okay, mach ich!\p"
	.string "Danke!$"

gText_ApprenticeWhichMon2::
	.string "{PLAYER}, hallo!\n"
	.string "Eine Frage.\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}.\p"
	.string "Was ist stärker?$"

gText_ApprenticeMonThanks2::
	.string "{STR_VAR_1}?\n"
	.string "Okay, kapiert!\p"
	.string "Ich fange ein starkes {STR_VAR_1}!\p"
	.string "Bis dann!$"

gText_ApprenticeWhichMon3::
	.string "Hallo, {PLAYER}…\p"
	.string "Du hast mich sicher vergessen…\p"
	.string "…Aber egal, gib mir Rat…\p"
	.string "Welches POKéMON soll ich nehmen…\p"
	.string "{STR_VAR_1} und {STR_VAR_2}…\p"
	.string "{PLAYER}, du willst sicher nicht,\n"
	.string "aber entscheide.$"

gText_ApprenticeMonThanks3::
	.string "Aber beachtet mich ein wildes\n"
	.string "{STR_VAR_1}?\p"
	.string "Ich versuch’s!\p"
	.string "Kann ich es fangen…\n"
	.string "Nein! Ich schaff das!\p"
	.string "Danke!$"

gText_ApprenticeWhichMon4::
	.string "Oh, {PLAYER}{KUN}! Ich freu mich!\n"
	.string "Ich wollte dich suchen!\p"
	.string "Welches POKéMON soll ich nutzen?\p"
	.string "{STR_VAR_1} und {STR_VAR_2}?\p"
	.string "Was ist besser?$"

gText_ApprenticeMonThanks4::
	.string "{STR_VAR_1}? Toll!\p"
	.string "Da du entschieden hast,\n"
	.string "{PLAYER}{KUN}, bin ich nicht sauer,\l"
	.string "wenn ich verliere.\p"
	.string "Bis zum nächsten Rat.\n"
	.string "Bye!$"

gText_ApprenticeWhichMon5::
	.string "Wenn das nicht {PLAYER}{KUN} ist!\n"
	.string "Bin beschäftigt!\p"
	.string "Ich will gut sein, aber welches\n"
	.string "POKéMON?\p"
	.string "{STR_VAR_1} sieht stark aus.\n"
	.string "{STR_VAR_2} ist zäh.\p"
	.string "{PLAYER}{KUN}, gib mir Rat!$"

gText_ApprenticeMonThanks5::
	.string "Okay, kapiert.\n"
	.string "Ich fange {STR_VAR_1}.\p"
	.string "Gut, dich als Mentor zu haben.\n"
	.string "Danke! Bis dann!$"

gText_ApprenticeWhichMon6::
	.string "Oh!\n"
	.string "Yay, {PLAYER}!\p"
	.string "Ich hab angegeben, dass ich dich\n"
	.string "kenne!\p"
	.string "Ich brauch deinen Kopf.\n"
	.string "Leicht für dich!\p"
	.string "Trommelwirbel!\n"
	.string "Die Frage ist…\p"
	.string "Ein {STR_VAR_1} oder {STR_VAR_2},\n"
	.string "was soll es sein?$"

gText_ApprenticeMonThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, sagst du!\l"
	.string "Danke für die coole Antwort!\p"
	.string "Das war’s.\p"
	.string "Treffen wir uns wieder hier?\n"
	.string "Danke!$"

gText_ApprenticeWhichMon7::
	.string "Oh, bist du es, {PLAYER}?\n"
	.string "Freut mich!\p"
	.string "Seit ich Lehrling bin, blühe ich auf.\p"
	.string "Ich bin bereit für ein POKéMON!\p"
	.string "{PLAYER}, wähle für mich!\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}…\l"
	.string "Was ist richtig?$"

gText_ApprenticeMonThanks7::
	.string "Ein {STR_VAR_1}!\n"
	.string "Ich finde eins!\p"
	.string "Danke, {PLAYER}.\n"
	.string "Hoffentlich hilfst du mir wieder.\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeWhichMon8::
	.string "Ieek! {PLAYER}! Wiedersehen!\n"
	.string "Ich… freu mich!\p"
	.string "Oh-oh-oh, ich weiß!\n"
	.string "Nutze die Chance!\p"
	.string "Wähle ein POKéMON für mich!\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}!$"

gText_ApprenticeMonThanks8::
	.string "Wow! Du hast entschieden!\n"
	.string "{STR_VAR_1} ziehe ich auf.\p"
	.string "Hoffentlich bringst du mir mehr bei.$"

gText_ApprenticeWhichMon9::
	.string "Hey, hey!\n"
	.string "Mein Mentor, {PLAYER}{KUN}!\p"
	.string "Ich hab dich gesucht!\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}?\p"
	.string "Nicht schüchtern.\n"
	.string "Raus damit!$"

gText_ApprenticeMonThanks9::
	.string "Uh-huh, {STR_VAR_1}!\n"
	.string "OK, alles klar!\l"
	.string "Ich fang eins, zack!\p"
	.string "Danke, wie immer!\n"
	.string "Adios!$"

gText_ApprenticeWhichMon10::
	.string "{PLAYER}{KUN}, hör zu! News!\n"
	.string "Ich fing ein Wunder-POKéMON!\p"
	.string "Gelogen!\n"
	.string "Wahahaha!\p"
	.string "Aber das nicht.\n"
	.string "Ich kann nicht fangen.\p"
	.string "Entscheide, was ich fangen soll,\n"
	.string "Meister!\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}?$"

gText_ApprenticeMonThanks10::
	.string "Okay, {STR_VAR_1}?\n"
	.string "Ich nehme das andere!\p"
	.string "Scherz!\n"
	.string "Ich gehorche, Meister!\p"
	.string "Danke, Meister!\n"
	.string "Lehre mich weiter!$"

gText_ApprenticeWhichMon11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Der Rapper-MATROSE!\n"
	.string "Du kennst mich?\p"
	.string "Heute eine POKéMON-Frage,\n"
	.string "ich brauch deinen Rat!\p"
	.string "{STR_VAR_1} und {STR_VAR_2}.\l"
	.string "Was soll ich fangen?$"

gText_ApprenticeMonThanks11::
	.string "{STR_VAR_1}, sagst du, hey, hey!\n"
	.string "Ich hol mir eins!\p"
	.string "Wenn ich Rat brauche,\n"
	.string "{PLAYER}, hör ich auf dich!$"

gText_ApprenticeWhichMon12::
	.string "Oh, wow, ist das {PLAYER}!\p"
	.string "Soll ich Rat holen?\n"
	.string "Warum nicht! Ich rede ja schon!\p"
	.string "Lange her. Ich brauch Rat!\l"
	.string "Hörst du mich?\l"
	.string "Du hörst mich!\p"
	.string "Mein POKéMON--welches?\n"
	.string "{STR_VAR_1} oder {STR_VAR_2}.\l"
	.string "Was wählst du?$"

gText_ApprenticeMonThanks12::
	.string "Wenn {STR_VAR_1} das Beste ist,\n"
	.string "mach ich das!\p"
	.string "Nun, {PLAYER}, ich muss los,\n"
	.string "vergiss mich nicht.\p"
	.string "Bis dann, mein Freund!$"

gText_ApprenticeWhichMon13::
	.string "Oh, hi, {PLAYER}{KUN}…\n"
	.string "Kopfschmerzen…\p"
	.string "Zu viel Sorgen um POKéMON.\p"
	.string "Also, entscheide du.\p"
	.string "{PLAYER}{KUN}, {STR_VAR_1} oder\n"
	.string "{STR_VAR_2}, was?$"

gText_ApprenticeMonThanks13::
	.string "Hm, {STR_VAR_1}, okay.\n"
	.string "Ich such eins, wenn ich gesund bin.\p"
	.string "Hoffentlich kann ich dich weiter\n"
	.string "fragen.$"

gText_ApprenticeWhichMon14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Guck nicht so.\n"
	.string "Ich werde nervös…\l"
	.string "Ich… brauch Rat.\p"
	.string "Peinlich, aber ich weiß nicht.\p"
	.string "{STR_VAR_1} oder {STR_VAR_2}?$"

gText_ApprenticeMonThanks14::
	.string "Oh… Okay!\n"
	.string "Ich nehme {STR_VAR_1}.\p"
	.string "Hoffentlich werde ich nicht rot.\p"
	.string "Danke, {PLAYER}{KUN}.\n"
	.string "Hoffentlich hilfst du mir wieder.$"

gText_ApprenticeWhichMon15::
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein…\n"
	.string "Aber bist du echt?\p"
	.string "Nein, nein, wenn du echt bist, gut.\n"
	.string "Kein Grund zur Sorge!\p"
	.string "Ich brauche Rat.\p"
	.string "Mein POKéMON.\p"
	.string "{STR_VAR_1} und {STR_VAR_2}, was ist\n"
	.string "würdiger?$"

gText_ApprenticeMonThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Keine Frage?\p"
	.string "Verstehe. Gut.\n"
	.string "Danke für die Zeit.\p"
	.string "Hoffentlich schaff ich das.\p"
	.string "Auf Wiedersehen!$"

gText_ApprenticeWhichMove0::
	.string "Waaah! Oh, {PLAYER}!\n"
	.string "Schnief… Hicks…\p"
	.string "Dilemma!\n"
	.string "Welche Attacke für {STR_VAR_1}…\p"
	.string "Bitte, {PLAYER}.\n"
	.string "Entscheide du!\p"
	.string "Für mein {STR_VAR_1}, {STR_VAR_2}\n"
	.string "oder {STR_VAR_3}?$"

gText_ApprenticeMoveThanks0::
	.string "{STR_VAR_1}?\n"
	.string "Waaaaah!\p"
	.string "Oh! Sorry, {PLAYER}!\n"
	.string "Ich heule vor Freude…\p"
	.string "Schnief…\n"
	.string "Danke vielmals!$"

gText_ApprenticeWhichMove1::
	.string "Yay! Hi, {PLAYER}!\n"
	.string "Ich brauch Rat!\p"
	.string "Coole Attacke für {STR_VAR_1}.\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}.\l"
	.string "Was empfiehlst du?$"

gText_ApprenticeMoveThanks1::
	.string "{STR_VAR_1} ist besser? Denk ich auch!\n"
	.string "Okay, mach ich!\p"
	.string "Lehre mich weiter, Lehrer!$"

gText_ApprenticeWhichMove2::
	.string "{PLAYER}, hallo!\n"
	.string "Mein {STR_VAR_1}, die Attacken.\p"
	.string "{STR_VAR_2} und {STR_VAR_3}.\p"
	.string "Was ist stärker für mein {STR_VAR_1}?$"

gText_ApprenticeMoveThanks2::
	.string "{STR_VAR_1}?\n"
	.string "Okay, kapiert!\p"
	.string "Ich bringe {STR_VAR_1} bei!\p"
	.string "Bis dann!$"

gText_ApprenticeWhichMove3::
	.string "Ohhh, {PLAYER}…\n"
	.string "Ich bin hoffnungslos!\p"
	.string "Ich hab ein POKéMON, aber welche\n"
	.string "Attacke…\p"
	.string "Es bedeutet dir nichts, {PLAYER}.\p"
	.string "Aber mir viel…\p"
	.string "Bitte, {PLAYER}, wähle für {STR_VAR_1}.\p"
	.string "{STR_VAR_2} und {STR_VAR_3}…$"

gText_ApprenticeMoveThanks3::
	.string "Verstanden!\p"
	.string "Will es überhaupt {STR_VAR_1} lernen…\l"
	.string "Nein! Ich schaff das!\p"
	.string "Danke!$"

gText_ApprenticeWhichMove4::
	.string "Oh, {PLAYER}{KUN}!\n"
	.string "Ich wollte dich sehen!\p"
	.string "Welche Attacke für {STR_VAR_1}?\p"
	.string "Entscheide du!\p"
	.string "{STR_VAR_2} und {STR_VAR_3}?\l"
	.string "Was ist besser?$"

gText_ApprenticeMoveThanks4::
	.string "{STR_VAR_1}? Toll!\p"
	.string "Da du entschieden hast,\n"
	.string "{PLAYER}{KUN}, bin ich nicht sauer,\l"
	.string "wenn ich verliere.\p"
	.string "Bis zum nächsten Rat.\n"
	.string "Bye!$"

gText_ApprenticeWhichMove5::
	.string "Wie kann man so beschäftigt sein?\n"
	.string "Hey, {PLAYER}{KUN}!\l"
	.string "Wie geht’s?\p"
	.string "Joggen, schwimmen, kochen!\p"
	.string "Ich bin so busy!\p"
	.string "Welche Attacke für {STR_VAR_1}?\p"
	.string "{STR_VAR_2} sieht gut aus?\n"
	.string "Aber {STR_VAR_3} auch.\p"
	.string "{PLAYER}{KUN}, gib mir Rat! Was ist gut?$"

gText_ApprenticeMoveThanks5::
	.string "Okay, kapiert.\n"
	.string "Ich mach Platz im Kalender und\l"
	.string "lehre es.\p"
	.string "Gut, dich als Mentor zu haben.\n"
	.string "Danke! Bis dann!$"

gText_ApprenticeWhichMove6::
	.string "Oh! Glück!\n"
	.string "Wieder da, {PLAYER}!\l"
	.string "Ich brauch deinen Kopf.\p"
	.string "Trommelwirbel!\n"
	.string "Die Frage ist…\p"
	.string "Für mein {STR_VAR_1}, {STR_VAR_2} oder\n"
	.string "{STR_VAR_3}?$"

gText_ApprenticeMoveThanks6::
	.string "Ahhh!\n"
	.string "{STR_VAR_1}, sagst du!\l"
	.string "Danke für die coole Antwort!\p"
	.string "Das war’s.\p"
	.string "Treffen wir uns wieder hier?\n"
	.string "Danke!$"

gText_ApprenticeWhichMove7::
	.string "Oh, hallo, {PLAYER}.\n"
	.string "Alles gut?\p"
	.string "Ich brauche Rat.\n"
	.string "Mein liebstes {STR_VAR_1}.\p"
	.string "Die ideale Attacke?\l"
	.string "{STR_VAR_2} oder {STR_VAR_3}?$"

gText_ApprenticeMoveThanks7::
	.string "{STR_VAR_1} also!\n"
	.string "Ich lehre das sofort!\p"
	.string "Danke, {PLAYER}.\n"
	.string "Hoffentlich hilfst du mir wieder.\l"
	.string "Pass auf dich auf!$"

gText_ApprenticeWhichMove8::
	.string "Ieek! {PLAYER}! Wiedersehen!\n"
	.string "Ich… freu mich!\p"
	.string "Du bist immer da für mich, {PLAYER}!\p"
	.string "Empfiehl mir eine Attacke!\p"
	.string "Für mein {STR_VAR_1}!\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?$"

gText_ApprenticeMoveThanks8::
	.string "Oh-oh-oh! Danke!\n"
	.string "{STR_VAR_1} ist es!\l"
	.string "Verstanden!\p"
	.string "Hoffentlich bringst du mir mehr bei.$"

gText_ApprenticeWhichMove9::
	.string "Hola, {PLAYER}{KUN}, bueno!\n"
	.string "Ich hoffe auf Rat!\p"
	.string "Beste Attacke für {STR_VAR_1}?\p"
	.string "Damit ich gewinne!\p"
	.string "{STR_VAR_2}?\n"
	.string "Oder {STR_VAR_3}?$"

gText_ApprenticeMoveThanks9::
	.string "Uh-huh, {STR_VAR_1}!\n"
	.string "Si, bueno!\l"
	.string "Ich bring’s bei, ka-blam!\p"
	.string "Danke, wie immer!\n"
	.string "Adios!$"

gText_ApprenticeWhichMove10::
	.string "{PLAYER}{KUN}, wild!\p"
	.string "Mein POKéMON!\n"
	.string "Hat sechs Attacken gelernt!\p"
	.string "Gelogen!\n"
	.string "Wahahaha!\p"
	.string "Aber das nicht.\n"
	.string "Ich bin schlecht in Attacken.\p"
	.string "Entscheide du, Meister!\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}--\n"
	.string "was passt zu {STR_VAR_1}?$"

gText_ApprenticeMoveThanks10::
	.string "Okay, {STR_VAR_1}?\n"
	.string "Ich nehme die andere!\p"
	.string "Scherz!\n"
	.string "Ich gehorche, Meister!\p"
	.string "Danke, Meister!\n"
	.string "Lehre mich weiter!$"

gText_ApprenticeWhichMove11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Der Rapper-MATROSE!\n"
	.string "Frag nicht warum.\p"
	.string "Eine Attacken-Frage,\n"
	.string "ich brauch deinen Rat!\p"
	.string "{STR_VAR_2} und {STR_VAR_3}.\n"
	.string "Was ist das Beste für {STR_VAR_1}?$"

gText_ApprenticeMoveThanks11::
	.string "{STR_VAR_1}, sagst du, hey, hey!\n"
	.string "Ich bring’s bei!\p"
	.string "Wenn ich Rat brauche,\n"
	.string "{PLAYER}, hör ich auf dich!$"

gText_ApprenticeWhichMove12::
	.string "Oh, yeah, ist das {PLAYER}!\p"
	.string "Soll ich Rat holen?\n"
	.string "Warum nicht! Ich rede ja schon!\p"
	.string "{PLAYER}, überrascht?\n"
	.string "Ich will Rat, siehst du?\p"
	.string "Hörst du mich?\n"
	.string "Du hörst mich!\p"
	.string "Mein {STR_VAR_1}--was soll es nutzen?\n"
	.string "{STR_VAR_2} oder {STR_VAR_3},\l"
	.string "was wählst du?$"

gText_ApprenticeMoveThanks12::
	.string "Wenn {STR_VAR_1} das Beste ist,\n"
	.string "mach ich das!\p"
	.string "Nun, {PLAYER}, ich muss los,\n"
	.string "vergiss mich nicht.\p"
	.string "Bis dann, mein Freund!$"

gText_ApprenticeWhichMove13::
	.string "Gahack! Gaah! Oh, {PLAYER}{KUN}…\n"
	.string "Erkältung…\p"
	.string "Will Attacke wählen,\n"
	.string "aber bin schwach…\p"
	.string "Also, entscheide du.\p"
	.string "{PLAYER}{KUN}, {STR_VAR_2} und\n"
	.string "{STR_VAR_3} für {STR_VAR_1}?$"

gText_ApprenticeMoveThanks13::
	.string "Hm, {STR_VAR_1}, okay. Hust!\n"
	.string "Ich bring’s bei, wenn ich fit bin.\p"
	.string "Hoffentlich kann ich dich weiter\n"
	.string "fragen.$"

gText_ApprenticeWhichMove14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…?\p"
	.string "Guck nicht so.\n"
	.string "Ich werde nervös…\l"
	.string "Ich… brauch Rat.\p"
	.string "Peinlich, aber ich weiß nicht.\p"
	.string "Für mein {STR_VAR_1}.\n"
	.string "{STR_VAR_2} oder {STR_VAR_3}?$"

gText_ApprenticeMoveThanks14::
	.string "Oh… Okay!\n"
	.string "Ich versuche {STR_VAR_1}.\p"
	.string "Hoffentlich kann ich das lehren…\n"
	.string "Nervös…\p"
	.string "Danke, {PLAYER}{KUN}.\n"
	.string "Hoffentlich hilfst du mir wieder.$"

gText_ApprenticeWhichMove15::
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein…\n"
	.string "Aber bist du echt?\p"
	.string "Ein Mimikry?\p"
	.string "Nein, nein, wenn du echt bist, gut.\n"
	.string "Nicht böse sein!\p"
	.string "Ich brauche Rat.\p"
	.string "Mein {STR_VAR_1}.\p"
	.string "{STR_VAR_2} oder {STR_VAR_3}?$"

gText_ApprenticeMoveThanks15::
	.string "{STR_VAR_1}?\n"
	.string "Keine Frage?\p"
	.string "Verstehe. Gut.\n"
	.string "Danke für die Zeit.\p"
	.string "Hoffentlich kann mein POKéMON das\n"
	.string "lernen.\p"
	.string "Auf Wiedersehen!$"

gText_ApprenticePickWinSpeech0::
	.string "Oh… {PLAYER}?\n"
	.string "Es ist {PLAYER}!\l"
	.string "Oh! Schnief… heul… Hör zu!\p"
	.string "Ich… Ich bin so nervös,\n"
	.string "ich heule, auch wenn ich gewinne…\p"
	.string "Ich will was Cooles sagen…\p"
	.string "Bitte, {PLAYER}!\n"
	.string "Bring mir was Cooles bei,\l"
	.string "damit ich nicht heule!$"

gText_ApprenticeWinSpeechThanks0::
	.string "{STR_VAR_1}\p"
	.string "Geil! Krass! Awoooh!\n"
	.string "Echt cool!\p"
	.string "Oh… Sorry…\n"
	.string "Ich heule vor Freude…\p"
	.string "Schnief… {PLAYER}!\n"
	.string "Danke für alles!\p"
	.string "Ich kämpfe für dich, {PLAYER}!\p"
	.string "{PLAYER}…\n"
	.string "Nächstes Mal… Kämpfen wir!$"

gText_ApprenticePickWinSpeech1::
	.string "Yay! Es ist {PLAYER}! Hallo!\n"
	.string "Ich wollte was fragen!\p"
	.string "Ich will was Cooles sagen, wenn ich\n"
	.string "gewinne.\p"
	.string "Hast du einen Spruch?$"

gText_ApprenticeWinSpeechThanks1::
	.string "{STR_VAR_1}\p"
	.string "Oh, wow! So cool!\n"
	.string "Okay, das sag ich!\p"
	.string "Danke fürs Lehren!\n"
	.string "Ich geb alles!\p"
	.string "Wenn wir uns wiedersehen, kämpfen\n"
	.string "wir!$"

gText_ApprenticePickWinSpeech2::
	.string "{PLAYER}, hallo!\p"
	.string "Wir sind bereit, außer eine Sache.\p"
	.string "Ich will was schreien beim Sieg.\p"
	.string "Denk dir was aus!$"

gText_ApprenticeWinSpeechThanks2::
	.string "{STR_VAR_1}\p"
	.string "…Cool!\n"
	.string "Das nutze ich!\p"
	.string "Ich kämpfe überall.\p"
	.string "Vielleicht auch gegen dich, {PLAYER}.\p"
	.string "Nächstes Mal auf dem Schlachtfeld!$"

gText_ApprenticePickWinSpeech3::
	.string "Hallo, {PLAYER}…\n"
	.string "Sorry, ich bin hoffnungslos…\p"
	.string "Sogar wenn…\n"
	.string "Wenn ich gewinne, weiß ich nicht\l"
	.string "was ich sagen soll…\p"
	.string "Es bedeutet dir nichts, {PLAYER}.\p"
	.string "Aber mir viel…\p"
	.string "Bitte, {PLAYER}, was soll ich sagen?$"

gText_ApprenticeWinSpeechThanks3::
	.string "{STR_VAR_1}\p"
	.string "Inspirierend…\p"
	.string "Äh… Darf jemand wie ich das sagen?\p"
	.string "Nein! Ich mach’s!\p"
	.string "{PLAYER}, danke für deine Geduld…\p"
	.string "Ich verspreche Besserung.\p"
	.string "Du vergisst mich sicher, aber lass\n"
	.string "uns wiedersehen!$"

gText_ApprenticePickWinSpeech4::
	.string "Oh, {PLAYER}{KUN}.\n"
	.string "Hör mal.\p"
	.string "Ich klinge nicht immer nett…\p"
	.string "Wenn ich gewinne, wirke ich arrogant.\p"
	.string "Ich will nicht gehasst werden,\n"
	.string "also will ich was Nettes sagen.\p"
	.string "Aber mir fällt nichts ein!\n"
	.string "Denk dir was aus!$"

gText_ApprenticeWinSpeechThanks4::
	.string "{STR_VAR_1}\p"
	.string "Nicht schlecht!\n"
	.string "Jup, das nehm ich!\p"
	.string "Ich geh los und nutze deine Lehren.\p"
	.string "Sorry, dass ich so aufdringlich war!\p"
	.string "Nächstes Mal kämpfen wir, okay?\n"
	.string "Tschö!$"

gText_ApprenticePickWinSpeech5::
	.string "Oh, ich bin so beschäftigt!\n"
	.string "Oh, hey, ich hab dich gesucht,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Alles gut?\n"
	.string "Bei mir wie immer.\p"
	.string "Rennen, Kämpfen, Karten. Warum so\n"
	.string "busy?\p"
	.string "Aber auch wenn ich busy bin, ist es\n"
	.string "unhöflich, wortlos zu gehen.\p"
	.string "Was ist ein cooler Spruch zum\n"
	.string "Abgang? {PLAYER}{KUN}, hilf mir!$"

gText_ApprenticeWinSpeechThanks5::
	.string "{STR_VAR_1}\p"
	.string "Okay, kapiert.\n"
	.string "Dafür hab ich Zeit!\p"
	.string "Ehrlich, gut, dich als Mentor zu\n"
	.string "haben.\p"
	.string "Ich mach Zeit zum Kämpfen.\p"
	.string "Danke, {PLAYER}{KUN}!\n"
	.string "Wir müssen kämpfen, eines Tages!$"

gText_ApprenticePickWinSpeech6::
	.string "Glück gehabt!\n"
	.string "{PLAYER}! Froh dich zu sehen!\l"
	.string "Brauch Rat!\p"
	.string "Trommelwirbel!\n"
	.string "Die letzte Frage…\p"
	.string "Siegspruch mit Flair?$"

gText_ApprenticeWinSpeechThanks6::
	.string "{STR_VAR_1}\p"
	.string "Das… Das ist fabelhaft!\n"
	.string "Würdevol und cool! Meins!\p"
	.string "…Ich werde besser, was?\p"
	.string "Ich fordere andere heraus.\p"
	.string "{PLAYER}, dein Rat half.\p"
	.string "Vielleicht kämpfen wir mal!\p"
	.string "Danke für alles!$"

gText_ApprenticePickWinSpeech7::
	.string "Oh, {PLAYER}.\n"
	.string "Froh dich zu treffen!\p"
	.string "Keine Sorgen mehr um POKéMON.\p"
	.string "Ich sorge mich um mich…\p"
	.string "TRAINER sagen was beim Sieg.\p"
	.string "Ich will das auch!\p"
	.string "Bitte, was soll ich sagen?$"

gText_ApprenticeWinSpeechThanks7::
	.string "{STR_VAR_1}\p"
	.string "Ah! Das erfrischt mich!\p"
	.string "Ich nutze es sofort!\p"
	.string "Ich muss gehen, {PLAYER}…\p"
	.string "Ich kämpfe, aber vergesse dich nie.\p"
	.string "Vielleicht eines Tages…\n"
	.string "Leb wohl!$"

gText_ApprenticePickWinSpeech8::
	.string "Ieek! {PLAYER}!\n"
	.string "Ich… freu mich!\p"
	.string "Oh-oh-oh! Ich muss fragen!\p"
	.string "Ich habe gewonnen.\n"
	.string "Berauschend!\p"
	.string "Aber ich konnte nichts sagen!\p"
	.string "Also {PLAYER}, denk dir einen\n"
	.string "Abgangs-Spruch aus!$"

gText_ApprenticeWinSpeechThanks8::
	.string "{STR_VAR_1}\p"
	.string "Waaaaah!\n"
	.string "Ich sage das?!\l"
	.string "Ich… bin delirisch!\p"
	.string "D-d-danke!\n"
	.string "Kein Bedauern!\p"
	.string "Ich reise und kämpfe.\p"
	.string "Alles dank dir, {PLAYER}.\n"
	.string "Wirklich, danke!\p"
	.string "Muss los, bis zum Kampf!$"

gText_ApprenticePickWinSpeech9::
	.string "Hola, bueno!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Ich will reisen und kämpfen.\p"
	.string "Aber vorher Rat!\p"
	.string "Wenn ich gewinne, was soll ich\n"
	.string "prahlen?$"

gText_ApprenticeWinSpeechThanks9::
	.string "{STR_VAR_1}\p"
	.string "Uh-huh, süß!\n"
	.string "Si, bueno!\l"
	.string "Ich sag das, zack!\p"
	.string "Zeit für Tschüss!\n"
	.string "Danke!\p"
	.string "Kämpf mal gegen mich, OK?\n"
	.string "Adios!$"

gText_ApprenticePickWinSpeech10::
	.string "{PLAYER}{KUN}, Problem!\p"
	.string "Wenn ich gewinne, prale ich eine\n"
	.string "Stunde!\p"
	.string "Gelogen!\n"
	.string "Wahahaha!\p"
	.string "Aber das nicht.\n"
	.string "Ich kann nicht gut reden.\p"
	.string "Entscheide, was ich sagen soll,\n"
	.string "Meister!$"

gText_ApprenticeWinSpeechThanks10::
	.string "{STR_VAR_1}\p"
	.string "Das soll ich sagen?\n"
	.string "Dann lass ich es!\p"
	.string "Scherz!\n"
	.string "Ich gehorche, Meister!\p"
	.string "Danke fürs Lehren, Meister!\p"
	.string "Ich verstehe jetzt TRAINER-Sein.\p"
	.string "Ich gewinne gegen jeden.\p"
	.string "Vielleicht gegen dich, Meister!\p"
	.string "Das war’s!\n"
	.string "Leb wohl, Meister!$"

gText_ApprenticePickWinSpeech11::
	.string "A-H-O-I!\n"
	.string "Das heißt Ahoi!\p"
	.string "Der Rapper-MATROSE!\n"
	.string "Letzte Frage, nicht weinen!\p"
	.string "Spruch-Frage,\n"
	.string "ich brauch Rat!\p"
	.string "Wenn ich siege, was sag ich cool?$"

gText_ApprenticeWinSpeechThanks11::
	.string "{STR_VAR_1}\p"
	.string "Perfekt! Das nehm ich.\n"
	.string "Gut gewählt!\p"
	.string "Ich flieg aus dem Nest!\p"
	.string "Danke!\n"
	.string "Kampf-Spree!\p"
	.string "B-O-N-V-O-Y-A-G-E!\n"
	.string "Bon Voyage,\l"
	.string "meine Hommage!$"

gText_ApprenticePickWinSpeech12::
	.string "Oh, yeah, {PLAYER}!\n"
	.string "Wieder da!\p"
	.string "Soll ich fragen?\n"
	.string "Warum nicht! Ich frage!\p"
	.string "Jedenfalls, {PLAYER}…\n"
	.string "Hörst du mich?\l"
	.string "Du hörst mich!\l"
	.string "Ich brauch Rat!\p"
	.string "Was soll ich schreien?\n"
	.string "Was Cooles beim Sieg.\p"
	.string "Komm schon, sag es!$"

gText_ApprenticeWinSpeechThanks12::
	.string "{STR_VAR_1}\p"
	.string "Alles klar!\n"
	.string "Ich nutze das!\p"
	.string "Keine Fragen mehr.\n"
	.string "Winken bleibt.\p"
	.string "Vielleicht treffen wir uns,\n"
	.string "einer verliert.\p"
	.string "Zeit für Abschied.\p"
	.string "Nun, {PLAYER}, ich muss los,\n"
	.string "vergiss mich nicht!\p"
	.string "Mach’s gut, {PLAYER}!\n"
	.string "Hab dich lieb!$"

gText_ApprenticePickWinSpeech13::
	.string "{PLAYER}{KUN}, ich bin fertig…\n"
	.string "Meine Nase läuft…\p"
	.string "Ich wollte was Cooles denken.\p"
	.string "Es inspirierte mich, ich weinte,\n"
	.string "Nase läuft…\p"
	.string "Also, entscheide du, {PLAYER}{KUN}.\p"
	.string "Wenn ich siege,\n"
	.string "was sag ich?$"

gText_ApprenticeWinSpeechThanks13::
	.string "{STR_VAR_1}\p"
	.string "… … …Gut.\n"
	.string "Nein, ehrfurchtgebietend!\l"
	.string "Neue Tränen!\p"
	.string "Trotz Tränen und Nase,\n"
	.string "ich nutze das!\p"
	.string "Keine Fragen mehr, {PLAYER}{KUN}.\p"
	.string "Ab jetzt Rivalen!\n"
	.string "Danke für alles!$"

gText_ApprenticePickWinSpeech14::
	.string "Äh… Ähm…\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Guck nicht so.\n"
	.string "Ich werde nervös.\p"
	.string "Ich… brauch Rat.\n"
	.string "Der letzte…\p"
	.string "Peinlich, aber wenn ich siege?\l"
	.string "Was sag ich?$"

gText_ApprenticeWinSpeechThanks14::
	.string "{STR_VAR_1}\p"
	.string "Oh… Okay!\n"
	.string "Ich versuche es!\l"
	.string "Vielleicht zu nervös…\p"
	.string "Danke, {PLAYER}{KUN}.\n"
	.string "Ich muss gehen.\p"
	.string "Ich gehorche dir,\n"
	.string "{PLAYER}{KUN}, und gebe mein Bestes.$"

gText_ApprenticePickWinSpeech15::
	.string "Hm? Du scheinst {PLAYER}{KUN} zu sein…\n"
	.string "Echt?\l"
	.string "Eine Puppe?\p"
	.string "Nein, nein!\n"
	.string "Wenn echt, vergiss Rudeness.\p"
	.string "Sei nicht böse. Ich will Rat.\p"
	.string "Ein Spruch.\p"
	.string "Was soll ich sagen,\n"
	.string "wenn ich siege?$"

gText_ApprenticeWinSpeechThanks15::
	.string "{STR_VAR_1}\p"
	.string "… … … … … …\n"
	.string "Wenn ich siege…\p"
	.string "{STR_VAR_1}\p"
	.string "…Ernsthaft?\p"
	.string "Verstehe. Gut.\n"
	.string "Danke für die Zeit.\p"
	.string "Hoffentlich kann ich das nutzen.\p"
	.string "Keine Fragen mehr.\p"
	.string "Zeit für Abschied.\p"
	.string "Danke, Mentor!\n"
	.string "Sorry für Skepsis!$"
