BattleDome_Text_Potential1::
	.string "Der absolute Top-Favorit auf den Sieg!$"

BattleDome_Text_Potential2::
	.string "Ein Team, das sicher im Finale landet.$"

BattleDome_Text_Potential3::
	.string "Landet höchstwahrscheinlich unter den Top 3.$"

BattleDome_Text_Potential4::
	.string "Ein ernsthafter Kandidat für den Titel.$"

BattleDome_Text_Potential5::
	.string "Ein Team mit erstklassigem Potenzial.$"

BattleDome_Text_Potential6::
	.string "Der gefährliche Außenseiter des Turniers.$"

BattleDome_Text_Potential7::
	.string "Ein überdurchschnittlich starkes Team.$"

BattleDome_Text_Potential8::
	.string "Absolutes Mittelmaß in diesem Turnier.$"

BattleDome_Text_Potential9::
	.string "Ein Team mit durchschnittlichem Potenzial.$"

BattleDome_Text_Potential10::
	.string "Eher schwächer als der Durchschnitt.$"

BattleDome_Text_Potential11::
	.string "Sucht verzweifelt nach dem ersten Sieg.$"

BattleDome_Text_Potential12::
	.string "Schon ein einziger Sieg wäre ein Wunder.$"

BattleDome_Text_Potential13::
	.string "Insgesamt ein ziemlich erbärmliches Team.$"

BattleDome_Text_Potential14::
	.string "Ein Team mit extrem geringem Potenzial.$"

BattleDome_Text_Potential15::
	.string "Siegchancen? Gehen gegen Null.$"

BattleDome_Text_Potential16::
	.string "Das Team, das am sichersten verlieren wird.$"

BattleDome_Text_PotentialDomeAceTucker::
	.string "Der perfekte, unbesiegbare Superstar!$"

BattleDome_Text_StyleRiskDisaster::
	.string "Riskiert für den Sieg die totale Katastrophe.$"

BattleDome_Text_StyleEndureLongBattles::
	.string "Spezialisiert auf zermürbende Kämpfe.$"

BattleDome_Text_StyleVariesTactics::
	.string "Passt die Taktik brutal dem Gegner an.$"

BattleDome_Text_StyleToughWinningPattern::
	.string "Folgt einem knallharten Sieg-Schema.$"

BattleDome_Text_StyleUsesVeryRareMove::
	.string "Überrascht mit extrem seltenen Attacken.$"

BattleDome_Text_StyleUsesStartlingMoves::
	.string "Nutzt verstörende und störende Attacken.$"

BattleDome_Text_StyleConstantlyWatchesHP::
	.string "Achtet manisch auf die eigenen KP.$"

BattleDome_Text_StyleStoresAndLoosesPower::
	.string "Sammelt Energie, um sie zu entfesseln.$"

BattleDome_Text_StyleEnfeeblesFoes::
	.string "Meister darin, den Gegner zu schwächen.$"

BattleDome_Text_StylePrefersLuckTactics::
	.string "Verlässt sich blind auf das reine Glück.$"

BattleDome_Text_StyleRegalAtmosphere::
	.string "Greift mit einer arroganten Aura an.$"

BattleDome_Text_StylePowerfulLowPPMoves::
	.string "Setzt auf brachiale Gewalt mit wenig AP.$"

BattleDome_Text_StyleEnfeebleThenAttack::
	.string "Erst den Geist brechen, dann angreifen.$"

BattleDome_Text_StyleBattlesWhileEnduring::
	.string "Steckt alles ein und schlägt dann zu.$"

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.string "Zielt darauf ab, Gegner psychisch zu ruinieren.$"

BattleDome_Text_StyleStrongAndStraightforward::
	.string "Nutzt starke und plumpe Attacken.$"

BattleDome_Text_StyleAggressivelyStrongMoves::
	.string "Setzt aggressiv auf rohe Gewalt.$"

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.string "Weicht Angriffen feige und geschickt aus.$"

BattleDome_Text_StyleUsesUpsettingMoves::
	.string "Nutzt Attacken, die den Gegner entnerven.$"

BattleDome_Text_StyleUsesPopularMoves::
	.string "Nutzt nur, was gerade im Trend liegt.$"

BattleDome_Text_StyleHasPowerfulComboMoves::
	.string "Setzt auf tödliche Attacken-Kombos.$"

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.string "Geht kein Risiko ein. Nur sichere Treffer.$"

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.string "Setzt aggressiv auf effekthascherische Shows.$"

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.string "Scheißt auf die Abwehr. Alles in den Angriff.$"

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.string "Versteckt sich feige hinter der Abwehr.$"

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.string "Schlägt schnell und unbarmherzig zu.$"

BattleDome_Text_StyleUsesAddedEffectMoves::
	.string "Setzt auf fiese Nebeneffekte.$"

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.string "Nutzt eine ausgewogene Mischung an Qualen.$"

BattleDome_Text_StyleSampleMessage1::
	.string "Das ist Testnachricht 1.$"

BattleDome_Text_StyleSampleMessage2::
	.string "Das ist Testnachricht 2.$"

BattleDome_Text_StyleSampleMessage3::
	.string "Das ist Testnachricht 3.$"

BattleDome_Text_StyleSampleMessage4::
	.string "Das ist Testnachricht 4.$"

BattleDome_Text_EmphasizesHPAndAtk::
	.string "Fokus auf KP und ANGRIFF.$"

BattleDome_Text_EmphasizesHPAndDef::
	.string "Fokus auf KP und VERTEIDIGUNG.$"

BattleDome_Text_EmphasizesHPAndSpeed::
	.string "Fokus auf KP und INITIATIVE.$"

BattleDome_Text_EmphasizesHPAndSpAtk::
	.string "Fokus auf KP und SP.-ANGRIFF.$"

BattleDome_Text_EmphasizesHPAndSpDef::
	.string "Fokus auf KP und SP.-VERTEIDIGUNG.$"

BattleDome_Text_EmphasizesAtkAndDef::
	.string "Fokus auf ANGRIFF und VERTEIDIGUNG.$"

BattleDome_Text_EmphasizesAtkAndSpeed::
	.string "Fokus auf ANGRIFF und INITIATIVE.$"

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.string "Fokus auf ANGRIFF und SP.-ANGRIFF.$"

BattleDome_Text_EmphasizesAtkAndSpDef::
	.string "Fokus auf ANGRIFF und SP.-VERTEIDIGUNG.$"

BattleDome_Text_EmphasizesDefAndSpeed::
	.string "Fokus auf VERTEIDIGUNG und INITIATIVE.$"

BattleDome_Text_EmphasizesDefAndSpAtk::
	.string "Fokus auf VERTEIDIGUNG und SP.-ANGRIFF.$"

BattleDome_Text_EmphasizesDefAndSpDef::
	.string "Fokus auf VERTEIDIGUNG und SP.-VERT.$"

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.string "Fokus auf INITIATIVE und SP.-ANGRIFF.$"

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.string "Fokus auf INITIATIVE und SP.-VERT.$"

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.string "Fokus auf SP.-ANGRIFF und SP.-VERT.$"

BattleDome_Text_EmphasizesHP::
	.string "Fokus auf KP.$"

BattleDome_Text_EmphasizesAtk::
	.string "Fokus auf ANGRIFF.$"

BattleDome_Text_EmphasizesDef::
	.string "Fokus auf VERTEIDIGUNG.$"

BattleDome_Text_EmphasizesSpeed::
	.string "Fokus auf INITIATIVE.$"

BattleDome_Text_EmphasizesSpAtk::
	.string "Fokus auf SPEZIAL-ANGRIFF.$"

BattleDome_Text_EmphasizesSpDef::
	.string "Fokus auf SPEZIAL-VERTEIDIGUNG.$"

BattleDome_Text_NeglectsHPAndAtk::
	.string "Vernachlässigt KP und ANGRIFF.$"

BattleDome_Text_NeglectsHPAndDef::
	.string "Vernachlässigt KP und VERTEIDIGUNG.$"

BattleDome_Text_NeglectsHPAndSpeed::
	.string "Vernachlässigt KP und INITIATIVE.$"

BattleDome_Text_NeglectsHPAndSpAtk::
	.string "Vernachlässigt KP und SP.-ANGRIFF.$"

BattleDome_Text_NeglectsHPAndSpDef::
	.string "Vernachlässigt KP und SP.-VERT.$"

BattleDome_Text_NeglectsAtkAndDef::
	.string "Vernachlässigt ANGRIFF und VERT.$"

BattleDome_Text_NeglectsAtkAndSpeed::
	.string "Vernachlässigt ANGRIFF und SPEED.$"

BattleDome_Text_NeglectsAtkAndSpAtk::
	.string "Vernachlässigt ANGRIFF und SP.-ANG.$"

BattleDome_Text_NeglectsAtkAndSpDef::
	.string "Vernachlässigt ANGRIFF und SP.-VERT.$"

BattleDome_Text_NeglectsDefAndSpeed::
	.string "Vernachlässigt VERT. und SPEED.$"

BattleDome_Text_NeglectsDefAndSpAtk::
	.string "Vernachlässigt VERT. und SP.-ANG.$"

BattleDome_Text_NeglectsDefAndSpDef::
	.string "Vernachlässigt VERT. und SP.-VERT.$"

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.string "Vernachlässigt SPEED und SP.-ANG.$"

BattleDome_Text_NeglectsSpeedAndSpDef::
	.string "Vernachlässigt SPEED und SP.-VERT.$"

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.string "Vernachlässigt SP.-ANG. und SP.-VERT.$"

BattleDome_Text_NeglectsHP::
	.string "Vernachlässigt die KP.$"

BattleDome_Text_NeglectsAtk::
	.string "Vernachlässigt den ANGRIFF.$"

BattleDome_Text_NeglectsDef::
	.string "Vernachlässigt die VERTEIDIGUNG.$"

BattleDome_Text_NeglectsSpeed::
	.string "Vernachlässigt die INITIATIVE.$"

BattleDome_Text_NeglectsSpAtk::
	.string "Vernachlässigt den SP.-ANGRIFF.$"

BattleDome_Text_NeglectsSpDef::
	.string "Vernachlässigt die SP.-VERTEIDIGUNG.$"

BattleDome_Text_RaisesMonsWellBalanced::
	.string "Trainiert seine Pokémon ausgeglichen.$"

BattleDome_Text_LetTheBattleBegin::
	.string "Lasset das Gemetzel beginnen!$"

BattleDome_Text_TrainerWonUsingMove::
	.string "{STR_VAR_1} siegte durch {STR_VAR_2}!$"

BattleDome_Text_TrainerBecameChamp::
	.string "{STR_VAR_1} ist der neue Champ!$"

BattleDome_Text_TrainerWonByDefault::
	.string "{STR_VAR_1} siegte kampflos!$"

BattleDome_Text_TrainerWonOutrightByDefault::
	.string "{STR_VAR_1} siegte haushoch kampflos!$"

BattleDome_Text_TrainerWonNoMoves::
	.string "{STR_VAR_1} siegte, ohne anzugreifen!$"

BattleDome_Text_TrainerWonOutrightNoMoves::
	.string "{STR_VAR_1} demütigte alle ohne Angriff!$"

BattleDome_Text_Round1Match1::
	.string "Runde 1, Kampf 1$"

BattleDome_Text_Round1Match2::
	.string "Runde 1, Kampf 2$"

BattleDome_Text_Round1Match3::
	.string "Runde 1, Kampf 3$"

BattleDome_Text_Round1Match4::
	.string "Runde 1, Kampf 4$"

BattleDome_Text_Round1Match5::
	.string "Runde 1, Kampf 5$"

BattleDome_Text_Round1Match6::
	.string "Runde 1, Kampf 6$"

BattleDome_Text_Round1Match7::
	.string "Runde 1, Kampf 7$"

BattleDome_Text_Round1Match8::
	.string "Runde 1, Kampf 8$"

BattleDome_Text_Round2Match1::
	.string "Runde 2, Kampf 1$"

BattleDome_Text_Round2Match2::
	.string "Runde 2, Kampf 2$"

BattleDome_Text_Round2Match3::
	.string "Runde 2, Kampf 3$"

BattleDome_Text_Round2Match4::
	.string "Runde 2, Kampf 4$"

BattleDome_Text_SemifinalMatch1::
	.string "Halbfinale 1$"

BattleDome_Text_SemifinalMatch2::
	.string "Halbfinale 2$"

BattleDome_Text_FinalMatch::
	.string "Finale$"
