gText_Birch_Welcome::
	.string "Sorry, dass du warten musstest.\p"
	.string "Willkommen in der Welt der POKéMON!\p"
	.string "Mein Name ist BIRK.\p"
	.string "Aber jeder nennt mich nur\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "Das nennt man ein “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Ich rede einfach nicht so\n"
	.string "lange. Du kennst ja alles.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Und du bist?$"

gText_Birch_BoyOrGirl::
	.string "Bist du ein Junge?\n"
	.string "Oder ein Mädchen?$"

gText_Birch_WhatsYourName::
	.string "Gut.\n"
	.string "Wie ist dein Name?$"

gText_Birch_SoItsPlayer::
	.string "Also,{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Cool!\p"
	.string "Du bist{PLAYER}{KUN}, der dieses\n"
	.string "ungewöhnliche Spiel freiwillig\l"
	.string "Spielen will? Naja..\p"
	.string "Deine Entscheidung.\n"
	.string "Lol.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Gut, bist du bereit?\p"
	.string "Dein eigenes Abenteuer wird\n"
	.string "nun beginnen.\p"
	.string "Sprich jeden an und Lies\n"
	.string "alles was die leute sagen,\l"
	.string "auch in allen Häusern.\p"
	.string "Komm später in mein POKéMON-LABOR,\n"
	.string "ich erwarte dich dort.\p"
	.string "$"
