gText_Birch_Welcome::
	.string "Sorry, dass du warten musstest.\p"
	.string "Willkommen in der Welt der Pokémon…\p"
	.string "Mein Name ist BIRK.\p"
	.string "Ich bin sozusagen der PROF für alles\n"
	.string "was mit Pokémon zu tun hat.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "In dieser Version gibt es ALLE\n"
	.string "Pokémon bis zur 9. Generation.\p"
    .string "Also auch deine Lieblings-\n"
    .string "Pokémon.\p"
	.string "Ach ja…\n"
	.string "Es passieren seltsame Dinge…\p"
	.string "Legendäre Pokémon tauchen in einer\n"
	.string "noch nie gesehenen Form auf…\p"
	.string "Manche nennen sie die “NYXTHRA-FORM“.\n"
	.string "Seltener als jedes Shiny.\p"
	.string "$"

gText_Birch_MainSpeech::
	.string "Keiner weiß, woher sie kommt.\n"
	.string "Unfälle? Mutationen? Experimente?\p"
	.string "Und mehrere Organisationen…\n"
	.string "…verhalten sich auffällig ruhig.\p"
	.string "Und ausgerechnet DU ziehst genau\n"
	.string "jetzt hierher. Zufall? Sicher nicht.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Aber gut, kommen wir\n"
    .string "erstmal zu dir!$"

gText_Birch_BoyOrGirl::
	.string "Bist du ein Junge?\n"
	.string "Oder ein Mädchen?$"

gText_Birch_WhatsYourName::
	.string "Gut.\n"
	.string "Wie ist dein Name?$"

gText_Birch_SoItsPlayer::
	.string "Also… {PLAYER}{KUN}, ja?\n"
	.string "Klingt nach Ärger.$"


gText_Birch_YourePlayer::
	.string "Cool.\p"
	.string "Du bist also {PLAYER}{KUN} - jemand,\n"
	.string "der freiwillig Smaragd nochmal spielt.\p"
	.string "Respekt. Du wirst es brauchen.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Gut, bist du bereit?\p"
	.string "Dein Abenteuer beginnt.\n"
	.string "Und diesmal ist einiges anders.\p"
	.string "Sprich mit allen. Hör hin.\n"
	.string "Vielleicht hat jemand Antworten…\p"
	.string "Ich bin im LABOR. Komm vorbei,\n"
	.string "wemm du Infos hast.\p"
	.string "$"
