@ NOTE: The brailleformat macro in this file is leftover from RS.
@	   The numbers are simply skipped over. If you'd like to omit
@	   this macro you must also stop it from skipping over this
@	   section by editing ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "SETZE STARKE EIN.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "ZUERST KOMMT\n"
	.braille "WAILORD.\n"
	.braille "ZU LETZT\n"
	.braille "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "IN DIESER\n"
	.braille "HOHLE\n"
	.braille "LEBTEN\n"
	.braille "WIR.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "WIR VERDANKEN\n"
	.braille "ALLES DEN\n"
	.braille "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "DOCH WIR\n"
	.braille "VERSIEGELTEN\n"
	.braille "DIE POKEMON\n"
	.braille "FORT.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "WIR FURCHTETEN SIE.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "DIE MIT MUT,\n"
	.braille "DIE MIT\n"
	.braille "HOFFNUNG.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "OFFNE EINE\n"
	.braille "TUR. EIN\n"
	.braille "EWIGES\n"
	.braille "POKEMON\n"
	.braille "WARTET.$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "LINKS, LINKS,\n"
	.braille "RUNTER, RUNTER.\n"
	.braille "DANN SETZE\n"
	.braille "ZERTRUMMERER EIN.$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "BLEIBE NAH\n"
	.braille "AN DER WAND.\n"
	.braille "LAUFE EINEN\n"
	.braille "KREIS.$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "DIE UNSEREN\n"
	.braille "WILLEN\n"
	.braille "ERBEN, SOLLEN\n"
	.braille "MITTEN IM\n"
	.braille "RAUM LEUCHTEN.$"

BabyBootCamp_Braille_SecretMessage:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DIES IST EINE\n"
	.braille "GEHEIME\n"
	.braille "BOTSCHAFT.$"

GraniteCave_B2F_Braille_JohtoStarters:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "ZWEITE ENDIVIE\n"
	.braille "VIERTE GLUMANDA\n"
	.braille "SECHSTE SCHIGGY.$"

