gContestHallPaintingCaption::
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}s {STR_VAR_3}$"

@ Unused
gContestPaintingContest::
	.string "WETTBEWERB$"

gContestRankNormal::
	.string "NORMAL-KLASSE$"

gContestRankSuper::
	.string "SUPER-KLASSE$"

gContestRankHyper::
	.string "HYPER-KLASSE$"

gContestRankMaster::
	.string "MEISTER-KLASSE$"

gContestLink::
	.string "LINK-WETTBEWERB$"

gContestCoolness::
	.string "COOLNESS$"

gContestBeauty::
	.string "SCHÖNHEIT$"

gContestCuteness::
	.string "NIEDLICHKEIT$"

gContestSmartness::
	.string "KLUGHEIT$"

gContestToughness::
	.string "STÄRKE$"


gContestPaintingCool1::
	.string "Unfassbar cool!\n"
	.string "Der legendäre {STR_VAR_1}$"

gContestPaintingCool2::
	.string "Hey, schau mal!\n"
	.string "Das ultra-coole {STR_VAR_1}$"

gContestPaintingCool3::
	.string "Achtung! Hier kommt\n"
	.string "das unfassbare {STR_VAR_1}$"


gContestPaintingBeauty1::
	.string "Die Schönheit des Jahrhunderts—\n"
	.string "{STR_VAR_1}$"

gContestPaintingBeauty2::
	.string "{STR_VAR_1}s funkelnder\n"
	.string "Blick verzaubert alle$"

gContestPaintingBeauty3::
	.string "Das Idol aller Trainer!\n"
	.string "{STR_VAR_1}$"


gContestPaintingCute1::
	.string "Zum Dahinschmelzen!\n"
	.string "{STR_VAR_1}$"

gContestPaintingCute2::
	.string "So süß, dass man\n"
	.string "einfach lächeln muss—{STR_VAR_1}$"

gContestPaintingCute3::
	.string "Ein Zwinkern genügt!\n"
	.string "Das niedliche {STR_VAR_1}$"


gContestPaintingSmart1::
	.string "Ein wahres Genie!\n"
	.string "{STR_VAR_1}$"

gContestPaintingSmart2::
	.string "{STR_VAR_1}—\n"
	.string "klüger als der Rest!$"

gContestPaintingSmart3::
	.string "Ein Meister des Verstands:\n"
	.string "{STR_VAR_1}$"


gContestPaintingTough1::
	.string "Geballte Kraft!\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough2::
	.string "Härter, stärker, besser—\n"
	.string "{STR_VAR_1}$"

gContestPaintingTough3::
	.string "Ein wahres Kraftpaket:\n"
	.string "{STR_VAR_1}$"
