@ With the exception of Link standby, none of the below texts are used

gTest_MissedTurn::
	.string "Zug verpennt!$"

gText_LinkStandby4::
	.string "Verbindung läuft… bleib locker!$"

gText_WinnerIsPlayersMon::
	.string "Der Sieger ist {STR_VAR_1}s{STR_VAR_2}!\n"
	.string "Respekt!$"

gText_WinnerIsPlayersMon2::
	.string "Der Sieg geht an {STR_VAR_1}s{STR_VAR_2}!{PAUSE_UNTIL_PRESS}$"

gText_PrimaryJudgingNumX::
	.string "Hauptwertung: Nummer {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SecondaryJudgingNumX::
	.string "Zweitwertung: Nummer {STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX::
	.string "Event festgelegt: Nr.{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MoveUsedMostOften::
	.string "Am häufigsten eingesetzter Move:\n"
	.string "{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_MostImpressiveMon::
	.string "Das beeindruckendste Pokémon:\n"
	.string "{STR_VAR_1}s {STR_VAR_2}{PAUSE_UNTIL_PRESS}$"

gText_SetEventNumX2::
	.string "Event gesetzt: Nr.{STR_VAR_1}{PAUSE_UNTIL_PRESS}$"

gText_LinkTVProgramWillNotBeMadeTrainerLost::
	.string "Kein TV-Beitrag heute.\n"
	.string "Der Trainer hat ordentlich verloren.{PAUSE_UNTIL_PRESS}$"
