gText_AppealNumWhichMoveWillBePlayed::
	.string "Auftritt Nr. {STR_VAR_1}!\n"
	.string "Wer blamiert sich jetzt?$"

gText_AppealNumButItCantParticipate::
	.string "Auftritt Nr. {STR_VAR_1}!\n"
	.string "Aber es ist unfähig!$"

gText_MonAppealedWithMove::
	.string "{STR_VAR_1} versucht es mit\n"
	.string "{STR_VAR_2}!$"

gText_MonWasWatchingOthers::
	.string "{STR_VAR_1} glotzt nur\n"
	.string "die anderen an.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AllOutOfAppealTime::
	.string "Die Zeit ist um!\n"
	.string "Gott sei Dank!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.string "Es schämt sich vor den\n"
	.string "anderen POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonCantMakeAnAppealAfterThis::
	.string "{STR_VAR_1} gibt auf und\n"
	.string "macht nichts mehr.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SettledDownJustLittleBit::
	.string "Es hat aufgehört zu\n"
	.string "zittern.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameObliviousToOtherMons::
	.string "Es ignoriert die\n"
	.string "Realität völlig.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_BecameLessAwareOfOtherMons::
	.string "Die anderen sind ihm\n"
	.string "langsam egal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoppedCaringAboutOtherMons::
	.string "Es scheißt auf die\n"
	.string "anderen POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToStartleOtherMons::
	.string "Es versucht, Panik zu\n"
	.string "verbreiten.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToDazzleOthers::
	.string "Es versucht, alle zu\n"
	.string "blenden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAwayFromMon::
	.string "Der JUROR wendet sich\n"
	.string "ekelnd von {STR_VAR_1} ab.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToUnnerveNextMon::
	.string "Es will das nächste\n"
	.string "Opfer brechen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonBecameNervous::
	.string "{STR_VAR_1} kriegt\n"
	.string "Panikattacken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_AppealTriedToUnnerveWaitingMons::
	.string "Der Auftritt soll den\n"
	.string "Warteraum verstören.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TauntedMonsDoingWell::
	.string "Es mobbt die guten\n"
	.string "POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonRegainedItsForm::
	.string "{STR_VAR_1} reißt sich\n"
	.string "zusammen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_TriedToJamMonDoingWell::
	.string "Sabotage gegen das\n"
	.string "gute POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StandoutMonHustledEvenMore::
	.string "Das arrogante {STR_VAR_1}\n"
	.string "gibt noch mehr an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_LargelyUnnoticedMonWorkedHard::
	.string "Das unsichtbare\n"
	.string "{STR_VAR_1} müht sich ab.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsMonBefore::
	.string "Es kopiert nur das\n"
	.string "POKéMON davor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell::
	.string "{STR_VAR_1} hat voll\n"
	.string "versagt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_WorkedAsMuchAsPrecedingMon::
	.string "Es macht denselben Mist\n"
	.string "wie der Vorgänger.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell2::
	.string "{STR_VAR_1} hat voll\n"
	.string "versagt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotGoWell3::
	.string "{STR_VAR_1} hat voll\n"
	.string "versagt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell::
	.string "{STR_VAR_1} war nicht\n"
	.string "ganz scheiße.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell::
	.string "{STR_VAR_1} war ganz\n"
	.string "okay.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently::
	.string "{STR_VAR_1} war\n"
	.string "überraschend gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWasDud::
	.string "{STR_VAR_1} war eine\n"
	.string "Enttäuschung.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealDidNotWorkVeryWell::
	.string "{STR_VAR_1} hat kaum\n"
	.string "funktioniert.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentSlightlyWell2::
	.string "{STR_VAR_1} war nicht\n"
	.string "ganz scheiße.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentPrettyWell2::
	.string "{STR_VAR_1} war ganz\n"
	.string "okay.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentVeryWell::
	.string "{STR_VAR_1} war richtig\n"
	.string "gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsAppealWentExcellently2::
	.string "{STR_VAR_1} war\n"
	.string "überraschend gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_SameTypeAsOneBeforeGood::
	.string "Dasselbe wie der davor.\n"
	.string "Herdentrieb--gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_NotSameTypeAsOneBeforeGood::
	.string "Nicht dasselbe wie der\n"
	.string "davor--gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_StoodOutMuchMoreThanMonBefore::
	.string "Es stiehlt dem Vorgänger\n"
	.string "die Show.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_DidntDoAsWellAsMonBefore::
	.string "Schlechter als das\n"
	.string "POKéMON davor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsConditionRoseAboveUsual::
	.string "{STR_VAR_1} ist voll\n"
	.string "aufgedreht.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MonsHotStatusMadeGreatAppeal::
	.string "{STR_VAR_1} ist auf\n"
	.string "Drogen--super Show!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedUpInLineForNextAppeal::
	.string "Es drängelt sich vor für\n"
	.string "die nächste Runde.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_MovedBackInLineForNextAppeal::
	.string "Es versteckt sich weiter\n"
	.string "hinten in der Schlange.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_ScrambledUpOrderForNextTurn::
	.string "Es bringt die Ordnung\n"
	.string "durcheinander.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"

gText_JudgeLookedAtMonExpectantly::
	.string "Der JUROR wartet auf\n"
	.string "einen Fehler von {STR_VAR_1}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverWell::
	.string "Die Kombo kam\n"
	.string "ganz gut an.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverVeryWell::
	.string "Die Kombo kam\n"
	.string "sehr gut an.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AppealComboWentOverExcellently::
	.string "Die Kombo war\n"
	.string "der Wahnsinn.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvertGaze::
	.string "{STR_VAR_1} guckt weg\n"
	.string "vor Scham.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonManagedToAvoidSeeingIt::
	.string "{STR_VAR_1} will das\n"
	.string "nicht sehen.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonIsntFazedByThatSortOfThing::
	.string "{STR_VAR_1} ist innerlich\n"
	.string "schon tot.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonBecameALittleDistracted::
	.string "{STR_VAR_1} verliert\n"
	.string "den Verstand.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_TriedToStartleOtherPokemon::
	.string "Es versucht, Panik zu\n"
	.string "verbreiten.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonLookedDownOutOfDistraction::
	.string "{STR_VAR_1} starrt\n"
	.string "auf den Boden.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTurnedBackOutOfDistraction::
	.string "{STR_VAR_1} dreht sich\n"
	.string "weg.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpUtteringCry::
	.string "{STR_VAR_1} schreit\n"
	.string "vor Angst.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCouldntHelpLeapingUp::
	.string "{STR_VAR_1} zuckt\n"
	.string "heftig zusammen.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonTrippedOutOfDistraction::
	.string "{STR_VAR_1} fällt auf\n"
	.string "die Fresse.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasTooNervousToMove::
	.string "{STR_VAR_1} ist gelähmt\n"
	.string "vor Angst.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItMessedUp2::
	.string "Aber es hat verkackt.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeTargetNervous::
	.string "Aber das Ziel blieb\n"
	.string "cool.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItFailedToMakeAnyoneNervous::
	.string "Niemand hatte Angst.\n"
	.string "Peinlich.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_ButItWasIgnored::
	.string "Aber alle haben es\n"
	.string "ignoriert…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CouldntImproveItsCondition::
	.string "Zustand nicht verbessert.\n"
	.string "Sinnlos…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_BadConditionResultedInWeakAppeal::
	.string "Schlechter Zustand,\n"
	.string "miese Show.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonWasUnaffected::
	.string "{STR_VAR_1} ist das\n"
	.string "egal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_RepeatedAppeal::
	.string "{STR_VAR_1} enttäuscht\n"
	.string "mit Wiederholung.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXWentOverGreat::
	.string "{STR_VAR_1}s {STR_VAR_3}\n"
	.string "war der Hammer.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXDidntGoOverWell::
	.string "{STR_VAR_1}s {STR_VAR_3}\n"
	.string "kam scheiße an…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsXGotTheCrowdGoing::
	.string "{STR_VAR_1}s {STR_VAR_3}\n"
	.string "heizt den Mob an.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonCantAppealNextTurn::
	.string "{STR_VAR_1} setzt\n"
	.string "nächstes Mal aus…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_AttractedCrowdsAttention::
	.string "Der Mob starrt es an.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_CrowdContinuesToWatchMon::
	.string "Der Mob starrt weiter\n"
	.string "auf {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_MonsMoveIsIgnored::
	.string "{STR_VAR_1}s\n"
	.string "{STR_VAR_2} wird ignoriert.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

gText_Contest_Shyness::
	.string "Feigheit$"

gText_Contest_Anxiety::
	.string "Panik$"

gText_Contest_Laziness::
	.string "Nullbock$"

gText_Contest_Hesitancy::
	.string "Zweifel$"

gText_Contest_Fear::
	.string "Terror$"
