EventTicket_Text_ShowOldSeaMap:
	.string "Die Fähre nach GRAPHITPORT ist…\p"
	.string "Hä? Was willst du?\n"
	.string "Diese Karte ist ja total versifft.\p"
	.string "Du willst da hin? Mitten ins Nichts?\n"
	.string "Ich hol den Boss. Der steht auf\l"
	.string "Himmelfahrtskommandos. Warte.$"

EventTicket_Text_ThatPass:
	.string "Die Fähre ist voll. Geh schwimmen.\p"
	.string "Oh?\n"
	.string "Dieser PASS… Er riecht nach Ärger.$"

EventTicket_Text_ShowEonTicket:
	.string "Ahoi, Landratte! Bist du der Irre mit\n"
	.string "dem Ticket zur Hölle?\p"
	.string "Du willst zu diesem Felsen im Süden?\n"
	.string "Da gibt's nichts außer Tod und Wasser.\p"
	.string "Das klingt nach Spaß!\n"
	.string "Mir juckt schon das Holzbein!\p"
	.string "Steig ein, wir saufen ab!$"

EventTicket_Text_SouthernIslandSailBack:
	.string "Hier ist tote Hose.\n"
	.string "Nur Sand und Depressionen.\p"
	.string "Ich krieg Durst.\n"
	.string "Hauen wir ab nach SEEGRASULB CITY?$"

EventTicket_Text_SailHome:
	.string "Endlich!\n"
	.string "Nichts wie weg von diesem Friedhof!$"

EventTicket_Text_AsYouLike:
	.string "Dann bleib halt hier und verrotte.\n"
	.string "Mir egal.$"

SouthernIsland_Interior_Text_Sign:
	.string "“Träume sind nur Lügen, die dein Gehirn\n"
	.string "erzählt, damit du nicht durchdrehst.”$"

SouthernIsland_Exterior_Text_Sign:
	.string "“Wer vergisst, ist verdammt.\n"
	.string "Wer sich erinnert, leidet ewig.”$"
