EventTicket_Text_OldSeaMapTooFar::
	.string "Na, Kleiner?\n"
	.string "Du willst mir erzählen, du hast\n"
	.string "so ’ne alte, vergammelte Karte?\p"
	.string "Na, mal sehen…\n"
	.string "… … … … … …\p"
	.string "Puh! Das Ding führt verdammt weit weg.\n"
	.string "Da kann selbst ich nichts machen…$"

EventTicket_Text_BrineyHoldOnASecond::
	.string "HEY, WARTE MAL!\p"
	.string "Wie kannst du jemanden einfach\n"
	.string "abwimmeln, dem du noch was schuldest?!$"

EventTicket_Text_BrineyLetsSail::
	.string "{PLAYER}{KUN}, tut mir leid!\p"
	.string "So ein Verhalten geht gar nicht.\n"
	.string "Du hast meine Hilfe verdient!\p"
	.string "Also gut, wir stechen in See!\p"
	.string "Los, wir suchen diese verfluchte Insel\n"
	.string "auf dieser alten Karte!$"

EventTicket_Text_OddTicketGetOnBoard::
	.string "Du bist also der mit dem seltsamen\n"
	.string "Ticket, hm?\p"
	.string "Der Ort liegt verdammt weit draußen.\n"
	.string "Keiner weiß, was dort lauert.\p"
	.string "Allein der Gedanke jagt mir\n"
	.string "einen Schauer über den Rücken!\p"
	.string "Steig ein, Kleiner!$"

FarawayIsland_Entrance_Text_SailorReturn::
	.string "CAPT. BRINEY ist manchmal echt\n"
	.string "unberechenbar…\p"
	.string "Willst du zurück nach LILYCOVE?$"

BirthIsland_Harbor_Text_SailorReturn::
	.string "Seltsame Insel, was?\n"
	.string "Willst du zurück nach LILYCOVE?$"

EventTicket_Text_OddTicketsWhereTo::
	.string "Du hast diese komischen Tickets?\p"
	.string "Hmm…\p"
	.string "Die führen an Orte, wo sonst keiner\n"
	.string "auch nur hinzukommen wagt.\p"
	.string "Niemand weiß, was dort lauert.\p"
	.string "Allein der Gedanke lässt mir das Blut\n"
	.string "in den Adern kochen!\p"
	.string "Also los, wohin soll's gehen?$"

NavelRock_Harbor_Text_SailorReturn::
	.string "Hast du das gehört?\n"
	.string "Dieses Grollen… tief aus dem Inneren.\p"
	.string "Bist du dir sicher, dass wir hierbleiben\n"
	.string "sollten?$"

FarawayIsland_Entrance_Text_Sign::
	.string "Die Schrift ist fast verwittert…\p"
	.string "„…Tag unbekannt…\n"
	.string "Wer diesen Ort betritt…\l"
	.string "…sollte bereit sein, alles zu verlieren…“$"

FarawayIsland_Interior_Text_Mew::
	.string "Mew…$"
