Trade_Text_LookingForMonWannaTradeForMon::
	.string "Ey! Ich such schon ewig nach ’nem\n"
	.string "{STR_VAR_1}!\p"
	.string "Haste Bock, den gegen mein\n"
	.string "{STR_VAR_2} zu tauschen?$"

Trade_Text_AwwOhWell::
	.string "Ach man…\n"
	.string "Dann halt nicht…$"

Trade_Text_WhatThatsNoMon::
	.string "Hä?!\n"
	.string "Das ist doch kein {STR_VAR_1}!$"

Trade_Text_HeyThanks::
	.string "Haha, nice! Danke dir!$"

Trade_Text_IsntMyOldMonGreat::
	.string "Na, ist mein altes {STR_VAR_2}\n"
	.string "nicht einfach mega cool?$"

Trade_Text_DoYouHaveMonWouldYouTradeForMon::
	.string "Ey, sag mal!\n"
	.string "Hast du zufällig ein {STR_VAR_1}?\p"
	.string "Ich würd’s sofort gegen mein\n"
	.string "{STR_VAR_2} tauschen!$"

Trade_Text_WellIfYouDontWantTo::
	.string "Pff… wenn du nicht willst,\n"
	.string "dann eben nicht.$"

Trade_Text_ThisIsntMon::
	.string "Äh… das ist doch kein\n"
	.string "{STR_VAR_1}?\p"
	.string "Meld dich, wenn du eins hast.$"

Trade_Text_Thanks::
	.string "Nice! Danke dir!$"

Trade_Text_HasTradedMonGrownStronger::
	.string "Na, ist mein altes {STR_VAR_2}\n"
	.string "mittlerweile stärker geworden?$"

Trade_Text_DoYouHaveMonWantToTradeForMon::
	.string "Hey du!\n"
	.string "Hast du zufällig ein {STR_VAR_1}?\p"
	.string "Ich würd’s sofort gegen mein\n"
	.string "{STR_VAR_2} tauschen!$"

Trade_Text_ThatsTooBad::
	.string "Mist… echt schade.$"

Trade_Text_ThisIsNoMon::
	.string "Äh… nee.\n"
	.string "Das ist kein {STR_VAR_1}.\p"
	.string "Meld dich, wenn du eins hast.$"

Trade_Text_ThanksYoureAPal::
	.string "Danke dir! Du bist echt korrekt!$"

Trade_Text_HowIsMyOldMon::
	.string "Na, wie geht’s meinem alten\n"
	.string "{STR_VAR_2}? Hoffentlich gut!$"
