LilycoveCity_DepartmentStore_1F_Text_LotteryCornerDrawTicket:
	.string "Das ist die POKéMON-LOTTERIE.\n"
	.string "Hier beginnt die Spielsucht.\p"
	.string "Jeder Idiot darf hier ein LOS ziehen.\p"
	.string "Wenn die Nummer auf dem LOS zu einem\n"
	.string "deiner Viecher passt, kriegst du was.\p"
	.string "Wahrscheinlich verlierst du eh.\n"
	.string "Willst du dich blamieren?$"

LilycoveCity_DepartmentStore_1F_Text_ComeBackTomorrow:
	.string "Komm morgen wieder, du Suchti.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain:
	.string "Geh mir aus den Augen.$"

LilycoveCity_DepartmentStore_1F_Text_PleasePickTicket:
	.string "Zieh ein LOS.\n"
	.string "Mach schon…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"

LilycoveCity_DepartmentStore_1F_Text_TicketNumberIsXPleaseWait:
	.string "Die Nummer ist {STR_VAR_1}.\p"
	.string "Ich guck mal nach, ob du überhaupt\n"
	.string "Freunde hast, deren ID dazu passt.\l"
	.string "Warte gefälligst.$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPartyMon:
	.string "Nicht zu fassen!\p"
	.string "Die ID von deinem {STR_VAR_1} passt.\n"
	.string "Hast du das geklaut?$"

LilycoveCity_DepartmentStore_1F_Text_TicketMatchesPCMon:
	.string "Nicht zu fassen!\p"
	.string "Die ID von deinem {STR_VAR_1} im PC passt.\n"
	.string "Immerhin zu was nütze.$"

LilycoveCity_DepartmentStore_1F_Text_NoNumbersMatched:
	.string "Tja, Pech gehabt.\n"
	.string "Nichts passt. Du bist ein Versager.$"

LilycoveCity_DepartmentStore_1F_Text_TwoDigitsMatched:
	.string "Zwei Ziffern passen. Wow.\n"
	.string "Hier ist dein Trostpreis für Arme:\l"
	.string "{STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_ThreeDigitsMatched:
	.string "Drei Ziffern passen. Nicht ganz\n"
	.string "scheiße. Du kriegst den zweiten Preis!\l"
	.string "Nimm das {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_FourDigitsMatched:
	.string "Vier Ziffern passen. Das ist ja fast\n"
	.string "verdächtig. Du kriegst den ersten Preis!\l"
	.string "Hier: {STR_VAR_1}!$"

LilycoveCity_DepartmentStore_1F_Text_AllFiveDigitsMatched:
	.string "Ach du Scheiße! Alle fünf Ziffern?!\p"
	.string "Du verdammter Cheater!\n"
	.string "Das ist der Jackpot!\l"
	.string "Nimm das {STR_VAR_1} und hau ab!$"

LilycoveCity_DepartmentStore_1F_Text_NoRoomForThis:
	.string "Hä?\n"
	.string "Dein Beutel ist voll mit Müll.\p"
	.string "Räum auf, du Messi, und sag mir dann\n"
	.string "Bescheid.$"

LilycoveCity_DepartmentStore_1F_Text_PrizeWeveBeenHolding:
	.string "{PLAYER}?\n"
	.string "Ah, du schon wieder.\p"
	.string "Ich hab deinen Kram hier aufgehoben.\n"
	.string "Nimm es endlich.$"

LilycoveCity_DepartmentStore_1F_Text_PleaseVisitAgain2:
	.string "Verpiss dich.$"
