MatchCall_WildBattleText1::
	.string "Hey,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Hab vorhin versucht, dieses {STR_VAR_2}\n"
	.string "zu fangen, aber Pustekuchen!\p"
	.string "War echt verdammt knapp!\n"
	.string "Naja, bis dann!$"

MatchCall_WildBattleText2::
	.string "Hey,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich hab vorhin versucht, ein\n"
	.string "{STR_VAR_2} zu fangen.\p"
	.string "Tja… ist mir natürlich abgehauen.\n"
	.string "Mega frustrierend!\p"
	.string "Na gut, bis dann!$"

MatchCall_WildBattleText3::
	.string "Yo,{PLAYER}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich war soooo kurz davor, dieses\n"
	.string "{STR_VAR_2} zu erwischen!\p"
	.string "Aber nein… weg war es.\p"
	.string "Richtig mies gelaufen.\n"
	.string "Man sieht sich!$"

MatchCall_WildBattleText4::
	.string "Hey,{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Kennst du dieses {STR_VAR_2}?\n"
	.string "Ich war so kurz davor, es zu fangen!\p"
	.string "Und zack… weg war es.\p"
	.string "Beim nächsten Mal krieg ich es!\n"
	.string "Ganz sicher!$"

MatchCall_WildBattleText5::
	.string "Yo,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Hast du in letzter Zeit was gefangen?\p"
	.string "Ich war haarscharf dran, aber das\n"
	.string "Mistvieh ist abgehauen!\p"
	.string "Naja, man sieht sich!$"

MatchCall_WildBattleText6::
	.string "Hey,{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\l"
	.string "Hast du in letzter Zeit Glück gehabt?\p"
	.string "Ich hatte fast eins… wirklich fast!\n"
	.string "Aber dann - zack - weg war’s.\p"
	.string "Manchmal ist das Leben mies.$"

MatchCall_WildBattleText7::
	.string "Äh… {PLAYER}{KUN}?\n"
	.string "Ich bin’s, {STR_VAR_1}.\p"
	.string "Ich hatte es schon fast!\n"
	.string "Dieses {STR_VAR_2} war zum Greifen nah!\p"
	.string "Und dann… zack! Weg!\n"
	.string "Das war echt frustrierend!$"

MatchCall_WildBattleText8::
	.string "Oh,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Hattest du in letzter Zeit Glück\n"
	.string "beim Fangen von Pokémon?\p"
	.string "Ich war so nah dran…\n"
	.string "aber es ist mir entwischt.\p"
	.string "Ich geb nicht auf!$"

MatchCall_WildBattleText9::
	.string "Hey,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Sag mal, hast du gerade Erfolg?\n"
	.string "Bei mir läuft’s echt mies.\p"
	.string "Die Viecher hauen alle ab!\n"
	.string "Zum Verrücktwerden!$"

MatchCall_WildBattleText10::
	.string "Oh,{PLAYER}{KUN}…\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich war soooo nah dran,\n"
	.string "dieses {STR_VAR_2} zu fangen…\p"
	.string "Und dann? Zack - weg!\p"
	.string "Das nervt total.\n"
	.string "Bis dann…$"

MatchCall_WildBattleText11::
	.string "Hey,{PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Wie läuft’s bei dir?\p"
	.string "Ich hatte eben ein wildes {STR_VAR_2}\n"
	.string "vor mir - und hab’s vermasselt.\p"
	.string "Echt frustrierend…$"

MatchCall_WildBattleText12::
	.string "Hallo,{PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Fängst du noch fleißig Pokémon?\p"
	.string "Ich versuche es auch, aber das ist\n"
	.string "gar nicht so leicht, wie es aussieht.\p"
	.string "Respekt, echt!$"

MatchCall_WildBattleText13::
	.string "Hey,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Hast du wieder was gefangen?\p"
	.string "Ich hab’s versucht, ehrlich…\n"
	.string "Aber das Vieh war schneller als ich.\p"
	.string "Tja, Pech gehabt!$"

MatchCall_WildBattleText14::
	.string "Oh,{PLAYER}{KUN}, hey!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich war kurz davor, ein\n"
	.string "{STR_VAR_2} zu schnappen.\p"
	.string "Aber es ist mir entwischt!\n"
	.string "So ein Mist!$"

MatchCall_WildBattleText15::
	.string "Hey,{PLAYER}!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Ich hab mir vorgenommen, endlich\n"
	.string "mehr Pokémon zu fangen.\p"
	.string "Aber irgendwie läuft’s nicht…\p"
	.string "Naja, wird schon noch!$"

MatchCall_NegativeBattleText1::
	.string "Moin {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich hab mich geprügelt und\n"
	.string "voll aufs Maul gekriegt.\p"
	.string "Echt peinlich.\n"
	.string "Man sieht sich!$"

MatchCall_NegativeBattleText2::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} am Apparat.\p"
	.string "Ich hab jemanden herausgefordert.\n"
	.string "War eine dumme Idee.\p"
	.string "Knapp daneben ist auch verloren.\n"
	.string "Mein Leben ist ein Witz.$"

MatchCall_NegativeBattleText3::
	.string "Hey {PLAYER}!\n"
	.string "Ich bin's, {STR_VAR_1}.\p"
	.string "Ich wurde gerade komplett rasiert.\n"
	.string "Zerstört. Vernichtet.\p"
	.string "Ich glaub, ich verkauf mein Team\n"
	.string "an ein Versuchslabor.$"

MatchCall_NegativeBattleText4::
	.string "Hey {PLAYER}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Gestern wieder verloren.\n"
	.string "Ich bin wohl einfach unfähig.\p"
	.string "Vielleicht sollte ich Briefmarken\n"
	.string "sammeln. Ciao.$"

MatchCall_NegativeBattleText5::
	.string "Na, {PLAYER}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Wie läuft's?\p"
	.string "Ich verliere am laufenden Band.\n"
	.string "Ich bin ein Magnet für Niederlagen.\p"
	.string "Ich krieg einfach nichts gebacken.\n"
	.string "Mach's gut!$"

MatchCall_NegativeBattleText6::
	.string "Hey {PLAYER}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Alles fit im Schritt?\p"
	.string "Ich kämpfe hart, aber ich verkacke\n"
	.string "trotzdem ständig.\p"
	.string "Es ist zum Heulen.\n"
	.string "Hau rein.$"

MatchCall_NegativeBattleText7::
	.string "{STR_VAR_1} hier.\n"
	.string "Was geht?\p"
	.string "Die Niederlage gestern liegt mir\n"
	.string "schwer im Magen.\p"
	.string "Ich brauch 'nen Plan…\n"
	.string "Oder Alkohol. Bis dann.$"

MatchCall_NegativeBattleText8::
	.string "Oh, {PLAYER}{KUN}, na du?\n"
	.string "Hier spricht {STR_VAR_1}.\p"
	.string "Leben deine Pokémon noch?\n"
	.string "Ich hab neulich wieder verloren.\p"
	.string "Ich bin so ein Lappen!\n"
	.string "Bis später!$"

MatchCall_NegativeBattleText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Hör zu, hör zu, das glaubst du nicht!\p"
	.string "Ich hab gekämpft und in der letzten\n"
	.string "Sekunde verloren!\p"
	.string "Ich könnte vor Wut platzen!\n"
	.string "Alles Schiebung!$"

MatchCall_NegativeBattleText10::
	.string "Oh, {PLAYER}{KUN}, hallo…\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich hab mich grad blamiert.\n"
	.string "Schon wieder verloren.\p"
	.string "Meine Pokémon sind nutzlos.\n"
	.string "Man sieht sich.$"

MatchCall_NegativeBattleText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Alles klar bei dir?\p"
	.string "Rate mal? Ich hab schon wieder\n"
	.string "verloren. Überraschung.\p"
	.string "Tja, bis dann!$"

MatchCall_NegativeBattleText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Kämpfst du immer noch?\p"
	.string "Ich hab verloren, also gibt es jetzt\n"
	.string "Straftraining bis zum Erbrechen.\p"
	.string "Bis bald.$"

MatchCall_NegativeBattleText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Hoffe, du bist nicht tot.\p"
	.string "Ich hab mich grad prügeln lassen.\n"
	.string "War nicht schön.\p"
	.string "{PLAYER}{KUN}, mach was aus deinem Leben.\n"
	.string "Nicht so wie ich. Tschö!$"

MatchCall_NegativeBattleText14::
	.string "Oh, hi {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Bist du gut drauf?\p"
	.string "Geh lieber heim zu Mami, bevor\n"
	.string "du auch so endest.\p"
	.string "Bye-bye!$"

MatchCall_PositiveBattleText1::
	.string "Ey {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Hab gerade wieder wen plattgemacht.\n"
	.string "Mein {STR_VAR_2} hat komplett abgeliefert!\p"
	.string "Das war einfach nur geil!$"

MatchCall_PositiveBattleText2::
	.string "Hey,{PLAYER}{KUN}!\n"
	.string "Hier spricht {STR_VAR_1}.\p"
	.string "Hab eben jemanden zerlegt.\n"
	.string "War fast schon unfair, ehrlich!$"

MatchCall_PositiveBattleText3::
	.string "Yo,{PLAYER}!\n"
	.string "Ich bin’s, {STR_VAR_1}.\l"
	.string "Wie läuft’s bei dir?\p"
	.string "Ich hab eben einen Kampf gewonnen,\n"
	.string "mein {STR_VAR_2} hat komplett abgeräumt!\p"
	.string "Beim nächsten Mal bist du dran!$"

MatchCall_PositiveBattleText4::
	.string "Hey,{PLAYER}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Ich hatte eben einen Kampf.\n"
	.string "War knapp, aber ich hab gewonnen.\p"
	.string "Mein {STR_VAR_2} war einfach on fire!$"

MatchCall_PositiveBattleText5::
	.string "Hey,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Wie läuft’s bei dir so?\n"
	.string "Ich hab gerade wieder jemanden plattgemacht!\p"
	.string "Mein {STR_VAR_2} war einfach brutal gut.\p"
	.string "Beim nächsten Mal bist du dran!$"

MatchCall_PositiveBattleText6::
	.string "Hey,{PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Läuft bei dir alles?\p"
	.string "Ich bin gerade richtig im Flow.\n"
	.string "Schon wieder einen Kampf gewonnen!\p"
	.string "Nächstes Mal gehörst du mir!$"

MatchCall_PositiveBattleText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Mein {STR_VAR_2} ist einfach krank stark!\p"
	.string "Hab eben wieder gewonnen.\n"
	.string "Ich freu mich schon auf unser Duell!$"

MatchCall_PositiveBattleText8::
	.string "Hey,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Alles klar bei dir?\n"
	.string "Ich hab grad wieder zugeschlagen!\p"
	.string "Mein {STR_VAR_2} hat richtig abgeliefert.\p"
	.string "Bis bald!$"

MatchCall_PositiveBattleText9::
	.string "Oh,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Wie läuft’s bei dir?\n"
	.string "Ich hab grad wieder jemanden weggeputzt!\p"
	.string "Mein {STR_VAR_2} war einfach unschlagbar!\p"
	.string "Wir sehen uns!$"

MatchCall_PositiveBattleText10::
	.string "Hey,{PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Wie geht’s dir?\p"
	.string "Meine Pokémon sind gerade richtig on fire.\p"
	.string "Hab eben wieder einen Kampf gewonnen!\p"
	.string "Bis bald!$"

MatchCall_PositiveBattleText11::
	.string "Ah,{PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Schon wieder gewonnen!\n"
	.string "Läuft einfach gerade bei mir.\p"
	.string "Mal sehen, ob du mich schlagen kannst!$"

MatchCall_PositiveBattleText12::
	.string "Hey,{PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich bin top drauf!\n"
	.string "Hab gerade wieder einen Sieg eingefahren.\p"
	.string "Ich bin noch lange nicht am Ende!$"

MatchCall_PositiveBattleText13::
	.string "Ah,{PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Alles läuft perfekt!\n"
	.string "Ich hab schon wieder gewonnen.\p"
	.string "Du wirst mich noch erleben!$"

MatchCall_PositiveBattleText14::
	.string "Hey,{PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Mein {STR_VAR_2} war heute einfach unfassbar stark.\p"
	.string "Das hättest du sehen müssen!\n"
	.string "Bis bald!$"

MatchCall_SameRouteBattleRequestText1::
	.string "Hey! {PLAYER}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Mein Radar sagt, du bist bei\n"
	.string "{STR_VAR_2}?\p"
	.string "Bleib stehen! Ich komm vorbei und\n"
	.string "polier dir die Fresse!$"

MatchCall_SameRouteBattleRequestText2::
	.string "Hallo {PLAYER}!\n"
	.string "Es ist {STR_VAR_1}.\p"
	.string "Bist du gerade bei\n"
	.string "{STR_VAR_2}?\p"
	.string "Gut. Ich brauche einen Sandsack.\n"
	.string "Warte auf mich!$"

MatchCall_SameRouteBattleRequestText3::
	.string "Na, {PLAYER}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Oh, du treibst dich bei\n"
	.string "{STR_VAR_2} rum?\p"
	.string "Diesmal mach ich dich fertig!\n"
	.string "Lauf bloß nicht weg!$"

MatchCall_SameRouteBattleRequestText4::
	.string "Hey {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} am Apparat.\p"
	.string "Wo steckst du? \n"
	.string "{STR_VAR_2}?\p"
	.string "Perfekt. Zeit für Schmerzen.\n"
	.string "Ich komme!$"

MatchCall_SameRouteBattleRequestText5::
	.string "Hiya {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Alles fit?\p"
	.string "Du bist bei {STR_VAR_2}?\p"
	.string "Lass uns kämpfen, bevor ich es mir\n"
	.string "anders überlege.\p"
	.string "Ich such dich!$"

MatchCall_SameRouteBattleRequestText6::
	.string "Hey {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\l"
	.string "Leben deine Pokémon noch?\p"
	.string "Aha, du bist bei {STR_VAR_2}?\p"
	.string "Dann machen wir jetzt Nägel mit Köpfen.\n"
	.string "Kampfzeit!\p"
	.string "Bis gleich!$"

MatchCall_SameRouteBattleRequestText7::
	.string "…Äh, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier…\p"
	.string "Bist du wirklich bei\n"
	.string "{STR_VAR_2}?\p"
	.string "Dann lass uns kämpfen.\n"
	.string "Sofort. Keine Ausreden.\p"
	.string "Ich warte.$"

MatchCall_SameRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, was geht?\n"
	.string "Hier spricht {STR_VAR_1}.\p"
	.string "Ich hoffe, du hast Angst.\n"
	.string "Du bist bei {STR_VAR_2}.\p"
	.string "Komm her und kämpf wie ein Mann!\n"
	.string "Oder eine Frau! Egal!\p"
	.string "Ich warte!$"

MatchCall_SameRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Bist du bereit zu leiden?\n"
	.string "Du bist bei {STR_VAR_2}?\p"
	.string "Dann komm her. Ich hab Wut im Bauch\n"
	.string "und Zeit zu viel!\p"
	.string "Beeil dich!$"

MatchCall_SameRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hallo…\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Alles gut?\n"
	.string "Ah, du bist bei {STR_VAR_2}.\p"
	.string "Wir sollten kämpfen.\n"
	.string "Jetzt.\p"
	.string "Ich bin bereit.\n"
	.string "Zack zack!$"

MatchCall_SameRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Das ist {STR_VAR_1}.\p"
	.string "Du bist also bei\n"
	.string "{STR_VAR_2}?\p"
	.string "Dann gibt es keine Entschuldigung.\n"
	.string "Kampf! Jetzt!\p"
	.string "Ich lauere dir auf!$"

MatchCall_SameRouteBattleRequestText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Wo treibst du dich rum?\p"
	.string "{STR_VAR_2}?\n"
	.string "Das ist ja um die Ecke!\p"
	.string "Komm her, ich will dich verhauen.\p"
	.string "Ich warte.$"

MatchCall_SameRouteBattleRequestText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Hoffe, du bist gesund.\n"
	.string "Du bist bei {STR_VAR_2}?\p"
	.string "Komm vorbei, damit ich das ändern kann.\p"
	.string "Bis gleich.$"

MatchCall_SameRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Du bist wo? … {STR_VAR_2}?\n"
	.string "Das ist sehr nah.\p"
	.string "Zu nah für meinen Geschmack.\n"
	.string "Lass uns kämpfen, damit du abhaust.\p"
	.string "Ich such dich!\n"
	.string "Tschö!$"

MatchCall_DifferentRouteBattleRequestText1::
	.string "Hi! {PLAYER}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Willst du 'ne Tracht Prügel?\p"
	.string "Ich warte bei {STR_VAR_2}!\n"
	.string "Komm her, wenn du dich traust!$"

MatchCall_DifferentRouteBattleRequestText2::
	.string "Hallo {PLAYER}!\n"
	.string "Es ist {STR_VAR_1}.\p"
	.string "Willst du wieder verlieren?\p"
	.string "Du findest mich bei\n"
	.string "{STR_VAR_2}. Ich warte!$"

MatchCall_DifferentRouteBattleRequestText3::
	.string "Hey {PLAYER}!\n"
	.string "Ich bin's, {STR_VAR_1}.\p"
	.string "Meine Pokémon haben Steroide genommen.\n"
	.string "Sie sind riesig.\p"
	.string "Ich will sehen, wie sie dich zerlegen,\n"
	.string "{PLAYER}.\p"
	.string "Also komm ran!\p"
	.string "Ich warte bei {STR_VAR_2}.$"

MatchCall_DifferentRouteBattleRequestText4::
	.string "Hey {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\l"
	.string "Was geht?\p"
	.string "Meine Pokémon sind aggressiv drauf.\n"
	.string "Sie brauchen ein Opfer.\p"
	.string "Hast du Lust?\p"
	.string "Wir treffen uns bei\n"
	.string "{STR_VAR_2}, okay?$"

MatchCall_DifferentRouteBattleRequestText5::
	.string "Hiya {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Meine Pokémon mutieren langsam.\n"
	.string "Es sieht eklig, aber stark aus.\p"
	.string "Ich will das an dir testen.\p"
	.string "Ich warte bei {STR_VAR_2}.\n"
	.string "Bis dann!$"

MatchCall_DifferentRouteBattleRequestText6::
	.string "Hey {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\l"
	.string "Hoffe, du hast keine Angst.\p"
	.string "Ich dachte, ich vermöbel dich mal wieder.\n"
	.string "Was sagst du?\p"
	.string "Wenn du Mumm hast, komm zu\n"
	.string "{STR_VAR_2}.\p"
	.string "Bis dann!$"

MatchCall_DifferentRouteBattleRequestText7::
	.string "…Äh, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier…\l"
	.string "Na? Leben deine Viecher noch?\p"
	.string "Meine sind Killer geworden.\n"
	.string "Ich will es dir zeigen.\p"
	.string "Ich bin bei {STR_VAR_2}.\n"
	.string "Komm vorbei und stirb.\p"
	.string "Man sieht sich.$"

MatchCall_DifferentRouteBattleRequestText8::
	.string "Oh, {PLAYER}{KUN}, na?\n"
	.string "Hier spricht {STR_VAR_1}.\p"
	.string "Mir geht's super.\n"
	.string "Meine Pokémon sind tollwütig.\p"
	.string "Wenn du in der Nähe bist, lass dich\n"
	.string "beißen.\p"
	.string "Ich bin bei {STR_VAR_2}.\n"
	.string "Tschüssikowski!$"

MatchCall_DifferentRouteBattleRequestText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Wie geht's deinen Krüppeln?\p"
	.string "Meine Pokémon werden immer besser.\n"
	.string "Das muss ich dir unter die Nase reiben,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Ich bin jetzt bei {STR_VAR_2}.\n"
	.string "Komm her, wenn du dich traust.\p"
	.string "Hoffentlich bis bald!$"

MatchCall_DifferentRouteBattleRequestText10::
	.string "Oh, {PLAYER}{KUN}, hallo…\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Also, wie läuft's?\p"
	.string "Meine Pokémon sind jetzt viel stärker.\n"
	.string "Dank illegaler Substanzen.\p"
	.string "Ich würde gerne gegen dich kämpfen,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Ich bin bei {STR_VAR_2}.\n"
	.string "Komm vorbei.$"

MatchCall_DifferentRouteBattleRequestText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Wo steckst du?\p"
	.string "Meine Pokémon sind voller Energie.\n"
	.string "Sie wollen deine Pokémon fressen,\l"
	.string "{PLAYER}{KUN}.\p"
	.string "Ich bin bei {STR_VAR_2}.\n"
	.string "Komm her und lass dich fressen.$"

MatchCall_DifferentRouteBattleRequestText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Ich sags dir, meine Pokémon sind\n"
	.string "Maschinen geworden.\p"
	.string "Ich will sehen, wie sie dich\n"
	.string "zerlegen, {PLAYER}{KUN}.\p"
	.string "Wir sind bei {STR_VAR_2}.\n"
	.string "Komm jederzeit!$"

MatchCall_DifferentRouteBattleRequestText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Alles gut?\p"
	.string "Meine Pokémon sind so gesund,\n"
	.string "es ist fast schon widerlich!\p"
	.string "Ich will wieder gegen dich kämpfen.\p"
	.string "Wenn du bei {STR_VAR_2} bist,\n"
	.string "komm vorbei.$"

MatchCall_DifferentRouteBattleRequestText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Lebst du noch?\p"
	.string "Oh, ja! Meine Pokémon sind\n"
	.string "viel stärker als vorher.\p"
	.string "Wir sollten kämpfen,\n"
	.string "{PLAYER}{KUN}, oder hast du Angst?\p"
	.string "Wir warten bei {STR_VAR_2}.\p"
	.string "Komm vorbei, okay?$"

MatchCall_PersonalizedText1::
	.string "Ich bin's, der Berg-Freak\n"
	.string "{STR_VAR_1}!\p"
	.string "Hast du gelernt, Steine zu lieben?\n"
	.string "So wie ich?\p"
	.string "Du bist selten in den Bergen…\n"
	.string "Du Weichei.\p"
	.string "Nächstes Mal treffen wir uns bei\n"
	.string "{STR_VAR_2}. Bring Steine mit.$"

MatchCall_PersonalizedText2::
	.string "Hier ist {STR_VAR_1}.\n"
	.string "Hallo.\p"
	.string "Ich hab einer neuen TRAINERIN von\n"
	.string "dir erzählt.\p"
	.string "Ich sagte ihr: Da gibt es jemanden,\n"
	.string "der absolut rücksichtslos ist.\p"
	.string "Ich hoffe, du wirst ein TRAINER,\n"
	.string "den alle fürchten.\p"
	.string "Bis dann!$"

MatchCall_PersonalizedText3::
	.string "Hallo! Hier ist {STR_VAR_1}.\p"
	.string "Es stinkt hier so gut!\n"
	.string "Nach Blumen und Dünger!\p"
	.string "Jemand hat BEEREN gepflanzt,\n"
	.string "und jetzt ist alles zugewuchert.\p"
	.string "Riech mal dran!$"

MatchCall_PersonalizedText4::
	.string "Hallo! 30 Jahre im Dreck,\n"
	.string "{STR_VAR_1} zu Diensten!\p"
	.string "Du scheinst ja viel rumzukommen.\n"
	.string "Hektisch, hektisch.\p"
	.string "Hast du Ruinen gefunden?\n"
	.string "Alte Steine? Kaputte Häuser?\p"
	.string "Sag es mir!\n"
	.string "Ich muss jetzt graben.$"

MatchCall_PersonalizedText5::
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Weißt du, was ich mache?\n"
	.string "Ich glotze aufs Meer!\p"
	.string "Seufz… Es glitzert so dumm.\n"
	.string "Mir wird schlecht davon.\l"
	.string "Ich geh was essen. Tschö!$"

MatchCall_PersonalizedText6::
	.string "Mampf-schmatz…\n"
	.string "Oh, hi, hier ist {STR_VAR_1}.\l"
	.string "Sand im Essen ist mein Hobby.\p"
	.string "Meine Pokémon sind fett gefressen.\n"
	.string "Wir sind vollgetankt!\l"
	.string "Ich geh jetzt untergehen. Bye!$"

MatchCall_PersonalizedText7::
	.string "Hallo, hier ist {STR_VAR_1}…\p"
	.string "Ich hasse mein Leben als\n"
	.string "TOP-TRAINER…\p"
	.string "Alle denken, ich bin perfekt.\n"
	.string "Der Druck macht mich fertig.\p"
	.string "Aber ich muss wohl lächeln und\n"
	.string "winken.\p"
	.string "Du bist der Einzige, dem ich mein\n"
	.string "Leid klagen kann.\p"
	.string "Aber wenn wir uns sehen,\n"
	.string "werde ich dich trotzdem vernichten.$"

MatchCall_PersonalizedText8::
	.string "Yahoo, hier ist {STR_VAR_1}!\n"
	.string "Alles fit?\p"
	.string "Ich habe meine Pokémon trainiert,\n"
	.string "nur um dich zu schlagen.\p"
	.string "Du bist meine Obsession.\p"
	.string "Ist es nicht toll, Rivalen zu haben?\n"
	.string "Lass uns kämpfen!$"

MatchCall_PersonalizedText9::
	.string "Es ist {STR_VAR_1}…\n"
	.string "Hinter dir…\l"
	.string "War da was…?\p"
	.string "Die Macht des PYROBERGS…\n"
	.string "Die Toten sprechen zu mir…\p"
	.string "Sie erzählen mir von dir…\p"
	.string "Du solltest weglaufen…\n"
	.string "Ganz schnell…\p"
	.string "Kicher…\n"
	.string "Lebe wohl…$"

MatchCall_PersonalizedText10::
	.string "Hier ist {STR_VAR_1}.\n"
	.string "Guten Tag.\p"
	.string "Ist es nicht praktisch, dass wir\n"
	.string "aus der Ferne reden können?\p"
	.string "Früher musste mich mein Chauffeur\n"
	.string "zu meinen Freunden fahren…\l"
	.string "Das Leben ist hart für Reiche.\p"
	.string "Ich muss jetzt Kaviar essen.\n"
	.string "War nett mit dir.$"

MatchCall_PersonalizedText11::
	.string "Hier ist {STR_VAR_1}!\n"
	.string "Hör dir das an!\p"
	.string "Ich liebe die SAFARI-ZONE,\n"
	.string "aber ich verlaufe mich immer!\p"
	.string "Zu viel Gras!\n"
	.string "Und alles sieht gleich aus!\p"
	.string "Ich hasse Natur!\p"
	.string "Ich geh wieder rein!\n"
	.string "Bis dann!$"

MatchCall_PersonalizedText12::
	.string "Hallo, {STR_VAR_1} hier.\n"
	.string "Ja, richtig, ich bin reich.\p"
	.string "Ich bin noch reicher geworden,\n"
	.string "seit wir uns das letzte Mal sahen.\p"
	.string "Und meine Pokémon sind auch teurer.\p"
	.string "Ich glaube, die Welt dreht sich nur\n"
	.string "um mich!\p"
	.string "Du musst nichts sagen!\n"
	.string "Jeder weiß es!\p"
	.string "Entschuldige, ich muss zu einem\n"
	.string "Dinner. Ohne dich.$"

MatchCall_PersonalizedText13::
	.string "Ufufufufu…\n"
	.string "Ich bin's, {STR_VAR_1}…\p"
	.string "Rate mal, was ich sehe?\n"
	.string "Zwei {STR_VAR_2} beim Kampf.\p"
	.string "Vielleicht fange ich den Gewinner…\n"
	.string "Ufufufufufu…\p"
	.string "Ich… bin beschäftigt.\n"
	.string "Tschüss.$"

MatchCall_PersonalizedText14::
	.string "Oh, es ist {STR_VAR_1}!\p"
	.string "Ich langweile mich zu Tode auf dem\n"
	.string "WRACK.\p"
	.string "Aber da ich schon mal hier bin,\n"
	.string "und dich besiegen will,\l"
	.string "bleib ich noch was.\p"
	.string "Wenn du Lust hast, komm vorbei.\p"
	.string "Heute fordere ich den Typen nebenan\n"
	.string "heraus. Er nervt.\p"
	.string "Wir sehen uns!$"

MatchCall_PersonalizedText15::
	.string "Ich bin {STR_VAR_1}!\n"
	.string "Der Mann des Meeres!\p"
	.string "Weißt du was?\p"
	.string "TRAINER auf dem Meer sind die\n"
	.string "härtesten Hunde!\p"
	.string "Lern von mir und trainiere im\n"
	.string "Wasser…\p"
	.string "Hoppla, Riesenwelle!\n"
	.string "Ich ersaufe! Großartig!\n"
	.string "Muss auflegen! Blubb!$"

MatchCall_PersonalizedText16::
	.string "Es ist {STR_VAR_1}! Hör zu, ich hab\n"
	.string "Karate an meine Pokémon weitergegeben.\p"
	.string "Jetzt verprügeln sie mich!\n"
	.string "Ich verliere ständig gegen sie!\p"
	.string "Aber gegen dich verliere ich nicht!\n"
	.string "Niemals!\p"
	.string "Wir kämpfen wieder!\n"
	.string "Ugwaah! Aua! Nicht ins Gesicht!$"

MatchCall_PersonalizedText17::
	.string "Ich bin's, {STR_VAR_1}.\n"
	.string "Wie läuft die Reise?\p"
	.string "…Echt? Klingt anstrengend!\p"
	.string "Ich könnte ein Lied über dein\n"
	.string "Leid schreiben.\p"
	.string "…Oh, ich spür es.\n"
	.string "Das Riff des Schmerzes.\p"
	.string "Ich muss das aufschreiben!\n"
	.string "Tschö!$"

MatchCall_PersonalizedText18::
	.string "Hier ist {STR_VAR_1}…\n"
	.string "Hör meinen neuen Song.\p"
	.string "Lalala, {STR_VAR_2}, {STR_VAR_2}!\n"
	.string "Warum bist du so {STR_VAR_2}?\l"
	.string "Warum bin ich nicht du, {STR_VAR_2}?\l"
	.string "Lala, {STR_VAR_2} und {STR_VAR_1},\l"
	.string "{STR_VAR_1} und {STR_VAR_2}…\p"
	.string "Fade out… Kauf mein Album.$"

MatchCall_PersonalizedText19::
	.string "Ich bin {STR_VAR_1},\n"
	.string "der Camping-Gott!\p"
	.string "Als wir kämpften, hab ich verloren.\n"
	.string "Ich kann halt nur Zelte aufbauen.\p"
	.string "Aber egal, ich kämpfe gerne beim\n"
	.string "Campen.\p"
	.string "Komm vorbei, bring Marshmallows mit!\n"
	.string "Und Verbandszeug!$"

MatchCall_PersonalizedText20::
	.string "Ich bin's, ich, {STR_VAR_1}!\p"
	.string "Ich würde gerne woanders klettern.\p"
	.string "Aber gibt es woanders so heiße\n"
	.string "Braute wie am SCHLOTBERG?\p"
	.string "Wenn du Berge mit Frauen kennst,\n"
	.string "sag Bescheid!\p"
	.string "Ehehehe, du Ferkel!$"

MatchCall_PersonalizedText21::
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Es ist {STR_VAR_1}…\p"
	.string "… … … … … …\n"
	.string "… … … … … …\l"
	.string "Kein Kommentar…$"

MatchCall_PersonalizedText22::
	.string "Hier ist {STR_VAR_1}. Ich hatte heute\n"
	.string "das Gefühl, ich müsste dich nerven.\p"
	.string "Mein Verlangen, dich zu schlagen,\n"
	.string "wächst jeden Tag.\p"
	.string "Hast du auch so einen Rivalen?\n"
	.string "Ich wünschte, ich wäre es…\p"
	.string "Danke fürs Zuhören.\n"
	.string "Tschö!$"

MatchCall_PersonalizedText23::
	.string "Es ist {STR_VAR_1}.\p"
	.string "Wenn ein starker TRAINER in der\n"
	.string "Nähe ist, riech ich das.\p"
	.string "Warst du das, {PLAYER}{KUN}?\n"
	.string "Du riechst nach Angst.\p"
	.string "Ich warte auf dich.\n"
	.string "Bye!$"

MatchCall_PersonalizedText24::
	.string "Hallo, hier ist {STR_VAR_1}.\n"
	.string "Klingst gut, {PLAYER}{KUN}.\p"
	.string "Ich war überall auf der Welt,\n"
	.string "aber diese Region ist okay.\p"
	.string "Ich bleib noch eine Weile hier.\n"
	.string "Um dich zu nerven.\p"
	.string "Ich hab deine Tricks nicht vergessen.\p"
	.string "Ich will Rache.$"

MatchCall_PersonalizedText25::
	.string "Schnief… Es ist… {STR_VAR_1}…\n"
	.string "…Heul…\p"
	.string "FELIZIA hat mich heute zur Sau\n"
	.string "gemacht.\p"
	.string "Aber ich mag das.\p"
	.string "FELIZIA sagt mir, wie dumm ich bin,\n"
	.string "damit ich lerne.\p"
	.string "Ich geh morgen wieder hin!\n"
	.string "Bis dann!$"

MatchCall_PersonalizedText26::
	.string "Es ist {STR_VAR_1}!\p"
	.string "FELIZIA hat mich gestern kämpfen\n"
	.string "lassen.\p"
	.string "Das Ergebnis…\n"
	.string "Massaker. War ja klar.\p"
	.string "Aber ich war so glücklich, dass sie\n"
	.string "mich überhaupt beachtet hat!\p"
	.string "Ich bete sie an!\p"
	.string "Ich werde mich anstrengen!\n"
	.string "Muss weg!$"

MatchCall_PersonalizedText27::
	.string "Hi, hier ist ANNA! Ich bin wieder mit\n"
	.string "meiner Sklavin… äh, Partnerin IDA.\p"
	.string "Ich liebe es, mich um IDA zu kümmern.\n"
	.string "Sie ist so niedlich dumm!\p"
	.string "Oh, hi, IDA!\n"
	.string "Hast du die Brötchen?\p"
	.string "Hä? Nein, ich behandel dich nicht\n"
	.string "wie Dreck!\p"
	.string "Du hast verloren, also musst du\n"
	.string "einkaufen gehen! Das ist Gesetz!\p"
	.string "Ich würde dich nie ausnutzen,\n"
	.string "IDA! Du bist mein Spielzeug!\p"
	.string "Ich muss jetzt essen.\n"
	.string "Tschüss!$"

MatchCall_PersonalizedText28::
	.string "Ich liebe POKéMON!\n"
	.string "Hier ist {STR_VAR_1} vom FANCLUB!\p"
	.string "Hör dir das an!\n"
	.string "Mein süßes POKéMON…\p"
	.string "Schnauf! Wahaha!\n"
	.string "Es ist zu süß! Ich dreh durch!\l"
	.string "Es hat gerade gepupst!\p"
	.string "Oh, mein süßes {STR_VAR_2} will\n"
	.string "einen {POKEBLOCK}!\p"
	.string "Friss, mein Kleines!\p"
	.string "Sorry, keine Zeit!\n"
	.string "Hör dir das später an!$"

MatchCall_PersonalizedText29::
	.string "Ohoho!\p"
	.string "Hier ist {STR_VAR_1}! Ich muss dir\n"
	.string "von meinem Liebling erzählen!\p"
	.string "Bitte, du musst zuhören.\n"
	.string "Es geht um {STR_VAR_2}.\p"
	.string "Immer wenn ich es anfasse,\n"
	.string "beißt es mich!\p"
	.string "Oh… Oh… Ist das nicht\n"
	.string "pure Liebe?\p"
	.string "Es tut so weh, herrlich!\p"
	.string "Ich bin so froh, dass ich das teilen\n"
	.string "konnte.\p"
	.string "Ich muss zum Arzt.\n"
	.string "Tschüss!$"

MatchCall_PersonalizedText30::
	.string "Ich bin… {STR_VAR_1}.\n"
	.string "Man nennt mich den EXPERTEN.\p"
	.string "Aber ich weiß eins.\n"
	.string "Ohne Pokémon bin ich ein Nichts.\p"
	.string "Nur mit Pokémon kann ich so tun,\n"
	.string "als wäre ich wer.\p"
	.string "Humph! Das klang tiefsinnig!\n"
	.string "Ich hoffe, du bist beeindruckt!$"

MatchCall_PersonalizedText31::
	.string "Es ist {STR_VAR_1}.\n"
	.string "Nett, mit dir zu plaudern!\p"
	.string "Ich koche gerade in der heißen\n"
	.string "Quelle. Wie eine Suppe.\p"
	.string "Ich hab viele junge Hüpfer besiegt,\n"
	.string "aber du nervst am meisten.\p"
	.string "Vielleicht wirst du im Alter auch\n"
	.string "so schrumpelig wie ich! Ohohoho…$"

MatchCall_PersonalizedText32::
	.string "Yay! Hier ist {STR_VAR_1}!\n"
	.string "Was geht?\p"
	.string "Ich bild mir das vielleicht ein, aber\n"
	.string "wenn ich gewinne, fühlen sich meine\l"
	.string "Shorts besser an.\p"
	.string "Wie mein ich das?\n"
	.string "Schwer zu erklären…\l"
	.string "Sie scheuern weniger!\p"
	.string "Und als ich gegen dich verlor,\n"
	.string "waren sie kratzig und eklig.\p"
	.string "… … … … … …\n"
	.string "Glaubst du das?\l"
	.string "Ehehehe, ich bin komisch! Bye!$"

MatchCall_PersonalizedText33::
	.string "Ahoi!\n"
	.string "{STR_VAR_1} hier!\p"
	.string "Wie immer angle ich wie ein Irrer!\p"
	.string "Gibt es noch andere Orte als\n"
	.string "Meer und Fluss?\p"
	.string "Ich will in der Toilette angeln!\n"
	.string "Oder in Pfützen!\p"
	.string "Verdammt!\n"
	.string "Haken im Finger!\p"
	.string "Muss weg!\n"
	.string "Such mir neue Angelplätze!$"

MatchCall_PersonalizedText34::
	.string "Hey! Hier ist {STR_VAR_1}.\n"
	.string "Bist du entspannt?\p"
	.string "Schon als Kind war ich so\n"
	.string "langsam, weißt du?\p"
	.string "Stress ist Gift.\n"
	.string "Aber jetzt bin ich TRIATHLET.\p"
	.string "Ironie des Schicksals, was?\p"
	.string "Du bist jetzt TRAINER, aber wer\n"
	.string "weiß? Morgen vielleicht tot?\p"
	.string "Oder Friseur.\n"
	.string "Bleib cool. Mach langsam.\n"
	.string "Man sieht sich.$"

MatchCall_PersonalizedText35::
	.string "Hier ist {STR_VAR_1}!\n"
	.string "Ich radle gerade.\p"
	.string "Schwimmen und Laufen stinkt,\n"
	.string "Radfahren ist Leben!\p"
	.string "Der Wind in den Haaren…\n"
	.string "Die Insekten in den Zähnen…\p"
	.string "Es ist geil!\p"
	.string "Heute breche ich den Rekord auf dem\n"
	.string "RADWEG! Oder meine Knochen!\p"
	.string "Mach mit!\n"
	.string "Tschüss!$"

MatchCall_PersonalizedText36::
	.string "Yo, hier ist {STR_VAR_1}! Ich bin\n"
	.string "mitten im Triathlon!\p"
	.string "Aber hey, ich hab immer Zeit zum\n"
	.string "Quatschen!\p"
	.string "Sport mit Pokémon ist Mord!\p"
	.string "Mein Herz rast!\n"
	.string "Ich sehe Licht am Ende des Tunnels!\p"
	.string "Inspirierend!\p"
	.string "Keuch… Reden beim Rennen…\n"
	.string "Ich kipp gleich um…\l"
	.string "Keuch… Muss… kotzen…$"

MatchCall_PersonalizedText37::
	.string "Hi, es ist {STR_VAR_1}.\n"
	.string "Höhentraining ist der Hammer!\p"
	.string "Lauf auf einem Berg.\n"
	.string "Du erstickst fast!\p"
	.string "Mir wird schwarz vor Augen!\n"
	.string "Tschüss!$"

MatchCall_PersonalizedText38::
	.string "Oh, es ist {STR_VAR_1}, hallo.\p"
	.string "Ich schwimme seit Tagen, aber ich\n"
	.string "finde PRACHTPOLIS nicht.\p"
	.string "Schwimme ich im Kreis?\p"
	.string "Nein, unmöglich.\n"
	.string "Wahahaha.\l"
	.string "Ich werde hier sterben!$"

MatchCall_PersonalizedText39::
	.string "Hey, es ist {STR_VAR_1}…\n"
	.string "Hoppla!\p"
	.string "Platsch!\p"
	.string "Blubb-blubb-blubb…\p"
	.string "Spritz!\p"
	.string "Hust! Hust!\p"
	.string "Hey! Ups!\n"
	.string "Ich hab mich eingeölt.\p"
	.string "Der POKéNAV ist mir aus der Hand\n"
	.string "geflutscht! Ins Wasser!\p"
	.string "Aber das Ding von DEVON ist\n"
	.string "unkaputtbar. Leider!\p"
	.string "Ich bin zu ölig zum Telefonieren.\n"
	.string "Tschüss.$"

MatchCall_PersonalizedText40::
	.string "Hallo, hier ist {STR_VAR_1}.\p"
	.string "Von den drei Disziplinen mag ich\n"
	.string "Schwimmen am liebsten.\p"
	.string "Aber wenn ich zu lange drin bleibe,\n"
	.string "schrumpelt meine Haut.\p"
	.string "Ich sehe aus wie eine Rosine!\n"
	.string "Triathlon macht hässlich! Bye!$"

MatchCall_PersonalizedText41::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Alles klar?\p"
	.string "Meine DRACHEN sind hungrig.\n"
	.string "Pass auf dich auf. Tschüss.$"

MatchCall_PersonalizedText42::
	.string "{STR_VAR_1} hier.\p"
	.string "Mein {STR_VAR_2} ist noch härter\n"
	.string "geworden.\p"
	.string "Ich verliere nicht nochmal.\n"
	.string "Warte nur!\p"
	.string "Du bist fällig!$"

MatchCall_PersonalizedText43::
	.string "Es ist {STR_VAR_1} hier.\p"
	.string "Ich habe meine Tarnung perfektioniert.\p"
	.string "Ich bin zu gut.\n"
	.string "Niemand findet mich. Niemand ruft an.\l"
	.string "Ich bin so einsam…\p"
	.string "Wie ein Furz im Wind verweh ich!\n"
	.string "Leb wohl!$"

MatchCall_PersonalizedText44::
	.string "Das ist {STR_VAR_1}.\n"
	.string "Ich habe weiter trainiert.\p"
	.string "Mein {STR_VAR_2} ist jetzt\n"
	.string "brutal.\p"
	.string "Training am Strand bringt's voll,\n"
	.string "der Sand in den Augen härtet ab!$"

MatchCall_PersonalizedText45::
	.string "Guten Tag.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Wann hört diese Asche auf?\n"
	.string "Es ist so dreckig!\p"
	.string "Mein Schirm ist ruiniert…\n"
	.string "Alles ist grau und traurig…\p"
	.string "Bis dann!$"

MatchCall_PersonalizedText46::
	.string "Hi, {STR_VAR_1} hier.\p"
	.string "Wusstest du, dass Leichen im Meer\n"
	.string "besser treiben als im Pool?\p"
	.string "Einfach stillliegen.\n"
	.string "Das Wasser trägt dich.\p"
	.string "Aber pass auf die Strömung auf.\n"
	.string "Sonst bist du weg.\p"
	.string "…Wo bin ich eigentlich?\n"
	.string "Hilfe!$"

MatchCall_PersonalizedText47::
	.string "Oh, {PLAYER}{KUN}, hallo!\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Ich bin auf dem Berg.\p"
	.string "Der Boden ist zu hart.\n"
	.string "Mein Zelt hält nicht…\p"
	.string "Ich hab eine Idee!\p"
	.string "Ich lass meine Pokémon den Boden\n"
	.string "plattwalzen! Bis er glatt ist!\p"
	.string "Das wird ihnen eine Lehre sein!\n"
	.string "Bye-bye!$"

MatchCall_PersonalizedText48::
	.string "Oh, hi, hi, hier ist {STR_VAR_1}!\p"
	.string "Ich ziehe Pokémon mit LIV auf!\n"
	.string "Wir geben alles!\p"
	.string "Wenn wir uns mehr anstrengen,\n"
	.string "mögen sie uns vielleicht? Bye!$"

MatchCall_PersonalizedText49::
	.string "{STR_VAR_1} hier!\p"
	.string "Ich bin MATROSE, aber an Land.\n"
	.string "Trocken wie ein Fischstäbchen.\p"
	.string "Wie nennt man einen Matrosen an Land?\n"
	.string "Arbeitslos?\p"
	.string "Das frag ich mich beim Starren aufs\n"
	.string "Meer.\p"
	.string "Na dann, Ahoi!$"

MatchCall_PersonalizedText50::
	.string "Es ist {STR_VAR_1}.\n"
	.string "Na? Neue Pokémon?\p"
	.string "Wenn du was Neues hast,\n"
	.string "zeig es mir.\p"
	.string "Ich bettel nicht, ehrlich.\n"
	.string "Ich befehle es. Bis dann.$"

MatchCall_PersonalizedText51::
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Quälst du deine Pokémon auch richtig?\n"
	.string "Damit sie stark werden?\p"
	.string "Die Luft hier ist rein.\n"
	.string "Perfekt für hartes Training.\p"
	.string "Komm nach {STR_VAR_2}.\n"
	.string "Ich zeig dir wahre Härte.$"

MatchCall_PersonalizedText52::
	.string "Hi, hier ist {STR_VAR_1}.\p"
	.string "Ich gab meinem {STR_VAR_2} einen\n"
	.string "{POKEBLOCK}.\p"
	.string "Es hat ihn wieder ausgespuckt.\n"
	.string "Mitten in mein Gesicht.\p"
	.string "Faszinierend, dieser Hass.\n"
	.string "Pass auf dich auf.$"

MatchCall_PersonalizedText53::
	.string "{STR_VAR_1} hier.\p"
	.string "Wenn man mit Pokémon kooperiert,\n"
	.string "überlebt man vielleicht.\p"
	.string "Jeder sollte das wissen.\n"
	.string "Sonst fressen sie dich.\p"
	.string "Das wäre ideal.\n"
	.string "Find ich.\p"
	.string "Du machst das schon!\n"
	.string "Bis später!$"

MatchCall_PersonalizedText54::
	.string "Hi, es ist {STR_VAR_1}.\n"
	.string "Der Paranoide!\p"
	.string "{PLAYER}{KUN}, hast du genug Zeug?\n"
	.string "Sind deine Pokémon bereit?\p"
	.string "Alles kontrollieren.\n"
	.string "Immer wieder. Sonst stirbst du.\p"
	.string "Ich zähl meine Tränke nach.\n"
	.string "Sei wachsam!$"

MatchCall_PersonalizedText55::
	.string "Es ist {STR_VAR_1}!\n"
	.string "Es ist {STR_VAR_1}!\p"
	.string "{STR_VAR_2} ist die Hölle.\n"
	.string "Jeder will kämpfen.\p"
	.string "Ich hab fünfmal gewonnen und nur\n"
	.string "dreimal verloren! Bilanz!\p"
	.string "Wie war dein Tag?\n"
	.string "Erzähl es deiner Oma!$"

MatchCall_PersonalizedText56::
	.string "Ich bin's, {STR_VAR_1}.\p"
	.string "Ich bin beliebt wegen meiner Käfer,\n"
	.string "oder?\p"
	.string "Ich hab sie mit zur Schule genommen.\n"
	.string "Das Mädchen, das ich mag, hat geweint!\p"
	.string "Lach ruhig.\n"
	.string "Sie hat geschrien: 'Nimm sie weg!'\p"
	.string "Ich muss ihr zeigen, wie toll Käfer\n"
	.string "sind. In ihrem Gesicht.\p"
	.string "Schnief…\n"
	.string "Bis dann!$"

MatchCall_PersonalizedText57::
	.string "Hah! Hah! Hah! Hah!\p"
	.string "Hi! Ich bin's {STR_VAR_1}! Hah! Hah!\p"
	.string "Reden…\n"
	.string "Beim Klettern…\l"
	.string "Ist Folter… Hah! Hah!\p"
	.string "Urgh! Oof…\n"
	.string "Es wird steil…\l"
	.string "Ich leg auf…\l"
	.string "Hah! Hah! Sterbe!$"

MatchCall_PersonalizedText58::
	.string "Oh, hi!\p"
	.string "Ich suche Schätze mit KIRA!\n"
	.string "Aber wir finden nur Müll…\p"
	.string "Vielleicht gibt es hier nichts…\p"
	.string "Aber Hauptsache KIRA ist da.\p"
	.string "Oh, hey, KIRA!\n"
	.string "Warum bist du sauer?\p"
	.string "Ich ignorier dich nicht, Schatz!\n"
	.string "Nimm die Schaufel runter!\p"
	.string "…{PLAYER}, hilfe, bye!$"

MatchCall_PersonalizedText59::
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Ich war wieder bei KAMILLO.\n"
	.string "Er wird immer arroganter.\p"
	.string "Irgendwas von wegen 'Wellenreiten'.\n"
	.string "Er hält sich für so cool.\p"
	.string "Die Frauen lieben ihn!\l"
	.string "Ich könnte kotzen.\p"
	.string "Ob sein Kumpel BRUNO auch so ist?\p"
	.string "Verschwitzt und dumm?\n"
	.string "Bestimmt.\p"
	.string "Aber Neid ist hässlich, oder?\p"
	.string "Vergiss das Gespräch.\n"
	.string "Tschö!$"

MatchCall_PersonalizedText60::
	.string "Nett, mit einem jungen TRAINER\n"
	.string "zu reden.\p"
	.string "Ich denke, du wirst Pokémon auch im\n"
	.string "Alter noch mögen.\p"
	.string "Wäre es nicht toll, so zu sein wie wir?\p"
	.string "Natürlich, {PLAYER}{KUN}, du hast\n"
	.string "jetzt schon eine Bindung.\p"
	.string "Aber hält das ewig?\n"
	.string "Wahrscheinlich nicht!\p"
	.string "Hahaha!\n"
	.string "Gib die Hoffnung auf!$"

MatchCall_PersonalizedText61::
	.string "Hi, hier ist {STR_VAR_1}!\n"
	.string "Wir haben gewonnen!\p"
	.string "Endlich mal! Gegen so einen\n"
	.string "Schwimmer-Typen.\p"
	.string "Meine Schwester war sauer!\p"
	.string "Sie wollte verlieren, damit er sie\n"
	.string "tröstet! Ekelhaft!\p"
	.string "Sie meckert immer, egal was passiert!\p"
	.string "{PLAYER}{KUN}, sag ihr mal die Meinung!\p"
	.string "Okay, bis dann!$"

MatchCall_PersonalizedText62::
	.string "{STR_VAR_1} hier, ja.\n"
	.string "Ich war gestern auf See.\p"
	.string "Ich wollte Ruinen finden.\p"
	.string "Aber die Strömung hat mich im Kreis\n"
	.string "gedreht.\p"
	.string "Ich bin ein Versager…\n"
	.string "Lach mich ruhig aus…\l"
	.string "Aber ich gebe nicht auf.\p"
	.string "Irgendwann finde ich was!\n"
	.string "Bestimmt nur Müll!\p"
	.string "Das war's!\n"
	.string "Leb wohl!$"

MatchCall_PersonalizedText63::
	.string "Ahoi!\n"
	.string "Ich bin's, {STR_VAR_1}!\l"
	.string "Ich bin auf ROUTE 108!\l"
	.string "Wie immer! Mein Leben ist öd!\p"
	.string "Heute schwamm eine heiße Braut\n"
	.string "vorbei!\p"
	.string "Ich hab sie angeschrien!\p"
	.string "Sie hat mich böse angeguckt!\p"
	.string "Das war's von ROUTE 108!\n"
	.string "Präsentiert von {STR_VAR_1}!$"

MatchCall_PersonalizedText64::
	.string "Es ist {STR_VAR_1}!\p"
	.string "Ich bin beschäftigt, aber ich wollte\n"
	.string "angeben: Fünf Siege heute.\p"
	.string "Wenn das so weitergeht, mach ich\n"
	.string "dich nächstes Mal platt.\p"
	.string "Wir werden gute Rivalen,\n"
	.string "bis ich dich vernichte. Bye!$"

MatchCall_BattleFrontierStreakText1::
	.string "Hi! Hier ist {STR_VAR_1}.\n"
	.string "Ich hab's gehört!\p"
	.string "Du warst gut im\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_3} Siege in Folge?\n"
	.string "Wie viel hast du bezahlt?$"

MatchCall_BattleFrontierStreakText2::
	.string "Hallo, es ist {STR_VAR_1}!\n"
	.string "Ich hab von dir gehört!\p"
	.string "Man sagt, du hast {STR_VAR_3} Siege\n"
	.string "im {STR_VAR_2}.\p"
	.string "Toll. Ich bin neidisch.\n"
	.string "Ich hasse dich! Bye!$"

MatchCall_BattleFrontierStreakText3::
	.string "Hey {PLAYER}!\n"
	.string "Ich bin's, {STR_VAR_1}.\p"
	.string "Ich hörte, du hast im\n"
	.string "{STR_VAR_2} gewütet!\p"
	.string "{STR_VAR_3}-Siege-Serie…\n"
	.string "Sicher nur Glück, oder?\p"
	.string "Ich muss wohl auch cheaten!\n"
	.string "Bis bald!$"

MatchCall_BattleFrontierStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier. Was geht?\p"
	.string "Gerüchte sagen, du hast {STR_VAR_3}\n"
	.string "Siege im {STR_VAR_2}.\p"
	.string "Ich muss mich anstrengen.\n"
	.string "Tschüss!$"

MatchCall_BattleFrontierStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Du warst im {STR_VAR_2}\n"
	.string "und hast {STR_VAR_3} mal gewonnen?\l"
	.string "Unglaublich!\p"
	.string "Ich fühl mich jetzt schlecht.\n"
	.string "Bis dann!$"

MatchCall_BattleFrontierStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier. Alles klar?\p"
	.string "Ich hörte von {STR_VAR_3} Siegen im\n"
	.string "{STR_VAR_2}.\p"
	.string "Das motiviert mich, meine Pokémon\n"
	.string "härter zu drillen.$"

MatchCall_BattleFrontierStreakText7::
	.string "…Äh, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier…\p"
	.string "Oh, du warst im\n"
	.string "{STR_VAR_2}, oder?\p"
	.string "Und hast {STR_VAR_3} mal gewonnen.\p"
	.string "Oh, ein seltenes Pokémon!\n"
	.string "Ich leg auf!$"

MatchCall_BattleFrontierStreakText8::
	.string "Oh, {PLAYER}{KUN}, was geht?\n"
	.string "Hier spricht {STR_VAR_1}.\l"
	.string "Alles gut?\p"
	.string "Muss ja. Ich hörte, du hast\n"
	.string "{STR_VAR_3} Siege im {STR_VAR_2}.\p"
	.string "Beeindruckend!\n"
	.string "Hoffentlich verlierst du bald.$"

MatchCall_BattleFrontierStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Ich hab's gehört! {STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}!\p"
	.string "Das ist so cool!\n"
	.string "Ich bin ein Versager!$"

MatchCall_BattleFrontierStreakText10::
	.string "Oh, {PLAYER}{KUN}, hallo…\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Du hast {STR_VAR_3} mal im\n"
	.string "{STR_VAR_2} gewonnen?\p"
	.string "Nicht schlecht.\n"
	.string "Ich muss härter arbeiten.$"

MatchCall_BattleFrontierStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Du bist der Schrecken vom\n"
	.string "{STR_VAR_2}?\p"
	.string "{STR_VAR_3} Siege in Folge?\n"
	.string "Du bist gut.\n"
	.string "Zu gut. Es nervt.$"

MatchCall_BattleFrontierStreakText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Alles fit?\p"
	.string "Jemand hat gelabert.\n"
	.string "{STR_VAR_3} Siege im {STR_VAR_2}?\p"
	.string "Nette Geschichte.\n"
	.string "Tschüss!$"

MatchCall_BattleFrontierStreakText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Hoffe, dir geht's gut.\p"
	.string "Man sagt, du hast {STR_VAR_3} Siege\n"
	.string "im {STR_VAR_2}.\p"
	.string "Ich bewundere deine Zeitverschwendung!\n"
	.string "Bye.$"

MatchCall_BattleFrontierStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Ich hab gehört!\n"
	.string "{STR_VAR_3} Siege im {STR_VAR_2}?\p"
	.string "Du bist eine Inspiration!\n"
	.string "Oder ein Freak! Bye-bye!$"

MatchCall_BattleFrontierRecordStreakText1::
	.string "Hi! Hier ist {STR_VAR_1}.\n"
	.string "Ich hab's gehört!\p"
	.string "Du warst gut im\n"
	.string "{STR_VAR_2}.\p"
	.string "{STR_VAR_3} Siege? Krass.\n"
	.string "Wie machst du das? Drogen?$"

MatchCall_BattleFrontierRecordStreakText2::
	.string "Hallo, es ist {STR_VAR_1}!\n"
	.string "Nachrichten über dich!\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}.\p"
	.string "Super! Ich bin neidisch!\n"
	.string "Tschüss!$"

MatchCall_BattleFrontierRecordStreakText3::
	.string "Hey {PLAYER}!\n"
	.string "Ich bin's, {STR_VAR_1}.\p"
	.string "Du hast im {STR_VAR_2}\n"
	.string "aufgeräumt!\p"
	.string "{STR_VAR_3}-Siege-Serie…\n"
	.string "Rekord, was?\p"
	.string "Ich muss besser werden!\n"
	.string "Bis bald!$"

MatchCall_BattleFrontierRecordStreakText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier. Was los?\p"
	.string "Gerüchte sagen, du hast {STR_VAR_3}\n"
	.string "Siege im {STR_VAR_2}.\p"
	.string "Ich muss Gas geben.\n"
	.string "Tschau!$"

MatchCall_BattleFrontierRecordStreakText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Du warst im {STR_VAR_2}\n"
	.string "und hast {STR_VAR_3} mal gewonnen?\l"
	.string "Wahnsinn!\p"
	.string "Ich? Ich bin okay.\n"
	.string "Bis dann!$"

MatchCall_BattleFrontierRecordStreakText6::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier. Na?\p"
	.string "Ich hörte von {STR_VAR_3} Siegen im\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich streng mich an!\n"
	.string "Bis bald!$"

MatchCall_BattleFrontierRecordStreakText7::
	.string "…Äh, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier…\p"
	.string "Du warst im {STR_VAR_2}, ja?\p"
	.string "Und hast {STR_VAR_3} mal gewonnen.\p"
	.string "Oh, ein Pokémon!\n"
	.string "Weg bin ich!$"

MatchCall_BattleFrontierRecordStreakText8::
	.string "Oh, {PLAYER}{KUN}, hallo?\n"
	.string "Hier spricht {STR_VAR_1}.\l"
	.string "Alles gut?\p"
	.string "Sicher. Ich hörte von {STR_VAR_3}\n"
	.string "Siegen im {STR_VAR_2}.\p"
	.string "Sehr beeindruckend!\n"
	.string "Ich muss meine Pokémon treten!$"

MatchCall_BattleFrontierRecordStreakText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Gehört! {STR_VAR_3}-Siege im\n"
	.string "{STR_VAR_2}!\p"
	.string "So cool!\n"
	.string "Ich will auch!$"

MatchCall_BattleFrontierRecordStreakText10::
	.string "Oh, {PLAYER}{KUN}, hallo.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}?\p"
	.string "Gute Leistung.\n"
	.string "Ich arbeite dran.$"

MatchCall_BattleFrontierRecordStreakText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Schrecken vom {STR_VAR_2}?\p"
	.string "{STR_VAR_3} Siege in Folge?\n"
	.string "Du bist gut.\n"
	.string "Kann ich das auch?\p"
	.string "…Wohl kaum.\n"
	.string "Tschö!$"

MatchCall_BattleFrontierRecordStreakText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Alles fit?\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}?\p"
	.string "Nette Geschichte.\n"
	.string "Bis dann!$"

MatchCall_BattleFrontierRecordStreakText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Alles gut?\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}?\p"
	.string "Du hast Energie!\n"
	.string "Bye.$"

MatchCall_BattleFrontierRecordStreakText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}?\p"
	.string "Inspirierend!\n"
	.string "Bye-bye!$"

MatchCall_BattleDomeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Nachrichten!\p"
	.string "Du bist Champ im {STR_VAR_2}\n"
	.string "{STR_VAR_3} mal?\p"
	.string "Krass! Ich muss besser werden!\n"
	.string "Tschau!$"

MatchCall_BattleDomeText2::
	.string "Hallo, {STR_VAR_1} hier!\n"
	.string "Ich hab's gehört!\p"
	.string "{STR_VAR_3} Titel im\n"
	.string "{STR_VAR_2}.\p"
	.string "Super! Kann ich das auch?\n"
	.string "Wahrscheinlich nicht.$"

MatchCall_BattleDomeText3::
	.string "Hey {PLAYER}!\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Was geht?\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}!\p"
	.string "Mach noch einen!\n"
	.string "Bis bald!$"

MatchCall_BattleDomeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Champ im {STR_VAR_2}\n"
	.string "{STR_VAR_3} mal.\p"
	.string "Du arbeitest hart.\n"
	.string "Ich versuche mitzuhalten!$"

MatchCall_BattleDomeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss Gas geben!\n"
	.string "Tschö!$"

MatchCall_BattleDomeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier. Na?\p"
	.string "{STR_VAR_3} mal Champ im\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss meine Pokémon drillen.$"

MatchCall_BattleDomeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier.\p"
	.string "Du warst im {STR_VAR_2}\n"
	.string "und wurdest {STR_VAR_3} mal Champ?\p"
	.string "Nett. Hast du seltene Pokémon?\p"
	.string "Aha.\n"
	.string "Okay, bye.$"

MatchCall_BattleDomeText8::
	.string "Oh, {PLAYER}{KUN}, hallo.\n"
	.string "Hier spricht {STR_VAR_1}.\l"
	.string "Alles gut?\l"
	.string "Sicher.\p"
	.string "{STR_VAR_3} Titel im\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss so sein wie du.\n"
	.string "Bis dann.$"

MatchCall_BattleDomeText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "{STR_VAR_3} Titel im\n"
	.string "{STR_VAR_2}!\p"
	.string "Cool!\n"
	.string "Ich versuch's auch!$"

MatchCall_BattleDomeText10::
	.string "Oh, {PLAYER}{KUN}, hallo.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}?\p"
	.string "Gute Leistung.\n"
	.string "Muss arbeiten.$"

MatchCall_BattleDomeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Schrecken vom {STR_VAR_2}?\p"
	.string "{STR_VAR_3} Siege?\n"
	.string "Kann ich Champ werden?\p"
	.string "…Unmöglich?\n"
	.string "Tschö!$"

MatchCall_BattleDomeText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Alles fit?\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}?\p"
	.string "Nette Story.\n"
	.string "Bis dann!$"

MatchCall_BattleDomeText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Alles gut?\p"
	.string "{STR_VAR_3} Siege im\n"
	.string "{STR_VAR_2}?\p"
	.string "Du hast Energie!\n"
	.string "Bye.$"

MatchCall_BattleDomeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Titel im\n"
	.string "{STR_VAR_2}?\p"
	.string "Inspirierend!\n"
	.string "Bye!$"

MatchCall_BattlePikeText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}!\p"
	.string "Krass!\n"
	.string "Tschö!$"

MatchCall_BattlePikeText2::
	.string "Hallo, {STR_VAR_1} hier!\n"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss mich anstrengen!\n"
	.string "Bye!$"

MatchCall_BattlePikeText3::
	.string "Hey {PLAYER}!\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Na?\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}!\p"
	.string "Mach es besser!\n"
	.string "Bis bald!$"

MatchCall_BattlePikeText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss trainieren!$"

MatchCall_BattlePikeText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss loslegen!\n"
	.string "Bis dann!$"

MatchCall_BattlePikeText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier. Na?\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss Pokémon züchten.$"

MatchCall_BattlePikeText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier.\p"
	.string "{STR_VAR_2} und\n"
	.string "{STR_VAR_3} Räume?\p"
	.string "Wicked.\p"
	.string "Oh, ein Pokémon!\n"
	.string "Bye.$"

MatchCall_BattlePikeText8::
	.string "Oh, {PLAYER}{KUN}, hallo.\n"
	.string "Hier spricht {STR_VAR_1}.\l"
	.string "Alles gut?\l"
	.string "Sicher.\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Beeindruckend!\n"
	.string "Ich muss üben.\l"
	.string "Bis dann.$"

MatchCall_BattlePikeText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Gehört! {STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}!\p"
	.string "Cool!\n"
	.string "Ich will auch!$"

MatchCall_BattlePikeText10::
	.string "Oh, {PLAYER}{KUN}, hallo.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Gute Leistung.\n"
	.string "Muss arbeiten.$"

MatchCall_BattlePikeText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Schrecken der {STR_VAR_2}?\p"
	.string "{STR_VAR_3} Räume?\n"
	.string "Zählt was.\p"
	.string "Werde ich Champ?\p"
	.string "…Unmöglich?\n"
	.string "Tschö!$"

MatchCall_BattlePikeText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Alles fit?\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Nette Story.\n"
	.string "Bis dann!$"

MatchCall_BattlePikeText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Alles gut?\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Energie!\n"
	.string "Bye.$"

MatchCall_BattlePikeText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Räume in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Inspirierend!\n"
	.string "Bye!$"

MatchCall_BattlePyramidText1::
	.string "Hi! {PLAYER}?\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}, ja?\p"
	.string "Krass!\n"
	.string "Ich sollte das probieren.$"

MatchCall_BattlePyramidText2::
	.string "Hallo, {STR_VAR_1} hier!\n"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Fantastisch!\n"
	.string "Ich muss trainieren!$"

MatchCall_BattlePyramidText3::
	.string "Hey {PLAYER}!\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Na?\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}!\p"
	.string "Mach es besser!\n"
	.string "Bis bald!$"

MatchCall_BattlePyramidText4::
	.string "Hey, {PLAYER}{KUN}.\n"
	.string "{STR_VAR_1} hier.\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss mithalten!$"

MatchCall_BattlePyramidText5::
	.string "Hiya, {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss loslegen!\n"
	.string "Tschö!$"

MatchCall_BattlePyramidText6::
	.string "Hey, {PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier. Na?\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Ich muss trainieren.$"

MatchCall_BattlePyramidText7::
	.string "{PLAYER}{KUN}?\n"
	.string "{STR_VAR_1} hier.\p"
	.string "{STR_VAR_2} und\n"
	.string "{STR_VAR_3} Ebenen?\p"
	.string "Nett. Seltene Pokémon?\p"
	.string "Nein?\n"
	.string "Okay, bye.$"

MatchCall_BattlePyramidText8::
	.string "Oh, {PLAYER}{KUN}, hallo.\n"
	.string "Hier spricht {STR_VAR_1}.\l"
	.string "Alles gut?\l"
	.string "Sicher.\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}.\p"
	.string "Beeindruckend!\n"
	.string "Ich muss üben.\l"
	.string "Bis dann.$"

MatchCall_BattlePyramidText9::
	.string "Oh, {PLAYER}{KUN}, hi!\n"
	.string "Hier ist {STR_VAR_1}!\p"
	.string "Gehört! {STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}!\p"
	.string "Cool!\n"
	.string "Ich will auch!$"

MatchCall_BattlePyramidText10::
	.string "Oh, {PLAYER}{KUN}, hallo.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Gute Leistung.\n"
	.string "Muss arbeiten.$"

MatchCall_BattlePyramidText11::
	.string "Ah, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\p"
	.string "Schrecken der {STR_VAR_2}?\p"
	.string "{STR_VAR_3} Ebenen?\n"
	.string "Zählt was.\p"
	.string "Werde ich Champ?\p"
	.string "…Unmöglich?\n"
	.string "Tschö!$"

MatchCall_BattlePyramidText12::
	.string "Hallo {PLAYER}{KUN}.\n"
	.string "Ich bin's, {STR_VAR_1}.\l"
	.string "Alles fit?\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Nette Story.\n"
	.string "Bis dann!$"

MatchCall_BattlePyramidText13::
	.string "Ah, hallo {PLAYER}{KUN}!\n"
	.string "Hier ist {STR_VAR_1}!\l"
	.string "Alles gut?\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Energie!\n"
	.string "Bye.$"

MatchCall_BattlePyramidText14::
	.string "Oh, hi, {PLAYER}{KUN}.\n"
	.string "Hier ist {STR_VAR_1}.\l"
	.string "Gehört!\p"
	.string "{STR_VAR_3} Ebenen in der\n"
	.string "{STR_VAR_2}?\p"
	.string "Inspirierend!\n"
	.string "Bye!$"

MatchCall_Text_Mom1::
	.string "MOM: Dein Vater und du…\n"
	.string "Alle lieben Pokémon.\p"
	.string "Was ist so toll daran?\p"
	.string "Ich?\n"
	.string "Ich mag Pokémon, die für mich putzen.$"

MatchCall_Text_Mom2::
	.string "MOM: Hi, {PLAYER}!\n"
	.string "Dein Vater versteckt sich in der\l"
	.string "BLÜTENBURG ARENA.\p"
	.string "Er kommt nur zum Essen heim.\n"
	.string "Sobald der Kühlschrank leer ist,\l"
	.string "haut er wieder ab.\p"
	.string "Er schämt sich wohl, weil er gegen\n"
	.string "dich verloren hat!$"

MatchCall_Text_Mom3::
	.string "MOM: {PLAYER}…\n"
	.string "Sorg dich nicht um das Haus.\p"
	.string "Lauf in deinen TURBODRETERN,\n"
	.string "bis sie auseinanderfallen, Schatz!$"

MatchCall_Text_Roxanne1::
	.string "FELIZIA: Oh, hallo {PLAYER}!\p"
	.string "Ich lerne Tag und Nacht, seit wir\n"
	.string "uns trafen.\p"
	.string "Ich brauche noch Zeit, um meine\n"
	.string "ARENA zu öffnen.\p"
	.string "Ich studiere deine Schwachstellen!$"

MatchCall_Text_Roxanne2::
	.string "FELIZIA: Bist du das, {PLAYER}?\n"
	.string "Glückwunsch!\l"
	.string "Ich höre von dir!\p"
	.string "Ich bin noch nicht bereit.\n"
	.string "Ich muss mehr lesen.\p"
	.string "Wenn ich bereit bin, komm zur ARENA\n"
	.string "für die Prüfung!$"

MatchCall_Text_Roxanne3::
	.string "FELIZIA: {PLAYER}!\n"
	.string "ARENA bereit!\p"
	.string "Komm nach METAROST wann du willst!$"

MatchCall_Text_Roxanne4::
	.string "FELIZIA: In der METAROST ARENA\n"
	.string "ist unser Kampf, {PLAYER},\l"
	.string "ein Lehrbeispiel.$"

MatchCall_Text_Brawly1::
	.string "KAMILLO: Hey, {PLAYER}{KUN}!\p"
	.string "Ich hab viel gelernt aus unserem\n"
	.string "Kampf.\p"
	.string "Ich trainiere neu.\n"
	.string "Die ARENA bleibt zu.\p"
	.string "Es dauert noch.\n"
	.string "Aber wenn sie offen ist,\n"
	.string "will ich Revanche.$"

MatchCall_Text_Brawly2::
	.string "KAMILLO: Hey, {PLAYER}{KUN}!\n"
	.string "Glückwunsch!\p"
	.string "Die Wellen erzählen von dir!\p"
	.string "Ich muss härter trainieren.\p"
	.string "Die ARENA bleibt zu.\n"
	.string "Aber wenn sie offen ist,\n"
	.string "will ich Revanche.$"

MatchCall_Text_Brawly3::
	.string "KAMILLO: Hey, {PLAYER}{KUN}!\n"
	.string "ARENA ist bereit!\p"
	.string "Komm nach FAUSTAUHAVEN!\n"
	.string "Lass uns surfen!$"

MatchCall_Text_Brawly4::
	.string "KAMILLO: {PLAYER}{KUN}, Kämpfe gegen dich\n"
	.string "sind wie die perfekte Welle!$"

MatchCall_Text_Wattson1::
	.string "WALTER: Oh, du bist es!\p"
	.string "Seit du weg bist, trainiere ich\n"
	.string "von null an.\p"
	.string "Brauche noch etwas Zeit.\p"
	.string "Warte noch!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson2::
	.string "WALTER: Wahahahaha!\p"
	.string "Du hast es geschafft, was?\n"
	.string "Ich höre von dir!\p"
	.string "Ich muss mehr trainieren.\p"
	.string "Brauche noch etwas Zeit.\p"
	.string "Warte noch!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson3::
	.string "WALTER: Oh, du!\n"
	.string "ARENA bereit!\p"
	.string "Komm nach MALVENFROH!\n"
	.string "Wahahahaha!$"

MatchCall_Text_Wattson4::
	.string "WALTER: Wahahaha!\p"
	.string "Ein Kampf mit dir steht immer\n"
	.string "unter Hochspannung!$"

MatchCall_Text_Flannery1::
	.string "FLAVIA: {PLAYER}…\p"
	.string "Ich habe gemerkt, wie schlecht ich\n"
	.string "war.\p"
	.string "Aber ich bin nicht fertig!\p"
	.string "Ich trainiere neu.\n"
	.string "ARENA bleibt zu.\p"
	.string "Wenn es soweit ist, {PLAYER},\n"
	.string "fordere mich heraus.$"

MatchCall_Text_Flannery2::
	.string "FLAVIA: Hallo, {PLAYER}?\n"
	.string "Glückwunsch!\p"
	.string "Dein Erfolg brennt wie Feuer!\p"
	.string "Training läuft gut.\p"
	.string "Wenn die ARENA bereit ist, siehst\n"
	.string "du ein Zeichen im POKéNAV.$"

MatchCall_Text_Flannery3::
	.string "FLAVIA: Oh, {PLAYER}?\n"
	.string "ARENA bereit!\p"
	.string "Komm nach BAD LAVASTADT!\n"
	.string "Es wird heiß!$"

MatchCall_Text_Flannery4::
	.string "FLAVIA: {PLAYER}…\n"
	.string "Du wirst immer besser.\l"
	.string "Ich verbrenne fast vor Neid.$"

MatchCall_Text_Winona1::
	.string "WIBKE: Hallo, {PLAYER}!\p"
	.string "Dank dir kenne ich meine Schwächen!\p"
	.string "Wenn ich die ARENA öffne, stürze ich\n"
	.string "nicht mehr ab!$"

MatchCall_Text_Winona2::
	.string "WIBKE: Du hast es geschafft, {PLAYER}!\p"
	.string "Neuer CHAMP?\n"
	.string "Wir hörten es in BAUMHAUSEN!\p"
	.string "Aber… Nächstes Mal gewinne ich.$"

MatchCall_Text_Winona3::
	.string "WIBKE: Ist das {PLAYER}?\n"
	.string "ARENA offen!\p"
	.string "Wir warten in BAUMHAUSEN!$"

MatchCall_Text_Winona4::
	.string "WIBKE: {PLAYER}…\n"
	.string "Auch wenn ich verlor, meine Flügel\l"
	.string "brechen nicht.\p"
	.string "Genau wie du deinen Traum nie\n"
	.string "aufgabst.$"

MatchCall_Text_TateLiza1::
	.string "BEN: Oh! Du bist…\n"
	.string "SVENJA: {PLAYER}!\p"
	.string "BEN: Wir trainieren…\n"
	.string "SVENJA: ARENA öffnen!\p"
	.string "BEN: Wenn ARENA bereit…\n"
	.string "SVENJA: Wenn ARENA bereit…\p"
	.string "BEN: Ein Zeichen erscheint…\n"
	.string "SVENJA: Im MATCH CALL.$"

MatchCall_Text_TateLiza2::
	.string "BEN: {PLAYER}, Glückwunsch!\n"
	.string "SVENJA: {PLAYER}, Glückwunsch!\p"
	.string "BEN: Wir beide sind…\n"
	.string "SVENJA: Im Training!\p"
	.string "BEN: Brauchen Zeit, aber…\n"
	.string "SVENJA: Wenn ARENA bereit…\p"
	.string "BEN: Ein Zeichen erscheint…\n"
	.string "SVENJA: Im MATCH CALL.$"

MatchCall_Text_TateLiza3::
	.string "BEN: {PLAYER}!\n"
	.string "SVENJA: {PLAYER}!\p"
	.string "BEN: ARENA bereit!\n"
	.string "SVENJA: ARENA bereit!\p"
	.string "BEN: Bitte besuche…\n"
	.string "SVENJA: MOOSBACH CITY!$"

MatchCall_Text_TateLiza4::
	.string "BEN: {PLAYER}, der Kampf…\n"
	.string "SVENJA: War unbezahlbar.\p"
	.string "BEN: Es wäre schön…\n"
	.string "SVENJA: Wieder zu kämpfen!$"

MatchCall_Text_Juan1::
	.string "JUAN: Hmm…\n"
	.string "{PLAYER}{KUN}… Warst du das?\p"
	.string "Unser Kampf erinnerte mich an\n"
	.string "WASSILI.\p"
	.string "Vielleicht übertriffst du ihn!$"

MatchCall_Text_Juan2::
	.string "JUAN: Fufu… {PLAYER}{KUN}…\n"
	.string "Ziel erreicht.\p"
	.string "Ich hatte recht…\p"
	.string "Ich will dich wiedersehen, du\n"
	.string "Gipfelstürmer.$"

MatchCall_Text_Juan3::
	.string "JUAN: Hoho… {PLAYER}{KUN}…\p"
	.string "XENEROVILLE ARENA ist offen.\p"
	.string "Besuche mich, wann du willst.$"

MatchCall_Text_Juan4::
	.string "JUAN: {PLAYER}{KUN}…\p"
	.string "Wie Musik, unsere Kämpfe sind\n"
	.string "Inspiration…\p"
	.string "Ich sehe dich tanzen…$"

MatchCall_Text_Sidney::
	.string "ULRICH: Yo, {PLAYER}!\p"
	.string "Willst du kämpfen?\n"
	.string "Komm zur POKéMON LIGA.\p"
	.string "Ich bin hier!\n"
	.string "Ich warte!$"

MatchCall_Text_Phoebe::
	.string "ANTONIA: Hi, {PLAYER}!\p"
	.string "Komm doch mal wieder vorbei.\p"
	.string "Ich will sehen, wie eng deine\n"
	.string "Bindung zu den Geistern ist.$"

MatchCall_Text_Glacia::
	.string "FROSTINA: Hallo, {PLAYER}.\p"
	.string "Bist du arrogant geworden?\p"
	.string "Wenn du Abkühlung brauchst, komm\n"
	.string "zur POKéMON LIGA…$"

MatchCall_Text_Drake::
	.string "DRAGAN: Diese Stimme… {PLAYER}?\n"
	.string "Klingst gut…\p"
	.string "KAMPFZONE ist nett für Kinder.\p"
	.string "Aber echte Kämpfe gibt es nur in\n"
	.string "der POKéMON LIGA!\p"
	.string "Stimmst du zu, {PLAYER}?$"

MatchCall_Text_Wallace::
	.string "WASSILI: Hallo, {PLAYER}{KUN}.\n"
	.string "Kennst du TROY?\p"
	.string "Er ist…\n"
	.string "Sehr fähig.\p"
	.string "Aber seltsam. Kämpft selten.\p"
	.string "Sucht lieber Steine.\p"
	.string "Er gräbt sicher irgendwo.\p"
	.string "Was sind seltene Steine?\n"
	.string "Meteoriten?$"

MatchCall_Text_MayRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Piep!\p"
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "Ich war in FLOSSBRUNN.\p"
	.string "Ich sah ein grünes Riesenvieh im\n"
	.string "Himmel.\p"
	.string "Ich…\n"
	.string "Noch nie sowas gesehen.\p"
	.string "Was war das?\n"
	.string "Wichtig?\p"
	.string "… … … … … …\n"
	.string "… … … … … Klick!$"

MatchCall_Text_BrendanRayquazaCall:
	.string "… … … … … …\n"
	.string "… … … … … Piep!\p"
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hey, {PLAYER}!\n"
	.string "War in FLOSSBRUNN.\p"
	.string "Sah riesiges grünes Ding fliegen.\p"
	.string "Krass.\p"
	.string "Hättest du sehen sollen,\n"
	.string "{PLAYER}.\p"
	.string "… … … … … …\n"
	.string "… … … … … Klick!$"

MatchCall_Text_May1::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "MR. BRACK ist in Rente, aber\n"
	.string "fährt immer noch Boot mit PECKO.\p"
	.string "Er liebt das Meer wohl.$"

MatchCall_Text_May2::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "Kleine Käffer wie BLÜTENBURG haben\n"
	.string "ARENEN.\p"
	.string "Aber GRAPHITPORT nicht.\p"
	.string "Wenn sie eine bauen, werde ich\n"
	.string "LEITER.$"

MatchCall_Text_May3::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "Kennst du den ZERSCHNEIDER-Typ in\n"
	.string "METAROST?\l"
	.string "Sein Bruder wohnt in MALVENFROH.\p"
	.string "Rate mal, wie er heißt?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "ZERTRÜMMERER-TYP!$"

MatchCall_Text_May4::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}{KUN}?\p"
	.string "METAFLURTUNNEL…\n"
	.string "Heißt so wegen METAROST und\l"
	.string "WIESENFLUR.$"

MatchCall_Text_May5::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}{KUN}, wie geht's?\p"
	.string "Bin auf ROUTE 111.\p"
	.string "Raste bei der alten Frau.\p"
	.string "Nördlich der Wüste.$"

MatchCall_Text_May6::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "Kennst du den WUNDERTURM?\p"
	.string "Erscheint und verschwindet.\p"
	.string "Will ihn sehen.$"

MatchCall_Text_May7::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}{KUN}, yahoo!\n"
	.string "Bin auf ROUTE 119.\p"
	.string "Großer Fluss. Regen.\p"
	.string "Bin nass!$"

MatchCall_Text_May8::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}{KUN}, hi.\p"
	.string "PYROBERG ist ein Friedhof.\p"
	.string "Deshalb spukt es da!$"

MatchCall_Text_May9::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "Wollte nach BAD LAVASTADT.\p"
	.string "Traf üble Typen am STEILPASS.\n"
	.string "War gruselig!$"

MatchCall_Text_May10::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\n"
	.string "Nachrichten gesehen?\p"
	.string "KAPT. BRIGG fand die TIEFSEEHÖHLE.$"

MatchCall_Text_May11::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\n"
	.string "Toll, oder?\p"
	.string "Ohne Boot übers Meer.\n"
	.string "Mit Pokémon.\p"
	.string "Gibt auch Tauchen.$"

MatchCall_Text_May12::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\n"
	.string "Alles okay?\p"
	.string "Weg blockiert auf See?\p"
	.string "Tauch unter.\n"
	.string "Such Gräben.\p"
	.string "Komm auf der anderen Seite hoch.\n"
	.string "Einfach!$"

MatchCall_Text_May13::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}{KUN}!\p"
	.string "Was geht?\n"
	.string "POKéDEX voll?\p"
	.string "Gerücht: Uralte Pokémon.\n"
	.string "Drei Stück!\p"
	.string "Will eins sehen…$"

MatchCall_Text_May14::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}{KUN}!\n"
	.string "Gerüchte!\p"
	.string "XENEROVILLE LEITER besiegt?\p"
	.string "Fast geschafft, was?$"

MatchCall_Text_May15::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Jeder kennt dich jetzt,\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Wenn ich sage, wir sind Freunde,\n"
	.string "staunen alle!$"

MatchCall_Text_Brendan1::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hey, {PLAYER}!\p"
	.string "MR. BRACK fährt immer noch Boot.\n"
	.string "Mit PECKO.\p"
	.string "Er mag das Meer.$"

MatchCall_Text_Brendan2::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hey, {PLAYER}!\p"
	.string "Kleine Käffer haben ARENEN.\n"
	.string "GRAPHITPORT nicht.\p"
	.string "Wenn eine kommt, bewerb ich mich.$"

MatchCall_Text_Brendan3::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Yo, {PLAYER}!\p"
	.string "ZERSCHNEIDER in METAROST?\n"
	.string "Sein Bruder wohnt in MALVENFROH.\p"
	.string "Rate mal?\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "ZERTRÜMMERER-TYP!$"

MatchCall_Text_Brendan4::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}?\p"
	.string "METAFLURTUNNEL verbindet METAROST\n"
	.string "und WIESENFLUR.\p"
	.string "Wusstest du das?$"

MatchCall_Text_Brendan5::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}, was geht?\p"
	.string "Bin ROUTE 111.\p"
	.string "Raste bei der Oma.\n"
	.string "Besuch sie mal.$"

MatchCall_Text_Brendan6::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hey, {PLAYER}!\p"
	.string "Kennst du WUNDERTURM?\p"
	.string "Ist nur manchmal da.\p"
	.string "Will ihn sehen!$"

MatchCall_Text_Brendan7::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Wer da? Oh, {PLAYER}?\n"
	.string "Bin ROUTE 119.\p"
	.string "Regen und Fluss.\p"
	.string "Bin komplett nass!$"

MatchCall_Text_Brendan8::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}!\p"
	.string "PYROBERG ist Friedhof.\p"
	.string "Voller GEISTER!$"

MatchCall_Text_Brendan9::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hey, {PLAYER}.\p"
	.string "Wollte nach BAD LAVASTADT.\p"
	.string "Traf üble Typen am STEILPASS.\p"
	.string "TEAM MAGMA.$"

MatchCall_Text_Brendan10::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hi, {PLAYER}!\n"
	.string "Nachrichten?\p"
	.string "KAPT. BRIGG fand TIEFSEEHÖHLE.$"

MatchCall_Text_Brendan11::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hey, {PLAYER}!\n"
	.string "Krass, oder?\p"
	.string "Übers Meer surfen.\p"
	.string "Und tauchen.\p"
	.string "Pokémon können alles!$"

MatchCall_Text_Brendan12::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Moin, {PLAYER}!\n"
	.string "Alles klar?\p"
	.string "Weg blockiert?\p"
	.string "Tauch unter.\n"
	.string "Such Gräben.\p"
	.string "Komm hoch. Einfach!$"

MatchCall_Text_Brendan13::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Hey, {PLAYER}!\p"
	.string "Wie läuft's? POKéDEX?\p"
	.string "Gerücht: Uralte Pokémon.\n"
	.string "Drei Stück!\p"
	.string "Will eins fangen…$"

MatchCall_Text_Brendan14::
	.string "{COLOR RIVAL_CLR}{RIVAL}: {PLAYER}!\n"
	.string "Gerüchte!\p"
	.string "XENEROVILLE LEITER besiegt?\n"
	.string "Krass!$"

MatchCall_Text_Brendan15::
	.string "{COLOR RIVAL_CLR}{RIVAL}: Jeder kennt dich jetzt,\n"
	.string "{PLAYER}!\p"
	.string "Alle sind neidisch, dass ich dich\n"
	.string "kenne!$"

MatchCall_Text_Wally1::
	.string "HEIKO: Oh, {PLAYER}!\p"
	.string "Ich werde gesünder.\n"
	.string "Ich will so stark sein wie du,\n"
	.string "{PLAYER}!$"

MatchCall_Text_Wally2::
	.string "HEIKO: {PLAYER}, hallo!\p"
	.string "Wibke freut sich über den TUNNEL!$"

MatchCall_Text_Wally3::
	.string "HEIKO: Oh, {PLAYER}!\p"
	.string "Ich… bin abgehauen.\n"
	.string "Ohne was zu sagen.\p"
	.string "Mein Onkel ist bestimmt sauer…\p"
	.string "{PLAYER}, du verstehst das, oder?$"

MatchCall_Text_Wally4::
	.string "HEIKO: {PLAYER}?\n"
	.string "Ich bin's, HEIKO!\p"
	.string "TRAINER sein ist toll!\p"
	.string "Leute grüßen mich!\p"
	.string "Alle sind verbunden!$"

MatchCall_Text_Wally5::
	.string "HEIKO: {PLAYER}? Krass!\n"
	.string "Das TRASLA?\l"
	.string "Hat sich entwickelt, {PLAYER}!\p"
	.string "Vielleicht hab ich Talent…\p"
	.string "Oh, ich sollte nicht angeben!\p"
	.string "Das Pokémon macht die Arbeit!$"

MatchCall_Text_Wally6::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "HEIKO ist außer Reichweite…$"

MatchCall_Text_Wally7::
	.string "HEIKO: Oh, {PLAYER}!\p"
	.string "Früher war ich nie draußen…\p"
	.string "Jetzt bin ich auf Abenteuer…\p"
	.string "{PLAYER}…\n"
	.string "Danke…$"

MatchCall_Text_Scott1::
	.string "SCOTT: Moin, {PLAYER}{KUN}!\p"
	.string "Pokémon sind überall.\n"
	.string "Überall.\p"
	.string "TRAINER auch.\p"
	.string "Ich muss überall hin. Stress!$"

MatchCall_Text_Scott2::
	.string "SCOTT: Bin auf ROUTE 119.\n"
	.string "Voller TRAINER!\p"
	.string "Und hohes Gras.\p"
	.string "Es kitzelt an den Beinen!$"

MatchCall_Text_Scott3::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Warst du auf dem PYROBERG?\p"
	.string "Gedenkstätte.\p"
	.string "Sollte man mal gesehen haben.$"

MatchCall_Text_Scott4::
	.string "SCOTT: Hi, {PLAYER}{KUN}!\p"
	.string "Ich höre von Banden.\n"
	.string "TEAM MAGMA und AQUA.\p"
	.string "Haben die gute TRAINER?\p"
	.string "…Wenn's nur Schläger sind…$"

MatchCall_Text_Scott5::
	.string "SCOTT: Oh, hi, {PLAYER}{KUN}.\p"
	.string "Gibt es starke TRAINER am\n"
	.string "Meeresgrund?\p"
	.string "Ich kann nicht schwimmen.\n"
	.string "Ich hab keine Pokémon…$"

MatchCall_Text_Scott6::
	.string "SCOTT: Hi, hi, {PLAYER}{KUN}!\p"
	.string "Alle ORDEN?\n"
	.string "Dann zur POKéMON LIGA!\p"
	.string "Du kannst CHAMP werden.\p"
	.string "Aber weißt du?\n"
	.string "Es gibt was Besseres.\p"
	.string "Sag ich noch nicht.\p"
	.string "Freu dich drauf.\p"
	.string "Wenn du in der RUHMESHALLE bist!$"

MatchCall_Text_Scott7::
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "SCOTT ist außer Reichweite…$"

MatchCall_Text_Norman1::
	.string "DAD: In METAROST gibt es den\n"
	.string "ZERSCHNEIDER.\p"
	.string "Besuch ihn.$"

MatchCall_Text_Norman2::
	.string "DAD: Hm… Du wirst stärker,\n"
	.string "{PLAYER}.\p"
	.string "Du entfernst dich von uns…\p"
	.string "Schwer zu erklären.$"

MatchCall_Text_Norman3::
	.string "DAD: Aha…\n"
	.string "Vier ORDEN…\p"
	.string "Es ist soweit.\n"
	.string "Komm her.\p"
	.string "Ich warte!$"

MatchCall_Text_Norman4::
	.string "DAD: {PLAYER}! Besuch Mutter mal.\p"
	.string "Ich bleibe hier und trainiere.\p"
	.string "Der Weg des Kampfes ist hart!$"

MatchCall_Text_Norman5::
	.string "DAD: Oh, hi, {PLAYER}!\p"
	.string "MAGMA-EMBLEM?\n"
	.string "Kenn ich nicht.\p"
	.string "Klingt nach Vulkan!$"

MatchCall_Text_Norman6::
	.string "DAD: Hiyah! Haah! Dwah!\p"
	.string "…Oh? {PLAYER}!\p"
	.string "Du störst mein Training!$"

MatchCall_Text_Norman7::
	.string "DAD: {PLAYER}!\p"
	.string "CHAMP… Wer hätte das gedacht…\p"
	.string "Okay!\n"
	.string "Ich hole auf!$"

MatchCall_Text_Norman8::
	.string "DAD: Hm? {PLAYER}?\n"
	.string "Gutes Timing!\p"
	.string "Ich fordere dich heraus.\p"
	.string "Komm zur ARENA.\n"
	.string "Ich warte!$"

MatchCall_Text_Norman9::
	.string "DAD: …Du erstaunst mich, {PLAYER}.\n"
	.string "Wie hoch fliegst du noch?$"

MatchCall_Text_Steven1::
	.string "TROY: Hi, {PLAYER}{KUN}!\p"
	.string "Warst du in MALVENFROH?\p"
	.string "Hol dir das EILRAD.\p"
	.string "Dann ab zur GRANITHÖHLE.\p"
	.string "Vielleicht findest du was.$"

MatchCall_Text_Steven2::
	.string "TROY: Hi, {PLAYER}{KUN}!\p"
	.string "Ich traf viele TRAINER.\p"
	.string "Du bist einzigartig.\n"
	.string "Anders.$"

MatchCall_Text_Steven3::
	.string "TROY: Hi, {PLAYER}{KUN}!\p"
	.string "Was denkst du über Pokémon?\p"
	.string "Partner?\p"
	.string "Freunde?\p"
	.string "Deine Antwort bestimmt alles.$"

MatchCall_Text_Steven4::
	.string "TROY: Hallo?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Probleme im RAUMFAHRTZENTRUM.\p"
	.string "Keine Zeit.\n"
	.string "Bye!$"

MatchCall_Text_Steven5::
	.string "TROY: Oh!\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Nicht reden.\n"
	.string "Handeln.\p"
	.string "Glaub an dich.$"

MatchCall_Text_Steven6::
	.string "… … … … … …\p"
	.string "TROY geht nicht ran…$"

MatchCall_Text_Steven7::
	.string "TROY: {PLAYER}{KUN}… Glückwunsch\n"
	.string "zur RUHMESHALLE.\p"
	.string "… … … … … …\n"
	.string "… … … … … …\p"
	.string "Hoffentlich sehen wir uns wieder!$"

MatchCall_Text_BirchRegisterCall:
	.string "PROF. BIRK: Oh, {PLAYER}{KUN}!\n"
	.string "Hab schon gehört!\p"
	.string "Dein POKéNAV hat MATCH CALL.\p"
	.string "Ich trag mich ein!\p"
	.string "Dann kann ich deinen POKéDEX\n"
	.string "jederzeit kritisieren.\p"
	.string "… … … … … …$"

MatchCall_Text_RegisteredBirch:
	.string "PROF. BIRK registriert.$"

MatchCall_Text_UnusedProfBirch:
	.string "PROF. BIRK: Mit POKéDEX und NAV\n"
	.string "macht Forschen Spaß, was?$"

MatchCall_Text_MrStone1::
	.string "MR. TRUMM: Oh? {PLAYER}{KUN}!\p"
	.string "Du rufst an? POKéNAV geht also!\p"
	.string "Ruf andere an!\p"
	.string "Gut! Gut!\n"
	.string "Du klingst froh!\p"
	.string "Hm…\n"
	.string "Woher ich das weiß?\p"
	.string "Ich seh dich aus dem Fenster!\p"
	.string "Wahahaha!\n"
	.string "Bis dann!$"

MatchCall_Text_MrStone2::
	.string "MR. TRUMM: Oh? {PLAYER}{KUN}!\p"
	.string "Was ist? Auftrag vergessen?\p"
	.string "Brief an TROY in FAUSTAUHAVEN.\p"
	.string "Paket an KAPT. BRIGG in\n"
	.string "GRAPHITPORT.\p"
	.string "Weißt du noch?\p"
	.string "Ich bin beschäftigt! Bye-bye!$"

MatchCall_Text_MrStone3::
	.string "MR. TRUMM: Oh! {PLAYER}{KUN}!\p"
	.string "Du hast TROY getroffen!\n"
	.string "Belohnung!\p"
	.string "Komm nach METAROST.\p"
	.string "Ich warte!$"

MatchCall_Text_MrStone4::
	.string "MR. TRUMM: Oh! {PLAYER}{KUN}!\p"
	.string "DEVON hat den METAFLURTUNNEL\n"
	.string "gegraben?\p"
	.string "Wir haben aufgehört wegen der\n"
	.string "Pokémon.\p"
	.string "Logisch.\p"
	.string "Frieden ist wichtiger als\n"
	.string "Bequemlichkeit.$"

MatchCall_Text_MrStone5::
	.string "MR. TRUMM: Hallo, {PLAYER}{KUN}!\p"
	.string "Du bist WALTERs Kind!\p"
	.string "Kein Wunder, dass du gut bist!$"

MatchCall_Text_MrStone6::
	.string "MR. TRUMM: Was?\p"
	.string "Vater besiegt?\p"
	.string "Erstaunlich!\p"
	.string "Wusste nicht, dass du so speziell\n"
	.string "bist! Wahaha!$"

MatchCall_Text_MrStone7::
	.string "Hallo!\n"
	.string "Hier DEVON CORP…\l"
	.string "Oh, hallo, {PLAYER}!\p"
	.string "PRÄSIDENT ist weg.\p"
	.string "Er ist beschäftigt.\n"
	.string "Du auch, {PLAYER}.$"

MatchCall_Text_MrStone8::
	.string "…Hä? …Was?\p"
	.string "GROU… Ja? …DON?\p"
	.string "Verbindung schlecht…\n"
	.string "…hör nix…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone9::
	.string "…Hä? …Was?\p"
	.string "Tiefsee… Ja? …Höhle…?\p"
	.string "Verbindung schlecht…\n"
	.string "…hör nix…\p"
	.string "BZZZZ…$"

MatchCall_Text_MrStone10::
	.string "MR. TRUMM: {PLAYER}{KUN}! Ich bin's!\p"
	.string "Du hast Dinge getan, keine Ahnung\n"
	.string "was, bin beschäftigt!\p"
	.string "Geh deinen Weg.\p"
	.string "Ich bin stolz!\n"
	.string "Mach's gut!$"

MatchCall_Text_MrStone11::
	.string "MR. TRUMM: … … … … … …\n"
	.string "Ist das {PLAYER}{KUN}?\p"
	.string "Du klingst so selbstsicher!\p"
	.string "Hm! Besuch uns mal bei DEVON!$"
