@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.string "so abgefuckt!$"

GiddyText_SoDarling::
	.string "zum Kotzen!$"

GiddyText_SoRelaxed::
	.string "so drauf!$"

GiddyText_SoSunny::
	.string "so ätzend!$"

GiddyText_SoDesirable::
	.string "so billig!$"

GiddyText_SoExciting::
	.string "so stressig!$"

GiddyText_SoAmusing::
	.string "so lächerlich!$"

GiddyText_SoMagical::
	.string "so krank!$"

GiddyText_Is::
	.string "ist$"

GiddyText_DontYouAgree::
	.string "\n"
	.string "Bist du dumm?$"

GiddyText_ISoWantToGoOnAVacation::
	.string "Ich brauche Urlaub vom Leben.\n"
	.string "Ein goldener Schuss wäre nett.\l"
	.string "Kennst du ’nen guten Dealer?$"

GiddyText_IBoughtCrayonsWith120Colors::
	.string "Ich hab mir 120 Buntstifte in die\n"
	.string "Nase gesteckt!\l"
	.string "Jetzt riech ich den Regenbogen!$"

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.string "Wäre es nicht geil, wenn wir einfach\n"
	.string "platzen würden?\l"
	.string "Wie riesige Eiterpickel? Platsch!$"

GiddyText_WhenYouWriteOnASandyBeach::
	.string "Wenn du was in den Sand schreibst,\n"
	.string "ist es weg. Genau wie deine Zukunft.\l"
	.string "Alles ist sinnlos.$"

GiddyText_WhatsTheBottomOfTheSeaLike::
	.string "Wie ist es wohl am Meeresgrund?\n"
	.string "Mit Betonschuhen? Ich würde dich\l"
	.string "so gerne runterschubsen!$"

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.string "Wenn die Sonne untergeht, werde ich\n"
	.string "wach. Und hungrig. Lauf weg.$"

GiddyText_LyingBackInTheGreenGrass::
	.string "Im Gras liegen… zwischen Hundekacke\n"
	.string "und gebrauchten Spritzen…\l"
	.string "Das ist Romantik, Alter!$"

GiddyText_SecretBasesAreSoWonderful::
	.string "GEHEIMBASEN sind super!\n"
	.string "Da kann man Leichen lagern, ohne\l"
	.string "dass es sofort stinkt!$"
