MoveRelearner_Text_WouldLearnNewMoves:
	.string "Moin. Ich bin der Attacken-Helfer.\n"
	.string "Soll ich in den Hirnen deiner Pokémon\l"
	.string "nach vergessenen Kräften graben?$"

MoveRelearner_Text_LevelUpMoves:
	.string "Level-Up Attacken$"

MoveRelearner_Text_EggMoves:
	.string "Ei-Attacken$"

MoveRelearner_Text_TMMoves:
	.string "TM-Attacken$"

MoveRelearner_Text_TutormoveMoves:
	.string "Tutor-Attacken$"

MoveRelearner_Text_SeeYa:
	.string "Man sieht sich!$"

MoveRelearner_Text_AnythingElse:
	.string "Kann ich sonst noch was für dich tun?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Wähle das Versuchskaninchen… Äh,\n"
	.string "das Pokémon aus.$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Du hast gar keine Pokémon dabei.\n"
	.string "Willst du mich verarschen?$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Tut mir leid…\n"
	.string "Ein Ei hat noch kein Gehirn zum\l"
	.string "Manipulieren.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Sorry…\p"
	.string "Dieses Pokémon ist ein hoffnungsloser\n"
	.string "Fall. Ich kann ihm nichts beibringen.$"

MoveRelearner_Text_LevelUpMoveLWR::
	.string "Level-Up Attacke$"

MoveRelearner_Text_EggMoveLWR::
	.string "Ei-Attacke$"

MoveRelearner_Text_TMMoveLWR::
	.string "TM-Attacke$"

MoveRelearner_Text_TutorMoveLWR::
	.string "Tutor-Attacke$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Welche {STR_VAR_3} soll ich einprügeln?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Danke, dass du mein Versuchskaninchen\n"
	.string "gebracht hast. Komm bald wieder!$"
