MoveRelearner_Text_WouldLearnNewMoves:
	.string "Na, Bock auf neue Attacken?\n"
	.string "Ich bring deinem Pokémon gern was Neues bei!$"

MoveRelearner_Text_LevelUpMoves:
	.string "Level-Up-Attacken$"

MoveRelearner_Text_EggMoves:
	.string "Ei-Attacken$"

MoveRelearner_Text_TMMoves:
	.string "TM-Attacken$"

MoveRelearner_Text_TutorMoves:
	.string "Lehrer-Attacken$"

MoveRelearner_Text_SeeYa:
	.string "Alles klar, dann hau rein!$"

MoveRelearner_Text_AnythingElse:
	.string "Noch was, oder war’s das jetzt?$"

MoveRelearner_Text_ChoosePkmn:
	.string "Na los, welches Pokémon soll’s sein?$"

MoveRelearner_Text_HaveNoPkmn:
	.string "Äh… du hast ja gar kein Pokémon.$"

MoveRelearner_Text_CantTeachMoveToEgg:
	.string "Äh, nein.\n"
	.string "Ein Ei kann nun wirklich nichts lernen.$"

MoveRelearner_Text_CantTeachMoveToPkmn:
	.string "Hm… tut mir leid.\n"
	.string "Dem Pokémon kann ich nichts beibringen.$"

MoveRelearner_Text_LevelUpMoveLWR:
	.string "Level-Up-Attacke$"

MoveRelearner_Text_EggMoveLWR:
	.string "Ei-Attacke$"

MoveRelearner_Text_TMMoveLWR:
	.string "TM-Attacke$"

MoveRelearner_Text_TutorMoveLWR:
	.string "Lehrer-Attacke$"

MoveRelearner_Text_WhichXmoveShouldTeach:
	.string "Welche Attacke soll's denn werden?$"

MoveRelearner_Text_ThankYouComeAgain:
	.string "Danke fürs Vorbeischauen!\n"
	.string "Komm ruhig wieder, wenn du mehr willst!$"
