gOtherText_NewName::
	.string "ANDERER NAME$"

gNameChoice_Green::
	.string "KEVIN$"

gNameChoice_Red::
	.string "RONNY$"

gNameChoice_Leaf::
	.string "MANDY$"

gNameChoice_Fire::
	.string "FEUER$"

gNameChoice_Gary::
	.string "ATZE$"

gNameChoice_Kaz::
	.string "HORST$"

gNameChoice_Toru::
	.string "DETLEF$"

gNameChoice_Ash::
	.string "LAUCH$"

gNameChoice_Kene::
	.string "JUSTIN$"

gNameChoice_Geki::
	.string "MURAT$"

gNameChoice_Jak::
	.string "INGO$"

gNameChoice_Janne::
	.string "USCHI$"

gNameChoice_Jonn::
	.string "UWE$"

gNameChoice_Kamon::
	.string "PASCAL$"

gNameChoice_Karl::
	.string "KARL$"

gNameChoice_Taylor::
	.string "CHANTAL$"

gNameChoice_Oscar::
	.string "OSKAR$"

gNameChoice_Hiro::
	.string "YUSUF$"

gNameChoice_Max::
	.string "MAX$"

gNameChoice_Jon::
	.string "JON$"

gNameChoice_Ralph::
	.string "RALLE$"

gNameChoice_Kay::
	.string "KAI$"

gNameChoice_Tosh::
	.string "BODO$"

gNameChoice_Roak::
	.string "ROCKY$"

gNameChoice_Omi::
	.string "OMI$"

gNameChoice_Jodi::
	.string "GABI$"

gNameChoice_Amanda::
	.string "JESSICA$"

gNameChoice_Hillary::
	.string "ANGELA$"

gNameChoice_Makey::
	.string "MAIK$"

gNameChoice_Michi::
	.string "MICHI$"

gNameChoice_Paula::
	.string "PETRA$"

gNameChoice_June::
	.string "PEGGY$"

gNameChoice_Cassie::
	.string "CINDY$"

gNameChoice_Rey::
	.string "RENE$"

gNameChoice_Seda::
	.string "SANDRA$"

gNameChoice_Kiko::
	.string "KIKI$"

gNameChoice_Mina::
	.string "LISA$"

gNameChoice_Norie::
	.string "NORA$"

gNameChoice_Sai::
	.string "SAM$"

gNameChoice_Momo::
	.string "MOMO$"

gNameChoice_Suzi::
	.string "SUSI$"

gControlsGuide_Text_Intro::
	.string "Anleitung für Vollidioten.\n"
	.string "Lies das, sonst stirbst du.$"

gControlsGuide_Text_DPad::
	.string "Bewegt deine Spielfigur.\n"
	.string "Damit läufst du weg, wenn du Angst hast.$"

gControlsGuide_Text_AButton::
	.string "Labertaste. Damit bestätigst du dein\n"
	.string "Elend und liest Texte, die dich nerven.$"

gControlsGuide_Text_BButton::
	.string "Rückzieher-Taste.\n"
	.string "Für Feiglinge, die 'Nein' sagen.$"

gControlsGuide_Text_StartButton::
	.string "Drück das für das MENÜ.\n"
	.string "Pause, wenn du heulen musst.$"

gControlsGuide_Text_SelectButton::
	.string "Damit sortierst du deine Drogen\n"
	.string "(Items).$"

gControlsGuide_Text_LRButtons::
	.string "Hilfe für Noobs.\n"
	.string "Drück das, wenn du überfordert bist.$"

gOakSpeech_Text_AskPlayerGender::
	.string "Hose runter.\n"
	.string "Bist du ein Junge? Oder ein Mädchen?$"

gPikachuIntro_Text_Page1::
	.string "In der Welt, die du gleich betrittst,\n"
	.string "wirst du Schmerzen und Leid erfahren.\n"
	.string "Du bist kein Held, du bist ein Opfer.\n"
	.string "\n"
	.string "Rede mit Leuten, auch wenn sie stinken.\n"
	.string "Durchsuch den Müll nach Hinweisen.\n"
	.string "Traue niemandem.$"

gPikachuIntro_Text_Page2::
	.string "Neue Wege öffnen sich nur mit Gewalt.\n"
	.string "Hilf niemandem, hilf dir selbst.\n"
	.string "Löse Rätsel oder stirb beim Versuch.\n"
	.string "\n"
	.string "Du wirst überfallen und von wilden\n"
	.string "Bestien gejagt.\n"
	.string "Sei keine Heulsuse.$"

gPikachuIntro_Text_Page3::
	.string "Wir hoffen, dass du auf deiner Reise\n"
	.string "nicht draufgehst und vielleicht sogar\n"
	.string "etwas lernst. Wahrscheinlich nicht.\n"
	.string "Das ist uns eigentlich auch egal.\n"
	.string "\n"
	.string "Drück den A-Knopf.\n"
	.string "Dein Albtraum beginnt!$"

gOakSpeech_Text_WelcomeToTheWorld::
	.string "Moin.\n"
	.string "Wer bist du denn?\p"
	.string "Willkommen in der Hölle von POKéMON!\p"
	.string "Ich bin EICH.\p"
	.string "Die Leute nennen mich den POKéMON\n"
	.string "PROFESSOR, wenn sie nicht lästern.\p$"

gOakSpeech_Text_ThisWorld::
	.string "Diese Dreckswelt…$"

gOakSpeech_Text_IsInhabitedFarAndWide::
	.string "…ist verseucht mit Viechern,\n"
	.string "die wir POKéMON nennen.\p$"

gOakSpeech_Text_IStudyPokemon::
	.string "Manche halten sie als Haustiere.\n"
	.string "Andere lassen sie brutal kämpfen.\p"
	.string "Und ich…\p"
	.string "Ich glotze sie den ganzen Tag an.\n"
	.string "Jeder braucht ein Hobby.\p$"

gOakSpeech_Text_TellMeALittleAboutYourself::
	.string "Aber genug von mir. Wer bist du?\n"
	.string "Siehst nicht sehr helle aus.\p$"

gOakSpeech_Text_YourNameWhatIsIt::
	.string "Wie heißt du?\n"
	.string "Schreib’s auf, ich hör eh nicht zu.\p$"

gOakSpeech_Text_SoYourNameIsPlayer::
	.string "Echt jetzt?\n"
	.string "Du heißt {PLAYER}? Mein Beileid.$"

gOakSpeech_Text_WhatWasHisName::
	.string "Das ist mein Enkel.\p"
	.string "Er hasst dich, seit ihr Babys wart.\n"
	.string "Er ist ein ziemlicher Arsch.\p"
	.string "…Äh, wie hieß der Bastard noch gleich?$"

gOakSpeech_Text_YourRivalsNameWhatWasIt::
	.string "Sag schon, wie heißt die Ratte?$"

gOakSpeech_Text_ConfirmRivalName::
	.string "…Ah, hieß er {RIVAL}?$"

gOakSpeech_Text_RememberRivalsName::
	.string "Stimmt! Jetzt fällt’s mir ein!\n"
	.string "Er heißt {RIVAL}! Der kleine Pisser!\p$"

gOakSpeech_Text_LetsGo::
	.string "{PLAYER}!\p"
	.string "Deine Geschichte voller Enttäuschungen\n"
	.string "beginnt jetzt!\p"
	.string "Eine Welt voller Schmerz und Verrat\n"
	.string "erwartet dich! Los, verschwinde!$"
