gText_ObtainedTheItem::
	.string "{STR_VAR_2} erhalten!$"

gText_TheBagIsFull::
	.string "Der BEUTEL ist voll…$"

gText_PutItemInPocket::
	.string "{PLAYER} packt {STR_VAR_2} in die\n"
	.string "{STR_VAR_3}-TASCHE.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} hat {STR_VAR_2} gefunden!$"

gText_TooBadBagIsFull::
	.string "Zu schade!\n"
	.string "Der BEUTEL ist voll…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} packt {STR_VAR_2} in den\n"
	.string "PYRABEUTEL.$"

gText_ObtainedTheDecor::
	.string "{STR_VAR_2} erhalten.$"

gText_NoRoomLeftForAnother::
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "{STR_VAR_2} wurde auf den PC\n"
	.string "übertragen.$"

gText_ObtainedTheItems::
	.string "{STR_VAR_1} {STR_VAR_2} Erhalten!$"

gText_PlayerFoundItems::
	.string "{PLAYER} krallt sich {STR_VAR_1} {STR_VAR_2}!$"

gText_PutCoinsAwayInCoinCase::
	.string "{PLAYER} stopft die MÜNZEN in\n"
	.string "den scheiß MÜNZKORB.$"

gText_FoundXCoins::
	.string "{PLAYER} grappt sich\n"
	.string "{STR_VAR_1} {STR_VAR_2}!$"

gText_FoundXItems::
	.string "{PLAYER} sackt fette\n"
	.string "{STR_VAR_1} {STR_VAR_2} ein!$"

gText_CoinCaseIsFull::
	.string "Pech gehabt, du Lappen!\n"
	.string "Dein MÜNZKORB ist randvoll…$"

gText_NothingToPutThemIn::
	.string "Bist du komplett lost?!\n"
	.string "Du hast nix, wo du den\l"
	.string "Scheiß reinpacken kannst…$"
