gText_ObtainedTheItem::
	.string "{STR_VAR_2} erhalten!$"

gText_TheBagIsFull::
	.string "Der Beutel ist voll…$"

gText_PutItemInPocket::
	.string "{PLAYER} packt {STR_VAR_2} in die\n"
	.string "{STR_VAR_3}-TASCHE.$"

gText_PlayerFoundOneItem::
	.string "{PLAYER} hat {STR_VAR_2} gefunden!$"

gText_TooBadBagIsFull::
	.string "Oh nein!\n"
	.string "Der Beutel ist voll…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} hat {STR_VAR_2}\n"
	.string "in der TASCHE verstaut.$"

gText_ObtainedTheDecor::
	.string "Dekorationsobjekt {STR_VAR_2} erhalten!$"

gText_NoRoomLeftForAnother::
	.string "Oh nein! Es ist kein Platz mehr\n"
	.string "für ein weiteres Dekorationsobjekt {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
	.string "Das Dekorationsobjekt {STR_VAR_2} wurde\n"
	.string "zum PC übertragen.$"
