gText_PkmnTransferredSomeonesPC::
    .string "{STR_VAR_2} wurde zu\n"
    .string "JEMANDES PC übertragen.\p"
    .string "Es wurde in \n"
    .string "BOX “{STR_VAR_1}” gelegt.$"

gText_PkmnTransferredLanettesPC::
    .string "{STR_VAR_2} wurde zu\n"
    .string "JEMANDES PC übertragen.\p"
    .string "Es wurde in \n"
    .string "BOX “{STR_VAR_1}” gelegt.$"

gText_PkmnTransferredSomeonesPCBoxFull::
    .string "BOX “{STR_VAR_3}” auf\n"
    .string "JEMANDES PC war voll.\p"
    .string "{STR_VAR_2} wurde zu\n"
    .string "BOX “{STR_VAR_1}” übertragen.$"

gText_PkmnTransferredLanettesPCBoxFull::
    .string "BOX “{STR_VAR_3}” auf\n"
    .string "JEMANDES PC war voll.\p"
    .string "{STR_VAR_2} wurde zu\n"
    .string "BOX “{STR_VAR_1}” übertragen.$"

gText_PkmnSentToPCAfterCatch::
    .string "{STR_VAR_2} wurde zu\n"
    .string "{B_PC_CREATOR_NAME} PC gesendet.\p"
    .string "Es wurde in \n"
    .string "BOX “{STR_VAR_1}” gelegt.$"

gText_NoMoreRoomForPokemon::
	.string "Es ist kein Platz mehr für POKéMON\n"
	.string "vorhanden!\p"
	.string "Die POKéMON BOXen sind voll und\n"
	.string "es kann kein POKéMON mehr\l"
	.string "abgelegt werden!$"

gText_NicknameThisPokemon::
	.string "Möchtest du{STR_VAR_1}einen\n"
	.string "Spitznamen geben?$"
