gText_PkmnAlreadyFullyHealed::
	.string "Hm? Was willst du schon wieder?\n"
	.string "Deine Pokémon sind alle kerngesund!\p"
	.string "Das wäre reine Energieverschwendung.\n"
	.string "Geh lieber trainieren!$"

gText_IllTakeYourPkmn::
	.string "Willkommen im Pokémon-Center!\p"
	.string "Ich kümmere mich sofort um deine\n"
	.string "Pokémon, einen Moment bitte.$"

gText_RestoredPkmnToFullHealth::
	.string "Danke für deine Geduld!\p"
	.string "Deine Pokémon sind wieder\n"
	.string "vollkommen gesund und munter.$"

gText_WeHopeToSeeYouAgain::
	.string "Wir hoffen, dich jederzeit wieder\n"
	.string "begrüßen zu dürfen!$"

gText_WelcomeCutShort::
	.string "Boah, du nervst.\p"
	.string "Gib her die Viecher, ich hab gleich\n"
	.string "Raucherpause.$"

gText_NoticesGoldCard::
	.string "Was glänzt da so widerlich?\n"
	.string "Ist das… Gold?!?\p"
	.string "Ein GOLDPASS?! Alter, wo hast du den\n"
	.string "geklaut? Das Ding ist ja echt!\p"
	.string "Normalerweise behandle ich Leute wie\n"
	.string "Dreck, aber bei dir mach ich eine\l"
	.string "Ausnahme, du Bonze!\p"
	.string "Okay, {PLAYER}, gib mir die Viecher.\n"
	.string "Ich hoffe, du gibst Trinkgeld!$"

gText_YouWantTheUsual::
	.string "Ah, der Geldsack {PLAYER} ist da!\n"
	.string "Das Übliche? Champagner und Kaviar?$"

gText_IllTakeYourPkmn2::
	.string "Ich fasse sie nur mit Samthandschuhen\n"
	.string "an, Eure Hoheit.$"

gText_ThankYouForWaiting::
	.string "Hier, besser als neu.$"

gText_WeHopeToSeeYouAgain2::
	.string "Komm bald wieder, Sugar Daddy!$"
