gText_WouldYouLikeToRestYourPkmn::
	.string "Willkommen im POKéMON-CENTER!\p"
	.string "Wir heilen deine POKéMON und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine POKéMON.$"

gText_IllTakeYourPkmn::
	.string "Okay, ich übernehme dein POKéMON\n"
	.string "für ein paar Sekunden.$"

gText_RestoredPkmnToFullHealth::
	.string "Danke!\p"
	.string "Deine POKéMON sind wieder topfit!$"

gText_WeHopeToSeeYouAgain::
	.string "Komm jederzeit wieder vorbei!$"

gText_WelcomeCutShort::
	.string "Willkommen im POKéMON-CENTER!\p"
	.string "Wir heilen deine POKéMON und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine POKéMON.$"

gText_NoticesGoldCard::
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"

gText_YouWantTheUsual::
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"

gText_IllTakeYourPkmn2::
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"

gText_ThankYouForWaiting::
	.string "Danke für's warten.$"

gText_WeHopeToSeeYouAgain2::
	.string "Komm jederzeit wieder vorbei!$"
