gText_WouldYouLikeToRestYourPkmn::
	.string "Willkommen im Wartezimmer des Todes.\p"
	.string "Deine POKéMON sehen aus wie Hackfleisch.\n"
	.string "Soll ich sie wieder zusammenflicken?$"

gText_IllTakeYourPkmn::
	.string "Gib her den Müll. Ich werf sie\n"
	.string "in die Mikrowelle.$"

gText_RestoredPkmnToFullHealth::
	.string "Fertig.\p"
	.string "Sie leben noch. Leider.$"

gText_WeHopeToSeeYouAgain::
	.string "Hau ab und lass dich nicht überfahren!$"

gText_WelcomeCutShort::
	.string "Boah, du nervst.\p"
	.string "Gib her die Viecher, ich hab gleich\n"
	.string "Raucherpause.$"

gText_NoticesGoldCard::
	.string "Was glänzt da so widerlich?\n"
	.string "Ist das… Gold?!?\p"
	.string "Ein GOLDPASS?! Alter, wo hast du den\n"
	.string "geklaut? Das Ding ist ja echt!\p"
	.string "Normalerweise behandle ich Leute wie\n"
	.string "Dreck, aber bei dir mach ich eine\l"
	.string "Ausnahme, du Bonze!\p"
	.string "Okay, {PLAYER}, gib mir die Viecher.\n"
	.string "Ich hoffe, du gibst Trinkgeld!$"

gText_YouWantTheUsual::
	.string "Ah, der Geldsack {PLAYER} ist da!\n"
	.string "Das Übliche? Champagner und Kaviar?$"

gText_IllTakeYourPkmn2::
	.string "Ich fasse sie nur mit Samthandschuhen\n"
	.string "an, Eure Hoheit.$"

gText_ThankYouForWaiting::
	.string "Hier, besser als neu.$"

gText_WeHopeToSeeYouAgain2::
	.string "Komm bald wieder, Sugar Daddy!$"
