Pokedude_Text_SpeedierBattlerGoesFirst::
	.string "POKé ASSI: Wer schneller zieht,\n"
	.string "lebt länger. Der Schnellere darf\l"
	.string "zuerst zuschlagen.$"

Pokedude_Text_MyRattataFasterThanPidgey::
	.string "Siehst du? Mein RATTFRATZ war\n"
	.string "schneller als das Tauben-Vieh.$"

Pokedude_Text_BattlersTakeTurnsAttacking::
	.string "Wir prügeln uns abwechselnd, bis\n"
	.string "einer blutet und die KP auf Null sind.$"

Pokedude_Text_MyRattataWonGetsEXP::
	.string "Mein RATTFRATZ hat den Gegner\n"
	.string "zerstört. Sieg!\p"
	.string "Wer überlebt, kriegt E.-Punkte.\n"
	.string "Das ist wie Erfahrung auf der Straße.\p"
	.string "Wenn ein POKéMON genug Punkte hat,\n"
	.string "levelt es auf.\p"
	.string "Dann wird es zur absoluten\n"
	.string "Kampfmaschine.$"

Pokedude_Text_UhOhRattataPoisoned::
	.string "POKé ASSI: Scheiße…\n"
	.string "Mein RATTFRATZ ist vergiftet…\p"
	.string "Das ist wie ’ne Überdosis.\n"
	.string "Es verliert dauerhaft KP.$"

Pokedude_Text_HealStatusRightAway::
	.string "Wenn dein Vieh krank ist, gib ihm\n"
	.string "Stoff. Heil es sofort, Mann!$"

Pokedude_Text_UsingItemTakesTurn::
	.string "Zeug einwerfen kostet aber Zeit.\n"
	.string "Eine Runde.\p"
	.string "Jetzt darf das Opfer zuschlagen!$"

Pokedude_Text_YayWeManagedToWin::
	.string "Boah!\n"
	.string "Gerade so überlebt!$"

Pokedude_Text_WaterNotVeryEffectiveAgainstGrass::
	.string "POKé ASSI: BLUBB ist eine\n"
	.string "WASSER-Attacke.\p"
	.string "Das MYRAPLA da drüben ist aber\n"
	.string "PFLANZE/GIFT.\p"
	.string "Die Pflanze säuft das Wasser einfach.\n"
	.string "Bringt nix.\p"
	.string "Halber Schaden. Das kratzt den\n"
	.string "Gegner kaum.$"

Pokedude_Text_GrassEffectiveAgainstWater::
	.string "Kacke, pass auf!\p"
	.string "ABSORBER ist eine PFLANZEN-Attacke.\p"
	.string "QUAPSEL ist ein WASSER-Pokémon.\p"
	.string "Pflanze gegen Wasser tut weh.\n"
	.string "Sehr effektiv. Doppelter Schmerz.$"

Pokedude_Text_LetsTryShiftingMons::
	.string "So gewinnen wir keinen Blumentopf…\p"
	.string "Ich wechsel das Vieh aus, bevor\n"
	.string "es verreckt!$"

Pokedude_Text_ShiftingUsesTurn::
	.string "Auswechseln kostet Zeit.\n"
	.string "Eine Runde.\p"
	.string "Jetzt ist der Gegner dran.$"

Pokedude_Text_ButterfreeDoubleResistsGrass::
	.string "SMETTBO ist KÄFER/FLUG.\p"
	.string "Gegen das Ding ist PFLANZE ein Witz…\p"
	.string "…KÄFER lacht über PFLANZE…\p"
	.string "…und FLUG scheißt auf PFLANZE.\p"
	.string "SMETTBO kriegt also nur ein Viertel\n"
	.string "vom Schaden. Fast gar nix.$"

Pokedude_Text_ButterfreeGoodAgainstOddish::
	.string "MYRAPLA ist PFLANZE/GIFT.\p"
	.string "Hau mit FLUG oder PSYCHO drauf.\n"
	.string "Das macht es fertig.\p"
	.string "Doppelter Schaden. Mach es kaputt!\p"
	.string "Los jetzt, gib ihm!$"

Pokedude_Text_YeahWeWon::
	.string "Bäääm!\n"
	.string "Zerstört!$"

Pokedude_Text_WeakenMonBeforeCatching::
	.string "POKé ASSI: Willst du fangen?\n"
	.string "Wirf nicht gleich den Ball, Idiot.\p"
	.string "Erst weichklopfen.\n"
	.string "Brich ihm ein paar Knochen (KP runter).$"

Pokedude_Text_BestIfTargetStatused::
	.string "Okay, es blutet genug.\p"
	.string "Aber wenn du sicher gehen willst,\n"
	.string "setz es unter Drogen.\p"
	.string "Schlaf oder Paralyse.\n"
	.string "Dann wehrt es sich nicht mehr.$"

Pokedude_Text_CantDoubleUpOnStatus::
	.string "So kriegst du es in den Sack!\p"
	.string "Ach ja. Nur eine Krankheit auf einmal.\n"
	.string "Nicht gierig werden.\p"
	.string "Schlaf UND Paralyse geht nicht.\n"
	.string "Kapiert?$"

Pokedude_Text_LetMeThrowBall::
	.string "Alles klar!\n"
	.string "Jetzt gehört es mir!$"

Pokedude_Text_PickBestKindOfBall::
	.string "Bevor du wirfst:\n"
	.string "Nimm nicht den billigsten Ball für\l"
	.string "die harten Brocken. Denk nach!$"
