gBirchDexRatingText_AreYouCurious::
	.string "PROF. BIRK: Ah, {PLAYER}{KUN}!\p"
	.string "Na, du kleiner Lauch?\n"
	.string "Zeig mal deinen POKéDEX. Ist bestimmt\l"
	.string "genauso leer wie dein Kopf.$"

gBirchDexRatingText_Cancel::
	.string "War ja klar.\n"
	.string "Du schämst dich für dein Versagen.\l"
	.string "Geh mir aus den Augen.$"

gBirchDexRatingText_SoYouveSeenAndCaught::
	.string "Lass mal sehen…\p"
	.string "Aha. {STR_VAR_1} gesehen.\n"
	.string "Und {STR_VAR_2} gefangen…\p"
	.string "Das ist deine Ausbeute? Echt jetzt?$"

gBirchDexRatingText_LessThan10::
	.string "Bist du blind oder einfach nur faul?\n"
	.string "Geh ins Gras, du Opfer!\l"
	.string "Die Viecher beißen nicht. Meistens.$"

gBirchDexRatingText_LessThan20::
	.string "Wow, zweistellig. Applaus.\n"
	.string "Sogar ein Taubsi hat mehr Hirn als\l"
	.string "du beim Suchen.$"

gBirchDexRatingText_LessThan30::
	.string "Du läufst immer nur im Kreis, oder?\n"
	.string "Beweg deinen Arsch mal in andere\l"
	.string "Gebiete, sonst wird das nie was.$"

gBirchDexRatingText_LessThan40::
	.string "Es sieht langsam nicht mehr aus wie\n"
	.string "ein Malbuch für Dreijährige.\l"
	.string "Aber gut ist anders.$"

gBirchDexRatingText_LessThan50::
	.string "Die Hälfte von Hundert.\n"
	.string "Du bist der Durchschnitt. Mittelmaß.\l"
	.string "Langweilig.$"

gBirchDexRatingText_LessThan60::
	.string "Hast du Angst vor Wasser?\n"
	.string "Benutz eine ANGEL, du Landratte!\l"
	.string "Oder stinkst du zu sehr für Fische?$"

gBirchDexRatingText_LessThan70::
	.string "Deine Pokémon entwickeln sich nicht?\n"
	.string "Vielleicht weil du ein schlechter\l"
	.string "TRAINER bist. Denk mal drüber nach.$"

gBirchDexRatingText_LessThan80::
	.string "Langsam wird’s was.\n"
	.string "Vielleicht bist du doch kein\l"
	.string "hoffnungsloser Fall.$"

gBirchDexRatingText_LessThan90::
	.string "Du hast kein Privatleben, oder?\n"
	.string "So viele Viecher…\l"
	.string "Geh mal duschen.$"

gBirchDexRatingText_LessThan100::
	.string "Geh in die SAFARI-ZONE.\n"
	.string "Ach ne, Eintritt kostet Geld, was?\l"
	.string "Geh schnorren und dann fang was!$"

gBirchDexRatingText_LessThan110::
	.string "Über 100.\n"
	.string "Du bist offiziell süchtig.\p"
	.string "Deine Eltern machen sich sicher\n"
	.string "Sorgen um dich.$"

gBirchDexRatingText_LessThan120::
	.string "Hau mal Steine kaputt mit\n"
	.string "ZERTRÜMMERER.\l"
	.string "Randale machen kannst du doch, oder?$"

gBirchDexRatingText_LessThan130::
	.string "Tausch doch mal mit Freunden.\n"
	.string "Oh… warte.\l"
	.string "Du hast keine Freunde, stimmt’s?$"

gBirchDexRatingText_LessThan140::
	.string "Manche entwickeln sich nur durch Liebe.\n"
	.string "Kein Wunder, dass dein POKéDEX\l"
	.string "Lücken hat. Dich liebt keiner.$"

gBirchDexRatingText_LessThan150::
	.string "HOENN ist voll mit Ungeziefer.\n"
	.string "Und du sammelst es auch noch.\l"
	.string "Ekelhaft.$"

gBirchDexRatingText_LessThan160::
	.string "Manchmal gibt es Massen-Ausbrüche.\n"
	.string "Wie bei der Pest.\l"
	.string "Verpass das nicht.$"

gBirchDexRatingText_LessThan170::
	.string "Du stalkst die Pokémon ganz schön gut.\n"
	.string "Hast du das bei deinem Ex auch\l"
	.string "gemacht? Gruselig.$"

gBirchDexRatingText_LessThan180::
	.string "Willst du meinen Job?\n"
	.string "Vergiss es.\l"
	.string "Ich bin der Prof hier, du Wicht.$"

gBirchDexRatingText_LessThan190::
	.string "Du bist ein Nerd.\n"
	.string "Ein richtiger, schwitzender Nerd.\l"
	.string "Respekt? Nein, Mitleid.$"

gBirchDexRatingText_LessThan200::
	.string "Fast fertig.\n"
	.string "Deine Zwangsstörung kickt richtig\l"
	.string "rein, was?$"

gBirchDexRatingText_DexCompleted::
	.string "Scheiße, du hast ihn voll.\n"
	.string "Und jetzt? Fühlst du dich besser?\p"
	.string "Du hast dein Leben verschwendet für\n"
	.string "eine digitale Liste. Glückwunsch.$"

gBirchDexRatingText_OnANationwideBasis::
	.string "Hmhm…\n"
	.string "Auf nationaler Ebene…\p"
	.string "hast du {STR_VAR_1} gesehen\n"
	.string "und {STR_VAR_2} gefangen…\p"
	.string "Es hört nie auf, was? Du armes Schwein.$"

@ FRLG

PokedexRating_Text_HowIsPokedexComingAlong::
	.string "EICH: Yo, was geht!\n"
	.string "Wie läuft's mit dem Pokédex, Digga?\p"
	.string "Hier, zeig mal her den Lachs!$"

PokedexRating_Text_SeenXOwnedY::
	.string "So sieht's aktuell bei dir aus, Bro:\p"
	.string "{STR_VAR_1} Pokémon abgecheckt und\n"
	.string "{STR_VAR_2} Pokémon eingesteckt.\p"
	.string "{FONT_NORMAL}PROF. EICHs Rating:$"

PokedexRating_Text_LessThan10::
	.string "Bruder, da geht noch was.\p"
	.string "Geh mal ins hohe Gras und\n"
	.string "hustle für mehr Pokémon!$"

PokedexRating_Text_LessThan20::
	.string "Läuft bei dir, Diggi!\p"
	.string "Hab nem ASSISTENTEN die VM BLITZ\n"
	.string "gegeben. Gönn dir die mal!$"

PokedexRating_Text_LessThan30::
	.string "Dein Pokédex ist noch bisschen\n"
	.string "cringe, Bro!\p"
	.string "Fang mal paar andere Pokémon!$"

PokedexRating_Text_LessThan40::
	.string "Ey, man sieht, du schwitzt richtig\n"
	.string "rein!\p"
	.string "Hab nem ASSISTENTEN den DETEKTOR\n"
	.string "gegeben. Hol dir das Teil!$"

PokedexRating_Text_LessThan50::
	.string "Dein Pokédex wird langsam wild!\p"
	.string "Ein ASSISTENT hat das MÜNZAMULETT\n"
	.string "für dich. Mach Cash damit!$"

PokedexRating_Text_LessThan60::
	.string "Krass, 50 Arten geknackt!\p"
	.string "Ein ASSISTENT chillt mit nem\n"
	.string "EP-TEILER. Schnapp ihn dir!$"

PokedexRating_Text_LessThan70::
	.string "Uff! Das wird langsam ein echt\n"
	.string "stabiler Pokédex!$"

PokedexRating_Text_LessThan80::
	.string "Mashallah, sehr geil!\p"
	.string "Schmeiß mal ne Angel aus,\n"
	.string "dann kriegst du noch mehr Pokémon!$"

PokedexRating_Text_LessThan90::
	.string "Heftig! Du bist so ein richtiger\n"
	.string "Loot-Goblin, oder?$"

PokedexRating_Text_LessThan100::
	.string "Bin baff, no cap!\n"
	.string "Das war safe mies anstrengend!$"

PokedexRating_Text_LessThan110::
	.string "100 Arten! Geisteskrank,\n"
	.string "wie du ablieferst!$"

PokedexRating_Text_LessThan120::
	.string "Du hast sogar die ganzen\n"
	.string "Entwicklungen? Sick!$"

PokedexRating_Text_LessThan130::
	.string "Baba! Tausch bisschen mit den\n"
	.string "Zuhausis für noch mehr!$"

PokedexRating_Text_LessThan140::
	.string "Endlevel!\n"
	.string "Du bist echt ein Macher geworden!$"

PokedexRating_Text_LessThan150::
	.string "Wallah, mir fehlen die Worte!\n"
	.string "Du bist jetzt der wahre PROFESSOR!$"

PokedexRating_Text_Complete::
	.string "Dein Pokédex ist 100% durch!\n"
	.string "GG, mein Bester!!$"

PokedexRating_Text_NationalDexSeenXOwnedY::
	.string "Und dein NATIONALER Pokédex sagt:\p"
	.string "{STR_VAR_1} Pokémon abgecheckt und\n"
	.string "{STR_VAR_2} Pokémon eingesteckt.$"

PokedexRating_Text_LookForwardToFilledNationalDex::
	.string "Bin hyped zu sehen, wie du den\n"
	.string "NATIONALEN Pokédex rasierst!$"

PokedexRating_Text_YouveCompletedDex::
	.string "Diggi, endlich...\p"
	.string "Du hast den Pokédex komplett\n"
	.string "durchgespielt!\p"
	.string "Einfach wild!\n"
	.string "Was für ein krasser Flex!$"

PokedexRating_Text_Wroooaaarrr::
	.string "Wroooooooaaaaaarrrr!$"

PokedexRating_Text_ThankYouMadeDreamReality::
	.string "Ehrenmann, {PLAYER}!\n"
	.string "Kuss auf's Auge, danke!\l"
	.string "Du hast meinen Traum wahr gemacht!$"

PokedexRating_Text_LoveSeeingYourPokedex::
	.string "EICH: Yo, was geht!\p"
	.string "Sag mal, wie läuft's mit deinem\n"
	.string "Pokédex?\p"
	.string "Wahaha!\p"
	.string "Ich weiß es eh schon, aber\n"
	.string "ich feier das einfach extrem!\p"
	.string "Lass mal gucken...$"
