Text_MayIHelpYou::
    .string "Hallo, da!\n"
    .string "Kann ich dir helfen?$"

Text_FillOutQuestionnaire::
    .string "Es gibt einen Fragebogen.\n"
    .string "Möchtest du ihn ausfüllen?$"

Text_QuestionnaireThankYou::
    .string "Vielen Dank, dass du dir die Zeit\n"
    .string "genommen hast, unseren Fragebogen\l"
    .string "auszufüllen.\p"
    .string "Dein Feedback wird für zukünftige\n"
    .string "Referenzen verwendet.$"

Text_YouKnowThoseWords::
    .string "Oh, hallo!\n"
    .string "Du kennst diese Wörter?\p"
    .string "Das bedeutet, du weißt über das\n"
    .string "GEHEIMNISVOLLE GESCHENK Bescheid.\p"
    .string "Ab jetzt solltest du\n"
    .string "GEHEIMNISVOLLE GESCHENKE erhalten!$"

Text_YouCanAccessMysteryGift::
    .string "Sobald du dein Spiel speicherst,\n"
    .stirng "kannst du auf das\l"
    .string "GEHEIMNISVOLLE GESCHENK zugreifen.$"

Text_ThankYouForAccessingMysteryGift::
    .string "Vielen Dank für den Zugriff auf das\n"
    .string "GEHEIMNISVOLLE GESCHENK-System.$"
