Questionnaire_Text_FillOut::
	.string "Hier liegt ein Fragebogen rum.\n"
	.string "Willst du deine wertlose Meinung kundtun?$"

Questionnaire_Text_ThankYou::
	.string "Danke, dass du meine Zeit verschwendet hast.\n"
	.string "Dein Feedback landet direkt im Müll.\l"
	.string "Wir hassen Kunden.$"

Questionnaire_Text_YouKnowThoseWordsGift::
	.string "Oh, guck an!\n"
	.string "Du kennst die geheimen Worte?\p"
	.string "Du bist bestimmt so ein dreckiger Cheater.\n"
	.string "Egal, du kriegst dein\l"
	.string "GEHEIMNISVOLLES GESCHENK.$"

Questionnaire_Text_YouCanAccessMysteryGift::
	.string "Speicher dein Spiel, du Lauch.\n"
	.string "Dann kannst du den Kram benutzen.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
	.string "Was glotzt du?\n"
	.string "Du kennst die Worte?\p"
	.string "Du bist tief im kriminellen Sumpf,\n"
	.string "was? Das GEHEIMNISVOLLE EVENT ist offen.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
	.string "Speicher ab und verschwinde.\n"
	.string "Dann hast du deinen Willen.$"

MysteryGift_Text_TheresATicketForYou::
	.string "Endlich hab ich dich gefunden, {PLAYER}.\n"
	.string "Du hast dich gut versteckt, du Ratte.\p"
	.string "Hier, nimm den Wisch und lass mich in Ruhe.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
	.string "Geh damit zum Hafen von GRAPHITPORT CITY.\p"
	.string "Und komm bloß nicht zurück,\n"
	.string "wenn es eine Falle ist.$"
