Questionnaire_Text_FillOut::
    .string "Es gibt einen Fragebogen.\n"
    .string "Möchtest du ihn ausfüllen?$"

Questionnaire_Text_ThankYou::
    .string "Vielen Dank, dass du dir die Zeit\n"
    .string "genommen hast, unseren Fragebogen\l"
    .string "auszufüllen.\p"
    .string "Dein Feedback wird für zukünftige\n"
    .string "Referenzen verwendet.$"

Questionnaire_Text_YouKnowThoseWordsGift::
    .string "Oh, hallo!\n"
    .string "Du kennst diese Worte?\p"
    .string "Das bedeutet, du weißt über das\n"
    .string "GEHEIMNISVOLLE GESCHENK Bescheid.\p"
    .string "Ab jetzt solltest du\n"
    .string "GEHEIMNISVOLLE GESCHENKE erhalten!$"

Questionnaire_Text_YouCanAccessMysteryGift::
    .string "Sobald du dein Spiel speicherst,\n"
    .string "kannst du das\l"
    .string "GEHEIMNISVOLLE GESCHENK nutzen.$"

Questionnaire_Text_YouKnowThoseWordsEvent::
    .string "Oh, hallo!\n"
    .string "Du kennst diese Worte?\p"
    .string "Das bedeutet, du weißt über das\n"
    .string "GEHEIMNISVOLLE EVENT Bescheid.$"

Questionnaire_Text_YouCanAccessMysteryEvent::
    .string "Sobald du dein Spiel speicherst,\n"
    .string "kannst du das\l"
    .string "GEHEIMNISVOLLE GESCHENK nutzen.$"

MysteryGift_Text_TheresATicketForYou::
    .string "Danke, dass du das GEHEIMNISVOLLE\n"
    .string "EVENT-System benutzt hast.\p"
    .string "Du musst {PLAYER} sein.\n"
    .string "Hier ist ein Ticket für dich.$"

MysteryGift_Text_TryUsingItAtLilycovePort::
    .string "Es scheint für den Gebrauch am\n"
    .string "Hafen von GRAPHITPORT CITY zu sein.\p"
    .string "Probier es doch mal aus und schau,\n"
    .string "worum es geht!$"
