Text_OnlySkilledTrainersAllowedThrough::
	.string "Nur echte Macher dürfen hier durch.\p"
	.string "Du hast den {STR_VAR_1}\n"
	.string "nicht. Verpiss dich, du Lauch!$"

Text_CantLetYouPass::
	.string "Regeln sind Regeln.\n"
	.string "Ich lass dich nicht durch, Spast.$"

Text_OhThatsBadgeGoRightAhead::
	.string "Oh! Das ist der {STR_VAR_1}!\n"
	.string "Na endlich. Geh durch.$"

Text_OnlyPassWithBadgeDontHaveYet::
	.string "Hier kommst du nur rein, wenn du\n"
	.string "den {STR_VAR_1} hast.\p"
	.string "Du hast den {STR_VAR_1}\n"
	.string "nicht, du Versager.\p"
	.string "Ohne den kommst du nicht zur LIGA.\n"
	.string "Geh nach Hause zu Mami.$"

Text_OnlyPassWithBadgeOhGoAhead::
	.string "Hier kommst du nur rein, wenn du\n"
	.string "den {STR_VAR_1} hast.\p"
	.string "Oh! Das ist der {STR_VAR_1}!{PAUSE_MUSIC}{PLAY_BGM}{MUS_LEVEL_UP}{PAUSE 0x60}{RESUME_MUSIC}\p"
	.string "Okay, nicht schlecht.\n"
	.string "Mach, dass du weiterkommst.$"
