	.align 2
gText_ConfirmSave::
	.string "Möchtest du das Spiel speichern?$"

gText_AlreadySavedFile::
	.string "Es gibt bereits einen Spielstand.\n"
	.string "Willst du ihn überschreiben?$"

gText_SavingDontTurnOff::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"

gText_PlayerSavedGame::
	.string "{PLAYER}hat das Spiel gespeichert.$"

gText_DifferentSaveFile::
	.string "WARNING!\p"
	.string "There is a different game file that\n"
	.string "is already saved.\p"
	.string "If you save now, the other file's\n"
	.string "adventure, including items and\l"
	.string "POKéMON, will be entirely lost.\p"
	.string "Are you sure you want to save now\n"
	.string "and overwrite the other save file?$"

gText_SaveError::
	.string "Speicherfehler.\p"
	.string "Bitte wechsel die Batterie.$"

gText_SavingDontTurnOffPower::
	.string "SAVING…\n"
	.string "DON'T TURN OFF THE POWER.$"
