	.align 2
gText_ConfirmSave::
    .string "Möchtest du das Spiel speichern?$"

gText_AlreadySavedFile::
    .string "Es gibt bereits eine gespeicherte Datei.\n"
    .string "Möchtest du sie überschreiben?$"

gText_SavingDontTurnOff::
    .string "SPEICHERN…\n"
    .string "SCHALTE DAS GERÄT NICHT AUS.$"

gText_PlayerSavedGame::
    .string "{PLAYER} hat das Spiel gespeichert.$"

gText_DifferentSaveFile::
    .string "WARNUNG!\p"
    .string "Es existiert bereits eine andere\n"
    .string "Spielstand-Datei.\p"
    .string "Wenn du jetzt speicherst, wird das\n"
    .string "andere Abenteuer, inklusive Items und\l"
    .string "POKéMON, komplett gelöscht.\p"
    .string "Bist du sicher, dass du jetzt speichern\n"
    .string "und die andere Datei überschreiben willst?$"

gText_SaveError::
    .string "Speicherfehler.\p"
    .string "Bitte tausche den\n"
    .string "Backup-Speicher.$"

gText_SavingDontTurnOffPower::
    .string "SPEICHERN…\n"
    .string "SCHALTE DAS GERÄT NICHT AUS.$"
