	.align 2
gText_ConfirmSave::
	.string "Möchtest du das Spiel speichern?$"

gText_AlreadySavedFile::
	.string "Es gibt bereits einen Spielstand.\n"
	.string "Willst du ihn überschreiben?$"

gText_SavingDontTurnOff::
	.string "Speichern…\n"
	.string "SCHALTE DAS GERÄT NICHT AUS.$"

gText_PlayerSavedGame::
	.string "{PLAYER} hat das Spiel gespeichert.$"

gText_DifferentSaveFile::
	.string "WARNUNG!\p"
	.string "Es gibt bereits ein anderen Spielstand.\p"
	.string "Wenn du jetzt Speicherst, wird der\n"
	.string "vorherige Spielstand vollständig\l"
	.string "verloren gehen.\p"
	.string "Bist du Sicher, dass du dies tun willst?$"

gText_SaveError::
	.string "Speicherfehler.\p"
	.string "Bitte wechsel die Batterie.$"

gText_SavingDontTurnOffPower::
	.string "Speichern…\n"
	.string "SCHALTE DAS GERÄT NICHT AUS.$"
