@ For the NPC in Pallet Town that talks about the Trainer Tips sign

PalletTown_Text_HmmIsThatRight::
	.string "Hmm…\n"
	.string "Das sind zu viele Buchstaben…$"

PalletTown_Text_OhLookLook::
	.string "Ey!\n"
	.string "Guck dir den Scheiß an!$"

PalletTown_Text_ReadItReadIt::
	.string "Lies das! Sofort!\n"
	.string "Bevor ich ausraste!$"

@ Used by sign
PalletTown_Text_PressStartToOpenMenu::
	.string "TRAINER TIPPS FÜR LAPPEN\p"
	.string "Drück START, um das MENÜ zu öffnen!\n"
	.string "Hoffentlich findest du den Knopf.$"

PalletTown_Text_SignsAreUsefulArentThey::
	.string "Schilder sind nützlich, oder?\n"
	.string "Man kann dagegen treten.$"

PalletTown_Text_LookCopiedTrainerTipsSign::
	.string "Guck mal, guck mal!\p"
	.string "Ich hab den Text abgeschrieben.\n"
	.string "Ich kann schreiben! Staun, du Opfer!$"

@ Used by NPC
PalletTown_Text_PressStartToOpenMenuCopy::
	.string "TRAINER TIPPS!\p"
	.string "Drück START für das MENÜ!\n"
	.string "Hast du das kapiert?!$"
