LilycoveCity_ContestLobby_Text_InterviewRequest:
	.string "Oh, moin! Du warst grad bei so 'nem\n"
	.string "WETTBEWERB auf der Bühne, oder?\l"
	.string "Man sieht's an deinem armen POKéMON.\p"
	.string "Ich bin Reporter. Ich such nach krassen\n"
	.string "Storys für's Fernsehen.\p"
	.string "Haste mal 'ne Minute für 'n kurzes\n"
	.string "Interview, oder musst du weg?$"

LilycoveCity_ContestLobby_Text_DescribeContest:
	.string "Echt jetzt?\n"
	.string "Korrekt von dir.\p"
	.string "Also, pack aus: Wie war der WETTBEWERB\n"
	.string "grad so für dich?$"

LilycoveCity_ContestLobby_Text_WhatImageWhenYouHearX:
	.string "Ah, check ich.\n"
	.string "Echt 'ne tiefgründige Ansage.\p"
	.string "Man merkt voll, wie du den WETTBEWERB\n"
	.string "gefühlt hast.\p"
	.string "Eine letzte Frage noch, Digga.\p"
	.string "Wenn du “{STR_VAR_2}“ hörst,\n"
	.string "was für'n Bild hast du da im Kopf?$"

LilycoveCity_ContestLobby_Text_ThatsAllForInterview:
	.string "Krass!\p"
	.string "So stellst du dir also das Konzept\n"
	.string "von “{STR_VAR_2}“ vor.\p"
	.string "Fetten Dank!\n"
	.string "Hast mir echt geilen Scheiß geliefert.\p"
	.string "Daraus bastel ich locker 'ne Story,\n"
	.string "die richtig Klicks zieht.\p"
	.string "Vielleicht läuft die Kacke sogar im TV!\n"
	.string "Zieh's dir rein, wenn's soweit ist!$"

LilycoveCity_ContestLobby_Text_PleaseDoShareStoryWithMe:
	.string "Oh, mieser Abturn...\p"
	.string "Naja, wenn du mal 'ne geile Story hast,\n"
	.string "meld dich bei mir, ja?$"

LilycoveCity_ContestLobby_Text_LookingForwardToNextContest:
	.string "Ich behalt dich beim nächsten\n"
	.string "WETTBEWERB im Auge!$"

gTVBravoTrainerText00::
	.string "Yeah!\n"
	.string "Es ist BRAVO-TRAINER-Zeit, Bitches!\p"
	.string "Heute stalken wir ein POKéMON,\n"
	.string "das{STR_VAR_1}gehört.\p"
	.string "Dieses Vieh prahlt mit 'nem{STR_VAR_3}\n"
	.string "Rang in der Kategorie{STR_VAR_2}!$"

gTVBravoTrainerText01::
	.string "Macht Lärm für{STR_VAR_2},\n"
	.string "das{STR_VAR_1}!\p"
	.string "Der Spitzname{STR_VAR_2}...\p"
	.string "Da schreit echt alles nach\n"
	.string "“{STR_VAR_3}“!$"

gTVBravoTrainerText02::
	.string "Als der TRAINER{STR_VAR_1}\n"
	.string "sein POKéMON in den Ring geschickt hat,\l"
	.string "haben wir ihm direkt 'n Mikro unter die\l"
	.string "Nase gehalten!$"

gTVBravoTrainerText03::
	.string "Nach dem WETTBEWERB gefragt,\n"
	.string "grinst{STR_VAR_1}wie'n Honigkuchenpferd\l"
	.string "und meint: “{STR_VAR_2}!“\p"
	.string "Klar, das POKéMON von{STR_VAR_1}ist ja auch\n"
	.string "auf Platz{STR_VAR_3}gelandet.\p"
	.string "Der Spruch passt gerade echt wie die\n"
	.string "Faust aufs Auge zu{STR_VAR_1}!$"

gTVBravoTrainerText04::
	.string "Nach dem WETTBEWERB gefragt,\n"
	.string "murmelt{STR_VAR_1}richtig abgefuckt:\l"
	.string "“{STR_VAR_2}.“\p"
	.string "Klar, das POKéMON von{STR_VAR_1}hat ja auch\n"
	.string "nur Platz{STR_VAR_3}gemacht.\p"
	.string "Man merkt{STR_VAR_1}den puren\n"
	.string "Hass an, würd ich mal sagen!$"

gTVBravoTrainerText05::
	.string "Wollt ihr nicht auch wissen, was\n"
	.string "{STR_VAR_1}mit{STR_VAR_2}verbindet?\p"
	.string "Klar wollt ihr das!\n"
	.string "Also haben wir nachgebohrt!\p"
	.string "Die Antwort kurz und knackig:\n"
	.string "“{STR_VAR_3}!“\p"
	.string "Das ist also{STR_VAR_2}\n"
	.string "in den Augen von{STR_VAR_1}!$"

gTVBravoTrainerText06::
	.string "Die letzte Attacke{STR_VAR_2}von\n"
	.string "{STR_VAR_1}war einfach nur\l"
	.string "“{STR_VAR_3}“ pur!$"

gTVBravoTrainerText07::
	.string "Geiler Scheiß,{STR_VAR_1}!\n"
	.string "Geiler Scheiß,{STR_VAR_2}!\p"
	.string "Hoffentlich sehen wir{STR_VAR_1}\n"
	.string "bald noch weiter oben mitmischen!\p"
	.string "Das war's für heute, ihr Opfer!\n"
	.string "Haut rein bis zum nächsten Mal!$"

gTVBravoTrainerText08::
	.string "Hier ist{STR_VAR_1}vom TRAINER!$"

BattleFrontier_BattleTowerLobby_Text_InterviewRequest::
	.string "Ey! Du bist der TRAINER, der sich\n"
	.string "grad geboxt hat, oder?\p"
	.string "Ich sammel hier Interviews von Leuten,\n"
	.string "die was auf'm Kasten haben.\p"
	.string "Wie sieht's aus, hast du 'n paar\n"
	.string "Worte zu deinem Kampf für uns?$"

BattleFrontier_BattleTowerLobby_Text_HowDidBattleTowerTurnOut::
	.string "Echt jetzt?\n"
	.string "Geil, danke!\l"
	.string "Also, pass auf...\p"
	.string "Wie lief's heute für dich im\n"
	.string "DUELLTURM?\p"
	.string "Bist du zufrieden, oder hast du\n"
	.string "komplett reingeschissen?$"

BattleFrontier_BattleTowerLobby_Text_SorryWeDisturbedYou::
	.string "Oh...\n"
	.string "Sorry, dass ich genervt hab.\p"
	.string "Aber beim nächsten DUELLTURM-Besuch\n"
	.string "bist du fällig für'n Interview!$"

BattleFrontier_BattleTowerLobby_Text_ObviousYouHadGreatBattle::
	.string "Hab ich's mir doch gedacht!\p"
	.string "So wie du grinst...\p"
	.string "Da sieht man sofort, dass du jemanden\n"
	.string "komplett rasiert hast.$"

BattleFrontier_BattleTowerLobby_Text_DifficultToMakeBattleTurnOutAsPlanned::
	.string "Oh, mies...\p"
	.string "Ist halt echt nicht einfach, wenn der\n"
	.string "Gegner keinen Bock hat zu verlieren.$"

BattleFrontier_BattleTowerLobby_Text_DescribeYourBattle::
	.string "Ey, warte mal, eine Frage noch!\p"
	.string "Wenn du den Kampf mit nur einem\n"
	.string "einzigen Spruch beschreiben müsstest...\l"
	.string "Was würdest du raushauen?$"

BattleFrontier_BattleTowerLobby_Text_ThatsGreatLine::
	.string "Wow, das ist ja mal ne Ansage!\p"
	.string "Richtig geiler Spruch!\n"
	.string "Hoffentlich rasierst du nächstes Mal auch.\p"
	.string "Man sieht sich!$"

BattleFrontier_BattleTowerLobby_Text_SilentType::
	.string "Oh, verstehe...\p"
	.string "Einfach mal die Fresse halten hat ja\n"
	.string "auch irgendwie Stil, ne?\p"
	.string "Beim nächsten Mal quetsch ich aber\n"
	.string "was aus dir raus!$"

BattleFrontier_BattleTowerLobby_Text_LookingForwardToNextBattle::
	.string "Ich bin schon heiß auf deinen\n"
	.string "nächsten Kampf!$"

BravoTrainerBattleTower_Text_Intro::
	.string "Yeah!\n"
	.string "Es ist BRAVO-TRAINER-Zeit!\p"
	.string "Heute stalken wir{STR_VAR_1}, der\n"
	.string "den DUELLTURM rasiert hat!\p"
	.string "Dafür hat{STR_VAR_1}das miese\n"
	.string "{STR_VAR_2}in den Ring geschickt!$"

BravoTrainerBattleTower_Text_NewRecord::
	.string "Das Duo hat 'nen neuen Rekord von\n"
	.string "{STR_VAR_2}Siegen am Stück in der\l"
	.string "{STR_VAR_1}-Klasse aufgestellt!\l"
	.string "Kranker Scheiß, TRAINER!$"

BravoTrainerBattleTower_Text_Lost::
	.string "Am Ende gab's für das Duo in Match\n"
	.string "Nummer{STR_VAR_2}von{STR_VAR_1}voll\l"
	.string "auf die Fresse. Naja, netter Versuch!\p"
	.string "Aber ey, so früh schon auf{STR_VAR_1}\n"
	.string "zu treffen, ist auch mieses Pech.\p"
	.string "Wir haben mal gefragt, wie sich die\n"
	.string "Klatsche gegen{STR_VAR_1}angefühlt hat.$"

BravoTrainerBattleTower_Text_Won::
	.string "Die beiden haben das Ding gerockt und\n"
	.string "das{STR_VAR_2}von{STR_VAR_1}zerlegt.\l"
	.string "Respekt, TRAINER!\p"
	.string "Einfach mal{STR_VAR_1}weggeklatscht...\n"
	.string "Man glaubt es kaum! Einfach brutal!\p"
	.string "Wir haben den TRAINER zu diesem\n"
	.string "geilen Moment interviewt.$"

BravoTrainerBattleTower_Text_LostFinal::
	.string "Nach 'ner fetten Siegesserie gab's am\n"
	.string "Ende von{STR_VAR_1}s{STR_VAR_2}\l"
	.string "voll aufs Maul.\p"
	.string "Trotzdem geil gespielt!\p"
	.string "Muss man ja auch erstmal schaffen.\n"
	.string "So Legenden wie{STR_VAR_1}und{STR_VAR_2}\l"
	.string "sieht man nicht alle Tage.\p"
	.string "Wir haben gefragt, wie es war, gegen\n"
	.string "diese VIPs abzukacken.$"

BravoTrainerBattleTower_Text_Satisfied::
	.string "Der TRAINER hat nur das hier zu sagen:\n"
	.string "“Ich bin echt zufrieden!“\p"
	.string "Ist das nicht mal 'ne Ansage?\n"
	.string "Mega, TRAINER!\p"
	.string "Gibt nix Geileres, als nach 'nem Kampf\n"
	.string "so richtig befriedigt zu sein, oder?\p"
	.string "Wie befriedigt der TRAINER genau war,\n"
	.string "hab ich gemerkt, als der Spruch kam:$"

BravoTrainerBattleTower_Text_Unsatisfied::
	.string "Der TRAINER hatte Folgendes zu meckern:\n"
	.string "“Ich bin gar nicht zufrieden...“\p"
	.string "Da war wohl jemand richtig angepisst,\n"
	.string "als das rauskam.\p"
	.string "Ist halt auch schwer, immer den\n"
	.string "perfekten Kampf abzuliefern, ne?\p"
	.string "Wie hart der Abturn war, hab ich an\n"
	.string "diesem Spruch gemerkt:$"

BravoTrainerBattleTower_Text_None1::
	.string "Keins$"

BravoTrainerBattleTower_Text_None2::
	.string "Keins$"

BravoTrainerBattleTower_Text_None3::
	.string "Keins$"

BravoTrainerBattleTower_Text_None4::
	.string "Keins$"

BravoTrainerBattleTower_Text_Response::
	.string "“{STR_VAR_1}.“$"

BravoTrainerBattleTower_Text_ResponseSatisfied::
	.string "“{STR_VAR_1}.“\n"
	.string "Ist das nicht geil?\p"
	.string "Das zeigt so richtig die Freude\n"
	.string "von{STR_VAR_2}, würd ich sagen.\p"
	.string "Dieser Kampf mit{STR_VAR_3}am Ende...\n"
	.string "Das war einfach nur “{STR_VAR_1}“!$"

BravoTrainerBattleTower_Text_ResponseUnsatisfied::
	.string "“{STR_VAR_1}.“\n"
	.string "Passt doch perfekt, oder?\p"
	.string "Dieser Kampf mit{STR_VAR_3}am Ende...\n"
	.string "Das war einfach komplette “{STR_VAR_1}“!\p"
	.string "Da merkt man richtig den Hass von\n"
	.string "{STR_VAR_2}, würd ich mal behaupten!$"

BravoTrainerBattleTower_Text_Outro::
	.string "Applaus für{STR_VAR_1}!\n"
	.string "Applaus für{STR_VAR_2}!\p"
	.string "Ich hoffe, wir sehen{STR_VAR_1}\n"
	.string "bald noch mehr Leute wegklatschen!\p"
	.string "Das war's für heute, Leute!\n"
	.string "Bis zum nächsten Mal, haut rein!$"

SlateportCity_PokemonFanClub_Text_InterviewRequestHasName:
	.string "Wow!\p"
	.string "Man sieht echt sofort, dass du dein\n"
	.string "{STR_VAR_1}mega verhätschelst.\p"
	.string "Also, es heißt{STR_VAR_2}.\p"
	.string "Kann ich dich mal kurz was fragen?\p"
	.string "Ich bin vom Fernsehen und mach grad\n"
	.string "so 'ne Umfrage über POKéMON.\p"
	.string "Hättest du Bock, mir ein paar kurze\n"
	.string "Fragen zu beantworten?$"

SlateportCity_PokemonFanClub_Text_HereGoesQuickAnswers:
	.string "Geil! Danke dir!\p"
	.string "Okay, los geht's.\n"
	.string "Brauche nur kurze Antworten, okay?$"

SlateportCity_PokemonFanClub_Text_DescribeFeelingsFirstMetMon:
	.string "Als du{STR_VAR_1}zum ersten Mal\n"
	.string "gesehen hast, was hast du da gefühlt?\p"
	.string "Hau mal raus, wie war das damals so?$"

SlateportCity_PokemonFanClub_Text_LikenMonToSomethingYouLike:
	.string "Dein{STR_VAR_1}wird ja echt krass\n"
	.string "von dir umsorgt.\p"
	.string "Wenn du es mit irgendwas vergleichen\n"
	.string "müsstest, was du feierst, was wär das?$"

SlateportCity_PokemonFanClub_Text_WhatAttractedYouAboutMon:
	.string "Die Frage geht auch um dein heiß-\n"
	.string "geliebtes{STR_VAR_1}.\p"
	.string "Was genau hat dich an{STR_VAR_1}\n"
	.string "so extrem angemacht?$"

SlateportCity_PokemonFanClub_Text_WhatDoPokemonMeanToYou:
	.string "Okay, das macht Sinn.\p"
	.string "Die nächste Frage wird vielleicht\n"
	.string "ein bisschen knifflig.\p"
	.string "Pass auf...\p"
	.string "Was bedeuten POKéMON eigentlich für dich?$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview:
	.string "Verstehe!\p"
	.string "Mh-hm...\p"
	.string "Alles klar!\n"
	.string "Danke für deine Zeit.\p"
	.string "War echt lustig, bisschen mit dir zu\n"
	.string "quatschen.\p"
	.string "Könnte gut sein, dass unser Interview\n"
	.string "im Fernsehen landet. Check das mal ab!\p"
	.string "Okay, das wär's dann.\n"
	.string "Hau rein!$"

SlateportCity_PokemonFanClub_Text_HereIfYouGetUrgeToTellMe:
	.string "Oh, okay...\p"
	.string "Naja, wenn du mal Bock hast, mich\n"
	.string "vollzulabern, ich bin hier!$"

SlateportCity_PokemonFanClub_Text_EnjoyDoingInterviews:
	.string "Ich feier den Job voll -- man lernt\n"
	.string "echt krasse Sachen durch die Interviews.$"

SlateportCity_PokemonFanClub_Text_InterviewRequest:
	.string "Hi, du scheinst ja echt 'ne krasse\n"
	.string "Bindung zu deinem{STR_VAR_1}zu haben.\p"
	.string "Weißt du was?\n"
	.string "Ich bin vom Fernsehen.\p"
	.string "Ich reise rum und löchere Leute\n"
	.string "mit Fragen über POKéMON.\p"
	.string "Haste Bock, mir ein bisschen was über\n"
	.string "dein{STR_VAR_1}zu erzählen?$"

SlateportCity_PokemonFanClub_Text_TellMeAnythingAboutYourMon:
	.string "Geil, danke dir!\p"
	.string "Okay, dann hau mal raus, was du mir\n"
	.string "über dein{STR_VAR_1}sagen willst.$"

SlateportCity_PokemonFanClub_Text_ThatsAllForInterview2:
	.string "Wow...\n"
	.string "Das ist ja mal 'ne krasse Story.\p"
	.string "Ihr seid echt wie Arsch und Eimer,\n"
	.string "du und dein{STR_VAR_1}, was?\p"
	.string "Ich hab so das Gefühl, das gibt 'ne\n"
	.string "richtig geile Fernseh-Story.\p"
	.string "Ich versprech dir, da mach ich 'ne\n"
	.string "richtig krasse Show draus!\l"
	.string "Halt mal die Augen auf.\p"
	.string "Okay, das war's.\n"
	.string "Hau rein!$"

gTVFanClubOpinionsText00::
	.string "WIR SIND DER POKéMON-FANCLUB!\p"
	.string "Wir sind auf Sendung, Leute!\p"
	.string "In dieser Show holen wir eure Meinungen\n"
	.string "ein, und ich schrei sie für euch ins TV!\l"
	.string "Ist das nicht ein fettes Konzept?\p"
	.string "Heute haben wir nen Bericht von\n"
	.string "unserem Paparazzi aus dem FANCLUB.\p"
	.string "Also, wer ist heute das krasse Opfer...\n"
	.string "äh, der Fan des Tages?\p"
	.string "… … … … … … … …\p"
	.string "{STR_VAR_1}!\p"
	.string "Hören wir mal, was{STR_VAR_1}über\n"
	.string "sein{STR_VAR_2}namens{STR_VAR_3}so ablässt.\p"
	.string "Und ich werde diese Worte der Liebe\n"
	.string "ins Mikrofon brüllen!\p"
	.string "Ugah-Ugah!\p"
	.string "Lass schreien!$"

gTVFanClubOpinionsText01::
	.string "Wir fragten{STR_VAR_1}: “Als du dein\n"
	.string "{STR_VAR_2}zuerst gesehen hast, was war\l"
	.string "dein erster krasser Gedanke?“\p"
	.string "“{STR_VAR_3}!“\p"
	.string "Yeahah! Geiler Schrei!\p"
	.string "Da kommen doch direkt die alten\n"
	.string "Erinnerungen hoch, oder?$"

gTVFanClubOpinionsText02::
	.string "Wir fragten{STR_VAR_1}: “Wenn du dein\n"
	.string "{STR_VAR_2}mit irgendwas vergleichen\l"
	.string "müsstest, was wär das?“\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!“\p"
	.string "Whoah-oh, das ist ja mal originell!\p"
	.string "Man spürt förmlich die kranke\n"
	.string "Obsession, die der TRAINER für\l"
	.string "{STR_VAR_2}hat.$"

gTVFanClubOpinionsText03::
	.string "Und mal sehen...\n"
	.string "Was fand{STR_VAR_1}an{STR_VAR_2}\l"
	.string "eigentlich so geil?\p"
	.string "… … … … … … … …\p"
	.string "“{STR_VAR_3}!“\p"
	.string "Whoa! Was für 'ne Ansage!\p"
	.string "Die Liebe zum{STR_VAR_2}ist ja\n"
	.string "wohl nicht mehr normal!$"

gTVFanClubOpinionsText04::
	.string "Hm? Da ist ja noch mehr Müll.\n"
	.string "Gucken wir uns das mal an!\p"
	.string "Mal checken...\p"
	.string "Wir fragten{STR_VAR_1}: “Was bedeuten\n"
	.string "POKéMON eigentlich für dich?“\p"
	.string "… … … … … …\p"
	.string "“{STR_VAR_3}!“\p"
	.string "Bravo!\p"
	.string "Der geilste Schrei des ganzen Tages!\p"
	.string "“{STR_VAR_3}!“\p"
	.string "Da hat man direkt Bock, selbst\n"
	.string "rumzubrüllen!\p"
	.string "Nachdem wir uns jetzt die Lunge aus dem\n"
	.string "Leib geschrien haben, ist auch mal gut!\p"
	.string "Also, einen letzten Schrei noch!\n"
	.string "Alle zusammen...\p"
	.string "“{STR_VAR_3}!“$"

gTVFanClubText00::
	.string "WIR SIND DER POKéMON-FANCLUB!\p"
	.string "Wir sind auf Sendung!\p"
	.string "Heute starten wir mit der ekligen\n"
	.string "POKéMON-UMFRAGE-ECKE.\p"
	.string "Von all dem Drama zwischen POKéMON\n"
	.string "und TRAINERN, was für 'ne krasse\l"
	.string "Story haben wir heute ausgegraben?\p"
	.string "Mal gucken...\p"
	.string "Den Lappen hier!\p"
	.string "Wir fangen mit diesem Brief an!\p"
	.string "Ein Brief von{STR_VAR_1}über ein\n"
	.string "heißgeliebtes{STR_VAR_2}.\p"
	.string "Mal sehen, wie kitschig der Typ seine\n"
	.string "Liebe zum{STR_VAR_2}ausdrücken kann!\l"
	.string "Hmhm...$"

gTVFanClubText01::
	.string "Whoah!\n"
	.string "Was für ein kranker Brief!$"

gTVFanClubText02::
	.string "Ich feier den so hart, den les ich\n"
	.string "direkt nochmal vor!$"

gTVFanClubText03::
	.string "Einen geilen Text muss man einfach\n"
	.string "tausendmal lesen!$"

gTVFanClubText04::
	.string "Der Teil mit “{STR_VAR_3}“, das\n"
	.string "kickt richtig rein emotional!\p"
	.string "Ein geiler Brief mit richtig\n"
	.string "viel Gefühl... kotz.$"

gTVFanClubText05::
	.string "Besonders dieser “{STR_VAR_3}“ Teil!\p"
	.string "Ich liebe es, wie “{STR_VAR_3}“\n"
	.string "da benutzt wird!$"

gTVFanClubText06::
	.string "Nebenbei gesagt, und wen juckt's,\n"
	.string "aber “{STR_VAR_3}“ ist echt geil.\p"
	.string "Ich hau “{STR_VAR_3}“ in letzter\n"
	.string "Zeit ständig raus.$"

gTVFanClubText07::
	.string "Wenn ich dem Brief Punkte geben\n"
	.string "müsste, gäb's ne{STR_VAR_3}von 10.\p"
	.string "Nächstes Mal erwart ich was Besseres\n"
	.string "von dir,{STR_VAR_1}!\p"
	.string "Hoppla, guckt euch die Uhrzeit an!\n"
	.string "Zeit, sich zu verpissen. Ciao!$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequest:
	.string "Oh?\n"
	.string "Bist du vielleicht so'n POKéMON-Nerd?\p"
	.string "Ich bin hier für's Fernsehen.\p"
	.string "Ich sammel Storys über TRAINER und\n"
	.string "ihre Viecher, die in letzter Zeit\l"
	.string "so passiert sind.\p"
	.string "Wenn's dich nicht juckt, erzähl doch\n"
	.string "mal ein bisschen was von dir.$"

SlateportCity_OceanicMuseum_1F_Text_InterviewRequestShort:
	.string "Ich sammel Storys über POKéMON und\n"
	.string "TRAINER, die grad aktuell sind.\p"
	.string "Hast du Bock, mal bisschen was über\n"
	.string "dich rauszuhauen?$"

SlateportCity_OceanicMuseum_1F_Text_TellMeExperienceInvolvingPokemon:
	.string "Oh, echt jetzt?\n"
	.string "Fetten Dank!\p"
	.string "Dann schieß mal los mit irgendwas\n"
	.string "Krassem, das du mit POKéMON erlebt hast.$"

SlateportCity_OceanicMuseum_1F_Text_LetMeKnowIfYouHaveStory:
	.string "Ach so, na toll...\p"
	.string "Wenn du mal 'ne geile Story hast,\n"
	.string "dann nerv mich ruhig damit.$"

SlateportCity_OceanicMuseum_1F_Text_ThatsAllForInterview:
	.string "Oh, was für 'ne ergreifende Story!\p"
	.string "Das bring ich auf jeden Fall\n"
	.string "ins Fernsehen.\p"
	.string "Das wird sicher bald versendet, also\n"
	.string "halt mal die Augen offen.$"

SlateportCity_OceanicMuseum_1F_Text_BetterWriteUpStory:
	.string "Hmmm...\n"
	.string "Geile Story für's TV gefunden.\p"
	.string "Muss ich mal schnell aufschreiben,\n"
	.string "bevor ich's wieder vergesse!$"

gTVRecentHappeningsText00::
	.string "Hallo, Zeit für den KLATSCH & TRATSCH.\p"
	.string "Für POKéMON-TRAINER ist echt\n"
	.string "jeder Tag 'n einziger Film.\p"
	.string "Wir wollen euch heute mal ein bisschen\n"
	.string "von diesem Film zeigen.\p"
	.string "Heute geht's um den TRAINER\n"
	.string "{STR_VAR_1}.\p"
	.string "Was hat{STR_VAR_1}so Krasses erlebt?\n"
	.string "Checken wir's mal aus.\p"
	.string "Mal gucken...$"

gTVRecentHappeningsText01::
	.string "War das nicht erhellend?\p"
	.string "Die Story zeigt mal richtig, was\n"
	.string "{STR_VAR_1}in letzter Zeit so abzieht.\l"
	.string "Als wären wir live dabei gewesen!$"

gTVRecentHappeningsText02::
	.string "“{STR_VAR_3}.“ Das\n"
	.string "gibt der ganzen Sache so 'n tiefen Sinn.$"

gTVRecentHappeningsText03::
	.string "“{STR_VAR_3}.“\n"
	.string "Das zeigt so richtig, wo der Hase\l"
	.string "im Pfeffer liegt.$"

gTVRecentHappeningsText04::
	.string "Der “{STR_VAR_3}“\n"
	.string "Teil der Story knallt richtig rein.$"

gTVRecentHappeningsText05::
	.string "{STR_VAR_1}hat da 'ne echt wilde\n"
	.string "Story mit POKéMON rausgehauen.\p"
	.string "Und jetzt brennt sich die Story von\n"
	.string "{STR_VAR_1}auch in euer Hirn ein.\p"
	.string "Das war's für heute.\n"
	.string "Schaltet nächstes Mal wieder ein, Opfer.$"

gTVMassOutbreakText00::
	.string "Moin!\n"
	.string "Zeit für die POKéMON-NEWS.\p"
	.string "Wir haben grad 'ne Info reinbekommen,\n"
	.string "die echt selten ist.\p"
	.string "Es gab Berichte über 'ne fette Plage\n"
	.string "von{STR_VAR_2}in der Nähe\l"
	.string "von{STR_VAR_1}.\p"
	.string "{STR_VAR_2}ist ja, wie ihr Noobs\n"
	.string "wisst, mega selten und schwer zu finden.\p"
	.string "Klingt nach 'ner fetten Chance,\n"
	.string "diese kranke Plage von{STR_VAR_2}\l"
	.string "in freier Wildbahn zu sehen.\p"
	.string "Das waren die POKéMON-NEWS. Ciao.$"

gTV3CheersForPokeblocksText00::
	.string "MC: Hoffentlich seid ihr gut drauf!\n"
	.string "“3 CHEERS FOR{POKEBLOCK}S“ ist hier!\p"
	.string "Heute checken wir den{POKEBLOCK}, den\n"
	.string "{STR_VAR_1}und Co. gemixt haben.\p"
	.string "Ohne langes Gelaber verfüttere ich\n"
	.string "das jetzt an mein Feinschmecker-SCHLUPPUCK.\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTV3CheersForPokeblocksText01::
	.string "SCHLUPPUCK: Gubi! Gubii!\p"
	.string "MC: Und das Urteil ist mega{STR_VAR_1}!\n"
	.string "SCHLUPPUCK meint: “{STR_VAR_2}!“\p"
	.string "Vielen Dank,{STR_VAR_3}!$"

gTV3CheersForPokeblocksText02::
	.string "Die Mix-Skills von{STR_VAR_1}\n"
	.string "waren ja wohl ziemlich armselig.\p"
	.string "Wenn der TRAINER besser mixen könnte,\n"
	.string "wäre der{POKEBLOCK}viel geiler.$"

gTV3CheersForPokeblocksText03::
	.string "SCHLUPPUCK: Gubi! Gubii!\p"
	.string "MC: Hmm... Ist zu{STR_VAR_1}.\n"
	.string "SCHLUPPUCK meint: “{STR_VAR_2}!“\p"
	.string "Sieht so aus, als hätten die Fails\n"
	.string "von{STR_VAR_3}alles ruiniert...$"

gTV3CheersForPokeblocksText04::
	.string "Echt mies, dass die ganze Mühe von\n"
	.string "{STR_VAR_1}für'n Arsch war.\p"
	.string "Hoffen wir mal, dass{STR_VAR_2}das\n"
	.string "nächstes Mal nicht so hart verkackt!$"

gTV3CheersForPokeblocksText05::
	.string "Schaltet wieder ein, ihr Lappen!\n"
	.string "Unser Motto: “3 CHEERS FOR{POKEBLOCK}S!“$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer::
	.string "Was geht?!\p"
	.string "Ich bin so ein krasser Fan von\n"
	.string "{STR_VAR_1}.\l"
	.string "Was hältst du von{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_ThatsWhatYouThink::
	.string "Ah, ich verstehe. So denkst du also\n"
	.string "über den TRAINER.$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer::
	.string "Hast du{STR_VAR_1}komplett aus\n"
	.string "deinem Gedächtnis gelöscht, oder was?$"

LilycoveCity_PokemonTrainerFanClub_Text_WhatsYourOpinionOfTrainer2::
	.string "Ich bin mega Fan von{STR_VAR_1}.\n"
	.string "Was ist deine Meinung zu{STR_VAR_1}?$"

LilycoveCity_PokemonTrainerFanClub_Text_HowStrongRateTrainer::
	.string "Wie krass würdest du{STR_VAR_1}\n"
	.string "auf 'ner Skala von 1 bis 100 bewerten?$"

LilycoveCity_PokemonTrainerFanClub_Text_HaveYouForgottenTrainer2::
	.string "Hast du{STR_VAR_1}echt schon\n"
	.string "wieder vergessen? Opfer!$"

LilycoveCity_PokemonTrainerFanClub_Text_YouShouldMeetTrainer::
	.string "Ah, check!\n"
	.string "Du musst{STR_VAR_1}unbedingt mal\l"
	.string "treffen. Dann wirst du auch zum Fan!$"

LilycoveCity_PokemonTrainerFanClub_Text_ThankYouIllShareThisInfo::
	.string "Ah, alles klar.\p"
	.string "Danke!\n"
	.string "Das war echt gut zu wissen.\p"
	.string "Ich werd das den anderen Fans von\n"
	.string "{STR_VAR_1}stecken und wir lästern\l"
	.string "dann drüber.$"

LilycoveCity_PokemonTrainerFanClub_HopeYouCatchTVSpecial::
	.string "Bald gibt's 'n richtig geiles TV-Special\n"
	.string "über{STR_VAR_1}.\p"
	.string "Hoffe, du ziehst dir das rein!$"

gTVTrainerFanClubSpecialText00::
	.string "TRAINER FANCLUB\n"
	.string "{STR_VAR_1} SPECIAL!\p"
	.string "Das ist 'ne Sondersendung für alle\n"
	.string "Fans von{STR_VAR_1}in ganz HOENN!\p"
	.string "Heute fragen wir uns: “Was halten die\n"
	.string "Leute eigentlich von{STR_VAR_1}?“\p"
	.string "Wir haben{STR_VAR_2}als TRAINER-\n"
	.string "Vertreter ans Mikro gezerrt.\p"
	.string "Wir fragten: “Beschreib{STR_VAR_1}\n"
	.string "mal in einem Wort!“\p"
	.string "Die Antwort: “{STR_VAR_3}.“\p"
	.string "Respekt an{STR_VAR_2}!\n"
	.string "Was für 'ne krasse Meinung!\p"
	.string "“{STR_VAR_3} {STR_VAR_1}.“\n"
	.string "Klingt einfach geil!\p"
	.string "{STR_VAR_2}hat{STR_VAR_1}s\n"
	.string "Stärke auch noch von 0 bis 100 bewertet.$"

gTVTrainerFanClubSpecialText01::
	.string "Es gab fette{STR_VAR_3}Punkte!\n"
	.string "Das ist ja wohl mal ein kranker Score!\p"
	.string "{STR_VAR_2}muss echt mega viel\n"
	.string "von{STR_VAR_1}halten.$"

gTVTrainerFanClubSpecialText02::
	.string "Es gab{STR_VAR_3}Punkte!\n"
	.string "Das ist echt ein stabiler Score.\p"
	.string "{STR_VAR_2}sieht{STR_VAR_1}\n"
	.string "wohl echt als fetten Rivalen.$"

gTVTrainerFanClubSpecialText03::
	.string "Es gab lausige{STR_VAR_3}Punkte!\n"
	.string "Das ist echt 'n mieser Score.\p"
	.string "{STR_VAR_2}sieht{STR_VAR_1}\n"
	.string "wohl nur als kleinen Sidekick.$"

gTVTrainerFanClubSpecialText04::
	.string "Es gab jämmerliche{STR_VAR_3}Punkt(e)!\n"
	.string "Was für'n beschissener Score.\p"
	.string "{STR_VAR_2}hält{STR_VAR_1}\n"
	.string "wohl für 'n absolutes Opfer.$"

gTVTrainerFanClubSpecialText05::
	.string "Da habt ihr's, Leute!\p"
	.string "Denke, wir haben alle was Neues\n"
	.string "über{STR_VAR_1}gelernt.\p"
	.string "Zum Schluss lass ich euch mit den\n"
	.string "Worten von{STR_VAR_2}allein.\p"
	.string "{STR_VAR_3} {STR_VAR_1}!$"

gTVNameRaterText00::
	.string "Und jetzt Zeit für...\n"
	.string "DIE NAMENS-BEWERTER-SHOW.\p"
	.string "Ich sag euch die Zukunft voraus, anhand\n"
	.string "der dummen Namen eurer POKéMON.\p"
	.string "Ich geb euch Rat, auch wenn er wehtut.\p"
	.string "Heute les ich aus dem Namen\n"
	.string "{STR_VAR_3}von{STR_VAR_1}s POKéMON\l"
	.string "namens{STR_VAR_2}!\p"
	.string "Hmhm...\p"
	.string "Hmm...\n"
	.string "Dieser Spitzname ist...$"

gTVNameRaterText01::
	.string "Ein Name, der nach Multitalent schreit!\p"
	.string "Ich sag dem TRAINER: Zeig Eier und stell\n"
	.string "dich jeder dämlichen Herausforderung!$"

gTVNameRaterText02::
	.string "Ein Name, der perfekt zu dem Lappen\n"
	.string "namens{STR_VAR_1}passt.\p"
	.string "Das riecht nach 'ner Partnerschaft,\n"
	.string "die vom perfekten Timing lebt.$"

gTVNameRaterText03::
	.string "Ein Name für ein absolutes Unikat!\p"
	.string "Wenn man das Vieh richtig erzieht,\n"
	.string "wird's echt komplett durchdrehen!$"

gTVNameRaterText04::
	.string "Ein Name, der die POKéMON richtig weich\n"
	.string "und kuschelig macht.\p"
	.string "Wenn's richtig erzogen wird, wird dieses\n"
	.string "POKéMON ne echte Schmusekatze!$"

gTVNameRaterText05::
	.string "Ein mega geiler Name, der nach echter\n"
	.string "Größe stinkt.\p"
	.string "Bin echt gespannt, was dieses POKéMON\n"
	.string "noch so reißen wird.$"

gTVNameRaterText06::
	.string "Ein cooler Name, der das POKéMON\n"
	.string "richtig fit und krass machen sollte!\p"
	.string "Das Vieh wird sicher mega lange\n"
	.string "durchhalten.$"

gTVNameRaterText07::
	.string "Ein cooler Name, der das POKéMON\n"
	.string "bestimmt mega hyperaktiv macht!\p"
	.string "Ich wette, das Vieh rasiert in den\n"
	.string "Kämpfen so richtig.$"

gTVNameRaterText08::
	.string "Ein süßer Name, der das POKéMON zu\n"
	.string "einem echten Charmeur machen sollte!\p"
	.string "In den WETTBEWERBEN wickelt das Vieh\n"
	.string "sicher alle um den Finger.$"

gTVNameRaterText09::
	.string "Der Name{STR_VAR_1}wird geankert\n"
	.string "durch den Buchstaben “{STR_VAR_3}“.\p"
	.string "Das wird durch “{STR_VAR_2}“ gestützt\n"
	.string "und gibt dem Namen 'ne fette Präsenz.$"

gTVNameRaterText10::
	.string "Der Name{STR_VAR_1}ist echt\n"
	.string "mega angenehm geformt.\p"
	.string "Die Kombi aus “{STR_VAR_2}“ und\n"
	.string "“{STR_VAR_3}“ -- das ist echt krasser Shit!$"

gTVNameRaterText11::
	.string "Der Name{STR_VAR_1} -- der\n"
	.string "fließt einfach geil von den Lippen.\p"
	.string "Der Flow von “{STR_VAR_2}“ zu\n"
	.string "“{STR_VAR_3}“ ist echt der Wahnsinn.$"

gTVNameRaterText12::
	.string "Checken wir mal noch andere Beispiele\n"
	.string "für richtig geile Namen ab, okay?$"

gTVNameRaterText13::
	.string "Nimm das mal: Nimm'n Teil vom\n"
	.string "TRAINER{STR_VAR_1}und du hast den\l"
	.string "fetten Namen{STR_VAR_2}{STR_VAR_3}!$"

gTVNameRaterText14::
	.string "Der Name{STR_VAR_2}{STR_VAR_3}würde auch\n"
	.string "richtig knallen.$"

gTVNameRaterText15::
	.string "Die POKéMON-Spezies{STR_VAR_2}könnte\n"
	.string "man super nehmen, um den Namen\l"
	.string "{STR_VAR_1}{STR_VAR_3}zu bauen.$"

gTVNameRaterText16::
	.string "{STR_VAR_1}{STR_VAR_3}wäre auch 'n echt\n"
	.string "stabiler Name.$"

gTVNameRaterText17::
	.string "Was ihr Noobs lassen solltet: Einfach\n"
	.string "Namen von anderen POKéMON klauen.\p"
	.string "Nimm zum Beispiel nicht den Namen von\n"
	.string "{STR_VAR_2}, um{STR_VAR_1}{STR_VAR_3}daraus\l"
	.string "zu machen. Das ist echt lahm.$"

gTVNameRaterText18::
	.string "Muss schon sagen,{STR_VAR_1}ist ein\n"
	.string "echt verdammt guter Name.\p"
	.string "Hoffentlich behandelt der TRAINER\n"
	.string "{STR_VAR_1}auch nicht wie Dreck.\p"
	.string "Das war's für heute, ihr Lappen.\n"
	.string "Haut rein.$"

gTVPokemonAnglerText00::
	.string "{STR_VAR_2}-ANGLER\p"
	.string "ANNOUNCER: Moin! Heute gibt's Tipps\n"
	.string "zum Angeln von{STR_VAR_2}.\p"
	.string "GURU, was hast du für Tipps am Start,\n"
	.string "um{STR_VAR_2}zu fangen?\p"
	.string "GURU: Hm?{STR_VAR_2}fangen?\n"
	.string "Lass dir sagen: Geduld haben und\l"
	.string "warten. Das ist das ganze Geheimnis.\p"
	.string "Siehst du{STR_VAR_1}da drüben?\n"
	.string "Der Typ macht's genau richtig.\p"
	.string "Dem sind schon{STR_VAR_3}POKéMON\n"
	.string "abgehauen.\p"
	.string "Aber{STR_VAR_1}wartet einfach weiter.\n"
	.string "Nix mit Aufgeben. So fängt man{STR_VAR_2}.\p"
	.string "ANNOUNCER: Ah, verstehe...\p"
	.string "Oh!{STR_VAR_1}hat endlich ein fettes\n"
	.string "{STR_VAR_2}an Land gezogen!\p"
	.string "Der TRAINER heult ja fast vor Glück!\p"
	.string "Wenn ich dieses dumme Grinsen sehe,\n"
	.string "hab ich auch direkt Bock aufs Angeln!\p"
	.string "Zuschauer, schnappt euch 'ne Angel\n"
	.string "und holt euch auch ein{STR_VAR_2}!\p"
	.string "Bis zum nächsten Mal und Petri Heil,\n"
	.string "ihr Fischköppe!$"

gTVPokemonAnglerText01::
	.string "{STR_VAR_2}-ANGLER\p"
	.string "ANNOUNCER: Moin! Heute gibt's Tipps\n"
	.string "zum Angeln von{STR_VAR_2}.\p"
	.string "GURU, was hast du für Tipps am Start,\n"
	.string "um{STR_VAR_2}zu fangen?\p"
	.string "GURU: Hm?{STR_VAR_2}fangen?\n"
	.string "Lass dir sagen: Reiß die Angel\l"
	.string "mit richtig Power hoch!\p"
	.string "Siehst du{STR_VAR_1}da drüben?\n"
	.string "Siehste, wie die Angel gerissen wird?\p"
	.string "Der TRAINER hat schon{STR_VAR_3}am\n"
	.string "Stück gefangen.\p"
	.string "ANNOUNCER: Echt krank!\n"
	.string "Das sieht ja aus wie im Rausch...\p"
	.string "Wenn ich so 'ne Technik sehe, hab ich\n"
	.string "direkt Bock, selbst die Angel reinzuhauen.\p"
	.string "Zuschauer, schnappt euch 'ne Angel\n"
	.string "und holt euch auch ein{STR_VAR_2}!\p"
	.string "Bis zum nächsten Mal und Petri Heil,\n"
	.string "ihr Fischköppe!$"

gTVPokemonTodayFailedText00::
	.string "Moin!\p"
	.string "Zeit für POKéMON HEUTE!\p"
	.string "SCHWESTI: Hey! Alle schön\n"
	.string "assi drauf heute?\p"
	.string "Heute ziehen wir das POKéMON\n"
	.string "{STR_VAR_2}von{STR_VAR_1}durch den Kakao!\p"
	.string "BRUDI: Yeah! Genau das machen\n"
	.string "wir jetzt!$"

gTVPokemonTodayFailedText01::
	.string "Oh!\n"
	.string "Apropos{STR_VAR_1}...\p"
	.string "SCHWESTI, ich hab den TRAINER mit\n"
	.string "eigenen Augen gesehen!\p"
	.string "SCHWESTI: Oh, was gab's zu gaffen?\p"
	.string "BRUDI: Naja, ich musste nach\n"
	.string "{STR_VAR_2}gurken.\p"
	.string "Da hab ich{STR_VAR_1}gesehen, wie er\n"
	.string "versucht hat, 'n{STR_VAR_3}zu fangen,\l"
	.string "aber...$"

gTVPokemonTodayFailedText02::
	.string "Das POKéMON hat sich verpisst!\p"
	.string "Er hat einfach{STR_VAR_2}POKéBÄLLE\n"
	.string "komplett verschwendet!\p"
	.string "Du hättest das dumme Gesicht von\n"
	.string "{STR_VAR_1}sehen sollen, als das Vieh\l"
	.string "einfach abgehauen ist!$"

gTVPokemonTodayFailedText03::
	.string "Aber{STR_VAR_1}hat reingeschissen und\n"
	.string "das POKéMON einfach umgeklatscht!\p"
	.string "Er hat einfach{STR_VAR_2}POKéBÄLLE\n"
	.string "komplett verschwendet!\p"
	.string "Du hättest mal das komplett dumme\n"
	.string "Gesicht von{STR_VAR_1}sehen sollen,\l"
	.string "als das POKéMON K.O. gegangen ist!$"

gTVPokemonTodayFailedText04::
	.string "SCHWESTI: Ey, Hallo!\n"
	.string "Das ist voll fies!\p"
	.string "Man lacht nicht, wenn andere Leute\n"
	.string "komplett abkacken!\p"
	.string "Oh, armer{STR_VAR_1}.\n"
	.string "Was für 'ne Schande!\p"
	.string "BRUDI: Ja, stimmt!\n"
	.string "Sorry, dass ich gelacht hab.$"

gTVPokemonTodayFailedText05::
	.string "SCHWESTI: Pfffhihi...\p"
	.string "BRUDI: Ey!\n"
	.string "Du hast grad auch voll gelacht!\p"
	.string "SCHWESTI: Hä?!\p"
	.string "Ich hab gar nicht gelacht!\n"
	.string "Ehrlich nicht!\p"
	.string "Oh, armer{STR_VAR_1}.\n"
	.string "Was für 'ne Schande!\p"
	.string "BRUDI: ...$"

gTVPokemonTodayFailedText06::
	.string "SCHWESTI: Genug dummes Gelaber!\n"
	.string "Gucken wir uns das POKéMON von heute...\p"
	.string "Hä?\n"
	.string "Die Zeit ist schon um?\p"
	.string "Mies!\n"
	.string "Heute also kein POKéMON im Profil!\p"
	.string "BRUDI: Haut rein bis zum nächsten Mal!\p"
	.string "SCHWESTI: Ey, beende die Show\n"
	.string "nicht ohne mich, du Opfer!$"

gTVPokemonTodaySuccessfulText00::
	.string "Moin!\p"
	.string "Zeit für POKéMON HEUTE!\p"
	.string "SCHWESTI: Hey! Alle schön\n"
	.string "assi drauf heute?\p"
	.string "Heute ziehen wir das POKéMON\n"
	.string "{STR_VAR_2}von{STR_VAR_1}durch den Kakao!\p"
	.string "BRUDI: Yeah! Genau das machen\n"
	.string "wir jetzt!$"

gTVPokemonTodaySuccessfulText01::
	.string "SCHWESTI:{STR_VAR_1}hat dem{STR_VAR_2}\n"
	.string "den Namen{STR_VAR_3}gegeben!\p"
	.string "Klingt so, als würde{STR_VAR_3}ordentlich\n"
	.string "verhätschelt werden!$"

gTVPokemonTodaySuccessfulText02::
	.string "BRUDI: Der Typ musste so viele\n"
	.string "Bälle werfen, um es zu fangen:{STR_VAR_3}!\p"
	.string "Am Ende hat EIN einziger{STR_VAR_2}\n"
	.string "gereicht, um es einzutüten!$"

gTVPokemonTodaySuccessfulText03::
	.string "SCHWESTI: Wenn das so leicht war,\n"
	.string "war's bestimmt Schicksal, dass{STR_VAR_1}\l"
	.string "und{STR_VAR_2}zusammengefunden haben!$"

gTVPokemonTodaySuccessfulText04::
	.string "SCHWESTI: Wow! Das ist ja wild!\p"
	.string "Aber hey, ein POKéMON, das man schwer\n"
	.string "fängt, wird vom TRAINER später umso\l"
	.string "mehr abgeknutscht!$"

gTVPokemonTodaySuccessfulText05::
	.string "SCHWESTI: Das{STR_VAR_2}von{STR_VAR_1}\n"
	.string "ist echt unvergesslich, dafür ging\l"
	.string "sogar ein verfluchter MEISTERBALL drauf!\p"
	.string "BRUDI: Wow! Das ist mega krass!\p"
	.string "SCHWESTI:{STR_VAR_1}wollte das\n"
	.string "{STR_VAR_2}wohl echt verdammt dringend!$"

gTVPokemonTodaySuccessfulText06::
	.string "BRUDI: Und dem Vieh dann den\n"
	.string "Namen{STR_VAR_3}zu geben...\p"
	.string "Da merkt man richtig, was{STR_VAR_1}\n"
	.string "für'n komischen Geschmack hat.\p"
	.string "SCHWESTI: Da sagste was!$"

gTVPokemonTodaySuccessfulText07::
	.string "Ich würd diesen Namen ja eher für\n"
	.string "so'n{STR_VAR_3}benutzen!\p"
	.string "BRUDI: Whoa! Da könnte man glatt\n"
	.string "einen neuen Trend draus machen!$"

gTVPokemonTodaySuccessfulText08::
	.string "{STR_VAR_2}für ein{STR_VAR_1}?\n"
	.string "Klingt das nicht total bescheuert?\p"
	.string "Die Buchstaben und alles... das\n"
	.string "passt doch gar nicht zu{STR_VAR_1}!\p"
	.string "BRUDI: Ja, voll! Hast recht!$"

gTVPokemonTodaySuccessfulText09::
	.string "Soweit ich weiß, hat noch nie ein\n"
	.string "TRAINER sein{STR_VAR_1}einfach\l"
	.string "{STR_VAR_2}genannt!\p"
	.string "BRUDI: Das zeigt mal wieder, was\n"
	.string "für'n seltsamen Geschmack der TRAINER hat!$"

gTVPokemonTodaySuccessfulText10::
	.string "Wenn ich nächstes Mal ein POKéMON\n"
	.string "fange, nenn ich's auch{STR_VAR_2}.\p"
	.string "BRUDI: Hä? Ich auch!\n"
	.string "Ich nenn meins auch{STR_VAR_2}!$"

gTVPokemonTodaySuccessfulText11::
	.string "SCHWESTI: Oh, Mist!\n"
	.string "Guck mal auf die Uhr!\p"
	.string "Leute, das war's für heute.\n"
	.string "Bis zum nächsten Mal, ihr Opfer!\p"
	.string "BRUDI: Vergesst nicht, nächstes Mal\n"
	.string "könnte euer POKéMON hier blamiert werden!$"

SmartShopper_Text_Intro::
	.string "Moin!\p"
	.string "Zeit für den KONSUM-OPFER-REPORT!\p"
	.string "INTERVIEWER: Was geht ab, Zuschauer?\p"
	.string "Heute sind wir in 'nem Laden\n"
	.string "in{STR_VAR_2}.\p"
	.string "Checken wir mal ab, was hier in letzter\n"
	.string "Zeit so am härtesten über die Ladentheke\l"
	.string "geht.$"

SmartShopper_Text_ClerkNormal::
	.string "Interviewen wir mal den Kassierer,\n"
	.string "um die Infos rauszupressen.\p"
	.string "Ey, wie läuft das Geschäft so?\p"
	.string "KASSIERER: Oh, wir machen fett Asche.\p"
	.string "Besonders{STR_VAR_2}verkauft sich\n"
	.string "in letzter Zeit wie warme Semmeln.\p"
	.string "Neulich kam ein TRAINER namens{STR_VAR_1}\n"
	.string "und hat direkt{STR_VAR_3}davon gekauft.$"

SmartShopper_Text_RandomComment1::
	.string "INTERVIEWER: Der TRAINER hat\n"
	.string "{STR_VAR_3} {STR_VAR_2}S gekauft? Krass!\p"
	.string "Da muss{STR_VAR_1}sich ja wohl für 'n\n"
	.string "richtig langen Trip in die Pampa\l"
	.string "ausgerüstet haben.\p"
	.string "Für Reisen sind{STR_VAR_2}S ja echt\n"
	.string "mega wichtig, was?$"

SmartShopper_Text_RandomComment2::
	.string "INTERVIEWER: Apropos{STR_VAR_2},\n"
	.string "ich hab mir letztens auch{STR_VAR_3}\l"
	.string "davon gegönnt.\p"
	.string "{STR_VAR_2}ist halt einfach geil!$"

SmartShopper_Text_RandomComment3::
	.string "INTERVIEWER:{STR_VAR_2}?!\n"
	.string "Aber gleich{STR_VAR_3}davon?!\p"
	.string "Dachte nicht, dass irgendjemand so\n"
	.string "gestört ist und so viel davon kauft.\p"
	.string "Alter Schwede, ich kann mir höchstens\n"
	.string "eins oder zwei auf einmal leisten...$"

SmartShopper_Text_RandomComment4::
	.string "INTERVIEWER: Einmal hab ich voll über-\n"
	.string "trieben und mega viel{STR_VAR_2}gekauft.\p"
	.string "War dann doch 'n bisschen zu viel.\n"
	.string "Hab mich derbe geärgert...\p"
	.string "Seitdem kauf ich nur noch das, was ich\n"
	.string "wirklich unbedingt brauche...\p"
	.string "Hoppla!\p"
	.string "Was laber ich hier eigentlich über mich?$"

SmartShopper_Text_SecondItem::
	.string "KASSIERER:{STR_VAR_1}hat auch noch\n"
	.string "fett{STR_VAR_2}eingepackt, gleich{STR_VAR_3}.\p"
	.string "INTERVIEWER: Oh, nicht dumm.\n"
	.string "{STR_VAR_2}ist auch echt nützlich.$"

SmartShopper_Text_ThirdItem::
	.string "KASSIERER: Und der Typ hat sich auch\n"
	.string "noch{STR_VAR_3}mal{STR_VAR_2}gegönnt.$"

SmartShopper_Text_DuringSale::
	.string "KASSIERER: Und das auch noch während 'nem\n"
	.string "Schlussverkauf. Richtig schlau gemacht.$"

SmartShopper_Text_OutroNormal::
	.string "INTERVIEWER: Hmm...{STR_VAR_1}klingt\n"
	.string "wie 'n echter Schnäppchen-Jäger!\p"
	.string "Insgesamt hat{STR_VAR_1}also...\p"
	.string "¥{STR_VAR_2}rausgeballert?!\n"
	.string "Was für 'ne kranke Summe!\p"
	.string "Oops! Zeit ist um!\n"
	.string "Man sieht sich beim nächsten Mal!$"

SmartShopper_Text_IsVIP::
	.string "KASSIERER:{STR_VAR_1}ist absolut\n"
	.string "VIP bei uns, gar keine Frage.$"

SmartShopper_Text_ClerkMax::
	.string "Interviewen wir mal den Kassierer,\n"
	.string "um die Infos rauszupressen.\p"
	.string "Ey, wie läuft das Geschäft so?\p"
	.string "KASSIERER: Oh, der Laden brummt.\n"
	.string "Kommen kaum noch hinterher.\p"
	.string "Neulich kam dieser TRAINER{STR_VAR_1}\n"
	.string "und hat einfach palettenweise\l"
	.string "{STR_VAR_2}mitgenommen.\p"
	.string "Hat uns fast den ganzen Bestand an\n"
	.string "{STR_VAR_2}S leergekauft.\p"
	.string "Hab noch nie erlebt, dass irgendwer so\n"
	.string "viele{STR_VAR_2}S braucht.\l"
	.string "Komplett irre!\p"
	.string "INTERVIEWER: Also so 100 oder\n"
	.string "200 Stück, oder was?\p"
	.string "KASSIERER: Oh nee, noch viel mehr!\p"
	.string "INTERVIEWER: Heilige Scheiße!\n"
	.string "{STR_VAR_1}muss ja komplett kaufsüchtig sein!\p"
	.string "KASSIERER:{STR_VAR_1}ist absolut\n"
	.string "VIP bei uns, gar keine Frage.$"

SmartShopper_Text_OutroMax::
	.string "INTERVIEWER: Hmm...\n"
	.string "Das ist ja echt mega krank.\p"
	.string "Aber wozu braucht der Typ so\n"
	.string "unnormal viel von dem Zeug?\p"
	.string "… …\p"
	.string "Keiner weiß es, aber wir müssen Schluss\n"
	.string "machen. Zeit ist um.\l"
	.string "Man sieht sich bei der nächsten Sendung!\p"
	.string "Aber echt,{STR_VAR_1}ist schon 'n komischer Vogel...$"

gTVWorldOfMastersText00::
	.string "DIE WELT DER NERDS\p"
	.string "Moin Zuschauer.\p"
	.string "Vielleicht kennt ihr ja den TRAINER\n"
	.string "namens{STR_VAR_1}.\p"
	.string "{STR_VAR_1}ist voll der Meister im\n"
	.string "POKéMON-Fangen.\p"
	.string "{STR_VAR_1}s Suche nach POKéMON\n"
	.string "besteht eigentlich nur aus rumlatschen.\p"
	.string "An einem echt kaputten Tag ist der Typ\n"
	.string "einfach{STR_VAR_2}Schritte gelaufen.\p"
	.string "Die Gesamtzahl der gefangenen Viecher\n"
	.string "an dem Tag lag bei fetten{STR_VAR_3}!$"

gTVWorldOfMastersText01::
	.string "So'n kranker Rekord geht natürlich nur,\n"
	.string "wenn zwischen TRAINER und{STR_VAR_1}\l"
	.string "blindes Vertrauen herrscht.$"

gTVWorldOfMastersText02::
	.string "Der Nerd fing das letzte{STR_VAR_3}\n"
	.string "in der Nähe von{STR_VAR_2}.\p"
	.string "Dieses POKéMON feiert das scheinbar,\n"
	.string "jetzt 'n Rekordhalter zu sein.\p"
	.string "Andere Noobs sollten echt mal versuchen,\n"
	.string "diesen Rekord zu brechen.\p"
	.string "Das war's für heute.\n"
	.string "Schaltet nächstes Mal wieder ein.$"

gTVTodaysRivalTrainerText00::
	.string "DER RIVALE DES TAGES!\p"
	.string "Moin, ihr Lappen-TRAINER!\n"
	.string "Wie geht's uns denn heute?\p"
	.string "Heute, wie jeden Tag, knöpfen\n"
	.string "wir uns einen eurer Rivalen vor!$"

gTVTodaysRivalTrainerText07::
	.string "Unser heutiges Opfer ist{STR_VAR_1},\n"
	.string "hängt grad irgendwo bei{STR_VAR_3}rum.\p"
	.string "{STR_VAR_1}hat bis jetzt{STR_VAR_2}\n"
	.string "POKéMON in den POKéDEX gestopft.$"

gTVTodaysRivalTrainerText08::
	.string "Unser heutiges Opfer ist{STR_VAR_1},\n"
	.string "hockt grad in seiner GEHEIMBASIS.\p"
	.string "{STR_VAR_1}hat bis jetzt{STR_VAR_2}\n"
	.string "POKéMON in den POKéDEX gestopft.$"

gTVTodaysRivalTrainerText09::
	.string "Unser heutiges Opfer ist{STR_VAR_1}.\p"
	.string "Bis jetzt hat{STR_VAR_1}es geschafft,\n"
	.string "{STR_VAR_2}POKéMON in den POKéDEX zu stopfen.$"

gTVTodaysRivalTrainerText10::
	.string "Unser heutiges Opfer ist{STR_VAR_1},\n"
	.string "gurkt grad auf'm Schiff rum.\p"
	.string "{STR_VAR_1}hat bis jetzt{STR_VAR_2}\n"
	.string "POKéMON in den POKéDEX gestopft.$"

	.string "$"

gTVTodaysRivalTrainerText01::
	.string "Und wie viele ORDEN hat der Lappen\n"
	.string "schon gesammelt? Fette{STR_VAR_1}!$"

gTVTodaysRivalTrainerText02::
	.string "Aber unser Rivale hat noch keinen\n"
	.string "einzigen ORDEN auf die Kette gekriegt!$"

gTVTodaysRivalTrainerText03::
	.string "Unser Rivale hat noch kein einziges\n"
	.string "KAMPFZONEN-Symbol am Start. Mies!$"

gTVTodaysRivalTrainerText04::
	.string "Gucken wir mal, wie viele Symbole aus\n"
	.string "der KAMPFZONE unser Rivale hat.\p"
	.string "Gold-Symbole:{STR_VAR_1}!\n"
	.string "Silber-Symbole:{STR_VAR_2}!$"

gTVTodaysRivalTrainerText05::
	.string "Unser Rivale hat{STR_VAR_1}Gewinnpunkte\n"
	.string "in der KAMPFZONE abgestaubt.$"

gTVTodaysRivalTrainerText06::
	.string "Und, wie seht ihr im Vergleich\n"
	.string "zu{STR_VAR_1}aus? Besser oder schlechter?\p"
	.string "Das Abenteuer geht weiter!\p"
	.string "Macht euch ran, TRAINER!\p"
	.string "Lasst uns reinhauen und den Rivalen\n"
	.string "zeigen, wer hier der Boss ist!$"

TrendWatcher_Text_Intro::
	.string "FAUSTAUHAVEN TREND-WATCHER-NETZWERK!\p"
	.string "MC: Was geht?\n"
	.string "Wir halten euch auf dem Laufenden, was\l"
	.string "in FAUSTAUHAVEN grad der geilste Shit ist.\p"
	.string "Unser heutiger Gast ist so'n alter Sack,\n"
	.string "der angeblich alles über FAUSTAUHAVEN\l"
	.string "weiß.\p"
	.string "Alter Sack: Freut mich, hier zu sein.\p"
	.string "MC: Kommen wir direkt zur Sache.\p"
	.string "Was ist grad der heißeste Scheiß\n"
	.string "bei den Leuten hier in FAUSTAUHAVEN?\p"
	.string "Alter Sack:{STR_VAR_1} {STR_VAR_2}.\p"
	.string "MC:{STR_VAR_1} {STR_VAR_2},\n"
	.string "sachste?\p"
	.string "Alter Sack: Nö.\p"
	.string "{STR_VAR_1} {STR_VAR_2}war hier\n"
	.string "noch nie angesagt.\p"
	.string "Willste was drüber hören?\p"
	.string "MC: Äh, ne. Wir wollen wissen, was\n"
	.string "JETZT grad der Trend ist...$"

TrendWatcher_Text_MaleTaughtMePhrase::
	.string "Alter Sack:{STR_VAR_1} {STR_VAR_2}\n"
	.string "wurde mir von diesem{STR_VAR_3}aus WURZELHEIM\l"
	.string "als total trendy angedreht...$"

TrendWatcher_Text_FemaleTaughtMePhrase::
	.string "Alter Sack:{STR_VAR_1} {STR_VAR_2}\n"
	.string "wurde mir von dieser{STR_VAR_3}aus WURZELHEIM\l"
	.string "als total trendy angedreht...$"

TrendWatcher_Text_PhraseWasHopeless::
	.string "Aber das war ein kompletter Schuss in\n"
	.string "den Ofen.\p"
	.string "{STR_VAR_1} {STR_VAR_2}-Festival!\p"
	.string "{STR_VAR_1} {STR_VAR_2}-Wettbewerb!\p"
	.string "Ich hab echt versucht, das allen bei-\n"
	.string "zubringen, aber...\p"
	.string "Vielleicht war der{STR_VAR_1}-Teil einfach\n"
	.string "kompletter Müll...\p"
	.string "MC: Äh, Entschuldigung, Opa, aber ich\n"
	.string "muss wissen, was JETZT in ist...$"

TrendWatcher_Text_MaleTellMeBigger::
	.string "Alter Sack:{STR_VAR_3}!\n"
	.string "Bitte sag mir, dass es was Besseres gibt\l"
	.string "als dieses{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_FemaleTellMeBigger::
	.string "Alter Sack:{STR_VAR_3}!\n"
	.string "Bitte sag mir, dass es was Besseres gibt\l"
	.string "als dieses{STR_VAR_1} {STR_VAR_2}!$"

TrendWatcher_Text_Outro::
	.string "MC: ...Äh... Also, da habt ihr's,\n"
	.string "ihr trendigen Spackos da draußen!\p"
	.string "{STR_VAR_1} {STR_VAR_2}...äh...\n"
	.string "War in FAUSTAUHAVEN nie angesagt!\p"
	.string "Meine Zeit ist um. Haut rein!\p"
	.string "Alter Sack:{STR_VAR_1} {STR_VAR_2}!$"

gTVHoennTreasureInvestigatorsText00::
	.string "DIE HOENN-SCHATZSUCHER!\p"
	.string "Hi, Bande!\n"
	.string "Geheime Items abgestaubt in letzter Zeit?\p"
	.string "Wie immer checken wir Augenzeugen-\n"
	.string "berichte über verstecktes Zeug!\p"
	.string "Fangen wir mit 'nem Brief an.\n"
	.string "Da steht: “{STR_VAR_1}entdeckt!“$"

gTVHoennTreasureInvestigatorsText01::
	.string "Wow, den Brief müssen wir uns mal\n"
	.string "reinziehen! Ich les ihn euch vor.\p"
	.string "...Liebe SCHATZSUCHER,\n"
	.string "ich hoffe, euch geht's gut.\p"
	.string "Ich hab letztens{STR_VAR_2}irgendwo\n"
	.string "bei{STR_VAR_3}gesehen.\p"
	.string "Der TRAINER hat das Item\n"
	.string "{STR_VAR_1}gefunden. Ich bin mega neidisch.\p"
	.string "...Na, guter Job,{STR_VAR_2}!\p"
	.string "Zuschauer, lasst euch davon anheizen!\n"
	.string "Schmeißt den DETEKTOR an und sucht!\p"
	.string "Ich wart auf geile News von euch allen!$"

gTVHoennTreasureInvestigatorsText02::
	.string "Wow, den Brief müssen wir uns mal\n"
	.string "reinziehen! Ich les ihn euch vor.\p"
	.string "...Liebe SCHATZSUCHER,\n"
	.string "ich hoffe, euch geht's gut.\p"
	.string "Ich hab letztens{STR_VAR_2}auf'm\n"
	.string "Schiff gesehen.\p"
	.string "Der TRAINER hat das Item\n"
	.string "{STR_VAR_1}gefunden. Ich bin mega neidisch.\p"
	.string "...Na, guter Job,{STR_VAR_2}!\p"
	.string "Zuschauer, lasst euch davon anheizen!\n"
	.string "Schmeißt den DETEKTOR an und sucht!\p"
	.string "Ich wart auf geile News von euch allen!$"

gTVFindThatGamerText00::
	.string "FINDE DAS SPIELHALLEN-OPFER!\p"
	.string "Ey, ihr ganzen Zocker!\n"
	.string "Wie läuft's am{STR_VAR_2}?\p"
	.string "Wie immer beleuchten wir einen seltenen\n"
	.string "Spacko, der die SPIELHALLE besucht hat!\p"
	.string "Heute ist unser Top-Gamer...\n"
	.string "{STR_VAR_1}!$"

gTVFindThatGamerText01::
	.string "{STR_VAR_1}hat am{STR_VAR_2}\n"
	.string "gezockt und krankhafte{STR_VAR_3}\l"
	.string "MÜNZEN gewonnen.\p"
	.string "“Wenn{STR_VAR_1}reinkommt, müssen\n"
	.string "wir gucken, dass genug MÜNZEN da sind.“\p"
	.string "Das murmeln die Kassierer, wenn unser\n"
	.string "Zocker am Automaten hängt!\p"
	.string "Zuschauer, passt besser auf eure MÜNZEN\n"
	.string "auf, wenn ihr wie{STR_VAR_1}am\l"
	.string "{STR_VAR_2}in der SPIELHALLE hängt.\p"
	.string "Das ist live aus der SPIELHALLE -- wo die\n"
	.string "Spielsucht greifbar ist!\p"
	.string "Das war's für heute!$"

gTVFindThatGamerText02::
	.string "{STR_VAR_1}hat am{STR_VAR_2}\n"
	.string "gezockt und erbärmliche{STR_VAR_3}\l"
	.string "MÜNZEN verzockt.\p"
	.string "“Wenn{STR_VAR_1}reinkommt, geht unser\n"
	.string "MÜNZ-Verkauf steil nach oben.“\p"
	.string "Das sagen die Kassierer, wenn unser\n"
	.string "Zocker-Opfer da ist!$"

gTVFindThatGamerText03::
	.string "Zuschauer, passt besser auf eure MÜNZEN\n"
	.string "auf, wenn ihr wie{STR_VAR_1}am\l"
	.string "{STR_VAR_2}in der SPIELHALLE hängt.\p"
	.string "Das ist live aus der SPIELHALLE -- wo die\n"
	.string "Spielsucht greifbar ist!\p"
	.string "Das war's für heute!$"

gTVBreakingNewsText00::
	.string "EILMELDUNG-TV!$"

gTVBreakingNewsText01::
	.string "Seltenes{STR_VAR_2}von\n"
	.string "{STR_VAR_1}gefangen!\p"
	.string "Wir sind live aus der Nähe von\n"
	.string "{STR_VAR_3}!\p"
	.string "{STR_VAR_1}hat hier vorhin\n"
	.string "erfolgreich ein seltenes{STR_VAR_2}eingetütet!$"

gTVBreakingNewsText02::
	.string "Als{STR_VAR_1}dem seltenen\n"
	.string "{STR_VAR_2}begegnet ist, hat er sein\l"
	.string "{STR_VAR_3}in den Kampf geschickt.$"

gTVBreakingNewsText03::
	.string "Im Kampf hat der TRAINER ganze\n"
	.string "{STR_VAR_1}POKéBÄLLE verballert.\p"
	.string "Letztendlich wurde das Vieh mit\n"
	.string "dem letzten{STR_VAR_2}gefangen.$"

gTVBreakingNewsText04::
	.string "In dem Moment hallte{STR_VAR_1}s Sieges-\n"
	.string "schrei quer durch{STR_VAR_2}.\p"
	.string "Muss schon sagen, bin ein bisschen\n"
	.string "neidisch auf{STR_VAR_1}. Würd auch gern so\l"
	.string "rumbrüllen.\p"
	.string "...Damit beenden wir die Live-Schalte\n"
	.string "von diesem freudigen Ereignis!$"

gTVBreakingNewsText05::
	.string "{STR_VAR_1}verkackt es, ein seltenes\n"
	.string "{STR_VAR_2}zu fangen!\p"
	.string "Wir sind live aus der Nähe von\n"
	.string "{STR_VAR_3}!\p"
	.string "Hier hat{STR_VAR_1}es komplett verhauen,\n"
	.string "ein seltenes{STR_VAR_2}zu schnappen!$"

gTVBreakingNewsText06::
	.string "Als{STR_VAR_1}dem seltenen\n"
	.string "{STR_VAR_2}begegnet ist, hat er sein\l"
	.string "{STR_VAR_3}in den Kampf geschickt.$"

gTVBreakingNewsText07::
	.string "Der TRAINER hat sein{STR_VAR_2}\n"
	.string "die Attacke{STR_VAR_1}machen lassen.\p"
	.string "Aus Versehen hat der Dummbatz\n"
	.string "das seltene POKéMON umgeklatscht...$"

gTVBreakingNewsText12::
	.string "Aber{STR_VAR_1}hat beim Anblick des\n"
	.string "seltenen{STR_VAR_2}Panik bekommen.\p"
	.string "Völlig verwirrt hat der TRAINER\n"
	.string "{STR_VAR_3}den Angriffsbefehl gegeben.\p"
	.string "Aus Versehen hat der Dummbatz\n"
	.string "das seltene POKéMON umgeklatscht.$"

gTVBreakingNewsText08::
	.string "In dem Moment hallte{STR_VAR_1}s Frust-\n"
	.string "schrei quer durch{STR_VAR_2}...$"

gTVBreakingNewsText09::
	.string "Aber{STR_VAR_1}hatte scheinbar keine\n"
	.string "POKéBÄLLE mehr. Was für'n Noob.\p"
	.string "Der TRAINER musste den Kampf gegen das\n"
	.string "seltene{STR_VAR_2}abbrechen.\p"
	.string "In dem Moment hallte{STR_VAR_1}s Frust-\n"
	.string "schrei quer durch{STR_VAR_3}...$"

gTVBreakingNewsText10::
	.string "Aber das verfluchte{STR_VAR_2}ist einfach\n"
	.string "ohne Vorwarnung abgehauen.\p"
	.string "In dem Moment hallte{STR_VAR_1}s Frust-\n"
	.string "schrei quer durch{STR_VAR_3}...$"

gTVBreakingNewsText11::
	.string "Ich muss sagen, ich fühl mit{STR_VAR_1}.\n"
	.string "Da würd ich auch am liebsten losschreien.\p"
	.string "...Damit beenden wir die Live-Schalte\n"
	.string "von diesem extrem peinlichen Moment!$"

gTVSecretBaseVisitText00::
	.string "Moin Leute!\n"
	.string "Zeit für einen neuen\l"
	.string "GEHEIMBASIS-BESUCH.\p"
	.string "Heute brechen wir in die GEHEIMBASIS\n"
	.string "von{STR_VAR_1}ein.\p"
	.string "Wie hat{STR_VAR_1}seine Bude\n"
	.string "eingerichtet?\p"
	.string "Finden wir's raus!\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText01::
	.string "Oh!\n"
	.string "Wie geil ist das denn!\p"
	.string "Dieses{STR_VAR_2}...\n"
	.string "Das erwartet man hier ja mal gar nicht!$"

gTVSecretBaseVisitText02::
	.string "Oh!\n"
	.string "Wie bemerkenswert!\p"
	.string "Hier steht nicht ein einziges Möbelstück!\n"
	.string "Keine Deko, gar nichts!\p"
	.string "Normale Leute könnten so ein krasses\n"
	.string "Statement gar nicht bringen!\p"
	.string "Es ist simpel, aber es sprüht nur so\n"
	.string "vor purem Wahnsinn!\p"
	.string "Hut ab,{STR_VAR_1}.\n"
	.string "War ja klar, dass du das bringst!$"

gTVSecretBaseVisitText03::
	.string "Oh! Ich verstehe!\n"
	.string "Ganz klar, ich peil's jetzt!\p"
	.string "Dass dieses{STR_VAR_2}hier steht...\n"
	.string "Das hat 'ne richtige Message!$"

gTVSecretBaseVisitText04::
	.string "Oh! Ich verstehe!\n"
	.string "Ganz klar, ich peil's jetzt!\p"
	.string "Dieser Platz hier wird absichtlich\n"
	.string "komplett leer gelassen!\p"
	.string "Das hat 'ne richtige Message!$"

gTVSecretBaseVisitText05::
	.string "Puuuuh!\p"
	.string "Die Kombi aus{STR_VAR_2}\n"
	.string "und{STR_VAR_3}!\p"
	.string "Das ist mal echt 'ne kranke Traum-Kombi!$"

gTVSecretBaseVisitText06::
	.string "Puuuuh!\p"
	.string "Dass dieses{STR_VAR_2}\n"
	.string "genau hier platziert ist...\p"
	.string "Das füllt die ganze GEHEIMBASIS aus!$"

gTVSecretBaseVisitText07::
	.string "Puuuuh!\p"
	.string "Hier steht einfach absolut gar nichts.\p"
	.string "Dieser leere Raum wirkt sich auf die\n"
	.string "ganze GEHEIMBASIS aus.$"

gTVSecretBaseVisitText08::
	.string "Oh!\n"
	.string "Da kommt{STR_VAR_1}!\l"
	.string "Lasst uns den TRAINER herausfordern!\p"
	.string "… … … … … …\n"
	.string "… … … … … …$"

gTVSecretBaseVisitText09::
	.string "Seufz...\n"
	.string "Das muss man{STR_VAR_1}lassen.\p"
	.string "Die POKéMON waren echt auf\n"
	.string "CHAMP-Niveau.\p"
	.string "Die haben echt bewiesen, dass{STR_VAR_1}\n"
	.string "ein knallharter TRAINER ist.\p"
	.string "Dass das{STR_VAR_2}die Attacke\n"
	.string "{STR_VAR_3}draufhatte...\p"
	.string "Das zeigt schon, was für'n Typ\n"
	.string "{STR_VAR_1}ist.\p"
	.string "War auf jeden Fall 'ne krasse Lektion!$"

gTVSecretBaseVisitText10::
	.string "Aiyeeh!\n"
	.string "Das muss man{STR_VAR_1}lassen.\p"
	.string "Die POKéMON waren echt extrem krank\n"
	.string "drauf!\p"
	.string "Die haben echt bewiesen, dass{STR_VAR_1}\n"
	.string "niemals aufgibt.\p"
	.string "Dass das{STR_VAR_2}die Attacke\n"
	.string "{STR_VAR_3}draufhatte...\p"
	.string "Das zeigt schon, was für'n Typ\n"
	.string "{STR_VAR_1}ist.\p"
	.string "War auf jeden Fall 'ne krasse Lektion!$"

gTVSecretBaseVisitText11::
	.string "Puuuuh!\n"
	.string "Das muss man{STR_VAR_1}lassen.\p"
	.string "Die POKéMON waren extrem krass\n"
	.string "ausbalanciert trainiert.\p"
	.string "Die haben echt bewiesen, dass{STR_VAR_1}\n"
	.string "ein ziemlich schlauer TRAINER ist.\p"
	.string "Dass das{STR_VAR_2}die Attacke\n"
	.string "{STR_VAR_3}draufhatte...\p"
	.string "Das zeigt schon, was für'n Typ\n"
	.string "{STR_VAR_1}ist.\p"
	.string "War auf jeden Fall 'ne krasse Lektion!$"

gTVSecretBaseVisitText12::
	.string "Oha!\n"
	.string "Das muss man{STR_VAR_1}lassen.\p"
	.string "Die POKéMON haben echt extrem viel\n"
	.string "Potenzial.\p"
	.string "Da merkt man richtig{STR_VAR_1}s\n"
	.string "Träume und Hoffnungen.\p"
	.string "Dass das{STR_VAR_2}die Attacke\n"
	.string "{STR_VAR_3}draufhatte...\p"
	.string "Das zeigt schon, was für'n Typ\n"
	.string "{STR_VAR_1}ist.\p"
	.string "War auf jeden Fall 'ne krasse Lektion!$"

gTVSecretBaseVisitText13::
	.string "Muss man schon sagen, war 'ne geile\n"
	.string "GEHEIMBASIS!\p"
	.string "Zuschauer, wenn ihr mal die Chance habt,\n"
	.string "brecht bei{STR_VAR_1}ein.\p"
	.string "Bis zum nächsten Mal, ciao!$"

gTVPokemonLotteryWinnerFlashReportText00::
	.string "Es ist spannend!\n"
	.string "Es ist dramatisch!\p"
	.string "Es ist der POKéMON-LOTTERIE-\n"
	.string "GEWINNER-BLITZBERICHT!\p"
	.string "Hallo! Wir sind live aus der POKéMON-\n"
	.string "LOTTERIE im Erdgeschoss des\l"
	.string "EINKAUFSZENTRUMS in SEEGRAZUL CITY!\p"
	.string "Wie immer ist heute wieder ein TRAINER\n"
	.string "aufgetaucht, der mehr Glück als Verstand hat!\p"
	.string "Der Name des Glückspilzes...\n"
	.string "{STR_VAR_1}!\p"
	.string "{STR_VAR_1}hat den{STR_VAR_2}-Preis\n"
	.string "abgestaubt und nimmt das{STR_VAR_3}mit!\p"
	.string "{STR_VAR_1}!\n"
	.string "Glückwunsch, du Glücksschwein!\p"
	.string "Zuschauer, glotzt nicht nur, kauft\n"
	.string "auch mal 'n Los!\p"
	.string "Wir im EINKAUFSZENTRUM SEEGRAZUL CITY\n"
	.string "warten schon auf eure Kohle!\p"
	.string "Das war live aus dem EINKAUFSZENTRUM\n"
	.string "SEEGRAZUL CITY -- wir haben den geilsten\l"
	.string "Kram in ganz HOENN!$"

gTVThePokemonBattleSeminarText00::
	.string "DAS POKéMON KAMPF-SEMINAR!\p"
	.string "Wir checken Kämpfe ab, um zu sehen, was\n"
	.string "wir von den Fails der anderen lernen können.\p"
	.string "Heute lästern wir über den Kampf von\n"
	.string "{STR_VAR_1}.\p"
	.string "{STR_VAR_1}s{STR_VAR_2}hat gegen\n"
	.string "ein{STR_VAR_3}gekämpft...$"

gTVThePokemonBattleSeminarText01::
	.string "Und dann kam die Attacke{STR_VAR_3}\n"
	.string "auf das{STR_VAR_2}...\p"
	.string "Hmm...{STR_VAR_1}!\n"
	.string "Was für'n absolut dummer Move!$"

gTVThePokemonBattleSeminarText02::
	.string "Neben der verkackten Attacke hatte das\n"
	.string "{STR_VAR_1}vom TRAINER auch noch$"

gTVThePokemonBattleSeminarText03::
	.string "die Attacken{STR_VAR_1},{STR_VAR_2}\n"
	.string "und{STR_VAR_3}drauf.$"

gTVThePokemonBattleSeminarText04::
	.string "die Attacken{STR_VAR_1}und\n"
	.string "{STR_VAR_2}drauf.$"

gTVThePokemonBattleSeminarText05::
	.string "die Attacke{STR_VAR_2}drauf.$"

gTVThePokemonBattleSeminarText06::
	.string "Also, was hätte der TRAINER hier\n"
	.string "besser einsetzen sollen?\p"
	.string "… … … … … …\n"
	.string "Die Attacke{STR_VAR_1}!\p"
	.string "Die Attacke{STR_VAR_1}wär tausendmal\n"
	.string "besser gewesen als{STR_VAR_2}.\p"
	.string "Zuschauer, schaltet mal euer Hirn ein\n"
	.string "beim Kämpfen und lernt draus!\p"
	.string "Bis zum nächsten Mal, haut rein!$"

gTVTrainerFanClubText00::
	.string "Alle zusammen jetzt!\n"
	.string "TRAINER FANCLUB!\p"
	.string "MC: Wie ist die Stimmung, ihr Freaks?\n"
	.string "Heute haben wir die ganzen kranken Fans vom\l"
	.string "Hyper-TRAINER{STR_VAR_1}eingesammelt!\p"
	.string "FANS: Wrooooooaaaaah!\p"
	.string "FANS:{STR_VAR_1}!\p"
	.string "MC: Ey Leute!\n"
	.string "Wie geil findet ihr{STR_VAR_1}?!\p"
	.string "FANS: Wir lieben{STR_VAR_1}!\p"
	.string "MC: Was liebt ihr denn so an\n"
	.string "{STR_VAR_1}?!$"

gTVTrainerFanClubText01::
	.string "FANS: Diese unnormal coole Art, wie die\n"
	.string "POKéBÄLLE geworfen werden!$"

gTVTrainerFanClubText02::
	.string "FANS: Wie süß und knuffig rumgerannt wird!$"

gTVTrainerFanClubText03::
	.string "FANS: Wie der TRAINER einfach knallhart\n"
	.string "wird, wenn's mies aussieht!$"

gTVTrainerFanClubText04::
	.string "FANS: Das krasse Nerd-Wissen über POKéMON!$"

gTVTrainerFanClubText05::
	.string "FANS: Dass der TRAINER alle POKéMON\n"
	.string "so eklig lieb behandelt!$"

gTVTrainerFanClubText06::
	.string "FANS: Wie krass auf dem RAD rumgeheizt wird!$"

gTVTrainerFanClubText07::
	.string "FANS: Dieser absolut fette Einkaufs-Style!$"

gTVTrainerFanClubText08::
	.string "FANS: Diese mega dummen Spitznamen für\n"
	.string "die POKéMON!$"

gTVTrainerFanClubText09::
	.string "FANS: Der krasse Geschmack beim\n"
	.string "Einrichten der GEHEIMBASIS!$"

gTVTrainerFanClubText10::
	.string "FANS: Wie eiskalt die TMs rausgeballert\n"
	.string "werden!$"

gTVTrainerFanClubText11::
	.string "MC: Wie ihr seht, ist{STR_VAR_1}\n"
	.string "richtig heiß! Fast schon ZU heiß!\p"
	.string "Unter den Fans von{STR_VAR_1}\n"
	.string "gibt's 'nen krassen Insider-Spruch!\p"
	.string "MC: Wenn ich sage{STR_VAR_1},\n"
	.string "dann brüllt ihr...\p"
	.string "FANS:{STR_VAR_2}!\p"
	.string "FANS:{STR_VAR_3}!\p"
	.string "FANS:{STR_VAR_2}!\p"
	.string "FANS:{STR_VAR_3}!\p"
	.string "MC: Richtig, wenn einer schreit:\n"
	.string "“{STR_VAR_1}“...\p"
	.string "Dann brüllt ihr zurück: “{STR_VAR_2}\n"
	.string "{STR_VAR_3}!“\p"
	.string "Das klingt echt komplett bescheuert!\n"
	.string "Kein Wunder, dass alle Fans von\l"
	.string "{STR_VAR_1}werden!\p"
	.string "Okay, und ihr Opfer vorm Fernseher macht\n"
	.string "jetzt mit! Alle zusammen!\p"
	.string "MC: Wenn ich sage{STR_VAR_1},\n"
	.string "dann brüllt ihr...\p"
	.string "FANS:{STR_VAR_2}!\p"
	.string "FANS:{STR_VAR_3}!\p"
	.string "FANS:{STR_VAR_2}!\p"
	.string "FANS:{STR_VAR_3}!\p"
	.string "MC: Danke fürs Mitmachen, ihr\n"
	.string "gestörten Fans von{STR_VAR_1}!\l"
	.string "Das war die Show! Man sieht sich!\p"
	.string "MC: Wenn ich sage{STR_VAR_1},\n"
	.string "dann brüllt ihr...\p"
	.string "FANS:{STR_VAR_2}!\p"
	.string "FANS:{STR_VAR_3}!$"

TVSpotTheCuties_Text_Intro::
	.string "SUCH DIR DIE SÜSSEN RAUS!\n"
	.string "POKéMON MIT BÄNDERN!\p"
	.string "Hallo, meine süßen Zuschauer!\p"
	.string "Ich weiß genau, ihr gebt mir Recht: Ein\n"
	.string "POKéMON mit BÄNDERN ist einfach geil!\p"
	.string "Heute zeig ich euch ein echt schniekes\n"
	.string "POKéMON, das mir in der Stadt aufgefallen ist.\p"
	.string "Das heutige Fashion-Opfer ist das\n"
	.string "{STR_VAR_2}von{STR_VAR_1}.$"

TVSpotTheCuties_Text_RibbonsLow::
	.string "Die Anzahl der BÄNDER, die das\n"
	.string "{STR_VAR_2}trägt, ist{STR_VAR_3}.\p"
	.string "Man merkt echt, wie krass{STR_VAR_1}\n"
	.string "das POKéMON anhimmelt.$"

TVSpotTheCuties_Text_RibbonsMid::
	.string "{STR_VAR_2}hat sage und schreibe\n"
	.string "{STR_VAR_3}BÄNDER umhängen!\p"
	.string "Das zeigt mal, wie hart{STR_VAR_1}sich\n"
	.string "für das POKéMON den Arsch aufreißt!$"

TVSpotTheCuties_Text_RibbonsHigh::
	.string "{STR_VAR_2}hat unnormale\n"
	.string "{STR_VAR_3}BÄNDER umhängen!\p"
	.string "Das zeigt,{STR_VAR_1}ist komplett\n"
	.string "süchtig nach dem Sammeln!$"

TVSpotTheCuties_Text_RibbonIntro::
	.string "Lasst uns mal die ganzen BÄNDER\n"
	.string "von{STR_VAR_2}genauer abchecken.$"

TVSpotTheCuties_Text_RibbonChampion::
	.string "Das BAND DES CHAMPIONS ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für den Einzug in\n"
	.string "die RUHMESHALLE abgestaubt.\p"
	.string "Das zeigt echt, was für 'n harter Hund\n"
	.string "das{STR_VAR_2}ist.\p"
	.string "{STR_VAR_2}und das CHAMP-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonCool::
	.string "Das BAND DER COOLNESS ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für 'nen Sieg im\n"
	.string "COOLNESS-WETTBEWERB gekriegt.\p"
	.string "Das holt die ganze Coolness von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das COOLNESS-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonBeauty::
	.string "Das BAND DER SCHÖNHEIT ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für 'nen Sieg im\n"
	.string "SCHÖNHEITS-WETTBEWERB gekriegt.\p"
	.string "Das holt die ganze Schönheit von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das SCHÖNHEITS-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonCute::
	.string "Das BAND DER ANMUT ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für 'nen Sieg im\n"
	.string "ANMUT-WETTBEWERB gekriegt.\p"
	.string "Das holt die ganze Süßigkeit von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das ANMUT-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonSmart::
	.string "Das BAND DER KLUGHEIT ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für 'nen Sieg im\n"
	.string "KLUGHEITS-WETTBEWERB gekriegt.\p"
	.string "Das holt die ganze Klugheit von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das KLUGHEITS-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonTough::
	.string "Das BAND DER STÄRKE ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für 'nen Sieg im\n"
	.string "STÄRKE-WETTBEWERB gekriegt.\p"
	.string "Das holt die ganze Stärke von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das STÄRKE-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonWinning::
	.string "Das SIEGER-BAND ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für krasse Siege im\n"
	.string "DUELLTURM bekommen.\p"
	.string "Das holt die ganze Kampfkraft von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das SIEGER-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonVictory::
	.string "Das SIEG-BAND ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das für fette Siege im\n"
	.string "DUELLTURM bekommen.\p"
	.string "Das holt die unglaubliche Power von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das SIEG-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonArtist::
	.string "Das BAND DES KÜNSTLERS ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das bekommen, weil's für 'n\n"
	.string "Künstler Modell gestanden hat.\p"
	.string "Das holt den ganzen Popstar-Charme von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das KÜNSTLER-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_RibbonEffort::
	.string "Das FLEISS-BAND ist echt 'n\n"
	.string "Hingucker.\p"
	.string "{STR_VAR_2}hat das bekommen, weil's sich\n"
	.string "richtig den Arsch aufgerissen hat.\p"
	.string "Das holt den krassen Ehrgeiz von\n"
	.string "{STR_VAR_2}raus.\p"
	.string "{STR_VAR_2}und das FLEISS-BAND!\n"
	.string "Die Kombi ist echt sehr effektiv!$"

TVSpotTheCuties_Text_Outro::
	.string "...Seufz...\p"
	.string "BÄNDER und POKéMON...\n"
	.string "Das passt einfach wie Arsch auf Eimer!\p"
	.string "Bevor ich hier noch umkippe,\n"
	.string "hau ich lieber ab!$"

gTVPokemonNewsBattleFrontierText00::
	.string "Moin!\n"
	.string "Zeit für die POKéMON-NEWS.\p"
	.string "Wir haben ein paar kranke News aus der\n"
	.string "KAMPFZONE für euch.$"

gTVPokemonNewsBattleFrontierText01::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück in der\l"
	.string "EINZELKAMPF-Runde vom DUELLTURM aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText02::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück in der\l"
	.string "DOPPELKAMPF-Runde vom DUELLTURM aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText03::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück in der\l"
	.string "MULTIKAMPF-Runde vom DUELLTURM aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText04::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück in der\l"
	.string "LINK-MULTIKAMPF-Runde vom DUELLTURM aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText05::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Meisterschaften am Stück\l"
	.string "im EINZELKAMPF-Turnier vom KAMPFSTADION aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText06::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Meisterschaften am Stück\l"
	.string "im DOPPELKAMPF-Turnier vom KAMPFSTADION aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText07::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück im\l"
	.string "Tausch-Einzelkampf der KAMPFFABRIK aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText08::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück im\l"
	.string "Tausch-Doppelkampf der KAMPFFABRIK aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText09::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}geschafften Räumen bei der\l"
	.string "Wegwahl-Herausforderung in der KAMPFIPITIS aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText10::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück bei den\l"
	.string "K.O.-Turnieren im KAMPFRING aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText11::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück im\l"
	.string "EINZELKAMPF-Saal vom KAMPFPALAST aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText12::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}Siegen am Stück im\l"
	.string "DOPPELKAMPF-Saal vom KAMPFPALAST aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText13::
	.string "Der TRAINER{STR_VAR_1}hat einen neuen\n"
	.string "Rekord von{STR_VAR_2}geschafften Etagen bei der\l"
	.string "Kampf-Mission in der KAMPFPYRAMIDE aufgestellt.\p"
	.string "Applaus für{STR_VAR_1}!$"

gTVPokemonNewsBattleFrontierText14::
	.string "Und auch an die drei POKéMON,{STR_VAR_1},\n"
	.string "{STR_VAR_2}und{STR_VAR_3}!\p"
	.string "Glückwunsch zu dieser kranken Leistung!$"

gTVPokemonNewsBattleFrontierText15::
	.string "Und auch an die zwei POKéMON,{STR_VAR_1}\n"
	.string "und{STR_VAR_2}!\p"
	.string "Glückwunsch zu dieser kranken Leistung!$"

gTVPokemonNewsBattleFrontierText16::
	.string "Und an die vier POKéMON:{STR_VAR_1}!\p"
	.string "{STR_VAR_2}!\p"
	.string "{STR_VAR_3}!$"

gTVPokemonNewsBattleFrontierText17::
	.string "Und{STR_VAR_1}!\p"
	.string "Glückwunsch zu dieser kranken Leistung!$"

gTVPokemonNewsBattleFrontierText18::
	.string "Hoffen wir mal auf noch mehr Rekorde\n"
	.string "von{STR_VAR_1}und den Viechern!\p"
	.string "Das waren die POKéMON-NEWS!$"

gTVWhatsNo1InHoennTodayText00::
	.string "WER IST HEUTE NUMMER 1 IN HOENN?\n"
	.string "Ja, es ist wieder soweit!\p"
	.string "Moin, Zuschauer! Gebt ihr auch schön brav\n"
	.string "100 Prozent bei allem, was ihr so tut?\p"
	.string "Gucken wir uns mal an, welcher TRAINER\n"
	.string "heute am krassesten rasiert hat!\p"
	.string "Der TRAINER Numero 1 ist heute niemand\n"
	.string "Geringeres als{STR_VAR_1}!$"

gTVWhatsNo1InHoennTodayText01::
	.string "An nur einem Tag hat{STR_VAR_1}die Automaten\n"
	.string "in der SPIELHALLE{STR_VAR_2}Mal gedreht.\p"
	.string "Beim Zocken hat man{STR_VAR_1}murmeln\n"
	.string "hören: “Bei mir bewegen sich die Rollen\l"
	.string "nicht mal...“\l"
	.string "Echt interessant, oder?$"

gTVWhatsNo1InHoennTodayText02::
	.string "An nur einem Tag hat{STR_VAR_1}am\n"
	.string "ROULETTE in der SPIELHALLE ganze\l"
	.string "{STR_VAR_2}Mal gezockt.\p"
	.string "Dabei brüllte{STR_VAR_1}:\n"
	.string "“Lass die Kugeln entscheiden!“\p"
	.string "Man sah dem TRAINER die pure Spielsucht an.$"

gTVWhatsNo1InHoennTodayText03::
	.string "An nur einem Tag hat{STR_VAR_1}wilde\n"
	.string "POKéMON{STR_VAR_2}Mal verkloppt!\p"
	.string "Anscheinend sind die POKéMON von\n"
	.string "{STR_VAR_1}echt unnormal stark geworden.\p"
	.string "Die haben wohl Bock, immer und überall\n"
	.string "Stress zu schieben!$"

gTVWhatsNo1InHoennTodayText04::
	.string "An nur einem Tag hat{STR_VAR_1}den BEEREN-\n"
	.string "MIXER{STR_VAR_2}Mal zum Glühen gebracht!\p"
	.string "Am Ende war selbst{STR_VAR_1}komplett\n"
	.string "dizzy im Kopf.\p"
	.string "Der TRAINER torkelte rum wie ein\n"
	.string "besoffenes PANDIR!$"

gTVWhatsNo1InHoennTodayText05::
	.string "An nur einem Tag hat{STR_VAR_1}ganze\n"
	.string "{STR_VAR_2}BEEREN in den Dreck gesteckt!\p"
	.string "Danach sahen die Klamotten von\n"
	.string "{STR_VAR_1}aus wie Sau.\p"
	.string "Da, wo gepflanzt wurde, sprießen jetzt\n"
	.string "tausende Blumen aus dem Boden.\p"
	.string "Die Blumen sollen die Leute angeblich\n"
	.string "beruhigen. Wer's glaubt...$"

gTVWhatsNo1InHoennTodayText06::
	.string "An nur einem Tag hat{STR_VAR_1}ganze\n"
	.string "{STR_VAR_2}BEEREN abgerissen!\p"
	.string "{STR_VAR_1}s BEUTEL war so vollgestopft mit\n"
	.string "BEEREN, der Typ konnte danach kaum\l"
	.string "noch laufen!$"

gTVWhatsNo1InHoennTodayText07::
	.string "An nur einem Tag hat{STR_VAR_1}ganze\n"
	.string "{STR_VAR_2}Gewinnpunkte abgestaubt!\p"
	.string "{STR_VAR_1}wurde später gesehen, wie er\n"
	.string "verzweifelt überlegte, ob er die Punkte\l"
	.string "für Items oder Deko raushaut.\p"
	.string "Angeblich hat der TRAINER dabei die ganze\n"
	.string "Zeit dümmlich gegrinst.$"

gTVWhatsNo1InHoennTodayText08::
	.string "Ist das nicht geil?!\p"
	.string "{STR_VAR_1}!\n"
	.string "Du bist heute unsere Nummer 1!\p"
	.string "Zuschauer, nehmt euch ein Beispiel an\n"
	.string "{STR_VAR_1}! Auch ihr könnt jeden Tag\l"
	.string "die Nummer 1 sein (auch wenn ihr verliert)!$"

TVSecretBaseSecrets_Text_Intro::
	.string "GEHEIMBASIS-GEHEIMNISSE!\p"
	.string "Was treiben TRAINER eigentlich heimlich in\n"
	.string "ihren GEHEIMBASEN?\p"
	.string "Heute spionieren wir in der GEHEIMBASIS\n"
	.string "von{STR_VAR_1}rum.\p"
	.string "Oh? Sieht aus, als wäre{STR_VAR_2}\n"
	.string "auf Besuch da.\p"
	.string "Gucken wir mal zu!\p"
	.string "Was wird{STR_VAR_2}jetzt machen?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext1::
	.string "Was wird{STR_VAR_2}als Nächstes anstellen?$"

TVSecretBaseSecrets_Text_WhatWillPlayerDoNext2::
	.string "Und was macht{STR_VAR_2}jetzt?$"

TVSecretBaseSecrets_Text_TookXStepsBeforeLeaving::
	.string "Am Ende ist{STR_VAR_2}einfach{STR_VAR_3}Schritte\n"
	.string "durch{STR_VAR_1}s GEHEIMBASIS gelatscht,\l"
	.string "bevor er abgehauen ist.$"

TVSecretBaseSecrets_Text_BaseFailedToInterestPlayer::
	.string "Hmm...\p"
	.string "Sieht so aus, als ob{STR_VAR_1}s GEHEIMBASIS\n"
	.string "{STR_VAR_2}komplett am Arsch vorbei ging...$"

TVSecretBaseSecrets_Text_PlayerEnjoyedBase::
	.string "{STR_VAR_2}scheint{STR_VAR_1}s GEHEIMBASIS\n"
	.string "echt hart gefeiert zu haben.$"

TVSecretBaseSecrets_Text_PlayerHugeFanOfBase::
	.string "{STR_VAR_2}scheint jetzt wohl der größte Fan\n"
	.string "von{STR_VAR_1}s GEHEIMBASIS zu sein.$"

TVSecretBaseSecrets_Text_Outro::
	.string "Vielleicht haben die Zuschauer ja jetzt auch\n"
	.string "Bock, in{STR_VAR_1}s Bude einzubrechen.\p"
	.string "Schaltet nächstes Mal ein, wenn wir wieder in\n"
	.string "'ne fremde Basis stalken! Danke fürs Zusehen!$"

TVSecretBaseSecrets_Text_StoppedMoving1::
	.string "Der Besucher bleibt stehen!\p"
	.string "Der Typ bewegt sich gar nicht mehr!\p"
	.string "War{STR_VAR_1}s GEHEIMBASIS etwa so\n"
	.string "sterbenslangweilig?$"

TVSecretBaseSecrets_Text_StoppedMoving2::
	.string "Der Besucher bleibt stehen!\p"
	.string "Der Typ bewegt sich gar nicht mehr!\p"
	.string "Ist er müde?\n"
	.string "Geht dem Besucher die Puste aus?$"

TVSecretBaseSecrets_Text_UsedChair::
	.string "Der Besucher hat sich hingesetzt!\n"
	.string "Der Typ sitzt!\p"
	.string "Guckt euch an, wie der sich freut!\p"
	.string "Der Stuhl muss ja unnormal weich sein,\n"
	.string "bei der Reaktion!$"

TVSecretBaseSecrets_Text_UsedBalloon::
	.string "Der Besucher springt voll in 'nen Ballon rein!\p"
	.string "PENG!\n"
	.string "Meine Fresse, das Ding ist geplatzt!\p"
	.string "Der Besucher hat sich vor dem Knall voll\n"
	.string "in die Hose gemacht!$"

TVSecretBaseSecrets_Text_UsedTent::
	.string "Der Besucher kriecht ins ZELT!\p"
	.string "Der Typ rennt dadrin im Kreis!\p"
	.string "Oh mein Gott, der hat ja den Spaß\n"
	.string "seines Lebens!\p"
	.string "Der Besucher scheint von der Größe\n"
	.string "des ZELTS voll geflasht zu sein!$"

TVSecretBaseSecrets_Text_UsedPlant::
	.string "Der Besucher begafft\n"
	.string "ne Grünpflanze!\p"
	.string "Der Typ hat ja echt 'nen überraschend\n"
	.string "erwachsenen Geschmack!$"

TVSecretBaseSecrets_Text_UsedGoldShield::
	.string "Der Besucher begafft\n"
	.string "ein GOLD-SCHILD!\p"
	.string "Dem Typen fallen ja fast die Augen\n"
	.string "aus dem Kopf vor lauter Staunen!$"

TVSecretBaseSecrets_Text_UsedSilverShield::
	.string "Der Besucher begafft\n"
	.string "ein SILBER-SCHILD!\p"
	.string "Der Besucher guckt wie ein Auto!$"

TVSecretBaseSecrets_Text_UsedGlassOrnament::
	.string "Der Besucher begafft\n"
	.string "eine GLASFIGUR!\p"
	.string "Oh nein!\p"
	.string "Der Besucher tatscht das an!\p"
	.string "Jetzt ist das Ding voller\n"
	.string "Fettfinger...$"

TVSecretBaseSecrets_Text_UsedTV::
	.string "Der Besucher glotzt in die Röhre!\p"
	.string "Da haben wir wohl 'nen echten\n"
	.string "Couch-Potato erwischt!$"

TVSecretBaseSecrets_Text_UsedMudBall::
	.string "Der Besucher ist voll in 'nen LEHMBALL\n"
	.string "gelatscht!\p"
	.string "Der Typ sieht richtig happy aus!$"

TVSecretBaseSecrets_Text_UsedBag::
	.string "...Oh?\p"
	.string "Der Besucher greift in seinen eigenen\n"
	.string "BEUTEL und kramt dadrin rum!\p"
	.string "Der zieht einfach ein\n"
	.string "{STR_VAR_2}raus!\p"
	.string "Guck mal, wie bescheuert der grinst,\n"
	.string "während er das{STR_VAR_2}hochhält!\p"
	.string "Das ist ja wie im Teleshopping!$"

TVSecretBaseSecrets_Text_UsedCushion::
	.string "Der Besucher packt ein Kissen und...$"

TVSecretBaseSecrets_Text_HitCushion::
	.string "...boxt voll rein!\p"
	.string "Hat der Typ irgendwie Aggressionsprobleme?$"

TVSecretBaseSecrets_Text_HuggedCushion::
	.string "...drückt es ganz fest!\p"
	.string "Freut sich da jemand, dass er nicht\n"
	.string "mehr ganz so einsam ist?$"

TVSecretBaseSecrets_Text_BattledWon::
	.string "Der Besucher quatscht mit\n"
	.string "{STR_VAR_1}!\p"
	.string "Sieht so aus, als ob die beiden sich\n"
	.string "jetzt boxen wollen!\p"
	.string "Und...\p"
	.string "Es ist der Besucher!\n"
	.string "Der Besucher hat auswärts gewonnen!\p"
	.string "Der Typ macht grad echt 'nen dummen\n"
	.string "Siegestanz!$"

TVSecretBaseSecrets_Text_BattledLost::
	.string "Der Besucher quatscht mit\n"
	.string "{STR_VAR_1}!\p"
	.string "Sieht so aus, als ob die beiden sich\n"
	.string "jetzt boxen wollen!\p"
	.string "Und...\p"
	.string "Es ist{STR_VAR_1}!\n"
	.string "Der Besucher hat ordentlich kassiert!\p"
	.string "Der Typ guckt, als hätte man ihm den\n"
	.string "Lutscher geklaut!$"

TVSecretBaseSecrets_Text_DeclinedBattle::
	.string "Der Besucher quatscht mit\n"
	.string "{STR_VAR_1}!\p"
	.string "Sieht so aus, als ob die beiden sich\n"
	.string "jetzt boxen wollen!\p"
	.string "Und...\p"
	.string "Nein, der Besucher hat gekniffen!\p"
	.string "Gibt wohl doch keinen Kampf!\p"
	.string "Hat der Besucher vor{STR_VAR_1}\n"
	.string "in die Hose gemacht?$"

TVSecretBaseSecrets_Text_UsedPoster::
	.string "Der Besucher starrt richtig pervers\n"
	.string "auf ein Poster!\p"
	.string "Gefällt dem Besucher das Poster\n"
	.string "so gut?\p"
	.string "...Aber... Dieser Blick ist ja schon\n"
	.string "fast gruselig.$"

TVSecretBaseSecrets_Text_UsedNoteMat::
	.string "Der Besucher ist auf ne TONMATTE gelatscht!\p"
	.string "...Hmm...\n"
	.string "Der Besucher macht ne richtig dumme Melodie!$"

TVSecretBaseSecrets_Text_BattledDraw::
	.string "Der Besucher quatscht mit\n"
	.string "{STR_VAR_1}!\p"
	.string "Sieht so aus, als ob die beiden sich\n"
	.string "jetzt boxen wollen!\p"
	.string "Und...\p"
	.string "Unentschieden!\n"
	.string "Alles umsonst!\p"
	.string "Die beiden TRAINER sehen echt mega\n"
	.string "enttäuscht aus!$"

TVSecretBaseSecrets_Text_UsedSpinMat::
	.string "Der Besucher ist auf 'ne KREISELMATTE\n"
	.string "getreten!\p"
	.string "Dem Typen ist wohl kotzübel!\p"
	.string "Der Besucher torkelt durch die Gegend!\n"
	.string "Pass auf, Alter!$"

TVSecretBaseSecrets_Text_UsedSandOrnament::
	.string "Der Besucher greift nach\n"
	.string "einer SANDFIGUR!\p"
	.string "Oh!\p"
	.string "Es zerbröselt!\n"
	.string "Voll kaputt gegangen!\p"
	.string "Der Besucher guckt mega schuldbewusst!\n"
	.string "Selbst schuld!$"

TVSecretBaseSecrets_Text_UsedDesk::
	.string "Der Besucher reibt mit dem Finger über\n"
	.string "einen Tisch!\p"
	.string "Anscheinend hasst der Besucher Staub!\p"
	.string "Der Typ ist ja echt 'n richtiger Putzteufel!$"

TVSecretBaseSecrets_Text_UsedBrick::
	.string "Der Besucher starrt auf 'nen BLOCK!\p"
	.string "Vielleicht fragt sich der Typ, was der\n"
	.string "Scheiß überhaupt soll.$"

TVSecretBaseSecrets_Text_UsedSolidBoard::
	.string "Der Besucher läuft über das DICKE BRETT.\p"
	.string "Er guckt die ganze Zeit nach unten.\p"
	.string "Der Typ scheint echt ein mega Schisser\n"
	.string "zu sein!$"

TVSecretBaseSecrets_Text_UsedFence::
	.string "Der Besucher starrt mega konzentriert\n"
	.string "auf 'nen ZAUN!\p"
	.string "Denkt sich der Typ da grad 'ne neue\n"
	.string "Falle aus?$"

TVSecretBaseSecrets_Text_UsedGlitterMat::
	.string "Der Besucher ist auf 'ne GLITZERMATTE\n"
	.string "gelatscht!\p"
	.string "Der Besucher zieht voll die peinlichen\n"
	.string "Posen ab!\p"
	.string "Er träumt wohl davon, irgendwann mal\n"
	.string "berühmt zu sein!$"

TVSecretBaseSecrets_Text_UsedTire::
	.string "Der Besucher starrt wie gebannt auf\n"
	.string "einen REIFEN!\p"
	.string "Fragt sich der Typ ernsthaft, an was für 'n\n"
	.string "Auto das Teil gehört?$"

TVSecretBaseSecrets_Text_UsedStand::
	.string "Der Besucher ist auf ein PODEST geklettert!\p"
	.string "Der Typ glotzt von da oben auf\n"
	.string "{STR_VAR_1}s Bude runter!\p"
	.string "Und...\p"
	.string "Er brüllt rum!\n"
	.string "Der Besucher schreit sich die Seele aus'm Leib!$"

TVSecretBaseSecrets_Text_BrokeDoor::
	.string "Der Besucher ist voll in 'ne BRUCHTÜR\n"
	.string "gekracht!\p"
	.string "Der lacht sich ja fast tot darüber!$"

TVSecretBaseSecrets_Text_UsedDoll::
	.string "Der Besucher quatscht mit 'ner PUPPE!\p"
	.string "...Das ist echt gruselig...$"

TVSecretBaseSecrets_Text_UsedSlide::
	.string "Der Besucher klettert auf die RUTSCHE!\p"
	.string "Und...\p"
	.string "Der rutscht runter!\p"
	.string "Scheint ja den Spaß seines Lebens\n"
	.string "zu haben, der Freak!$"

TVSecretBaseSecrets_Text_UsedSlideButDidntGoDown::
	.string "Der Besucher klettert auf die RUTSCHE!\p"
	.string "Und...\p"
	.string "Der geht wieder runter!\p"
	.string "Hat der auf halber Strecke Schiss gekriegt?$"

TVSecretBaseSecrets_Text_UsedJumpMat::
	.string "Der Besucher ist auf 'ne SPRUNGMATTE\n"
	.string "gelatscht!\p"
	.string "Der springt einmal!\p"
	.string "Zweimal!\p"
	.string "Und saubere Landung!\p"
	.string "Der Besucher klatscht für sich selbst!\n"
	.string "Was für 'ne dumme One-Man-Show!$"

gTVSafariFanClubText00::
	.string "SAFARI FANCLUB!\p"
	.string "REPORTER: Okay, ihr Penner!\n"
	.string "Schmeißt ihr auch schön die Bälle rum?\p"
	.string "Ihr könnt drauf wetten, ich bin hier in der\n"
	.string "SAFARI-ZONE voller POKéMON-Viecher!\p"
	.string "Labern wir doch mal mit dem coolen\n"
	.string "SAFARI-WÄRTER hier!\p"
	.string "Also, Meister, was geht bei den TRAINERN so?$"

gTVSafariFanClubText01::
	.string "WÄRTER: Die schwitzen alle richtig rein.\p"
	.string "{STR_VAR_1}macht's besonders gut.\p"
	.string "Vorhin hat{STR_VAR_1}nämlich\n"
	.string "{STR_VAR_2}POKéMON geschnappt.$"

gTVSafariFanClubText02::
	.string "Der TRAINER hat's echt drauf mit den\n"
	.string "{POKEBLOCK}N. Hat{STR_VAR_2}benutzt.$"

gTVSafariFanClubText03::
	.string "Der TRAINER hat nicht einen einzigen\n"
	.string "{POKEBLOCK}verballert! Nicht einen!\p"
	.string "Da ist ein echter Profi am Werk.$"

gTVSafariFanClubText04::
	.string "REPORTER: Ach, ist das so?\p"
	.string "Klingt, als ob unser Kollege{STR_VAR_1}\n"
	.string "ein echter SAFARI-Boss ist!\p"
	.string "WÄRTER: Ich hoffe, der TRAINER kommt wieder\n"
	.string "und zeigt uns noch mal wie's geht.$"

gTVSafariFanClubText05::
	.string "WÄRTER: Keiner reißt hier irgendwas.\p"
	.string "{STR_VAR_1}hat's echt besonders hart\n"
	.string "verkackt.\p"
	.string "Vorhin hat der TRAINER nur lächerliche\n"
	.string "{STR_VAR_2}POKéMON gefangen.$"

gTVSafariFanClubText06::
	.string "WÄRTER: Keiner reißt hier irgendwas.\p"
	.string "{STR_VAR_1}hat's echt besonders hart\n"
	.string "verkackt.\p"
	.string "Vorhin hat der TRAINER kein einziges POKéMON\n"
	.string "gefangen. Einfach ein absoluter Lappen!$"

gTVSafariFanClubText07::
	.string "Der TRAINER nutzt zwar{POKEBLOCK}E.\n"
	.string "Hat{STR_VAR_2}Stück verbraucht.\p"
	.string "Aber meine Fresse, der Typ könnte echt\n"
	.string "mal üben, der kriegt ja gar nichts hin.$"

gTVSafariFanClubText08::
	.string "Ich glaub, der TRAINER würde mal was treffen,\n"
	.string "wenn er{POKEBLOCK}E nutzen würde... hat er\l"
	.string "nämlich überhaupt nicht.$"

gTVSafariFanClubText09::
	.string "REPORTER: Ach, ist das so?\p"
	.string "Klingt, als ob unser Kollege{STR_VAR_1}\n"
	.string "noch voll der Noob ist.\p"
	.string "WÄRTER: Hoffentlich kommt der TRAINER öfter,\n"
	.string "um mal zu üben. Ist ja peinlich.$"

gTVSafariFanClubText10::
	.string "REPORTER: Recht haste!\n"
	.string "Sich seinen Fails zu stellen, ist wichtig!\p"
	.string "Zuschauer, kommt zur SAFARI und zeigt,\n"
	.string "dass ihr nicht so hart abkackt!\p"
	.string "Bis zum nächsten Mal, ciao!$"

ContestLiveUpdates_Text_Intro::
	.string "“POKéMON-WETTBEWERB LIVE-UPDATES!“\p"
	.string "MC: Danke fürs Einschalten!\p"
	.string "Wir sind live beim gerade beendeten\n"
	.string "{STR_VAR_1}.\p"
	.string "Der Saal ist noch voll mit Zuschauern,\n"
	.string "die scheinbar kein Zuhause haben.\p"
	.string "Zuschauer:{STR_VAR_2}!\p"
	.string "Zuschauer:{STR_VAR_3}!\p"
	.string "MC: Wie ihr hört, hat das POKéMON\n"
	.string "{STR_VAR_2}von{STR_VAR_3}gewonnen.\p"
	.string "Zuschauer:{STR_VAR_2}!\n"
	.string "Du bist der Geilste!\p"
	.string "Zuschauer:{STR_VAR_3}!\n"
	.string "Sauber gemacht!\p"
	.string "MC: Hören wir mal, was die fanatischen\n"
	.string "Fans zu dem WETTBEWERB sagen.$"

ContestLiveUpdates_Text_WonBothRounds::
	.string "Zuschauer: Das{STR_VAR_2}war in der ersten\n"
	.string "und zweiten Runde absolut top!\p"
	.string "Das{STR_VAR_2}rasiert alle weg!$"

ContestLiveUpdates_Text_BetterRound2::
	.string "Zuschauer: Das{STR_VAR_2}hat in der ersten\n"
	.string "Runde voll reingeschissen, aber dann in der\l"
	.string "zweiten richtig aufgeräumt!\p"
	.string "Das war 'n mega Comeback von dem\n"
	.string "{STR_VAR_2}. Whoohoo!$"

ContestLiveUpdates_Text_EqualRounds::
	.string "Zuschauer: Das{STR_VAR_2}hat in beiden\n"
	.string "Runden einfach stabil abgeliefert.\p"
	.string "{STR_VAR_3}und das{STR_VAR_2},\n"
	.string "das ist echt ne krasse Kombi!$"

ContestLiveUpdates_Text_BetterRound1::
	.string "Zuschauer: Wenn's um{STR_VAR_1}geht,\n"
	.string "war das{STR_VAR_2}richtig geil.\p"
	.string "Aber beim Ausdrucken in Runde 2 war's echt\n"
	.string "mager, hoffe das wird nächstes Mal besser.$"

ContestLiveUpdates_Text_GotNervous::
	.string "Zuschauer: Als das{STR_VAR_2}mega\n"
	.string "nervös wurde, musst ich echt rumbrüllen.\p"
	.string "Ich würd dem{STR_VAR_2}gern einfach\n"
	.string "sagen: “Herzlichen Glückwunsch!“$"

ContestLiveUpdates_Text_StartledFoes::
	.string "Zuschauer: Der Auftritt von{STR_VAR_2}\n"
	.string "hat sogar mich vom Hocker gehauen!\p"
	.string "{STR_VAR_2}, du warst echt krass!$"

ContestLiveUpdates_Text_UsedCombo::
	.string "Zuschauer: Die Kombi von dem\n"
	.string "{STR_VAR_2}war einfach nur krank!\p"
	.string "Ich zitter immer noch!$"

ContestLiveUpdates_Text_ExcitingAppeal::
	.string "Zuschauer: Der Auftritt vom Sieger-\n"
	.string "{STR_VAR_2}hat echt mein Herz gepumpt!$"

ContestLiveUpdates_Text_WasCool::
	.string "{STR_VAR_2}!\n"
	.string "Du warst mega cool!$"

ContestLiveUpdates_Text_WasBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Du warst voll schön!$"

ContestLiveUpdates_Text_WasCute::
	.string "{STR_VAR_2}!\n"
	.string "Du warst voll süß!$"

ContestLiveUpdates_Text_WasSmart::
	.string "{STR_VAR_2}!\n"
	.string "Du warst mega klug!$"

ContestLiveUpdates_Text_WasTough::
	.string "{STR_VAR_2}!\n"
	.string "Du warst richtig stark!$"

ContestLiveUpdates_Text_VeryExcitingAppeal::
	.string "Zuschauer: Mein Herz rast immer noch vom\n"
	.string "Auftritt vom Sieger-{STR_VAR_2}!$"

ContestLiveUpdates_Text_VeryCool::
	.string "{STR_VAR_2}!\n"
	.string "Cooler als du geht echt nicht!$"

ContestLiveUpdates_Text_VeryBeautiful::
	.string "{STR_VAR_2}!\n"
	.string "Schöner als du geht echt nicht!$"

ContestLiveUpdates_Text_VeryCute::
	.string "{STR_VAR_2}!\n"
	.string "Süßer als du geht echt nicht!$"

ContestLiveUpdates_Text_VerySmart::
	.string "{STR_VAR_2}!\n"
	.string "Schlauer als du geht echt nicht!$"

ContestLiveUpdates_Text_VeryTough::
	.string "{STR_VAR_2}!\n"
	.string "Stärker als du geht echt nicht!$"

ContestLiveUpdates_Text_TookBreak::
	.string "Zuschauer: Selbst als das{STR_VAR_2}mal 'ne\n"
	.string "Pause gemacht hat, konnt ich nicht wegsehen.\p"
	.string "Das{STR_VAR_2}hat mich voll in seinen\n"
	.string "Bann gezogen.$"

ContestLiveUpdates_Text_GotStartled::
	.string "Zuschauer: Als das{STR_VAR_2}von den anderen\n"
	.string "POKéMON eingeschüchtert wurde, hätt ich fast\l"
	.string "geheult.\p"
	.string "{STR_VAR_2}, du hast durchgehalten!\n"
	.string "Echt geil!$"

ContestLiveUpdates_Text_MoveWonderful::
	.string "Zuschauer: Oh...\n"
	.string "Das{STR_VAR_3}vom{STR_VAR_2}!\l"
	.string "Einfach{STR_VAR_3}!\l"
	.string "Das war zu krass!\l"
	.string "Wie kann man nur so geil sein?$"

ContestLiveUpdates_Text_TalkAboutAnotherMon::
	.string "MC: Tja, da habt ihr's. Dieser Ort\n"
	.string "ist echt voll mit Fans von{STR_VAR_1}!\p"
	.string "Ich muss aber auch sagen, ein anderes\n"
	.string "POKéMON,{STR_VAR_3}von{STR_VAR_2},\l"
	.string "ist mir auch voll aufgefallen.\p"
	.string "Dieses{STR_VAR_3}von{STR_VAR_2}...$"

ContestLiveUpdates_Text_FailedToAppeal::
	.string "Das hat in der zweiten Runde so Schiss\n"
	.string "gehabt, dass es absolut gar nix hingekriegt hat.\p"
	.string "Nächstes Mal erwarte ich von{STR_VAR_1}\n"
	.string "wenigstens einen einzigen vernünftigen Move.$"

ContestLiveUpdates_Text_LastInBothRounds::
	.string "Das war in beiden Runden der absolute Letzte.\n"
	.string "Einfach nur peinlich.\p"
	.string "Ich hoffe,{STR_VAR_1}trainiert das\n"
	.string "{STR_VAR_2}nochmal, sonst bleibt das für\l"
	.string "immer das Schlusslicht.$"

ContestLiveUpdates_Text_NotExcitingEnough::
	.string "Das hat es überhaupt nicht geschafft, das\n"
	.string "Publikum auch nur ein bisschen mitzureißen.\p"
	.string "Hoffen wir mal, dass{STR_VAR_1}nächstes Mal\n"
	.string "lernt, wie man die Leute abgehen lässt.$"

ContestLiveUpdates_Text_LostAfterWinningRound1::
	.string "Das war zwar nach Runde 1 Erster, aber in der\n"
	.string "zweiten Runde kam einfach nur Müll.\p"
	.string "Das war ein richtig demütigender Absturz.\p"
	.string "Ich wette,{STR_VAR_1}überlegt sich jetzt,\n"
	.string "wie man beim nächsten Mal nicht so abkackt.$"

ContestLiveUpdates_Text_NeverExciting::
	.string "Das Publikum ist in der zweiten Runde fast\n"
	.string "eingeschlafen bei diesem Auftritt.\p"
	.string "Hoffentlich hört das Vieh auf, auf die anderen\n"
	.string "zu gucken, und liefert mal selber was ab.$"

ContestLiveUpdates_Text_LostBySmallMargin::
	.string "Das hat echt nur ganz knapp gegen das\n"
	.string "{STR_VAR_2}von{STR_VAR_1}verloren.\p"
	.string "Muss echt bitter sein, so nah dran zu sein\n"
	.string "und dann doch noch zu verkacken.\p"
	.string "Würd mich nicht wundern, wenn{STR_VAR_3}\n"
	.string "jetzt irgendwo in der Ecke heult.$"

ContestLiveUpdates_Text_RepeatedAppeals::
	.string "Das hat den JUROR komplett abgefuckt, weil\n"
	.string "es immer wieder denselben Scheiß gemacht hat.\p"
	.string "Das ist echt ein no-go in jedem WETTBEWERB,\n"
	.string "und das POKéMON hat dafür geblutet.\p"
	.string "{STR_VAR_1}sollte sich echt schämen für\n"
	.string "so ne traurige Leistung.$"

ContestLiveUpdates_Text_ValiantEffortButLost::
	.string "{STR_VAR_1}hat sich echt Mühe gegeben,\n"
	.string "aber...\p"
	.string "War alles für'n Arsch. Letzter Platz.\p"
	.string "{STR_VAR_1}sollte das als Lektion sehen\n"
	.string "und nächstes Mal nicht so hart reinkacken.$"

ContestLiveUpdates_Text_Outro::
	.string "Ich beende die Sendung mit dem üblichen\n"
	.string "Gelaber für die Sieger.\p"
	.string "Dieses Mal sind es{STR_VAR_1}und\n"
	.string "das{STR_VAR_2}!\p"
	.string "MC: Alle bereit?\n"
	.string "Alle zusammen!\p"
	.string "Zuschauer:{STR_VAR_1}!{STR_VAR_2}!\n"
	.string "Glückwunsch, ihr Streber!\l"
	.string "Ihr seid die Sieger!$"

gTVPokemonBattleUpdateText00::
	.string "“POKéMON-KAMPF-UPDATE!“\p"
	.string "Hier gibt's die Ergebnisse der POKéMON-\n"
	.string "Kämpfe direkt auf den Tisch!$"

gTVPokemonBattleUpdateText01::
	.string "Die TRAINER{STR_VAR_1}und\n"
	.string "{STR_VAR_2}haben sich im\l"
	.string "{STR_VAR_3}-KAMPF geboxt.\p"
	.string "Das Ding ging an{STR_VAR_1}!$"

gTVPokemonBattleUpdateText02::
	.string "In dem Kampf hat{STR_VAR_1}s\n"
	.string "{STR_VAR_2}mit{STR_VAR_3}\l"
	.string "richtig rasiert!$"

gTVPokemonBattleUpdateText03::
	.string "{STR_VAR_1}s{STR_VAR_2}war\n"
	.string "komplett nutzlos, das hat wehgetan.$"

gTVPokemonBattleUpdateText04::
	.string "Glückwunsch zum Sieg,\n"
	.string "{STR_VAR_1}!\p"
	.string "Und an{STR_VAR_2}, das Opfer:\n"
	.string "Üb mal ein bisschen für's nächste Mal!\p"
	.string "Das war das eklige\n"
	.string "“POKéMON-KAMPF-UPDATE!“$"

gTVPokemonBattleUpdateText05::
	.string "Die Teams von{STR_VAR_1}und\n"
	.string "{STR_VAR_2}haben sich im MULTIKAMPF\l"
	.string "aufs Maul gehauen.\p"
	.string "Der Sieg ging an das Team von\n"
	.string "{STR_VAR_1}.$"

gTVPokemonBattleUpdateText06::
	.string "Im Kampf war das{STR_VAR_2}von\n"
	.string "{STR_VAR_1}s Team mit der Attacke\l"
	.string "{STR_VAR_3}ne echte Maschine.$"

gTVPokemonBattleUpdateText07::
	.string "Das{STR_VAR_3}aus{STR_VAR_2}s Team\n"
	.string "war ein totaler Reinfall, das tat weh.\p"
	.string "Glückwunsch an das Team von\n"
	.string "{STR_VAR_1}!\p"
	.string "Und an{STR_VAR_2}s Verlierer-Team:\n"
	.string "Nächstes Mal nicht so hart reinkacken!\p"
	.string "Das war das eklige\n"
	.string "“POKéMON-KAMPF-UPDATE!“$"

GabbyAndTy_Text_GabbyPreFirstBattle:
	.string "GABBY: Oh! Wir haben da grad so'n\n"
	.string "richtig möchtegern-harten TRAINER entdeckt!\p"
	.string "Okay, Kamera läuft!\n"
	.string "Wir nerven den Typen jetzt.$"

GabbyAndTy_Text_GabbyIntro:
	.string "GABBY: Oh! Du bist doch{PLAYER}! Hi!\n"
	.string "Kennst du uns noch vom letzten Mal?\p"
	.string "Zeig mal her, wie viel krasser du\n"
	.string "geworden bist! Okay, Action!$"

GabbyAndTy_Text_GabbyDefeatFirstTime:
	.string "GABBY: Meine Augen haben mich nicht getäuscht!\n"
	.string "Wir haben hier 'n echtes Monster gefunden!$"

GabbyAndTy_Text_WhoAreYouInterview:
	.string "GABBY: Geil! Mega geil!\n"
	.string "Wer bist du überhaupt?!\p"
	.string "Ich wusste doch, dass wir hier jemanden\n"
	.string "Krankes am Start haben!\p"
	.string "Ey, lass mich das kurz erklären. Wir reisen\n"
	.string "rum und interviewen jeden Vollidioten.\p"
	.string "Also, opferst du 'ne Minute für uns?$"

GabbyAndTy_Text_QuoteFromLastInterview:
	.string "GABBY: “{STR_VAR_1}!“\p"
	.string "Weißt du noch? Den Spruch hast du letztes\n"
	.string "Mal am Ende rausgehauen.\p"
	.string "So'n Scheiß vergess ich nie!$"

GabbyAndTy_Text_YouStompedUsInterviewAgain:
	.string "Beim letzten Mal hast du uns echt so\n"
	.string "in den Boden gestampft...\p"
	.string "Wie sieht's aus?\n"
	.string "Bock auf noch'n Interview?$"

GabbyAndTy_Text_YouThrewABallAtUsInterviewAgain:
	.string "Beim letzten Mal hast du uns ernsthaft\n"
	.string "'n POKéBALL an den Kopf geworfen, oder?\p"
	.string "Wir waren komplett baff! Das haben wir echt\n"
	.string "jedem auf die Nase gebunden!\p"
	.string "Wie sieht's aus?\n"
	.string "Bock auf noch'n Interview?$"

GabbyAndTy_Text_CleverItemSkillsInterviewAgain:
	.string "Beim letzten Mal haben uns deine schmutzigen\n"
	.string "Item-Tricks echt fertig gemacht.\p"
	.string "Wie sieht's aus?\n"
	.string "Bock auf noch'n Interview?$"

GabbyAndTy_Text_WeLookedRespectableInterviewAgain:
	.string "Beim letzten Mal sahen wir ja noch halbwegs\n"
	.string "gut gegen dich aus.\p"
	.string "Wie sieht's aus?\n"
	.string "Bock auf noch'n Interview?$"

GabbyAndTy_Text_InterviewAgain:
	.string "Wie sieht's aus?\n"
	.string "Bock auf noch'n Interview?$"

GabbyAndTy_Text_DescribeYourFeelings:
	.string "Echt jetzt?\n"
	.string "Korrekt!\p"
	.string "Okay, hau mal raus, was du über unseren Kampf\n"
	.string "denkst. Aber mach's kurz und dreckig. Los!$"

GabbyAndTy_Text_PerfectWellBeSeeingYou:
	.string "GABBY: Mmm, fuck yeah!\n"
	.string "Das ist der perfekte Spruch!\p"
	.string "Ich hab das Gefühl, das wird richtig\n"
	.string "geiles Trash-TV.\p"
	.string "Gut möglich, dass die das im TV senden,\n"
	.string "also zieh dir das rein!\p"
	.string "Okay!\n"
	.string "Man sieht sich, Lappen!$"

GabbyAndTy_Text_DontGiveUpKeepingEyeOut:
	.string "GABBY: Oh...\p"
	.string "Okay, aber lass den Kopf nicht hängen!\n"
	.string "Wir stalken dich weiter!$"

GabbyAndTy_Text_KeepingAnEyeOutForYou:
	.string "GABBY: Wir stalken dich weiter!$"

GabbyAndTy_Text_GabbyNotEnoughMons:
	.string "GABBY: Gibt's hier eigentlich irgendwo\n"
	.string "'nen TRAINER, der auch POKéMON am Start hat?$"

GabbyAndTy_Text_GiveUsAnInterviewThisTime:
	.string "GABBY: Wow, du bist echt krank!\p"
	.string "Bist richtig krass stark geworden, seit\n"
	.string "wir uns das letzte Mal geprügelt haben.\p"
	.string "Da hatten wir echt recht, als wir dich\n"
	.string "als potenziellen Psycho eingeschätzt haben.\p"
	.string "Also, wie sieht's aus?\n"
	.string "Gibt's diesmal 'n Interview von dir?$"

GabbyAndTy_Text_GabbyDefeat:
	.string "GABBY: Das war'n richtig brutaler Kampf!\n"
	.string "Hast du die Scheiße auf Kamera?$"

GabbyAndTy_Text_TyPreFirstBattle:
	.string "TY: Ey, guck mal da! So'n Möchtegern-\n"
	.string "TRAINER hier in der Pampa!\l"
	.string "Kamera läuft!$"

GabbyAndTy_Text_TyIntro:
	.string "TY: Ey, guck mal!\n"
	.string "Ich kenn dich doch!\p"
	.string "Ich nehm jetzt auf, wie wir dich weghauen!$"

GabbyAndTy_Text_TyPostBattle:
	.string "TY: Du bist echt 'n Naturtalent!\n"
	.string "Gibt richtig geiles Material hier!$"

GabbyAndTy_Text_TyNotEnoughMons:
	.string "TY: Du hast nur ein einziges POKéMON\n"
	.string "und das war's?\p"
	.string "Wenn du mehr hättest, gäb's bessere\n"
	.string "Action, aber so...$"

GabbyAndTy_Text_TyDefeatFirstTime:
	.string "TY: Ja, da haben wir echt 'n heißes Eisen\n"
	.string "gefunden. Das ist 'ne fette Story!$"

GabbyAndTy_Text_TyDefeat:
	.string "TY: Yep, ich hab alles im Kasten.\n"
	.string "Die ganze Schlägerei ist gefilmt.$"

gTVInSearchOfTrainersText00::
	.string "TRAINER GESUCHT...\p"
	.string "GABBY: Hi! Heute schleich ich mich in der\n"
	.string "Gegend von{STR_VAR_1}rum.\p"
	.string "Wir suchen hier nach neuem Frischfleisch\n"
	.string "in der Szene.\p"
	.string "Heute haben wir uns den TRAINER\n"
	.string "{PLAYER}vorgenommen.\p"
	.string "Irgendwas an dem Psycho hat unsere\n"
	.string "Aufmerksamkeit erregt.$"

gTVInSearchOfTrainersText01::
	.string "Wir haben uns schon mal mit{PLAYER}\n"
	.string "geboxt, und wir schwören, der Typ ist\l"
	.string "noch brutaler geworden.\p"
	.string "Ich wusste, der Typ hat 'n Dachschaden,\n"
	.string "als wir ihn gesehen haben!$"

gTVInSearchOfTrainersText02::
	.string "Wie checkt man am besten, wie krass\n"
	.string "jemand ist?\p"
	.string "Na klar, einfach aufs Maul hauen.\n"
	.string "Also haben wir den einfach angegriffen!\p"
	.string "... ...\p"
	.string "So lief das also ab, als wir uns mit\n"
	.string "{PLAYER}geboxt haben.\p"
	.string "Wir wurden komplett auseinandergenommen\n"
	.string "und in die Tonne getreten!\p"
	.string "{PLAYER}kennt echt keine Gnade...\p"
	.string "Das ist unsere Meinung, nachdem wir den\n"
	.string "Asi-TRAINER erlebt haben.$"

gTVInSearchOfTrainersText03::
	.string "Die Kombi aus{STR_VAR_1}und\n"
	.string "{STR_VAR_3}war ja mal abartig!\p"
	.string "Wie die beiden --{STR_VAR_1}und\n"
	.string "{STR_VAR_3}-- sich im Gemetzel helfen...\p"
	.string "Das war echt kranker Scheiß!\p"
	.string "{STR_VAR_2}war der Move, den der Typ\n"
	.string "am Ende benutzt hat, um uns zu finishen.\p"
	.string "Die Attacke{STR_VAR_2}ist ein Zeichen für\n"
	.string "die kranke Freundschaft von{STR_VAR_1}\l"
	.string "und{STR_VAR_3}!$"

gTVInSearchOfTrainersText04::
	.string "...Ich hab nach der Aktion echt Komplexe\n"
	.string "bekommen.\p"
	.string "Wir wurden weggeklatscht, bevor wir\n"
	.string "auch nur irgendwas machen konnten.\l"
	.string "Ugh... heul...\p"
	.string "Trotzdem, Kämpfe von{PLAYER}sind\n"
	.string "echt hart anzusehen.\p"
	.string "Wenn ihr meint, ihr seid stark, lasst\n"
	.string "euch mal von{PLAYER}die Fresse polieren.$"

gTVInSearchOfTrainersText05::
	.string "Dazu gibt's nur eins zu sagen.\n"
	.string "Werft verdammt nochmal keinen POKéBALL\l"
	.string "in nem TRAINER-Kampf!\p"
	.string "{PLAYER}ist zwar stark, aber scheißt\n"
	.string "wohl komplett auf die Regeln.\p"
	.string "An die Zuschauer: Bitte tut mir 'n Gefallen.\p"
	.string "Wenn ihr{PLAYER}seht, haut dem\n"
	.string "Typen mal eine rein!$"

gTVInSearchOfTrainersText06::
	.string "{PLAYER}ist mega geil darin, den Gegner\n"
	.string "komplett auszuquetschen.\p"
	.string "Das Timing für die Items war einfach\n"
	.string "nur abartig!$"

gTVInSearchOfTrainersText07::
	.string "Ehrlich gesagt dachte ich, ich bin\n"
	.string "selber ziemlich geil.\p"
	.string "Wir haben zwar kassiert, aber es war\n"
	.string "ne ordentliche Straßenschlacht.\p"
	.string "Aber hey, wenn du gegen mich schon Probleme\n"
	.string "hast, musst du echt noch üben,{PLAYER}!$"

gTVInSearchOfTrainersText08::
	.string "Nach der Schlägerei haben wir{PLAYER}\n"
	.string "nach nem Kommentar gefragt.\p"
	.string "Der Lappen hat nur gesagt: “{STR_VAR_1}.“\p"
	.string "{PLAYER}s POKéMON{STR_VAR_2}und\n"
	.string "{STR_VAR_3}...\l"
	.string "Und dann “{STR_VAR_1}“...\p"
	.string "Mmm! Das ist deep! Das hat bestimmt\n"
	.string "irgendne abgefuckte Bedeutung!\p"
	.string "Kein Wunder -- 'n krasser TRAINER redet\n"
	.string "auch nur krasses Zeug.\p"
	.string "Das war's für heute!\n"
	.string "Zieht euch die nächste Sendung rein!$"

ContestLadyShow_Text_Intro::
	.string "“POKéMON-WETTBEWERB LIVE-UPDATES!“\p"
	.string "MC: Sorry, dass wir das Assi-TV unterbrechen!\n"
	.string "Danke, dass ihr zuschaut!\p"
	.string "Wir sind live beim just beendeten\n"
	.string "{STR_VAR_1}!\p"
	.string "Zuschauer: ?!!!!\p"
	.string "MC: Oh! Sieht so aus, als ob die\n"
	.string "Kandidaten gerade aus dem Gebäude kommen!\p"
	.string "Ich halt denen mal das Mikro vor die Nase!\p"
	.string "Zuschauer: ?!!!!\n"
	.string "?!!!!$"

ContestLadyShow_Text_Won::
	.string "MC: Ey, sorry!\n"
	.string "Danke fürs Live-Interview!\p"
	.string "Kann ich dir zum Sieg gratulieren?\p"
	.string "Was war dein Geheimnis bei diesem\n"
	.string "verrückten Sieg?\p"
	.string "SCHÖNHEIT: Wir haben einfach krass abgeliefert\n"
	.string "heute, mein{STR_VAR_2}und ich!\p"
	.string "Aber wir hätten das nicht gepackt, ohne\n"
	.string "die ganzen Noobs, die uns vorher geholfen haben!\p"
	.string "MC: Gibt's 'n bestimmten Nerd, mit dem\n"
	.string "du dich besonders freuen willst?\l"
	.string "Schrei's live raus!\p"
	.string "SCHÖNHEIT: Ey, du da draußen!\p"
	.string "{STR_VAR_3}! Guckst du das grad?\n"
	.string "Wir haben's gerockt!\l"
	.string "Danke dir!$"

ContestLadyShow_Text_Lost::
	.string "MC: Ey, sorry!\n"
	.string "Danke fürs Live-Interview!\p"
	.string "Bist bestimmt hart angepisst, dass du\n"
	.string "so versagt hast. Willst du was dazu ablassen?\p"
	.string "SCHÖNHEIT: Es ist voll zum Kotzen...\n"
	.string "Mein{STR_VAR_2}und ich haben echt alles gegeben...\p"
	.string "Aber ich hab das Gefühl, ich hab alle Fans\n"
	.string "enttäuscht.\p"
	.string "MC: Ich sag's echt ungern, aber die Farbe\n"
	.string "von dem Vieh ist echt'n bisschen billig.\p"
	.string "SCHÖNHEIT:{STR_VAR_3}, es tut mir so leid...\n"
	.string "Nächstes Mal kack ich nicht rein, schwör...\l"
	.string "...Schnief... Waaaaah!\p"
	.string "Zuschauer: Guck dir das an!\n"
	.string "Die heult ja voll rum!\p"
	.string "MC: Uh... Oh-oh...\p"
	.string "Ähm... Unsere Sendezeit ist leider um!\n"
	.string "Danke fürs Zuschauen, ihr Opfer!$"

ContestLadyShow_Text_LostBadly::
	.string "MC: Ey, sorry!\n"
	.string "Danke fürs Live-Interview!\p"
	.string "Wie lief der peinliche Auftritt denn so?\p"
	.string "SCHÖNHEIT: Es lief absolut beschissen...\n"
	.string "Irgendwie konnte mein{STR_VAR_2}\l"
	.string "überhaupt nicht ankommen.\p"
	.string "MC: Ich sag's echt ungern, aber die Farbe\n"
	.string "von dem Vieh ist echt'n bisschen billig.\p"
	.string "SCHÖNHEIT: ... ... ... ... ... ...\n"
	.string "...Schnief... Waaaaah!\p"
	.string "Zuschauer: Guck dir das an!\n"
	.string "Die heult ja voll rum!\p"
	.string "MC: Uh... Oh-oh...\p"
	.string "Ähm... Unsere Sendezeit ist leider um!\n"
	.string "Danke fürs Zuschauen, ihr Opfer!$"
