Text_FirstShouldRestoreMonsHealth::
	.string "Deine Viecher pfeifen aus dem letzten\n"
	.string "Loch. Geh sie heilen, du Tierquäler.$"

Text_MonsHealedShouldBuyPotions::
	.string "Ich habe sie zusammengeflickt.\n"
	.string "War eine ziemliche Sauerei.\p"
	.string "Wenn sie wieder fast verrecken, komm\n"
	.string "halt wieder her. Ist ja mein Job…\p"
	.string "Wenn du schlau bist, kaufst du dir\n"
	.string "TRÄNKE im SUPERMARKT. Dann muss ich\l"
	.string "deine Hackfresse seltener sehen.\p"
	.string "Und jetzt raus hier.$"

Text_MonsHealed::
	.string "Fertig. Sie bluten nicht mehr.\p"
	.string "Mach, dass du wegkommst.$"

Text_HadQuiteAnExperienceTakeRest::
	.string "Mom: {PLAYER}!\n"
	.string "Bist du auch mal wieder da?\p"
	.string "Du siehst aus wie ein Müllhaufen.\n"
	.string "Hast du dich geprügelt?\p"
	.string "Leg dich hin und nerv mich nicht.\n"
	.string "Ich muss meine Serie gucken.$"

Text_MomExplainHPGetPotions::
	.string "Mom: Na, ausgeschlafen?\n"
	.string "Du siehst immer noch scheiße aus.\p"
	.string "EICH hat angerufen. Der alte Sack\n"
	.string "labert was von KP und Energie.\p"
	.string "Wenn die KP weg sind, verreckt das\n"
	.string "Vieh. Kapiert? Dann ab ins Center.\p"
	.string "Oder du kaufst dir TRÄNKE.\n"
	.string "Drogen helfen immer, merk dir das.\p"
	.string "Mach mir keine Schande da draußen!\p"
	.string "Und wehe, die Cops rufen an!$"

Text_WhitedOutLostMoney::
	.string "{PLAYER} hat keine kampffähigen\n"
	.string "POKéMON mehr! Alle platt!\p"
	.string "Jemand hat {PLAYER} zusammengetreten\n"
	.string "und ¥ {STR_VAR_1} geklaut…\p"
	.string "… … … …\p"
	.string "{PLAYER} liegt im Koma!$"

Text_WhitedOut::
	.string "{PLAYER} hat keine kampffähigen\n"
	.string "POKéMON mehr!\p"
	.string "Alles wird schwarz…\n"
	.string "Gute Nacht, Opfer!$"
