Text_FirstShouldRestoreMonsHealth::
    .string "Zuerst solltest du die Gesundheit deiner\n"
    .string "POKéMON vollständig wiederherstellen.$"

Text_MonsHealedShouldBuyPotions::
    .string "Deine POKéMON wurden vollständig\n"
    .string "geheilt.\p"
    .string "Wenn die Energie oder KP deiner POKéMON\n"
    .string "niedrig sind, komm bitte zu uns.\p"
    .string "Wenn du vorhast, weit ins Feld zu gehen,\n"
    .string "solltest du im POKéMON-SUPERMARKT ein\l"
    .string "paar TRÄNKEkaufen.\p"
    .string "Wir wünschen dir viel Erfolg!$"

Text_MonsHealed::
    .string "Deine POKéMON wurden vollständig\n"
    .string "geheilt.\p"
    .string "Wir wünschen dir viel Erfolg!$"

Text_HadQuiteAnExperienceTakeRest::
    .string "Mom:{PLAYER}!\n"
    .string "Willkommen zu Hause.\p"
    .string "Es klingt, als hättest du einiges\n"
    .string "erlebt.\p"
    .string "Vielleicht solltest du dich kurz\n"
    .string "ausruhen.$"

Text_MomExplainHPGetPotions::
    .string "Mom: Oh, gut! Du und deine\n"
    .string "POKéMON seht großartig aus.\p"
    .string "Ich habe gerade von PROF. EICH gehört.\p"
    .string "Er sagte, dass die Energie von POKéMON\n"
    .string "in KP gemessen wird.\p"
    .string "Wenn deine POKéMON ihre KP verlieren,\n"
    .string "kannst du sie in jedem\l"
    .string "POKéMON-CENTER wiederherstellen.\p"
    .string "Wenn du weit reisen willst,\n"
    .string "sollte ein kluger TRAINER im\l"
    .string "POKéMON-SUPERMARKT TRÄNKE kaufen.\p"
    .string "Mach mich stolz, mein Schatz!\p"
    .string "Pass auf dich auf!$"

Text_WhitedOutLostMoney::
    .string "{PLAYER} hat keine kampffähigen\n"
    .string "POKéMON mehr!\p"
    .string " {PLAYER} geriet in Panik und verlor ¥ {STR_VAR_1} …\p"
    .string "… … … …\p"
    .string "{PLAYER} wurde ohnmächtig!$"

Text_WhitedOut::
    .string "{PLAYER} hat keine kampffähigen\n"
    .string "POKéMON mehr!\p"
    .string "{PLAYER} wurde ohnmächtig!$"
