VerdanturfTown_House_MapScripts::
	.byte 0

VerdanturfTown_House_EventScript_Woman1::
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end

VerdanturfTown_House_EventScript_Woman2::
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end

VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague::
	.string "Ganz weit weg, in PRACHTPOLIS CITY,\n"
	.string "hocken die Bosse der POKéMON LIGA.\p"
	.string "Die TRAINER dort sind so krankhaft\n"
	.string "stark, dass sie dich zum Frühstück\l"
	.string "fressen würden. Geh da bloß nicht hin!$"

VerdanturfTown_House_Text_DefeatEliteFourInARow::
	.string "Bei der LIGA musst du die TOP VIER\n"
	.string "am Stück weghauen. Ohne Pause.\l"
	.string "So sind die miesen Regeln.\p"
	.string "Wenn dich auch nur einer von denen\n"
	.string "abzieht, fliegst du hochkant raus und\l"
	.string "darfst den ganzen Mist von vorne\l"
	.string "anfangen. Reine Zeitverschwendung!$"
