MauvilleCity_Mart_MapScripts::
	.byte 0

MauvilleCity_Mart_EventScript_Clerk::
	lock
	faceplayer
	message gText_HowMayIServeYou
	waitmessage
	pokemart MauvilleCity_Mart_Pokemart
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
	release
	end

	.align 2
MauvilleCity_Mart_Pokemart:
	.2byte ITEM_POKE_BALL
	.2byte ITEM_GREAT_BALL
	.2byte ITEM_SUPER_POTION
	.2byte ITEM_ANTIDOTE
	.2byte ITEM_PARALYZE_HEAL
	.2byte ITEM_AWAKENING
	.2byte ITEM_X_SPEED
	.2byte ITEM_X_ATTACK
	.2byte ITEM_X_DEFENSE
	.2byte ITEM_GUARD_SPEC
	.2byte ITEM_DIRE_HIT
	.2byte ITEM_X_ACCURACY
	pokemartlistend

MauvilleCity_Mart_EventScript_ExpertM::
	msgbox MauvilleCity_Mart_Text_ItemsToTemporarilyElevateStats, MSGBOX_NPC
	end

MauvilleCity_Mart_EventScript_Man::
	msgbox MauvilleCity_Mart_Text_DecisionsDetermineBattle, MSGBOX_NPC
	end

MauvilleCity_Mart_Text_ItemsToTemporarilyElevateStats::
	.string "Es gibt Zeug, das den Status deiner\n"
	.string "Viecher kurzzeitig aufpumpt.\p"
	.string "X-ANGRIFF und X-VERTEIDIGUNG sind\n"
	.string "was für Leute, die zu faul zum\l"
	.string "Trainieren sind…\p"
	.string "Ich wette, es gibt noch mehr von diesem\n"
	.string "Doping-Müll, wenn man genug blecht.$"

MauvilleCity_Mart_Text_DecisionsDetermineBattle::
	.string "Drückst du wie ein Besoffener auf\n"
	.string "Attacken oder wirfst du Items?\p"
	.string "Am Ende ist es deine Schuld, wenn dein\n"
	.string "POKéMON im Dreck landet. Deine miesen\l"
	.string "Entscheidungen ruinieren den Kampf.$"
