SootopolisCity_House7_MapScripts::
	.byte 0

SootopolisCity_House7_EventScript_OldMan::
	msgbox SootopolisCity_House7_Text_CityFromEruptedVolcano, MSGBOX_NPC
	end

SootopolisCity_House7_EventScript_PokefanF::
	msgbox SootopolisCity_House7_Text_CaveMadeToKeepSomething, MSGBOX_NPC
	end

SootopolisCity_House7_Text_CityFromEruptedVolcano:
	.string "Ein Unterwasser-Vulkan ist\n"
	.string "hier komplett hochgegangen.\p"
	.string "Der Krater hat sich dann mit\n"
	.string "Regen gefüllt.\p"
	.string "Und zack, da war dieses Kaff\n"
	.string "Xeneroville geboren.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething:
	.string "Die Höhle, die Xeneroville mit\n"
	.string "der echten Welt verbindet…\p"
	.string "Irgendwie wirkt das so, als\n"
	.string "würde sie was einsperren.\p"
	.string "Oder schieb ich grad Paras?$"

