PetalburgCity_House2_MapScripts::
	.byte 0

PetalburgCity_House2_EventScript_Woman::
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end

PetalburgCity_House2_EventScript_SchoolKid::
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end

PetalburgCity_House2_Text_NormanBecameGymLeader:
	.string "Ich geh nicht raus. Hast du’s nicht gehört?\p"
	.string "Da laufen Leute rum in schwarzen Outfits…\n"
	.string "Einfach so - mitten am Tag!\p"
	.string "Sollen angeblich POKéMON klauen.\n"
	.string "Ich bleib hier, Bruder. Fenster zu.$"

PetalburgCity_House2_Text_BattledNormanOnce:
	.string "Was willst du?! Ich bin GEFANGEN hier!\p"
	.string "Meine Mom meint: “Draußen sind schwarze\n"
	.string "Typen, die Pokémon klauen.” - juckt doch nicht!\p"
	.string "Ich wollte nur in den Markt.\n"
	.string "POKÉMON-Karten kaufen. KEINE WILDKÄMPFE.\p"
	.string "Aber nein, sie dreht komplett durch.\n"
	.string "“Du bleibst hier drin, basta!” - Ey HALLO?\l"
	.string "Ich bin 10. ZEHN!\p"
	.string "Andere dürfen mit Glurak rumlaufen.\n"
	.string "Und ich? Ich darf nicht mal raus pissen.\p"
	.string "Ich schwör bei Gott:\n"
	.string "Diese Frau ist die größte HURENTOCHTER\n"
	.string "in ganz Hoenn.\p"
	.string "…Nein, ich nehm das nicht zurück.\n"
	.string "Sperr mich doch ein, du Hexe!$"

