Aide_EventScript_HaventCaughtEnough::
	msgbox Aide_Text_HaventCaughtEnoughMonsForItem
	release
	end

Aide_EventScript_NoRoomForItem::
	msgbox Aide_Text_DontHaveAnyRoomForItem
	release
	end

Aide_EventScript_DeclineCheckMons::
	msgbox Aide_Text_GetEnoughMonsComeBackForItem
	release
	end

Aide_Text_HaventCaughtEnoughMonsForItem::
	.string "Zeig mal her…\n"
	.string "Willst du mich eigentlich verarschen?!\l"
	.string "Du hast erst {STR_VAR_3} Pokemon gefangen!\p"
	.string "Du brauchst verdammte {STR_VAR_1} Stück,\n"
	.string "sonst kannst du dir {STR_VAR_2}\l"
	.string "in den Arsch schieben, du Lappen!$"

Aide_Text_GetEnoughMonsComeBackForItem::
	.string "…Tzz. Was ein Opfer.\p"
	.string "Beweg deinen Arsch erst wieder hierher,\n"
	.string "wenn du {STR_VAR_1} Pokemon hast. Dann\l"
	.string "gibts vielleicht {STR_VAR_2}.$"

Aide_Text_DontHaveAnyRoomForItem::
	.string "Ey, bist du zu dumm zum Packen?!\n"
	.string "Dein Rucksack ist randvoll mit Müll.\p"
	.string "Räum den Scheiß auf, sonst\n"
	.string "passt {STR_VAR_2} da nicht rein.$"
