@ Flavor text for interacting with various background objects

EventScript_Bookshelf::
	msgbox Text_Bookshelf, MSGBOX_SIGN
	end

EventScript_PokeMartShelf::
	msgbox Text_PokeMartShelf, MSGBOX_SIGN
	end

EventScript_Food::
	msgbox Text_Food, MSGBOX_SIGN
	end

EventScript_VideoGame::
	msgbox Text_VideoGame, MSGBOX_SIGN
	end

EventScript_Computer::
	msgbox Text_Computer, MSGBOX_SIGN
	end

EventScript_ImpressiveMachine::
	msgbox Text_ImpressiveMachine, MSGBOX_SIGN
	end

EventScript_Blueprints::
	msgbox Text_Blueprints, MSGBOX_SIGN
	end

EventScript_Burglary::
	msgbox Text_Burglary, MSGBOX_SIGN
	end

EventScript_PlayerFacingTVScreen::
	msgbox Text_PlayerFacingTVScreen, MSGBOX_SIGN
	end

EventScript_Cabinet::
	msgbox Text_DishesPlatesNeatlyLinedUp, MSGBOX_SIGN
	end

EventScript_Kitchen::
	msgbox Text_Kitchen, MSGBOX_SIGN
	end

EventScript_Dresser::
	msgbox Text_Dresser, MSGBOX_SIGN
	end

EventScript_Snacks::
	msgbox Text_Snacks, MSGBOX_SIGN
	end

EventScript_Painting::
	msgbox Text_Painting, MSGBOX_SIGN
	end

EventScript_PowerPlantMachine::
	msgbox Text_PowerPlantMachine, MSGBOX_SIGN
	end

EventScript_Telephone::
	msgbox Text_Telephone, MSGBOX_SIGN
	end

EventScript_AdvertisingPoster::
	msgbox Text_AdvertisingPoster, MSGBOX_SIGN
	end

EventScript_TastyFood::
	msgbox Text_TastyFood, MSGBOX_SIGN
	end

EventScript_TrashBin::
	msgbox Text_TrashBin, MSGBOX_SIGN
	end

EventScript_Cup::
	msgbox Text_Cup, MSGBOX_SIGN
	end

EventScript_PolishedWindow::
	msgbox Text_PolishedWindow, MSGBOX_SIGN
	end

EventScript_BeautifulSkyWindow::
	msgbox Text_BeautifulSkyWindow, MSGBOX_SIGN
	end

EventScript_BlinkingLights::
	msgbox Text_BlinkingLights, MSGBOX_SIGN
	end

EventScript_NeatlyLinedUpTools::
	msgbox Text_NeatlyLinedUpTools, MSGBOX_SIGN
	end

EventScript_PokemartSign::
	msgbox Text_PokemartSign, MSGBOX_SIGN
	end

EventScript_PokecenterSign::
	msgbox Text_PokecenterSign, MSGBOX_SIGN
	end

EventScript_Indigo_UltimateGoal::
	msgbox Text_Indigo_UltimateGoal, MSGBOX_SIGN
	end

EventScript_Indigo_HighestAuthority::
	msgbox Text_Indigo_HighestAuthority, MSGBOX_SIGN
	end

Text_Bookshelf::
	.string "Vollgestopft mit scheiß Pokemon-Büchern.\n"
	.string "Liest das echt jemand?$"

Text_NothingButPokemonBooks::
	.string "Nur bekackte Pokemon-Bücher im Regal.\n"
	.string "Richtiger Nerd-Scheiß.$"

Text_ATownMap::
	.string "Ne gammlige Karte.\n"
	.string "Wer braucht den Müll heutzutage noch?$"

Text_PokeMartShelf::
	.string "Alter!\n"
	.string "Ein Haufen überteuerter Pokemon-Scheiß!$"

Text_DishesPlatesNeatlyLinedUp::
	.string "Teller und Tassen, feinsäuberlich aufgereiht.\n"
	.string "Hat hier jemand nen Putzzwang?$"

Text_Kitchen::
	.string "Riecht geil!\n"
	.string "Irgendein Spast hat hier gekocht.$"

Text_Dresser::
	.string "Ne fette Kommode.\n"
	.string "Da passt ordentlich viel Scheiß rein.$"

Text_Snacks::
	.string "Geil, Snacks!\n"
	.string "Ich fress dem Fettsack hier alles weg.$"

Text_PokemartSign::
	.string "Wir ziehen dir die Kohle aus der Tasche!\n"
	.string "Pokemon-Supermarkt$"

Text_PokecenterSign::
	.string "Heil deine schwachen Pokemon!\n"
	.string "Pokemon-Center$"

Text_Indigo_UltimateGoal::
	.string "Indigo Plateau\p"
	.string "Das Ziel für alle Tryhards!\n"
	.string "Pokemon-Liga HQ$"

Text_Indigo_HighestAuthority::
	.string "Indigo Plateau\p"
	.string "Die fettesten Bosse hängen hier ab!\n"
	.string "Pokemon-Liga HQ$"

Text_Food::
	.string "Sollte voll mit geilem Fressen sein.\n"
	.string "Hab todes Hunger.$"

Text_Blueprints::
	.string "Irgendwelche Baupläne.\n"
	.string "Voll mit dummen Skizzen für Streber.$"

Text_Painting::
	.string "Ein dummes Bild von nem Pokemon.\n"
	.string "Sieht aus, als hätte es einen geraucht.$"

Text_PowerPlantMachine::
	.string "Was ist das für ne Scheiß-Maschine?\n"
	.string "Fass das bloß nicht an, sonst knallts!$"

Text_Telephone::
	.string "Ein uraltes Telefon.\n"
	.string "Wer ruft damit noch an, du Boomer?$"

Text_Computer::
	.string "Nur dumme Zahlen auf dem Bildschirm…\n"
	.string "Was für ein elendiger Nerd-Kram.$"

Text_AdvertisingPoster::
	.string "Irgendein billiges Werbeplakat.\n"
	.string "Kauf den Scheiß eh nicht.$"

Text_TastyFood::
	.string "Boah, das riecht verdammt geil!\n"
	.string "Da knurrt mir direkt der Magen, verdammt.$"

Text_TrashBin::
	.string "Da drin ist…\n"
	.string "……\p"
	.string "Nur Müll, genau wie du!$"

Text_Cup::
	.string "Ne billige Tasse mit nem Pokemon-Logo.\n"
	.string "Bestimmt aus China.$"

Text_PolishedWindow::
	.string "Das Fenster ist sauber wie sau.\n"
	.string "Da hatte jemand echt kein Leben.$"

Text_BeautifulSkyWindow::
	.string "Draußen vorm Fenster…\p"
	.string "Der Himmel sieht ganz okay aus.\n"
	.string "Wayne juckts?$"

Text_BlinkingLights::
	.string "Bunte Lichter blinken wie blöd.\n"
	.string "Krieg hier gleich nen Anfall.$"

Text_NeatlyLinedUpTools::
	.string "Haufenweise Werkzeug.\n"
	.string "Wer braucht den ganzen Scheiß?$"

Text_ImpressiveMachine::
	.string "Irgendeine fette Maschine.\n"
	.string "Sieht teuer aus, vielleicht klau ich die.$"

Text_VideoGame::
	.string "Das neueste Videospiel!\n"
	.string "Kostet bestimmt ein Vermögen, die Wichser.$"

Text_Burglary::
	.string "Hier wurde safe eingebrochen…\n"
	.string "Die dreckigen Bastarde haben alles zerlegt.$"

Text_PlayerFacingTVScreen::
	.string "Alter, Schnauze jetzt!\n"
	.string "Da läuft Joko & Klaas gegen {COLOR RED}ProSieben{COLOR DARK_GRAY}!\p"
	.string "Aber ich muss weiter…$"
