FortreeCity_House3_MapScripts::
	.byte 0

FortreeCity_House3_EventScript_Maniac::
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end

FortreeCity_House3_EventScript_SchoolKidM::
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end

FortreeCity_House3_Text_MetStevenHadAmazingPokemon::
	.string "Wo wir gerade von deinem mickrigen\n"
	.string "POKéDEX reden…… Ich erinnere mich……\p"
	.string "Ich hab diesen Typen, TROY, getroffen,\n"
	.string "als ich im Dreck nach Steinen gewühlt hab.\p"
	.string "Heilige Scheiße, hatte der krasse\n"
	.string "POKéMON dabei!\p"
	.string "Die waren nicht nur selten, sondern\n"
	.string "hätten dich wahrscheinlich mit einem\l"
	.string "Hustenstoß weggepustet!\p"
	.string "Der Typ ist garantiert tausendmal stärker\n"
	.string "als unsere eingebildete ARENALEITERIN!$"

FortreeCity_House3_Text_OhYouHavePokedex::
	.string "Was glotzt du so? Was hast du da in\n"
	.string "deiner ungewaschenen Hand?\p"
	.string "…… …… …… ……\n"
	.string "…… …… …… ……\p"
	.string "Oh, ein POKéDEX? Wer hat dir denn\n"
	.string "das teure Teil anvertraut?$"

