LilycoveCity_House4_MapScripts::
	.byte 0

LilycoveCity_House4_EventScript_Man1::
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end

LilycoveCity_House4_EventScript_Man2::
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end

LilycoveCity_House4_Text_MysteriesAtBottomOfSea::
	.string "Die größten Rätsel dieses Planeten\n"
	.string "liegen angeblich am Meeresgrund.\p"
	.string "Irgendein Schlaufuchs hat das mal\n"
	.string "behauptet, aber was weiß ich schon……$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis::
	.string "Zwischen MOOSBACH CITY und XENEROVILLE\n"
	.string "soll es einen tiefen Graben geben.\p"
	.string "Hat mir zumindest mal wer erzählt.\n"
	.string "Ist mir aber eigentlich auch egal.$"

